//! tsc-compatible diagnostic output formatting.

use std::fmt;
use std::path::Path;

/// THE registry of Verter-native CLI diagnostic codes.
///
/// A Verter rule — a rejection Verter makes on its own authority, not one the
/// TypeScript engine reported — needs a code, and it must not be a `TS` number:
/// borrowing one attributes the rejection to a compiler that never said it, and
/// collides with whatever TypeScript assigns that number next. The `VTER` prefix
/// sidesteps the TypeScript namespace entirely.
///
/// It sidesteps nothing WITHIN Verter's own namespace, though, and that is what
/// this enum is for. `VTER1002` is only unambiguous while exactly one rule
/// claims it; a second rule spelling the same string in a second `const` is a
/// silent collision that no compiler and no reader would catch — two different
/// rejections reported under one code, and any consumer keying on it (an
/// editor's quick-fix, a CI grep, a suppression list) then serves the wrong one.
///
/// So codes are MINTED HERE, once, and nowhere else, from ONE list. The enum,
/// its code strings, and the enumeration the uniqueness guard walks are all
/// generated by [`verter_codes!`] from that single list, so a variant that is
/// not in the enumeration cannot exist: there is no separate enum body and no
/// separate `match` to add an arm to. An exhaustive `match` alone would not have
/// achieved this — a third variant plus its arm, with a hand-written `ALL` left
/// at two entries, compiles cleanly and the guard never sees the new code.
macro_rules! verter_codes {
    ($( $(#[$meta:meta])* $variant:ident => $code:literal ),+ $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum VerterCode {
            $( $(#[$meta])* $variant, )+
        }

        impl VerterCode {
            /// EVERY registered code, in allocation order — generated from the
            /// same list as the variants, so it cannot fall behind them.
            ///
            /// It is the ALLOCATION RECORD, not a lookup used on the reporting
            /// path (each site names its variant directly), and `verter_tsc` is
            /// a binary crate with no external consumers — so outside the
            /// uniqueness guard nothing reads it.
            #[allow(dead_code)]
            pub const ALL: &'static [Self] = &[ $( Self::$variant, )+ ];

            /// The rendered code string (`VTER` + a four-digit number).
            #[must_use]
            pub const fn code(self) -> &'static str {
                match self {
                    $( Self::$variant => $code, )+
                }
            }
        }
    };
}

verter_codes! {
    /// `VTER1001` — the public-API projection for an SFC could not be produced.
    PublicApiProjectionFailure => "VTER1001",
    /// `VTER1002` — the SFC's `<script>` and `<script setup>` declare different
    /// `lang`s. Vue's own `compileScript` throws on it; Verter refuses to
    /// generate any companion for it.
    ScriptLangMismatch => "VTER1002",
}

impl fmt::Display for VerterCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.code())
    }
}

/// A single diagnostic to report.
#[derive(Debug, Clone)]
pub struct Diagnostic {
    /// File path (as displayed to the user).
    pub file: String,
    /// 1-indexed line.
    pub line: u32,
    /// 1-indexed column.
    pub col: u32,
    /// TypeScript error code. Ignored when [`Self::verter_code`] is set.
    pub ts_code: u32,
    /// A VERTER-native error code, for a diagnostic Verter itself produced
    /// rather than one it relayed from the TypeScript engine.
    ///
    /// `Some` replaces the `TS<code>` slot in the rendered line: a Verter rule
    /// (an SFC that Vue's own compiler rejects, say) has no TypeScript error
    /// number, and borrowing one would attribute it to a compiler that never
    /// said it. The code comes from the [`VerterCode`] registry, never a
    /// locally-spelled string.
    pub verter_code: Option<VerterCode>,
    /// Human-readable message.
    pub message: String,
    /// Severity ("error" or "warning").
    pub severity: Severity,
}

impl Diagnostic {
    /// A Verter-native diagnostic at a 1-indexed position in an authored file.
    #[must_use]
    pub fn verter(file: String, line: u32, col: u32, code: VerterCode, message: String) -> Self {
        Self {
            file,
            line,
            col,
            ts_code: 0,
            verter_code: Some(code),
            message,
            severity: Severity::Error,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
}

impl fmt::Display for Severity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Error => write!(f, "error"),
            Self::Warning => write!(f, "warning"),
        }
    }
}

impl fmt::Display for Diagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.verter_code {
            Some(code) => write!(
                f,
                "{}({},{}): {} {}: {}",
                self.file, self.line, self.col, self.severity, code, self.message
            ),
            None => write!(
                f,
                "{}({},{}): {} TS{}: {}",
                self.file, self.line, self.col, self.severity, self.ts_code, self.message
            ),
        }
    }
}

/// Parse the raw output of `tsc` into a list of diagnostics.
///
/// tsc outputs lines in the format:
/// ```text
/// path/to/file.ts(line,col): error TS1234: message
/// ```
/// Multi-line messages (continuation lines without `(`/`: `) are folded into
/// the previous diagnostic.
pub fn parse_tsc_output(raw: &str) -> Vec<TscDiagnostic> {
    let mut result = Vec::new();

    for line in raw.lines() {
        if let Some(d) = parse_tsc_line(line) {
            result.push(d);
        }
    }

    result
}

/// A raw tsc diagnostic before source-map remapping.
#[derive(Debug, Clone)]
pub struct TscDiagnostic {
    /// File path as reported by tsc (may be `.tsc.tsx`).
    pub file: String,
    pub line: u32,
    pub col: u32,
    pub severity: Severity,
    pub ts_code: u32,
    pub message: String,
}

impl TscDiagnostic {
    /// Convert to a displayable `Diagnostic` using an optionally remapped file path.
    pub fn into_diagnostic(
        self,
        remapped_file: Option<String>,
        remapped_line: u32,
        remapped_col: u32,
    ) -> Diagnostic {
        Diagnostic {
            file: remapped_file.unwrap_or(self.file),
            line: remapped_line,
            col: remapped_col,
            severity: self.severity,
            ts_code: self.ts_code,
            verter_code: None,
            message: self.message,
        }
    }
}

/// Attempt to parse a tsc error line:
/// `<file>(<line>,<col>): error TS<code>: <message>`
fn parse_tsc_line(line: &str) -> Option<TscDiagnostic> {
    // Find the `(line,col): ` part.
    let paren_start = line.find('(')?;
    let paren_end = line[paren_start..].find(')')? + paren_start;

    let file = &line[..paren_start];
    let coords = &line[paren_start + 1..paren_end];

    // coords = "line,col"
    let mut parts = coords.splitn(2, ',');
    let line_n: u32 = parts.next()?.trim().parse().ok()?;
    let col_n: u32 = parts.next()?.trim().parse().ok()?;

    // Rest should be `: error TS<code>: <message>` or `: warning TS<code>: ...`
    let rest = line[paren_end + 1..].trim();
    let rest = rest.strip_prefix(':')?;
    let rest = rest.trim();

    let (severity, rest) = if let Some(after) = rest.strip_prefix("error ") {
        (Severity::Error, after)
    } else {
        let after = rest.strip_prefix("warning ")?;
        (Severity::Warning, after)
    };

    // rest = "TS<code>: <message>"
    let rest = rest.strip_prefix("TS")?;
    let colon = rest.find(':')?;
    let ts_code: u32 = rest[..colon].parse().ok()?;
    let message = rest[colon + 1..].trim().to_string();

    // Normalize file path separators.
    let file = file.replace('\\', "/");

    Some(TscDiagnostic {
        file,
        line: line_n,
        col: col_n,
        severity,
        ts_code,
        message,
    })
}

/// Returns `true` if the binary at `path` is a native executable (not a `.cmd`/`.sh` shim).
pub fn is_native_binary(path: &Path) -> bool {
    match path.extension().and_then(|e| e.to_str()) {
        Some(ext) if ext.eq_ignore_ascii_case("cmd") => false,
        Some(ext) if ext.eq_ignore_ascii_case("sh") => false,
        Some(ext) if ext.eq_ignore_ascii_case("exe") => true,
        Some(_) => false,
        // No extension: native on Unix (the platform package's `tsc`; a `.bin`
        // shim there carries a shebang and spawns fine), not directly
        // executable on Windows.
        None => !cfg!(target_os = "windows"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    // ── is_native_binary tests ───────────────────────────────────────

    #[test]
    fn is_native_binary_exe() {
        assert!(
            is_native_binary(Path::new("/some/path/tsgo.exe")),
            ".exe should be native"
        );
    }

    #[test]
    fn is_native_binary_cmd_is_not_native() {
        assert!(
            !is_native_binary(Path::new("/some/path/tsgo.cmd")),
            ".cmd should not be native"
        );
    }

    #[test]
    fn is_native_binary_platform_package_no_ext() {
        let path = Path::new("/project/node_modules/@typescript/typescript-linux-x64/lib/tsc");
        if cfg!(target_os = "windows") {
            assert!(
                !is_native_binary(path),
                "an extensionless name is not directly executable on Windows"
            );
        } else {
            assert!(
                is_native_binary(path),
                "the platform package's extensionless tsc is native on Unix"
            );
        }
    }

    #[test]
    fn is_native_binary_sh_is_not_native() {
        assert!(
            !is_native_binary(Path::new("/some/path/tsgo.sh")),
            ".sh should not be native"
        );
    }

    // ── parse_tsc_output tests (tsgo produces identical format) ──────

    #[test]
    fn parse_tsc_output_standard_error() {
        let output =
            "src/App.vue(10,5): error TS2322: Type 'string' is not assignable to type 'number'.";
        let diags = parse_tsc_output(output);
        assert_eq!(diags.len(), 1, "should parse one diagnostic");
        let d = &diags[0];
        assert_eq!(d.file, "src/App.vue");
        assert_eq!(d.line, 10);
        assert_eq!(d.col, 5);
        assert_eq!(d.ts_code, 2322);
        assert_eq!(d.severity, Severity::Error);
        assert!(d.message.contains("Type 'string' is not assignable"));
    }

    #[test]
    fn parse_tsc_output_ts5102_removed_option() {
        // tsgo emits TS5102 for removed compiler options; verify we parse it.
        let output =
            "tsconfig.json(3,5): error TS5102: Option 'importsNotUsedAsValues' has been removed.";
        let diags = parse_tsc_output(output);
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].ts_code, 5102);
        assert!(diags[0].message.contains("removed"));
    }

    #[test]
    fn parse_tsc_output_multiple_diagnostics() {
        let output = "\
src/a.ts(1,1): error TS2304: Cannot find name 'foo'.
src/b.ts(5,10): error TS2307: Cannot find module 'bar'.
";
        let diags = parse_tsc_output(output);
        assert_eq!(diags.len(), 2, "should parse both diagnostics");
        assert_eq!(diags[0].file, "src/a.ts");
        assert_eq!(diags[1].file, "src/b.ts");
    }

    #[test]
    fn parse_tsc_output_ignores_non_diagnostic_lines() {
        let output = "\
Starting compilation...
src/a.ts(1,1): error TS2304: Cannot find name 'foo'.
Found 1 error.
";
        let diags = parse_tsc_output(output);
        assert_eq!(diags.len(), 1, "should ignore non-diagnostic lines");
        assert_eq!(diags[0].ts_code, 2304);
    }

    #[test]
    fn parse_tsc_output_windows_backslash_paths() {
        let output = r"src\components\App.vue(3,12): error TS2345: Argument of type 'string' is not assignable.";
        let diags = parse_tsc_output(output);
        assert_eq!(diags.len(), 1);
        // Paths should be normalized to forward slashes.
        assert!(
            !diags[0].file.contains('\\'),
            "backslashes should be normalized"
        );
        assert_eq!(diags[0].file, "src/components/App.vue");
    }

    #[test]
    fn diagnostic_display_format() {
        let d = Diagnostic {
            file: "src/App.vue".to_string(),
            line: 10,
            col: 5,
            ts_code: 2322,
            verter_code: None,
            message: "Type error".to_string(),
            severity: Severity::Error,
        };
        let s = format!("{d}");
        assert_eq!(s, "src/App.vue(10,5): error TS2322: Type error");
        assert!(!s.contains("warning"), "should be error, not warning");
    }

    /// A Verter-native diagnostic renders its OWN code, never a TypeScript
    /// number it did not earn.
    ///
    /// Fails against the pre-change tree: `Diagnostic` had only `ts_code`, so a
    /// Verter rule could reach the CLI only by impersonating `TS0`.
    #[test]
    fn verter_native_diagnostic_renders_its_own_code() {
        let d = Diagnostic::verter(
            "src/App.vue".to_string(),
            1,
            1,
            VerterCode::ScriptLangMismatch,
            "<script> and <script setup> must have the same language type.".to_string(),
        );
        let rendered = format!("{d}");
        assert_eq!(
            rendered,
            "src/App.vue(1,1): error VTER1002: <script> and <script setup> must have the same language type."
        );
        assert!(
            !rendered.contains("TS"),
            "a Verter rule must not borrow a TypeScript error number: {rendered}"
        );
    }
    /// Every registered Verter code is UNIQUE and well-formed.
    ///
    /// The registry exists so a second rule cannot silently reuse a code a
    /// first rule already claimed — a collision no compiler catches, because
    /// two `const`s holding `"VTER1002"` are perfectly legal Rust, and no
    /// reader catches either, because the two rules live in different files.
    /// Reporting two different rejections under one code breaks every consumer
    /// that keys on it.
    ///
    /// Fails the moment a new variant reuses an allocated number, is left out
    /// of `ALL`, or is spelled outside the `VTER` + four digits shape (an
    /// accidental `TS…` spelling would collide with the TypeScript namespace
    /// the prefix exists to avoid).
    #[test]
    fn verter_codes_are_unique_and_well_formed() {
        let mut seen: Vec<&str> = Vec::new();
        for entry in VerterCode::ALL {
            let code = entry.code();
            assert!(
                !seen.contains(&code),
                "{code} is claimed by two registry entries: {seen:?} + {entry:?}"
            );
            seen.push(code);

            let digits = code
                .strip_prefix("VTER")
                .unwrap_or_else(|| panic!("{entry:?} must be spelled `VTER<nnnn>`, got {code}"));
            assert_eq!(
                digits.len(),
                4,
                "{entry:?} must carry a four-digit number, got {code}"
            );
            assert!(
                digits.bytes().all(|b| b.is_ascii_digit()),
                "{entry:?} must carry a four-digit number, got {code}"
            );
            assert_eq!(format!("{entry}"), code, "Display must render the code");
        }

        // `ALL` really enumerates the whole enum — structurally, not by a
        // hand-maintained count. `verter_codes!` generates the variants, their
        // code strings, and this list from ONE input list, so "a variant the
        // guard cannot see" is not a reachable state: there is no separate enum
        // body to add a variant to. A hard-coded length here would be the exact
        // hole it claims to close (add a third variant, leave the literal at
        // two, and every assertion above skips it), so this asserts the list is
        // non-empty and leaves completeness to the generator.
        assert!(
            !VerterCode::ALL.is_empty(),
            "the registry must enumerate at least one code"
        );
    }
}
