//! Script analysis lint rules.

mod component_api_style;
mod component_definition_name_casing;
mod define_emits_declaration;
mod define_macros_in_root;
mod define_macros_order;
mod define_props_declaration;
mod next_tick_style;
mod no_arrow_functions_in_watch;
mod no_async_in_computed;
mod no_export_in_script_setup;
mod no_expose_after_await;
mod no_inline_lifecycle;
mod no_lifecycle_after_await;
mod no_potential_component_option_typo;
mod no_required_prop_with_default;
mod no_reserved_keys;
mod no_reserved_props;
mod no_side_effects_in_computed;
mod no_unused_emit_declarations;
mod no_watch_after_await;
mod one_component_per_file;
mod order_in_components;
mod prefer_import_from_vue;
mod prefer_use_template_ref;
mod prop_name_casing;
mod require_default_prop;
mod require_emit_validator;
mod require_explicit_emits;
mod require_prop_types;
mod require_symbol_provide;
mod valid_define_emits;
mod valid_define_props;

mod no_boolean_default;
mod no_import_compiler_macros;
mod no_leaked_event_listeners;
mod prefer_define_options;
mod prefer_script_attrs;
mod require_typed_ref;

pub use component_api_style::ComponentApiStyle;
pub use component_definition_name_casing::ComponentDefinitionNameCasing;
pub use define_emits_declaration::DefineEmitsDeclaration;
pub use define_macros_in_root::DefineMacrosInRoot;
pub use define_macros_order::DefineMacrosOrder;
pub use define_props_declaration::DefinePropsDeclaration;
pub use next_tick_style::NextTickStyle;
pub use no_arrow_functions_in_watch::NoArrowFunctionsInWatch;
pub use no_async_in_computed::NoAsyncInComputed;
pub use no_export_in_script_setup::NoExportInScriptSetup;
pub use no_expose_after_await::NoExposeAfterAwait;
pub use no_inline_lifecycle::NoInlineLifecycle;
pub use no_lifecycle_after_await::NoLifecycleAfterAwait;
pub use no_potential_component_option_typo::NoPotentialComponentOptionTypo;
pub use no_required_prop_with_default::NoRequiredPropWithDefault;
pub use no_reserved_keys::NoReservedKeys;
pub use no_reserved_props::NoReservedProps;
pub use no_side_effects_in_computed::NoSideEffectsInComputed;
pub use no_unused_emit_declarations::NoUnusedEmitDeclarations;
pub use no_watch_after_await::NoWatchAfterAwait;
pub use one_component_per_file::OneComponentPerFile;
pub use order_in_components::OrderInComponents;
pub use prefer_import_from_vue::PreferImportFromVue;
pub use prefer_use_template_ref::PreferUseTemplateRef;
pub use prop_name_casing::PropNameCasing;
pub use require_default_prop::RequireDefaultProp;
pub use require_emit_validator::RequireEmitValidator;
pub use require_explicit_emits::RequireExplicitEmits;
pub use require_prop_types::RequirePropTypes;
pub use require_symbol_provide::RequireSymbolProvide;
pub use valid_define_emits::ValidDefineEmits;
pub use valid_define_props::ValidDefineProps;

pub use no_boolean_default::NoBooleanDefault;
pub use no_import_compiler_macros::NoImportCompilerMacros;
pub use no_leaked_event_listeners::NoLeakedEventListeners;
pub use prefer_define_options::PreferDefineOptions;
pub use prefer_script_attrs::PreferScriptAttrs;
pub use require_typed_ref::RequireTypedRef;
