// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the walker stopped.
 */
export type ChainTermination = "Complete" | { "DepthExceeded": { 
/**
 * Depth cap that was exceeded.
 */
cap: number, } } | { "Cycle": { 
/**
 * EdgeId where the walker detected the cycle.
 */
at_edge: EdgeId, } } | "NotFound";

/**
 * Conditional-select branch discriminator.
 */
export type ConditionalBranch = "True" | "False" | "Deferred";

/**
 * One derivation edge. `result` is the node produced; `sources` are
 * the nodes consumed; `meta` carries kind-specific payload.
 */
export type DerivationEdgeRecord = { 
/**
 * NodeId of the node produced by this edge.
 */
result: NodeId, 
/**
 * Kind of derivation step (see [`OriginEdgeKind`]).
 */
kind: OriginEdgeKind, 
/**
 * NodeIds of the input nodes consumed to produce `result`.
 */
sources: Array<NodeId>, 
/**
 * Kind-specific payload (substitution names, projection
 * segments, etc.). See [`OriginEdgeMetaDto`].
 */
meta: OriginEdgeMetaDto, };

/**
 * In-audit opaque edge id. Assigned by the miner from the sorted
 * canonicalisation of edges so identical requests produce identical
 * serialised footprints.
 */
export type EdgeId = number;

/**
 * Typed discriminator naming WHY a single-hop `ProjectMember` edge
 * was emitted. The variant identifies the structural operation that
 * produced the member edge; it is set at every production emit site
 * in `verter_session` (exhaustively — there is no default).
 *
 * Audit-side consumers (the validator, the inspect CLI) use this
 * provenance to distinguish edges whose member names are part of the
 * user-visible published surface from edges whose member names are
 * legitimate intermediates of a structural walk
 * (KeyOf-enumeration, Mapped-instantiation, multi-hop path projection).
 *
 * Adding a new emit site **must** add a new variant here and update
 * the validator's allowlist explicitly. The translator in
 * `verter_session::component_meta_audit::footprint_miner::translate_meta`
 * matches exhaustively on `OriginMeta::ProjectedMember`'s provenance
 * field, so no `_ =>` wildcard is permitted.
 */
export type MemberEdgeProvenance = "PublishedField" | "PathProjection" | "KeyOfEnumerated" | "MappedKeyEnumerated";

/**
 * In-audit opaque NodeId. Assigned by the miner from a sorted
 * canonicalisation of touched semantic node ids so identical
 * requests produce identical serialised footprints regardless of
 * thread interleaving.
 */
export type NodeId = number;

/**
 * Kind of normalization performed (union-flatten, intersection-
 * flatten, or a simplification pass).
 */
export type NormalizeKind = "Union" | "Intersection" | "Simplify";

/**
 * Audit-side origin edge kind. Mirrors the semantic graph's
 * `verter_session::semantic_query::OriginEdgeKind` (nine kinds) and
 * adds `SharedLoadReuse` — an audit-only edge emitted when a joiner
 * attaches to a winner's in-flight artifact.
 */
export type OriginEdgeKind = "Instantiate" | "SubstituteTypeParam" | "ConditionalSelect" | "InferBind" | "ProjectMember" | "ProjectIndex" | "ProjectPath" | "Normalize" | "AliasResolve" | "SharedLoadReuse";

/**
 * Kind-specific payload attached to a [`DerivationEdgeRecord`].
 */
export type OriginEdgeMetaDto = { "Instantiate": { 
/**
 * Names of the declared type parameters.
 */
type_params: Array<string>, } } | { "SubstituteTypeParam": { 
/**
 * Name of the parameter being substituted.
 */
param_name: string, 
/**
 * NodeId of the substituted-in type.
 */
substituted_with: NodeId, } } | { "ConditionalSelect": { 
/**
 * Which branch the solver chose.
 */
branch: ConditionalBranch, } } | { "InferBind": { 
/**
 * Name of the inferred parameter.
 */
param_name: string, 
/**
 * NodeId the parameter was bound to.
 */
bound_to: NodeId, } } | { "ProjectMember": { 
/**
 * Member name that was projected out.
 */
member_name: string, 
/**
 * Typed discriminator naming WHY this edge was emitted. See
 * [`MemberEdgeProvenance`]. Always populated at the producer
 * (no default); the audit-validator's Rule-5 check inspects
 * this field to distinguish published-surface fields from
 * legitimate structural intermediates.
 */
provenance: MemberEdgeProvenance, } } | { "ProjectIndex": { 
/**
 * Index key that was projected out.
 */
index_key: string, } } | { "ProjectPath": { 
/**
 * Path segments, in traversal order.
 */
path: Array<ProjectPathSegment>, } } | { "Normalize": { 
/**
 * Specific normalization kind performed.
 */
kind: NormalizeKind, } } | { "AliasResolve": { 
/**
 * Name of the alias that was followed.
 */
alias_name: string, } } | { "SharedLoadReuse": { 
/**
 * Winning request's id.
 */
winner_request_id: string, 
/**
 * `true` when the winner's own request was audited so its
 * record can be consulted.
 */
winner_audited: boolean, } };

/**
 * One step in a projection path (member / index / keyof).
 */
export type ProjectPathSegment = { "Member": { 
/**
 * Member name.
 */
name: string, } } | { "Index": { 
/**
 * Literal key used as the index.
 */
key: string, } } | "KeyOf";

/**
 * Provenance chain returned by [`RequestAuditRecord::why_loaded`] /
 * [`RequestAuditRecord::why_instantiated`]. Always carries a
 * [`ChainTermination`] so renderers can distinguish a complete walk
 * from a depth-capped, cycle-terminated, or shared-load-redirected
 * one.
 */
export type ProvenanceChain = { 
/**
 * In-audit `NodeId` the walk started from. `None` when the walker
 * could not locate any matching root in the audit record.
 */
root: NodeId | null, 
/**
 * Steps in BFS order. Each step is one derivation edge whose
 * `result` is the current frontier node; `depth` records the hop
 * count from the root.
 */
steps: Array<ProvenanceStep>, 
/**
 * Why the walk stopped. `Complete` means the frontier exhausted
 * without hitting any structural termination.
 */
terminated: ChainTermination, 
/**
 * Shared-load reuses observed for the queried canonical (only
 * populated by `why_loaded`). Renderers display these as terminal
 * branches per
 */
shared_load_terminals: Array<SharedLoadReuseRecord>, };

/**
 * One step on a [`ProvenanceChain`].
 */
export type ProvenanceStep = { 
/**
 * EdgeId of the derivation edge visited at this step.
 */
edge_id: EdgeId, 
/**
 * Distance from the walker's root node (BFS depth).
 */
depth: number, 
/**
 * `display_label` of the edge's result node.
 */
node_label: string, 
/**
 * The full derivation edge (result / sources / meta) captured
 * verbatim so the TS-side renderer doesn't need to re-resolve
 * edges against the source audit.
 */
edge: DerivationEdgeRecord, };

/**
 * Joiner record — this request attached to a winner's in-flight
 * cache slot instead of starting fresh.
 */
export type SharedLoadReuseRecord = { 
/**
 * Canonical id of the shared artifact.
 */
canonical_id: string, 
/**
 * Request id of the winning (first-to-arrive) request that owns
 * the in-flight slot.
 */
winner_request_id: string, 
/**
 * `true` when the winner's request was itself audited.
 */
winner_audited: boolean, };
