// This file is auto-generated by scripts/generate-vue-overrides.mjs
// Do not edit manually

// Local copies of Vue utility types
export type Data = Record<string, unknown>;
export type DefaultFactory<T> = (props: Data) => T | null | undefined;
export type DefineModelOptions<T = any, G = T, S = T> = {
  get?: (v: T) => G;
  set?: (v: S) => any;
};
export type InferDefault<P, T> =
  | ((props: P) => T & {})
  | (T extends NativeType ? T : never);
export type InferDefaults<T> = {
  [K in keyof T]?: InferDefault<T, T[K]>;
};
export type NativeType =
  | null
  | undefined
  | number
  | string
  | boolean
  | symbol
  | Function;
export interface PropOptions<T = any, D = T> {
  type?: import("vue").PropType<T> | true | null;
  required?: boolean;
  default?: D | DefaultFactory<D> | null | undefined | object;
  validator?(value: unknown, props: Data): boolean;
}

// Overrides for defineProps
/**
 * Vue `<script setup>` compiler macro for declaring component props. The
 * expected argument is the same as the component `props` option.
 *
 * Example runtime declaration:
 * ```js
 * // using Array syntax
 * const props = defineProps(['foo', 'bar'])
 * // using Object syntax
 * const props = defineProps({
 *   foo: String,
 *   bar: {
 *     type: Number,
 *     required: true
 *   }
 * })
 * ```
 *
 * Equivalent type-based declaration:
 * ```ts
 * // will be compiled into equivalent runtime declarations
 * const props = defineProps<{
 *   foo?: string
 *   bar: number
 * }>()
 * ```
 *
 * @see {@link https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits}
 *
 * This is only usable inside `<script setup>`, is compiled away in the
 * output and should **not** be actually called at runtime.
 */
export declare function defineProps_Box<PropNames extends string = string>(
  props: PropNames[]
): PropNames[];

export declare function defineProps_Box<
  PP extends import("vue").ComponentObjectPropsOptions = import("vue").ComponentObjectPropsOptions
>(props: PP): PP;

export declare function defineProps_Box<TypeProps>(): TypeProps;

// Overrides for withDefaults
/**
 * Vue `<script setup>` compiler macro for providing props default values when
 * using type-based `defineProps` declaration.
 *
 * Example usage:
 * ```ts
 * withDefaults(defineProps<{
 *   size?: number
 *   labels?: string[]
 * }>(), {
 *   size: 3,
 *   labels: () => ['default label']
 * })
 * ```
 *
 * This is only usable inside `<script setup>`, is compiled away in the output
 * and should **not** be actually called at runtime.
 *
 * @see {@link https://vuejs.org/guide/typescript/composition-api.html#typing-component-props}
 */
export declare function withDefaults_Box<
  T,
  BKeys extends keyof T,
  Defaults extends InferDefaults<T>
>(
  props: import("vue").DefineProps<T, BKeys>,
  defaults: Defaults
): [import("vue").DefineProps<T, BKeys>, Defaults];

// Overrides for defineEmits
/**
 * Vue `<script setup>` compiler macro for declaring a component's emitted
 * events. The expected argument is the same as the component `emits` option.
 *
 * Example runtime declaration:
 * ```js
 * const emit = defineEmits(['change', 'update'])
 * ```
 *
 * Example type-based declaration:
 * ```ts
 * const emit = defineEmits<{
 *   // <eventName>: <expected arguments>
 *   change: []
 *   update: [value: number] // named tuple syntax
 * }>()
 *
 * emit('change')
 * emit('update', 1)
 * ```
 *
 * This is only usable inside `<script setup>`, is compiled away in the
 * output and should **not** be actually called at runtime.
 *
 * @see {@link https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits}
 */
export declare function defineEmits_Box<EE extends string = string>(
  emitOptions: EE[]
): EE[];

export declare function defineEmits_Box<
  E extends import("vue").EmitsOptions = import("vue").EmitsOptions
>(emitOptions: E): E;

export declare function defineEmits_Box<
  T extends import("vue").ComponentTypeEmits
>(): T;

// Overrides for defineOptions
/**
 * Vue `<script setup>` compiler macro for declaring a component's additional
 * options. This should be used only for options that cannot be expressed via
 * Composition API - e.g. `inheritAttrs`.
 *
 * @see {@link https://vuejs.org/api/sfc-script-setup.html#defineoptions}
 */
export declare function defineOptions_Box<
  RawBindings = {},
  D = {},
  C extends import("vue").ComputedOptions = {},
  M extends import("vue").MethodOptions = {},
  Mixin extends import("vue").ComponentOptionsMixin = import("vue").ComponentOptionsMixin,
  Extends extends import("vue").ComponentOptionsMixin = import("vue").ComponentOptionsMixin
>(
  options?: import("vue").ComponentOptionsBase<
    {},
    RawBindings,
    D,
    C,
    M,
    Mixin,
    Extends,
    {}
  > & {
    props?: never;
    emits?: never;
    expose?: never;
    slots?: never;
  }
): import("vue").ComponentOptionsBase<
  {},
  RawBindings,
  D,
  C,
  M,
  Mixin,
  Extends,
  {}
> & {
  props?: never;
  emits?: never;
  expose?: never;
  slots?: never;
};

// Overrides for defineModel
/**
 * Vue `<script setup>` compiler macro for declaring a
 * two-way binding prop that can be consumed via `v-model` from the parent
 * component. This will declare a prop with the same name and a corresponding
 * `update:propName` event.
 *
 * If the first argument is a string, it will be used as the prop name;
 * Otherwise the prop name will default to "modelValue". In both cases, you
 * can also pass an additional object which will be used as the prop's options.
 *
 * The returned ref behaves differently depending on whether the parent
 * provided the corresponding v-model props or not:
 * - If yes, the returned ref's value will always be in sync with the parent
 *   prop.
 * - If not, the returned ref will behave like a normal local ref.
 *
 * @example
 * ```ts
 * // default model (consumed via `v-model`)
 * const modelValue = defineModel<string>()
 * modelValue.value = "hello"
 *
 * // default model with options
 * const modelValue = defineModel<string>({ required: true })
 *
 * // with specified name (consumed via `v-model:count`)
 * const count = defineModel<number>('count')
 * count.value++
 *
 * // with specified name and default value
 * const count = defineModel<number>('count', { default: 0 })
 * ```
 */
export declare function defineModel_Box<
  T,
  M extends PropertyKey = string,
  G = T,
  S = T
>(
  options: (
    | {
        default: any;
      }
    | {
        required: true;
      }
  ) &
    PropOptions<T> &
    DefineModelOptions<T, G, S>
): (
  | {
      default: any;
    }
  | {
      required: true;
    }
) &
  PropOptions<T> &
  DefineModelOptions<T, G, S>;

export declare function defineModel_Box<
  T,
  M extends PropertyKey = string,
  G = T,
  S = T
>(
  options?: PropOptions<T> & DefineModelOptions<T, G, S>
): PropOptions<T> & DefineModelOptions<T, G, S>;

export declare function defineModel_Box<
  T,
  M extends PropertyKey = string,
  G = T,
  S = T
>(
  name: string,
  options: (
    | {
        default: any;
      }
    | {
        required: true;
      }
  ) &
    PropOptions<T> &
    DefineModelOptions<T, G, S>
): [
  string,
  (
    | {
        default: any;
      }
    | {
        required: true;
      }
  ) &
    PropOptions<T> &
    DefineModelOptions<T, G, S>
];

export declare function defineModel_Box<
  T,
  M extends PropertyKey = string,
  G = T,
  S = T
>(
  name: string,
  options?: PropOptions<T> & DefineModelOptions<T, G, S>
): [string, PropOptions<T> & DefineModelOptions<T, G, S>];

// Overrides for defineExpose
/**
 * Vue `<script setup>` compiler macro for declaring a component's exposed
 * instance properties when it is accessed by a parent component via template
 * refs.
 *
 * `<script setup>` components are closed by default - i.e. variables inside
 * the `<script setup>` scope is not exposed to parent unless explicitly exposed
 * via `defineExpose`.
 *
 * This is only usable inside `<script setup>`, is compiled away in the
 * output and should **not** be actually called at runtime.
 *
 * @see {@link https://vuejs.org/api/sfc-script-setup.html#defineexpose}
 */
export declare function defineExpose_Box<
  Exposed extends Record<string, any> = Record<string, any>
>(exposed?: Exposed): Exposed;

// Overrides for defineSlots
export declare function defineSlots_Box<
  S extends Record<string, any> = Record<string, any>
>(): S;
