[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1-alpha.3"
edition = "2021"
license = "MIT"
authors = ["pikax"]
repository = "https://github.com/pikax/verter"
homepage = "https://verterjs.dev/"

[workspace.dependencies]
oxc_allocator = "0.117.0"
oxc_ast = "0.117.0"
oxc_parser = "0.117.0"
oxc_span = "0.117.0"
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
sha2 = "0.10"
lightningcss = { version = "1.0.0-alpha.71", features = ["visitor"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0
