packages:
  - "packages/*"
  - "packages/native/npm/*"
  - "packages/verter-lsp/npm/*"
  - "packages/verter-mcp/npm/*"
  - "packages/verter-tsc/npm/*"
  - "docs"

onlyBuiltDependencies:
  - "@swc/core"
  - "@vscode/vsce-sign"
  - esbuild
  - keytar
