//! PERF-0 Rail A — carrier-byte parity characterization (hermetic, deterministic).
//!
//! Pins the CURRENT ("Full-mode", `HostConfig::default()`) carrier bytes for the
//! two carrier surfaces the verter-tsc / LSP pipeline ships to tsgo:
//!   - the IDE TSX carrier (`.vue.tsx`), produced THROUGH `VerterHost`'s shared
//!     IDE-carrier path (`ensure_ide_compiled` + `get_ide`) — the EXACT path the
//!     LSP ships to tsgo (`crates/verter_lsp/src/background_init.rs` `get_ide`);
//!     NOT a direct `verter_compiler::compile()` call (which would bypass the host
//!     and silently miss a host-side Batch regression); and
//!   - the public-API stub (`.vue.verter.ts`), generated by
//!     `VerterHost::get_public_api` — the cross-component surface tsgo resolves
//!     sibling `.vue` imports against.
//!
//! WHY THIS EXISTS (the parity oracle): the perf campaign (see
//! `docs/arch/host-mode-perf-design.md`) will add a Batch `HostConfig` preset, a
//! stateless `BareCompiler`, and swap verter-tsc's checker backend to an
//! in-memory tsgo `--api` client. The codex ruling (§3, "Full <-> Batch — SAME
//! carrier bytes") requires every one of those changes to be PROVABLY
//! byte-identical on the carrier surface. These goldens are that proof: any later
//! block that drifts a carrier byte fails here, fail-before / pass-after. Because
//! the IDE carrier is acquired THROUGH the host (not a direct `compile()`), a
//! host-side regression — e.g. dropping the style-`v-bind` extraction the host
//! feeds into codegen — flips the golden, which a direct-`compile()` oracle could
//! not catch.
//!
//! DISCRIMINATING: each test pins the COMPLETE carrier bytes of one case against a
//! committed golden, so ANY change (a dropped binding, a reordered member, a
//! renamed helper) flips it RED. The goldens were produced by the current codegen
//! itself; they are not hand-authored. Line endings are normalized (CRLF -> LF) on
//! BOTH sides so a CRLF checkout of a golden cannot spuriously fail the byte
//! comparison (cross-platform portability rule). Canonical IDs are STABLE
//! forward-slash paths (`/proj/Foo.vue`) so the bytes — including the stub's inline
//! base64 source map, whose `sources` is the canonical ID — embed no
//! machine-specific absolute path and reproduce on macOS / Windows / Linux.

use std::sync::Arc;

use verter_session::{
    CompileProfile, CompileTarget, FileLanguage, HostConfig, UpsertRequest, VerterHost,
};

// ── Carrier generation helpers (mirror the LSP / verter-tsc carrier paths) ──

/// IDE TSX carrier bytes — produced THROUGH `VerterHost`'s shared IDE-carrier path
/// (`ensure_ide_compiled` + `get_ide`), the EXACT path the LSP ships to tsgo
/// (`crates/verter_lsp/src/background_init.rs` calls `host.get_ide(..)`), NOT a
/// direct `verter_compiler::compile()` call. Routing through the host is what lets
/// this oracle guard the future Batch (`HostConfig::batch_typecheck()`) / Bare seam
/// and exercise the host-side style-`v-bind` extraction
/// (`virtual_file_pipeline.rs`), whose facts the host feeds into codegen under its
/// analysis scope — a direct `compile()` call cannot see a host-side regression.
///
/// `files` are upserted into one host (stable canonical IDs); the IDE carrier for
/// `target` is then ensured + read. `get_ide` returns `None` only when the file is
/// not a resolvable carrier — a panic here is a real regression, not flake.
///
/// Defaults to the Full / `HostConfig::default()` preset (the golden baseline).
fn ide_tsx(files: &[(&str, &str, FileLanguage)], target: &str) -> String {
    ide_tsx_with(HostConfig::default(), files, target)
}

/// `ide_tsx` parametrised on the host preset, so the Full-vs-Batch parity test can
/// build the SAME carrier under `HostConfig::batch_typecheck()` and byte-compare it
/// against the `lsp_interactive()` (= default / golden) output.
fn ide_tsx_with(config: HostConfig, files: &[(&str, &str, FileLanguage)], target: &str) -> String {
    let host = VerterHost::new_standalone(config);
    for (canonical, source, lang) in files {
        let _ = host.upsert(UpsertRequest {
            canonical_id: Some((*canonical).to_string()),
            input_id: (*canonical).to_string(),
            source: Arc::<str>::from(*source),
            file_language: lang.clone(),
            aliases: Vec::new(),
        });
    }
    // The IDE/LSP carrier profile: the TSX surface tsgo type-checks
    // (`CompileTarget::IDE == TSX`). `source_map: true` matches the LSP `tsx_profile`
    // and verter-tsc's `generate_all_tsx`. The host normalizes the profile to add
    // the TSX bit internally, so `ensure_ide_compiled` populates exactly the slot
    // `get_ide` peeks.
    let profile = CompileProfile {
        source_map: true,
        target: CompileTarget::IDE,
        ..CompileProfile::default()
    };
    // Oracle extension points (the seams this pins): PERF-1 adds a parallel
    // assertion building this same carrier under HostConfig::batch_typecheck() and
    // asserting byte-equality vs this Full/default golden; PERF-4 adds BareCompiler
    // carrier parity for the single-file-applicable cases.
    host.ensure_ide_compiled(target, &profile)
        .unwrap_or_else(|e| panic!("ensure_ide_compiled failed for {target}: {e:?}"));
    host.get_ide(target, &profile)
        .unwrap_or_else(|| panic!("get_ide returned None for {target}"))
        .code
        .to_string()
}

/// Public-API stub bytes — mirrors the verter-tsc stub stage
/// (`crates/verter_tsc/src/checker.rs:269` upsert idiom + `get_public_api`).
/// `files` are upserted into one host (stable canonical IDs); the stub for
/// `target` is then read. `get_public_api` returns `None` only when the file is
/// not a resolvable carrier — a panic here is a real regression, not flake.
///
/// Defaults to the Full / `HostConfig::default()` preset (the golden baseline).
fn public_api_stub(files: &[(&str, &str, FileLanguage)], target: &str) -> String {
    public_api_stub_with(HostConfig::default(), files, target)
}

/// `public_api_stub` parametrised on the host preset, for the Full-vs-Batch parity
/// test (same cross-component stub under `batch_typecheck()` vs `lsp_interactive()`).
fn public_api_stub_with(
    config: HostConfig,
    files: &[(&str, &str, FileLanguage)],
    target: &str,
) -> String {
    let host = VerterHost::new_standalone(config);
    for (canonical, source, lang) in files {
        let _ = host.upsert(UpsertRequest {
            canonical_id: Some((*canonical).to_string()),
            input_id: (*canonical).to_string(),
            source: Arc::<str>::from(*source),
            file_language: lang.clone(),
            aliases: Vec::new(),
        });
    }
    host.get_public_api(target)
        .unwrap_or_else(|| panic!("get_public_api returned None for {target}"))
        .code
        .to_string()
}

/// CRLF -> LF normalization (cross-platform byte-comparison rule).
///
/// Normalizing (rather than asserting raw CRLF bytes) is MANDATED by the
/// "Cross-Platform Portability (CRITICAL)" rule: byte-equality comparisons over
/// checked-out text must normalize line endings (CRLF<->LF) or compare as text,
/// never raw bytes embedding EOL. `.gitattributes` pins `*.golden eol=lf`; this
/// normalizes BOTH sides so a CRLF checkout of a golden cannot spuriously fail.
fn norm(s: &str) -> String {
    s.replace("\r\n", "\n")
}

// ── Hermetic vendored fixtures (inline; no tsgo, no third-party repos) ──

const STYLE_V_BIND: &str = "<script setup lang=\"ts\">\nconst accent = 'red'\n</script>\n<template><div /></template>\n<style scoped>.x { color: v-bind(accent); }</style>\n";

const CROSS_FILE_TYPES: &str =
    "export interface ChildProps {\n  id: number\n  label: string\n}\nexport interface ChildEmits {\n  (e: 'change', value: number): void\n}\n";

const CROSS_FILE_CHILD: &str = "<script setup lang=\"ts\">\nimport type { ChildProps, ChildEmits } from './types'\ndefineProps<ChildProps>()\ndefineEmits<ChildEmits>()\n</script>\n<template><div /></template>\n";

const WITH_DEFAULTS: &str = "<script setup lang=\"ts\">\ninterface Props {\n  count: number\n  label: string\n}\nwithDefaults(defineProps<Props>(), { count: 0, label: 'hi' })\n</script>\n<template><div /></template>\n";

const SLOTS: &str = "<script setup lang=\"ts\">\ndefineSlots<{\n  default(props: { item: number }): any\n}>()\n</script>\n<template><div /></template>\n";

const GENERICS: &str = "<script setup lang=\"ts\" generic=\"T\">\ndefineProps<{ items: T[]; selected: T }>()\n</script>\n<template><div /></template>\n";

// ── Case 1 — style `v-bind` feeding carrier bytes (THE load-bearing case) ──

/// `accent` is referenced NOWHERE except a `<style> v-bind(accent)`, yet it must
/// stay LIVE: its value-read entry appears in the generated `shallowUnwrapRef`
/// object + the destructure (host side `virtual_file_pipeline.rs` builds
/// `style_v_bind_vars`; codegen side `ide/script/setup.rs` gates omission on
/// usage). Because the carrier is acquired THROUGH the host here, the host's
/// `style_v_bind_vars` extraction is exercised end-to-end: if style-v-bind liveness
/// tracking regresses, `accent` is dropped from the carrier and these bytes vanish
/// -> the golden flips RED. This is the case a later Batch/`--api` block will try to
/// mutate; the golden is tight enough that dropping `accent`'s entry breaks it.
#[test]
fn style_v_bind_ide_carrier_matches_golden() {
    let code = norm(&ide_tsx(
        &[("/proj/Accent.vue", STYLE_V_BIND, FileLanguage::vue())],
        "/proj/Accent.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/style_v_bind.tsx.golden"));
    assert_eq!(
        code, golden,
        "style-v-bind IDE carrier drifted from the golden. If intentional, regenerate \
         tests/carrier_byte_parity/style_v_bind.tsx.golden.\n--- ACTUAL ---\n{code}"
    );
    // Explicit liveness pin: the load-bearing bytes that keep a style-only `accent`
    // live. A regression that drops style-v-bind tracking removes exactly these.
    assert!(
        code.contains("accent: accent as unknown as typeof accent"),
        "REGRESSION: style-only `accent` lost its `shallowUnwrapRef` value-read entry \
         (style-v-bind liveness dropped)\n--- ACTUAL ---\n{code}"
    );
    assert!(
        code.contains("accent } = ___VERTER___unwrapped"),
        "REGRESSION: style-only `accent` lost its destructure binding\n--- ACTUAL ---\n{code}"
    );
}

/// Style-v-bind public-API stub: the cross-component surface for the style-only
/// `accent` SFC. Rail A pins the public-API stub for the other 4 cases; this is the
/// 5th, so stub drift is pinned for the style case too. Captured through the host's
/// `get_public_api` path under `HostConfig::default()`.
#[test]
fn style_v_bind_public_api_stub_matches_golden() {
    let code = norm(&public_api_stub(
        &[("/proj/Accent.vue", STYLE_V_BIND, FileLanguage::vue())],
        "/proj/Accent.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/style_v_bind.stub.golden"));
    assert_eq!(
        code, golden,
        "style-v-bind public-API stub drifted. If intentional, regenerate \
         tests/carrier_byte_parity/style_v_bind.stub.golden.\n--- ACTUAL ---\n{code}"
    );
}

// ── Case 2 — cross-file props/emits (imported types) ──

/// Child IDE carrier: the imported `ChildProps`/`ChildEmits` type refs and the
/// `./types` import must survive into the IDE TSX verbatim. The sibling `./types`
/// is upserted into the SAME host because the host's IDE compile RESOLVES the
/// macro type dependency (`defineProps<ChildProps>()`) end-to-end — a cross-file
/// host behavior a direct `compile()` call never exercises.
#[test]
fn cross_file_props_emits_child_ide_carrier_matches_golden() {
    let code = norm(&ide_tsx(
        &[
            (
                "/proj/types.ts",
                CROSS_FILE_TYPES,
                FileLanguage::script_ts(),
            ),
            ("/proj/Child.vue", CROSS_FILE_CHILD, FileLanguage::vue()),
        ],
        "/proj/Child.vue",
    ));
    let golden = norm(include_str!(
        "carrier_byte_parity/cross_file_child.tsx.golden"
    ));
    assert_eq!(
        code, golden,
        "cross-file child IDE carrier drifted. If intentional, regenerate \
         tests/carrier_byte_parity/cross_file_child.tsx.golden.\n--- ACTUAL ---\n{code}"
    );
}

/// Child public-API stub (the cross-component surface): the props/emits resolved
/// from the sibling `./types.ts` must materialize into the stub. Both files are
/// upserted into one host so the cross-file resolution runs.
#[test]
fn cross_file_props_emits_child_public_api_stub_matches_golden() {
    let code = norm(&public_api_stub(
        &[
            (
                "/proj/types.ts",
                CROSS_FILE_TYPES,
                FileLanguage::script_ts(),
            ),
            ("/proj/Child.vue", CROSS_FILE_CHILD, FileLanguage::vue()),
        ],
        "/proj/Child.vue",
    ));
    let golden = norm(include_str!(
        "carrier_byte_parity/cross_file_child.stub.golden"
    ));
    assert_eq!(
        code, golden,
        "cross-file child public-API stub drifted. If intentional, regenerate \
         tests/carrier_byte_parity/cross_file_child.stub.golden.\n--- ACTUAL ---\n{code}"
    );
}

// ── Case 3 — withDefaults ──

#[test]
fn with_defaults_ide_carrier_matches_golden() {
    let code = norm(&ide_tsx(
        &[("/proj/WithDefaults.vue", WITH_DEFAULTS, FileLanguage::vue())],
        "/proj/WithDefaults.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/with_defaults.tsx.golden"));
    assert_eq!(
        code, golden,
        "withDefaults IDE carrier drifted. If intentional, regenerate \
         tests/carrier_byte_parity/with_defaults.tsx.golden.\n--- ACTUAL ---\n{code}"
    );
}

#[test]
fn with_defaults_public_api_stub_matches_golden() {
    let code = norm(&public_api_stub(
        &[("/proj/WithDefaults.vue", WITH_DEFAULTS, FileLanguage::vue())],
        "/proj/WithDefaults.vue",
    ));
    let golden = norm(include_str!(
        "carrier_byte_parity/with_defaults.stub.golden"
    ));
    assert_eq!(
        code, golden,
        "withDefaults public-API stub drifted. If intentional, regenerate \
         tests/carrier_byte_parity/with_defaults.stub.golden.\n--- ACTUAL ---\n{code}"
    );
}

// ── Case 4 — slots ──

#[test]
fn slots_ide_carrier_matches_golden() {
    let code = norm(&ide_tsx(
        &[("/proj/Slots.vue", SLOTS, FileLanguage::vue())],
        "/proj/Slots.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/slots.tsx.golden"));
    assert_eq!(
        code, golden,
        "slots IDE carrier drifted. If intentional, regenerate \
         tests/carrier_byte_parity/slots.tsx.golden.\n--- ACTUAL ---\n{code}"
    );
}

#[test]
fn slots_public_api_stub_matches_golden() {
    let code = norm(&public_api_stub(
        &[("/proj/Slots.vue", SLOTS, FileLanguage::vue())],
        "/proj/Slots.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/slots.stub.golden"));
    assert_eq!(
        code, golden,
        "slots public-API stub drifted. If intentional, regenerate \
         tests/carrier_byte_parity/slots.stub.golden.\n--- ACTUAL ---\n{code}"
    );
}

// ── Case 5 — generics ──

#[test]
fn generics_ide_carrier_matches_golden() {
    let code = norm(&ide_tsx(
        &[("/proj/Generics.vue", GENERICS, FileLanguage::vue())],
        "/proj/Generics.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/generics.tsx.golden"));
    assert_eq!(
        code, golden,
        "generics IDE carrier drifted. If intentional, regenerate \
         tests/carrier_byte_parity/generics.tsx.golden.\n--- ACTUAL ---\n{code}"
    );
}

#[test]
fn generics_public_api_stub_matches_golden() {
    let code = norm(&public_api_stub(
        &[("/proj/Generics.vue", GENERICS, FileLanguage::vue())],
        "/proj/Generics.vue",
    ));
    let golden = norm(include_str!("carrier_byte_parity/generics.stub.golden"));
    assert_eq!(
        code, golden,
        "generics public-API stub drifted. If intentional, regenerate \
         tests/carrier_byte_parity/generics.stub.golden.\n--- ACTUAL ---\n{code}"
    );
}

// ── Full-vs-Batch parity (the load-bearing Batch-correctness proof) ──

/// For every oracle fixture, a host built with `HostConfig::batch_typecheck()`
/// must produce byte-identical IDE carrier bytes AND public-API stub bytes to a
/// host built with `HostConfig::lsp_interactive()` (the Full / default golden path,
/// the same `ensure_ide_compiled` + `get_ide` / `get_public_api` ship path the
/// goldens above pin). This is the core Batch invariant — Full and Batch emit the
/// SAME carrier bytes — proven directly on the carrier surface.
///
/// Diagnostic-set parity (Rail B, `crates/verter_tsc/tests/diagnostic_set_parity.rs`)
/// follows transitively: Batch keeps the carrier-affecting analysis facts
/// (`AnalysisScope::BUILD` includes STYLE_VBIND/STYLE_SCOPED), so identical carrier
/// + stub bytes under identical scope feed tsgo identical input ⇒ the same
/// diagnostic set. (verter-tsc still runs the default host until it adopts the Batch
/// preset, so a direct Batch diagnostic run is not wireable here.)
///
/// DISCRIMINATING: this parity test guards script-fact scope and
/// query-profile-induced cross-file differences — the `cross_file_child` fixture
/// exercises exactly that, and its pass confirms the default `LspInteractive` query
/// profile yields carrier bytes identical to `Build`. (The STYLE_VBIND
/// analysis-scope membership is pinned separately by the boundary tests in
/// `host_preset_policy.rs`, NOT here: the IDE carrier re-derives style v-bind from
/// the parse, so this test is invariant to that scope bit.)
/// Assert Batch ≡ Full for ONE fixture, on BOTH carrier surfaces (IDE TSX
/// carrier + public-API stub). Factored out so the per-fixture call sites
/// stay a flat list (and clippy's `type_complexity` stays happy).
fn assert_full_batch_parity(label: &str, files: &[(&str, &str, FileLanguage)], target: &str) {
    let full_carrier = norm(&ide_tsx_with(HostConfig::lsp_interactive(), files, target));
    let batch_carrier = norm(&ide_tsx_with(HostConfig::batch_typecheck(), files, target));
    assert_eq!(
        batch_carrier, full_carrier,
        "[{label}] batch_typecheck() IDE carrier bytes must equal lsp_interactive() \
         (Full) carrier bytes\n--- FULL ---\n{full_carrier}\n--- BATCH ---\n{batch_carrier}"
    );

    let full_stub = norm(&public_api_stub_with(
        HostConfig::lsp_interactive(),
        files,
        target,
    ));
    let batch_stub = norm(&public_api_stub_with(
        HostConfig::batch_typecheck(),
        files,
        target,
    ));
    assert_eq!(
        batch_stub, full_stub,
        "[{label}] batch_typecheck() public-API stub bytes must equal lsp_interactive() \
         (Full) stub bytes\n--- FULL ---\n{full_stub}\n--- BATCH ---\n{batch_stub}"
    );
}

#[test]
fn full_vs_batch_carrier_and_stub_byte_parity() {
    assert_full_batch_parity(
        "style_v_bind",
        &[("/proj/Accent.vue", STYLE_V_BIND, FileLanguage::vue())],
        "/proj/Accent.vue",
    );
    assert_full_batch_parity(
        "cross_file_child",
        &[
            (
                "/proj/types.ts",
                CROSS_FILE_TYPES,
                FileLanguage::script_ts(),
            ),
            ("/proj/Child.vue", CROSS_FILE_CHILD, FileLanguage::vue()),
        ],
        "/proj/Child.vue",
    );
    assert_full_batch_parity(
        "with_defaults",
        &[("/proj/WithDefaults.vue", WITH_DEFAULTS, FileLanguage::vue())],
        "/proj/WithDefaults.vue",
    );
    assert_full_batch_parity(
        "slots",
        &[("/proj/Slots.vue", SLOTS, FileLanguage::vue())],
        "/proj/Slots.vue",
    );
    assert_full_batch_parity(
        "generics",
        &[("/proj/Generics.vue", GENERICS, FileLanguage::vue())],
        "/proj/Generics.vue",
    );
}
