//! Architecture guards for the typeinfo wire surface.
//!
//! The wire-side of the typeinfo graph substrate is protobuf-
//! authoritative: Rust DTOs are generated from `.proto` via
//! `prost-build`; TypeScript DTOs are generated from the same
//! `.proto` via the existing protobuf-ts pipeline. `ts-rs` derives
//! are reserved for the audit envelope under `crates/verter_audit`
//! and MUST NOT appear on wire-side typeinfo DTOs. These guards
//! detect a regression where a future contributor reintroduces
//! `ts-rs` on the typeinfo wire-side or hand-edits the generated
//! TypeScript artifact.
//!
//! Discriminating shape: each guard scans a specific source surface
//! and asserts a structural property. Pre-substrate the surfaces do
//! not exist (the typeinfo proto file is the legacy 5-DTO schema,
//! the Rust submodule does not exist) and the scans fail. Post-
//! substrate the scans pass.

use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_root
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must be `<workspace>/crates/verter_session`")
        .to_path_buf()
}

fn read_workspace_file(rel: &str) -> String {
    let path = workspace_root().join(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "guard requires `{}` to exist and be readable: {err}",
            path.display()
        )
    })
}

#[test]
fn typeinfo_wire_dtos_are_proto_authoritative_with_no_ts_rs_derive() {
    let graph = read_workspace_file("crates/verter_protocol/src/typeinfo/graph.rs");
    // The Rust-side wire surface is a re-export module — every DTO
    // type is `pub use wire::...`, NOT a hand-rolled struct with
    // ts-rs derives.
    assert!(
        !graph.contains("ts_rs::TS"),
        "guard: typeinfo wire DTOs MUST NOT carry `ts_rs::TS` derives — \
         the wire surface is protobuf-authoritative",
    );
    assert!(
        !graph.contains("#[ts(export"),
        "guard: typeinfo wire DTOs MUST NOT carry `#[ts(export, ...)]` \
         attributes — `ts-rs` is reserved for the audit envelope",
    );
    // Sanity: the file actually re-exports from the generated module.
    assert!(
        graph.contains("use crate::verter::v1 as wire;"),
        "guard: typeinfo graph submodule must re-export from the prost-generated `wire` module",
    );
}

#[test]
fn verter_protocol_does_not_depend_on_ts_rs() {
    let cargo = read_workspace_file("crates/verter_protocol/Cargo.toml");
    assert!(
        !cargo.contains("ts-rs"),
        "guard: `verter_protocol/Cargo.toml` MUST NOT declare a `ts-rs` \
         dependency — wire DTOs are protobuf-authoritative; ts-rs lives \
         in `verter_audit`",
    );
}

#[test]
fn typeinfo_pb_ts_carries_protoc_gen_es_header() {
    let ts = read_workspace_file("packages/proto/src/gen/verter/v1/typeinfo_pb.ts");
    assert!(
        ts.contains("// @generated by protoc-gen-es"),
        "guard: `typeinfo_pb.ts` MUST be generated by `protoc-gen-es` — \
         a hand-rolled or edited TS surface loses the regenerator's \
         single source of truth",
    );
    assert!(
        ts.contains("@generated from file verter/v1/typeinfo.proto"),
        "guard: `typeinfo_pb.ts` MUST record `verter/v1/typeinfo.proto` \
         as its source file",
    );
}

#[test]
fn typeinfo_proto_carries_graph_substrate_messages() {
    let proto = read_workspace_file("crates/verter_protocol/proto/verter/v1/typeinfo.proto");
    let required = [
        "message SemanticTypeGraph",
        "message GraphTypeNode",
        "message StructuredTypeExpression",
        "message TypeInfoGraphRequest",
        "message TypeInfoGraphResponse",
        "message TypeInfoRequestError",
        "message FrameworkSurfacePayload",
        "message TypeInfoCapabilityHandshakeRequest",
        "message TypeInfoCapabilityHandshakeResponse",
    ];
    let mut missing = Vec::new();
    for need in required {
        if !proto.contains(need) {
            missing.push(need);
        }
    }
    assert!(
        missing.is_empty(),
        "guard: `typeinfo.proto` MUST declare every typeinfo graph substrate \
         message. Missing: {missing:?}",
    );
}

#[test]
fn typeinfo_request_validation_is_a_separate_module() {
    let typeinfo_mod = read_workspace_file("crates/verter_session/src/typeinfo/mod.rs");
    assert!(
        typeinfo_mod.contains("pub mod request_validation;"),
        "guard: the typeinfo module must expose a `request_validation` \
         submodule so validation runs BEFORE semantic execution",
    );

    let validation =
        read_workspace_file("crates/verter_session/src/typeinfo/request_validation.rs");
    // The validator must NOT call into the resolver or the
    // semantic-query engine. It is a shape-only pass that returns a
    // typed `TypeInfoRequestError`. Strip comment lines first so the
    // module's doc-comment references to `SemanticGraphStore::execute`
    // do not trip the guard — the guard targets actual call sites.
    let code_only: String = validation
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            !trimmed.starts_with("//!") && !trimmed.starts_with("///") && !trimmed.starts_with("//")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let banned_calls = [
        "ProjectSemanticDispatch::execute",
        "SemanticGraphStore::execute",
        "SemanticGraphStore::new",
        "FileArtifactStore::",
        ".project_type_store()",
        ".semantic_graph_store()",
        "ResolverContext::new",
    ];
    let mut hits = Vec::new();
    for word in banned_calls {
        if code_only.contains(word) {
            hits.push(word);
        }
    }
    assert!(
        hits.is_empty(),
        "guard: `request_validation.rs` MUST be a shape-only pass — \
         it cannot reach into the semantic execution layer. Banned \
         call patterns found: {hits:?}",
    );
}

/// Extract the `[dependencies]` section of a Cargo manifest as a single
/// string (until the next top-level `[` section header). Used by the
/// dependency-direction guard so a `verter_audit` mention in
/// `[dev-dependencies]` or a doc comment elsewhere does not trip the
/// one-way assertion.
fn manifest_dependencies_section(manifest: &str) -> String {
    let mut out = String::new();
    let mut in_deps = false;
    for line in manifest.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with('[') {
            in_deps = trimmed.starts_with("[dependencies]");
            continue;
        }
        if in_deps {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

#[test]
fn dependency_direction_one_way() {
    // The typeinfo layering is one-way and machine-checked: the
    // protobuf-authoritative wire crate (`verter_protocol`) and the
    // audit substrate (`verter_audit`) are independent leaves. Neither
    // depends on the other, and neither depends on `verter_session`
    // (the host). A back-edge — wire DTOs reaching up into audit/session,
    // or the audit substrate reaching into the wire crate — would form
    // the dependency cycle this guard forbids.
    let protocol = read_workspace_file("crates/verter_protocol/Cargo.toml");
    let audit = read_workspace_file("crates/verter_audit/Cargo.toml");

    let protocol_deps = manifest_dependencies_section(&protocol);
    let audit_deps = manifest_dependencies_section(&audit);

    // (1) The wire crate must NOT depend on the audit substrate or the
    // host session.
    for forbidden in ["verter_audit", "verter_session"] {
        assert!(
            !protocol_deps.contains(forbidden),
            "guard: `verter_protocol` MUST NOT depend on `{forbidden}` — \
             the wire DTO crate is a downstream leaf; a dependency on the \
             audit substrate or the host session inverts the typeinfo \
             layering. Found in `[dependencies]`.",
        );
    }

    // (2) The audit substrate must NOT depend on the wire crate or the
    // host session — it is the leaf-most observability layer (CLAUDE.md
    // leaf rule: `verter_audit` depends only on `verter_span`).
    for forbidden in ["verter_protocol", "verter_session"] {
        assert!(
            !audit_deps.contains(forbidden),
            "guard: `verter_audit` MUST NOT depend on `{forbidden}` — \
             the audit substrate is a leaf and must not back-edge into the \
             wire crate or the host session. Found in `[dependencies]`.",
        );
    }
}

#[test]
fn wire_dtos_generated_only_from_proto() {
    // Every typeinfo wire DTO the Rust side exposes is a `pub use
    // wire::...` re-export of a prost-generated type — NOT a
    // hand-rolled struct/enum declared in `graph.rs`. A contributor who
    // declares a wire DTO by hand (so it is no longer regenerated from
    // the proto) breaks the single source of truth; this guard fails on
    // any `struct`/`enum` definition in the re-export module.
    let graph = read_workspace_file("crates/verter_protocol/src/typeinfo/graph.rs");
    let code_only: String = graph
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            !trimmed.starts_with("//!") && !trimmed.starts_with("///") && !trimmed.starts_with("//")
        })
        .collect::<Vec<_>>()
        .join("\n");

    // The module is a pure re-export layer. It may declare typed
    // constructor helper `fn`s and `const`s, but MUST NOT define a
    // wire `struct`/`enum` (those come from prost). A `pub struct` /
    // `pub enum` / bare `struct` / `enum` declaration would mean a
    // hand-rolled DTO escaped the proto pipeline.
    for forbidden in ["pub struct ", "pub enum ", "\nstruct ", "\nenum "] {
        assert!(
            !code_only.contains(forbidden),
            "guard: the typeinfo wire re-export module `graph.rs` MUST NOT \
             declare a `{}` — wire DTOs are generated from \
             `typeinfo.proto` by prost and re-exported as `pub use wire::...`. \
             A hand-rolled DTO bypasses the proto single-source-of-truth.",
            forbidden.trim(),
        );
    }

    // Positive: the module sources its types from the prost-generated
    // `wire` alias.
    assert!(
        code_only.contains("use crate::verter::v1 as wire;"),
        "guard: `graph.rs` must alias the prost-generated module as `wire` \
         and re-export from it",
    );
    assert!(
        code_only.contains("pub use wire::GraphTypeNode"),
        "guard: `graph.rs` must re-export `GraphTypeNode` from the generated `wire` module",
    );
}

#[test]
fn ts_rs_not_applied_to_wire_dtos() {
    // `ts-rs` is reserved for the audit envelope (`verter_audit` →
    // `audit.generated.ts`). It must NEVER touch the protobuf-
    // authoritative wire surface, whose TypeScript comes from
    // protoc-gen-es. This guard pins BOTH halves: the wire re-export
    // module carries no `ts-rs` derive/attribute, and the wire crate's
    // manifest declares no `ts-rs` dependency.
    let graph = read_workspace_file("crates/verter_protocol/src/typeinfo/graph.rs");
    assert!(
        !graph.contains("ts_rs") && !graph.contains("#[ts("),
        "guard: typeinfo wire DTOs MUST NOT carry any `ts-rs` derive or \
         `#[ts(...)]` attribute — the wire surface is protobuf-authoritative \
         and its TS is generated by protoc-gen-es",
    );
    let cargo = read_workspace_file("crates/verter_protocol/Cargo.toml");
    let cargo_code: String = cargo
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !cargo_code.contains("ts-rs") && !cargo_code.contains("ts_rs"),
        "guard: `verter_protocol/Cargo.toml` MUST NOT declare a `ts-rs` \
         dependency in any dependency table — `ts-rs` lives in `verter_audit`",
    );
}

/// The closed taxonomic discriminant fields that MUST be declared with
/// their named proto enum type, never a raw `uint32`. Each tuple is
/// `(message, field_selector, enum_type)`. A raw-`uint32` discriminant
/// would silently accept any integer on the wire and erase the closed-set
/// guarantee, so the field type is part of the contract.
const CLOSED_ENUM_DISCRIMINANT_FIELDS: &[(&str, &str, &str)] = &[
    ("GraphSymbolNode", "namespace", "GraphSymbolNamespace"),
    ("GraphResolvedDeclSlotIdentity", "namespace", "GraphSymbolNamespace"),
    ("GraphOriginEdge", "kind", "GraphOriginEdgeKind"),
    ("GraphNodeStatus", "exactness", "GraphExactness"),
    ("GraphProjectionReductionContext", "mode", "GraphProjectionMode"),
    ("GraphProjectionReductionContext", "demand", "GraphReductionDemand"),
    ("GraphDiagnostic", "severity", "GraphDiagnosticSeverity"),
];

/// Slice the body of `message <name> { ... }` from the proto source.
fn proto_message_body<'a>(source: &'a str, message_name: &str) -> &'a str {
    let needle = format!("message {message_name} {{");
    let start = source
        .find(&needle)
        .unwrap_or_else(|| panic!("typeinfo.proto must define `message {message_name}`"));
    let body_start = start + needle.len();
    let rest = &source[body_start..];
    let mut depth = 1usize;
    let mut end = rest.len();
    for (i, c) in rest.char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = i;
                    break;
                }
            }
            _ => {}
        }
    }
    &rest[..end]
}

#[test]
fn proto_closed_enums_declared_not_raw_uint32() {
    // Each closed taxonomic discriminant in the typeinfo proto MUST be
    // typed as its named enum, not `uint32`. Discriminating: rewrite
    // e.g. `GraphSymbolNamespace namespace = 3;` to `uint32 namespace = 3;`
    // and this guard fails for that field.
    let proto = read_workspace_file("crates/verter_protocol/proto/verter/v1/typeinfo.proto");
    for (message, field, enum_type) in CLOSED_ENUM_DISCRIMINANT_FIELDS {
        let body = proto_message_body(&proto, message);
        let typed_decl = format!("{enum_type} {field} =");
        let raw_decl = format!("uint32 {field} =");
        assert!(
            body.contains(&typed_decl),
            "guard: `{message}.{field}` MUST be declared as the closed enum \
             `{enum_type}` (`{enum_type} {field} = N;`). A closed taxonomic \
             discriminant typed as anything else loses the closed-set \
             guarantee on the wire.",
        );
        assert!(
            !body.contains(&raw_decl),
            "guard: `{message}.{field}` is declared as a raw `uint32` — a \
             closed taxonomic discriminant MUST use its named enum `{enum_type}`, \
             not `uint32` (which accepts any integer and erases the closed set).",
        );
    }
}

/// Tally `enum <Name> {` declarations in proto source, returning each
/// name's declaration count. Extracted as a pure function so its
/// duplicate-detection can be characterised against a synthetic input
/// (a real duplicate enum cannot compile through prost/protoc, so the
/// only way to discriminate this guard's logic is to feed it a string).
fn proto_enum_declaration_counts(proto: &str) -> std::collections::BTreeMap<String, usize> {
    let mut seen = std::collections::BTreeMap::<String, usize>::new();
    for line in proto.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("enum ") {
            let name = rest
                .split(|c: char| c.is_whitespace() || c == '{')
                .next()
                .unwrap_or_default()
                .trim();
            if !name.is_empty() {
                *seen.entry(name.to_string()).or_insert(0) += 1;
            }
        }
    }
    seen
}

/// Names declared more than once.
fn proto_duplicate_enum_names(
    counts: &std::collections::BTreeMap<String, usize>,
) -> Vec<String> {
    counts
        .iter()
        .filter(|(_, &count)| count > 1)
        .map(|(name, _)| name.clone())
        .collect()
}

#[test]
fn proto_no_duplicate_enum_declarations() {
    // No enum name may be declared twice in the typeinfo proto. A
    // duplicate `enum X { ... }` is a copy-paste merge error that
    // produces an ambiguous wire taxonomy; protoc rejects it at build
    // time with a cryptic message, so this guard surfaces the offending
    // enum name readably. The detection logic's discrimination is
    // characterised by `proto_duplicate_enum_detector_flags_a_repeat`
    // below (a real duplicate cannot compile, so it is fed a synthetic
    // string there).
    let proto = read_workspace_file("crates/verter_protocol/proto/verter/v1/typeinfo.proto");
    let counts = proto_enum_declaration_counts(&proto);
    let duplicates = proto_duplicate_enum_names(&counts);
    assert!(
        duplicates.is_empty(),
        "guard: typeinfo.proto declares one or more enums more than once — \
         a duplicate enum declaration is an ambiguous wire taxonomy. \
         Duplicates: {duplicates:?}",
    );
    // Sanity: the scan actually found the documented enum set (so an
    // empty/zeroed parse can't make the guard pass vacuously).
    assert!(
        counts.len() >= 25,
        "guard: expected the typeinfo proto to declare its full closed-enum \
         set (>= 25 enums); the scanner found only {} — the parse is broken, \
         not the proto.",
        counts.len(),
    );
}

#[test]
fn proto_duplicate_enum_detector_flags_a_repeat() {
    // Characterise the duplicate-enum detector: a real duplicate enum
    // cannot pass protoc, so this proves the guard's logic FAILS on a
    // violating input (and PASSES on a clean one) using synthetic proto
    // text. Without this, `proto_no_duplicate_enum_declarations` could
    // not be shown to discriminate.
    let clean = "enum A { A_X = 0; }\nenum B { B_Y = 0; }\n";
    assert!(
        proto_duplicate_enum_names(&proto_enum_declaration_counts(clean)).is_empty(),
        "clean proto with distinct enums must report no duplicates",
    );
    let dup = "enum A { A_X = 0; }\nenum B { B_Y = 0; }\nenum A { A_Z = 1; }\n";
    let flagged = proto_duplicate_enum_names(&proto_enum_declaration_counts(dup));
    assert_eq!(
        flagged,
        vec!["A".to_string()],
        "a proto declaring `enum A` twice must be flagged with the name `A`",
    );
}

/// The "Part A" typeinfo wire-contract surfaces: the protobuf schema,
/// the Rust re-export module, and the audit-substrate carrier the wire
/// contract pairs with. These read as final-state code and must carry
/// no plan-phase / cutover / codename vocabulary in their comments.
const PART_A_WIRE_SURFACE_FILES: &[&str] = &[
    "crates/verter_protocol/proto/verter/v1/typeinfo.proto",
    "crates/verter_protocol/src/typeinfo/graph.rs",
    "crates/verter_protocol/src/typeinfo.rs",
    "crates/verter_audit/src/audited_result.rs",
];

#[test]
fn part_a_carries_no_phase_archaeology() {
    // The typeinfo wire-contract surfaces must read as final-state, not
    // as a plan changelog. Forbid project-management vocabulary
    // (plan-phase labels, cutover stages, codenames) in their source.
    // Discriminating: drop a `// phase 0a` or `// A0a` comment into the
    // proto or graph.rs and this guard fails naming the file + token.
    let forbidden_tokens = [
        "phase 0a",
        "phase 5",
        "phase 11",
        "post-cutover",
        "pre-cutover",
        "d-cutover",
        "cutover",
        " A0a",
        "U0 ",
        "U11",
        "U12",
        "plan §",
        "Plan §",
    ];
    let mut offenders: Vec<String> = Vec::new();
    for rel in PART_A_WIRE_SURFACE_FILES {
        let contents = read_workspace_file(rel);
        let lower = contents.to_lowercase();
        for token in forbidden_tokens {
            if lower.contains(&token.to_lowercase()) {
                offenders.push(format!("{rel}: contains `{token}`"));
            }
        }
    }
    assert!(
        offenders.is_empty(),
        "guard: the typeinfo wire-contract surfaces must read as final-state \
         and carry no plan-phase / cutover / codename vocabulary. \
         Offenders:\n{}",
        offenders.join("\n"),
    );
}
