//! The two-table manifest ledger for typeinfo full-parity tracking
//! (native-typeinfo-parity §10).
//!
//! Two tables live in this one module:
//!
//! - `IgnoredTestRow` — EXACTLY the 362 ignored test-site rows, one
//!   per `#[ignore = "..."]` annotation inside
//!   `crates/verter_session/src/typeinfo/typeinfo_tests/**/*.rs`,
//!   bijective with the source `#[ignore]`s and count-guarded at 362.
//!   Each row carries the full 13-column schema: `file`, `function`,
//!   `substrate`, `capability`, `organ`, `owning_u_block`, `block_id`,
//!   `semantic_queries`, `proof`, `status`, `mechanism_id`,
//!   `consumed_mechanisms`, `unblocker`.
//! - `AdditionalProofRow` — the CLOSED set of 7 coverage-only rows (the
//!   6 JSX no-new-key submatrix rows owned by `U2.JSX_FOUNDATIONS` + the
//!   1 mapped companion owned by `U2.MAPPED_TEMPLATE`). Same schema
//!   minus `status` / `unblocker`; EXCLUDED from the ignored count +
//!   bijection.
//!
//! Both tables, the `TYPEINFO_PARITY_BLOCKS` DAG, and every per-column
//! value are GENERATED by `scripts/gen-typeinfo-ignore-manifest.py`
//! (`pnpm gen:typeinfo-manifest`) from the authoritative §10.4.1
//! row→block partition joined with the live `#[ignore]` discovery + the
//! Capability Map. The guards below only diff/fail — they never write
//! the generated source (repo rule: generators are scripts, not tests).
//!
//! `EXPECTED_TOTAL_IGNORED_COUNT` is DERIVED as
//! `count(IgnoredTestRow where status == Ignored)` (§10.5), not a
//! frozen literal; it tracks the live ignore set as blocks lift rows
//! (and as same-file overload retention adds new ones) and currently
//! resolves to 362.
//!
//! Guards:
//!
//! Carried-forward bijection / quality guards
//! (`every_ignored_typeinfo_test_has_a_manifest_row`,
//! `every_manifest_row_corresponds_to_a_live_ignored_test`,
//! `every_manifest_row_lists_a_valid_substrate`,
//! `every_manifest_row_has_non_empty_unblocker`,
//! `every_manifest_row_unblocker_matches_live_ignore_reason`,
//! `per_file_ignored_test_counts_match_manifest`,
//! `total_ignored_typeinfo_test_count_matches_expected`,
//! `manifest_length_matches_documented_total`,
//! `every_ignored_typeinfo_test_carries_a_reason_string`,
//! `every_ignore_reason_meets_minimum_quality_bar`) plus the new
//! two-table ledger guards:
//!
//! - `ignored_test_row_table_holds_exactly_362_rows` (binding total +
//!   disjointness vs `AdditionalProofRow`),
//! - `additional_proof_row_table_holds_exactly_7_rows` (closed set),
//! - `typeinfo_parity_block_dag_is_acyclic_and_consumed_keys_and_mechanisms_are_prereqs`
//!   (§11.5 — block-DAG acyclicity + consumed-key + consumed-mechanism
//!   prerequisite consistency).

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use verter_session::semantic_query::SemanticQueryKeyTag;

fn workspace_root() -> PathBuf {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_root
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must be `<workspace>/crates/verter_session`")
        .to_path_buf()
}

fn typeinfo_tests_dir() -> PathBuf {
    workspace_root().join("crates/verter_session/src/typeinfo/typeinfo_tests")
}

/// Closed-enum classifier naming the substrate landing that will
/// unblock a specific ignored test. Adding an ignored test that does
/// not fit any existing variant requires adding a new variant in
/// the same change (and naming the substrate in the unblocker
/// column).
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum TargetSubstrate {
    /// String / Number / Boolean / Object prototype apparent-type
    /// dispatch.
    ApparentTypes,
    /// Audit-side footprint accounting for typeinfo entry-points.
    AuditFootprint,
    /// Cache-invalidation classes the typeinfo store has to honor.
    CacheInvalidation,
    /// Call signature / overload / generic call resolution.
    CallResolution,
    /// Class member projection, decorators, accessibility, static side.
    ClassFeatures,
    /// Composite surface scenarios (menu-like, table-like, message
    /// list, etc.) that combine multiple substrates.
    CompositeSurfaces,
    /// Conditional / infer / recursive-conditional resolution.
    ConditionalInfer,
    /// Contextual typing — narrowing through call-site context.
    ContextualTyping,
    /// Cross-file (multi-module) type resolution.
    CrossFileResolution,
    /// Demand boundary contracts (Identity / Navigate / Shallow /
    /// Expanded / Skeleton query-mode dispatch).
    DemandBoundary,
    /// Enum literal projection and bridging.
    EnumResolution,
    /// Expansion boundary scenarios (budget, depth, generic
    /// instantiation cap).
    ExpansionBoundaries,
    /// Flow narrowing (discriminated union, equality, in-operator,
    /// instanceof, truthiness, typeof, and the broader narrowing
    /// substrate).
    FlowNarrowing,
    /// Index signature projection and key-kind taxonomy.
    IndexSignatures,
    /// JSX intrinsic / component-binding resolution.
    JsxResolution,
    /// Macro-aware resolution for `defineProps` / `defineEmits` /
    /// `defineSlots` / `defineOptions` / `withDefaults`.
    MacroResolution,
    /// Mapped type modifiers + name remap + template literal name
    /// transformation.
    MappedTypes,
    /// Identity / Navigate / Shallow / Expanded / Skeleton
    /// projection-mode boundary invariants.
    ModeBoundary,
    /// Modern TS feature coverage (variance, const-tp, etc.).
    ModernTsFeatures,
    /// Module-level surfaces (ambient module / namespace / module
    /// augmentation).
    ModuleFeatures,
    /// Path projection (deep indexed-access + utility-type chains).
    PathProjection,
    /// Relation-step semantics (assignability, equality, identity).
    RelationSemantics,
    /// Template literal type inference + name-remap interplay.
    TemplateLiteralInference,
    /// Tuple labelling / variadic / rest spread.
    TupleFeatures,
    /// Type parameter features (substitution types, const, variance).
    TypeParameterFeatures,
    /// Direct TypeScript-rule fidelity (assignability, structural
    /// matching, etc.).
    TypeScriptRules,
    /// Union distribution and key-access surfaces.
    UnionDistribution,
    /// Unique-symbol identity and projection.
    UniqueSymbol,
    /// Pick / Omit / Required / Partial / Exclude / Extract / etc.
    UtilityComposition,
    /// Value-side inference (typeof, contextual return shaping).
    ValueInference,
}

// ──────────────────────────────────────────────────────────────────
// The two-table manifest ledger schema (native-typeinfo-parity §10).
//
// `IgnoredTestRow` carries the EXACT 362 ignored test-site rows
// (count-guarded, bijective with the source `#[ignore]`s).
// `AdditionalProofRow` carries the CLOSED set of 7 coverage-only rows
// (6 JSX no-new-key submatrix + 1 mapped companion) — excluded from the
// ignored count + bijection. Both tables and the per-column data are
// generated by `scripts/gen-typeinfo-ignore-manifest.py` from the
// authoritative §10.4.1 row→block partition + the Capability Map; the
// guards below only diff/fail, never write the generated source.
// ──────────────────────────────────────────────────────────────────

/// The capability class a manifest row exercises (parity Capability
/// Map §~3735). Mirrors the per-substrate capability classes; closed
/// set, non-placeholder.
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum TypeInfoCapability {
    ApparentTypes,
    AuditFootprint,
    CacheInvalidation,
    CallResolution,
    ClassFeatures,
    CompositeSurfaces,
    ConditionalInfer,
    ContextualTyping,
    CrossFileResolution,
    DemandBoundary,
    EnumResolution,
    ExpansionBoundaries,
    FlowNarrowing,
    IndexSignatures,
    JsxResolution,
    MacroResolution,
    MappedTypes,
    ModeBoundary,
    ModernTsFeatures,
    ModuleFeatures,
    PathProjection,
    RelationSemantics,
    TemplateLiteralInference,
    TupleFeatures,
    TypeParameterFeatures,
    TypeScriptRules,
    UnionDistribution,
    UniqueSymbol,
    UtilityComposition,
    ValueInference,
}

/// The architecture ORGAN a row's owning block lives in — the
/// mechanism-first decomposition (§10.4.1 framing): foundation / cache
/// / wire → relation+inference engine → type constructors/reducers →
/// flow/call solver → projection/session/adapters. Closed set.
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum ArchitectureOrgan {
    /// U0 ledger / coverage / proof substrate.
    LedgerSubstrate,
    /// U2 typed `SemanticQueryValue` + added-key foundation.
    QueryValueDomain,
    /// U2.RELATION_INFER — the relation / inference keystone.
    RelationInferenceEngine,
    /// U2 reducers (indexed-access, mapped/template, class, enum,
    /// utilities, module-augmentation, JSX foundations).
    TypeConstructorReducers,
    /// U6 — the demand-sliced flow / narrowing / call solver.
    FlowCallSolver,
    /// U3 — cache / fact model + typed admission rails.
    CacheFactModel,
    /// U8 — wire-surface closure.
    WireSurface,
    /// U10 — result DB + mode/demand/expansion exactness.
    ResultDb,
    /// U12 — exporter.
    Exporter,
    /// U11 — public relation / session surfaces.
    PublicSession,
    /// U13 — published projection.
    Projection,
    /// U14 — framework macro adapter.
    FrameworkAdapter,
    /// U15 — terminal composite-surface final lift.
    FinalLift,
}

/// Parent / aggregate U-block token (§11.9). A row's `owning_u_block`
/// is the PARENT of its `block_id` (e.g. `U2.UTILITIES` → `U2`).
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum UBlock {
    U0,
    U2,
    U3,
    U6,
    U8,
    U10,
    U11,
    U12,
    U13,
    U14,
    U15,
}

/// The child `block_id` that OWNS lifting a row (§10.4.1 partition).
/// Closed set: the 29 row-owning blocks PLUS the 5 zero-row substrate
/// blocks (`U0.MANIFEST_SUBSTRATE`, `U2.QUERY_VALUE_DOMAIN`,
/// `U8.WIRE_SURFACE_CLOSURE`, `U12.EXPORTER`, `U13.PROJECTION`).
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord, Hash)]
#[allow(dead_code)]
enum TypeInfoParityBlockId {
    // Zero-row substrate blocks (own no `IgnoredTestRow`s).
    U0ManifestSubstrate,
    U2QueryValueDomain,
    U8WireSurfaceClosure,
    U12Exporter,
    U13Projection,
    // U2 reducer blocks.
    U2RelationInfer,
    U2Utilities,
    U2IndexedAccess,
    U2MappedTemplate,
    U2ClassSurfaces,
    U2Enums,
    U2ModuleAugmentation,
    U2JsxFoundations,
    // U6 flow / call solver blocks.
    U6FlowReturnSubstrate,
    U6NarrowTypeof,
    U6NarrowEquality,
    U6NarrowTruthiness,
    U6NarrowIn,
    U6NarrowInstanceof,
    U6NarrowDiscriminated,
    U6NarrowSubstitution,
    U6NarrowInvalidation,
    U6PredicateAssertion,
    U6CallResolve,
    U6ContextualCallback,
    U6ValueInference,
    U6AsyncGenerator,
    U6CrossFile,
    U6LoopClosure,
    // Cache / result / session / projection / adapter blocks.
    U3CacheFactModel,
    U10ResultDb,
    U11PublicRelationSession,
    U14MacroAdapter,
    U15FinalLift,
}

/// Declares the name-only [`SemanticQueryName`] mirror enum, its
/// declaration-order witness array [`SEMANTIC_QUERY_NAME_ALL`], and an
/// exhaustive variant→name source ([`semantic_query_name_str`]) from ONE
/// variant list, so the three CANNOT diverge.
///
/// This is the enforcement mechanism behind the
/// `semantic_query_name_mirror_matches_live_tag_set` guard's drift claim:
/// because the enum, the array, and the name source are all expanded from the
/// same `$variant` token list, adding a `SemanticQueryName` variant WITHOUT
/// listing it in the array is structurally impossible — there is no second
/// place to forget. (Without this, the `#[allow(dead_code)]` enum would let an
/// array-less variant pass both the dead-code lint and the array-reading
/// guard.)
macro_rules! semantic_query_names {
    ($($variant:ident),+ $(,)?) => {
        /// The live `SemanticQueryKey` variant set, mirrored as a name-only
        /// closed enum (the U0 ledger keys queries by NAME — no payloads).
        /// Kept in sync — variant-for-variant — with the live
        /// [`verter_session::semantic_query::SemanticQueryKeyTag`] discriminant
        /// set (`SemanticQueryKeyTag::ALL`). The
        /// `semantic_query_name_mirror_matches_live_tag_set` guard FAILS if this
        /// mirror omits (or invents) any live tag, so the mirror can never
        /// silently drift behind the live key surface and the block-DAG guard's
        /// consumed-key check (`key_owning_block`) can never false-pass for a
        /// key the mirror does not yet name. That guard verifies EXACTLY ONE
        /// thing — the mirror name set ([`SEMANTIC_QUERY_NAME_ALL`] mapped
        /// through [`semantic_query_name_str`]) is bijective with the live
        /// `SemanticQueryKeyTag::ALL` name set. It does NOT, on its own, detect
        /// an enum variant that exists but is missing from the array (two
        /// distinct protections cover that): the `semantic_query_names!` macro
        /// generates this enum, its witness array, and `semantic_query_name_str`
        /// from the SAME variant token list, so a variant present in the enum but
        /// absent from the array is impossible by construction — there is no
        /// second place to forget; and the exhaustive (wildcard-free)
        /// [`key_owning_block`] match forces a new arm for every added variant
        /// or fails to compile. Later U-blocks that add keys extend the single
        /// `semantic_query_names!` invocation (and add a `key_owning_block`
        /// arm).
        #[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord, Hash)]
        #[allow(dead_code)]
        enum SemanticQueryName {
            $($variant),+
        }

        /// Every [`SemanticQueryName`] mirror variant, in live-tag declaration
        /// order. This is the witness the
        /// `semantic_query_name_mirror_matches_live_tag_set` guard diffs against
        /// `SemanticQueryKeyTag::ALL`: a live tag missing here (or an entry here
        /// with no live tag) FAILS the guard. The array is GENERATED from the
        /// same `semantic_query_names!` variant list as the enum, so a variant
        /// can never be present in the enum but absent from the array — the
        /// array and the enum stay aligned by construction (one token list),
        /// then aligned with the live tag set by the guard.
        const SEMANTIC_QUERY_NAME_ALL: &[SemanticQueryName] =
            &[$(SemanticQueryName::$variant),+];

        /// Exhaustive (wildcard-free) variant→name source for the mirror.
        /// Generated from the same `semantic_query_names!` variant list, so it
        /// names every variant and stays a single source of the variant set.
        /// The guard maps the witness array through this fn (not `Debug`), so a
        /// name here is the one the array contributes to the live-tag diff.
        fn semantic_query_name_str(name: SemanticQueryName) -> &'static str {
            match name {
                $(SemanticQueryName::$variant => stringify!($variant)),+
            }
        }
    };
}

semantic_query_names! {
    ResolveDecl,
    Instantiate,
    ProjectMember,
    IndexedAccess,
    KeyOf,
    MappedType,
    Conditional,
    TypeOf,
    NormalizeUnion,
    NormalizeIntersection,
    ProjectPath,
    ResolvedNamedType,
    Relate,
    ResolveMacroPayload,
    ResolveClassSurface,
    ResolveAmbientNamespace,
    ResolveEnum,
    ResolveOverloadSet,
    ApparentType,
    TemplateLiteralReduce,
    FlowNarrowingAt,
    ContextualTypeAt,
}

/// Deterministic identifier for a generated TS7 oracle snapshot. Closed
/// set: one per oracle-backed capability family.
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum OracleId {
    UtilityComposition,
    MappedTemplate,
    IndexedAccess,
    EnumProjection,
    ClassSurface,
    ApparentType,
    TupleProjection,
    ConditionalInfer,
    RelationSemantics,
    TemplateLiteral,
    FlowNarrowing,
    CallResolution,
    ContextualTyping,
    ValueInference,
    JsxResolution,
    ModuleAugmentation,
    CompositeSurface,
}

/// Deterministic identifier for a structural / negative guard test.
/// Closed set; non-placeholder.
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
#[allow(dead_code)]
enum GuardId {
    ModeBoundaryExactness,
    ExpansionBoundaryPrecision,
    DemandBoundaryPrecision,
    CacheInvalidationRoute,
    AuditFootprintAttachment,
    CrossFileRouteFact,
}

/// The dominant architecture MECHANISM that lifts a row (§11.5). Each
/// `block_id` OWNS exactly one mechanism; `mechanism_owning_block`
/// maps each mechanism back to its block. Non-placeholder.
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord, Hash)]
#[allow(dead_code)]
enum MechanismId {
    // Zero-row substrate mechanisms.
    LedgerCoverageGate,
    QueryValueDomainFoundation,
    WireSurfaceClosure,
    ExporterPublication,
    StructuralProjectionDecode,
    // U2 reducer mechanisms.
    RelateCoinductiveScc,
    UtilityGraphReduction,
    IndexedAccessUnionDistribution,
    MappedTemplateRemap,
    ClassSurfaceProjection,
    EnumValueTypeDuality,
    ResolveDeclarationAugmentation,
    ResolveAmbientNamespaceJsx,
    // U6 flow / call mechanisms.
    ReturnPathPeekerTwoFrontier,
    FlowNarrowingFrameTypeof,
    FlowNarrowingFrameEquality,
    FlowNarrowingFrameTruthiness,
    FlowNarrowingFrameIn,
    FlowNarrowingFrameInstanceof,
    FlowNarrowingFrameDiscriminated,
    FlowNarrowingFrameSubstitution,
    FlowNarrowingFrameInvalidation,
    PredicateAssertionEffect,
    ResolveCallDispatch,
    ContextualCallbackInference,
    ValueInferenceWidening,
    AsyncGeneratorCarrier,
    CrossFileRouteFact,
    LoopClosureFixedPoint,
    // Cache / result / session / adapter mechanisms.
    CacheFactModelAdmission,
    ResultDbModeDemandExactness,
    PublicSessionFootprintInvalidation,
    MacroSurfaceAdapter,
    CompositeSurfaceFinalLift,
}

/// Lifecycle status of an ignored test row (§10.1). Binary — there is
/// no tracked `Verifying` transient; the in-flight state is the block's
/// unmerged branch.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[allow(dead_code)]
enum IgnoreStatus {
    Ignored,
    Lifted { block_id: TypeInfoParityBlockId },
}

/// The executable proof a row resolves to (§10.2). There is NO
/// `NotTsOracleApplicable` escape hatch — every row resolves to an
/// executable artifact.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[allow(dead_code)]
enum ProofRequirement {
    Ts7Oracle(OracleId),
    StructuralGuard(GuardId),
    NegativeGuard(GuardId),
    OracleAndGuard {
        oracle: OracleId,
        guard: GuardId,
    },
    RowTestGuard {
        file: &'static str,
        function: &'static str,
    },
}

/// One manifest row per ignored typeinfo test — EXACTLY the 362
/// ignored test-site rows (§10.1). 13 fields.
#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
struct IgnoredTestRow {
    file: &'static str,
    function: &'static str,
    substrate: TargetSubstrate,
    capability: TypeInfoCapability,
    organ: ArchitectureOrgan,
    owning_u_block: UBlock,
    block_id: TypeInfoParityBlockId,
    semantic_queries: &'static [SemanticQueryName],
    proof: ProofRequirement,
    status: IgnoreStatus,
    mechanism_id: MechanismId,
    consumed_mechanisms: &'static [MechanismId],
    unblocker: &'static str,
}

/// One coverage-only row — the CLOSED set of 7 forward-declaration
/// coverage contracts (§10.1). 11 fields (= 13 minus `status` and
/// `unblocker`). Excluded from the ignored count + bijection.
#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
struct AdditionalProofRow {
    file: &'static str,
    function: &'static str,
    substrate: TargetSubstrate,
    capability: TypeInfoCapability,
    organ: ArchitectureOrgan,
    owning_u_block: UBlock,
    block_id: TypeInfoParityBlockId,
    semantic_queries: &'static [SemanticQueryName],
    proof: ProofRequirement,
    mechanism_id: MechanismId,
    consumed_mechanisms: &'static [MechanismId],
}

/// One block-contract row (§9 / §11.5). Pins the block prerequisite
/// DAG (`prereqs`) + the block's dominant `mechanism_id` and
/// `consumed_mechanisms`, plus the §9 contract metadata the parent requires
/// (`native-typeinfo-parity.md` §9): the `required_guards` the block must
/// carry green before it lands and the `verification_labels` (verification
/// command labels) it runs. `required_guards` is the COMPLETE
/// forward-declared required-guard set transcribed VERBATIM from the
/// "Required new guards" section of the block's owning subplan doc — NOT a
/// representative subset or arbitrary truncation. For a not-yet-landed block
/// these are forward declarations (the block FINALIZES and verifies them
/// live+green when it lands, via the deferred §11.5
/// `landed_typeinfo_blocks_have_required_guards` done-predicate — that
/// landing-enforcement guard itself lands in a later substrate block). The
/// list is authored in `scripts/gen-typeinfo-ignore-manifest.py`
/// (`BLOCK_TO_REQUIRED_GUARDS`) and regenerated into
/// `manifest_data/typeinfo_parity_blocks.rs`; row/test names and
/// doc-marked-not-landed phantom names are excluded. The
/// `every_block_contract_row_carries_required_guards` guard here pins only
/// that every block CARRIES non-empty, deduplicated labels.
#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
struct BlockContractRow {
    block_id: TypeInfoParityBlockId,
    owning_u_block: UBlock,
    organ: ArchitectureOrgan,
    prereqs: &'static [TypeInfoParityBlockId],
    mechanism_id: MechanismId,
    consumed_mechanisms: &'static [MechanismId],
    required_guards: &'static [&'static str],
    verification_labels: &'static [&'static str],
}

/// The single block that OWNS (produces) each `SemanticQueryName`
/// (§11.5). Owners follow the mechanism-first layering — the block whose
/// dominant mechanism PRODUCES the key's result, NOT where the key's shape
/// was first declared:
/// - foundational decl/value keys at `U2.QUERY_VALUE_DOMAIN` (incl.
///   `ApparentType`, the lib-fact apparent-member lookup that has no dedicated
///   reducer block);
/// - relation / instantiation / conditional at `U2.RELATION_INFER`;
/// - indexed-access / keyof / member / path at `U2.INDEXED_ACCESS`;
/// - mapped + template-literal reduction at `U2.MAPPED_TEMPLATE`;
/// - class-surface projection at `U2.CLASS_SURFACES`;
/// - enum value/type duality at `U2.ENUMS`;
/// - ambient-namespace (JSX foundation) at `U2.JSX_FOUNDATIONS`;
/// - overload-set / call dispatch at `U6.CALL_RESOLVE`;
/// - flow narrowing at `U6.FLOW_RETURN_SUBSTRATE` (the flow-frame substrate
///   every narrowing mechanism composes on);
/// - contextual typing at `U6.CONTEXTUAL_CALLBACK`;
/// - macro payload at `U14.MACRO_ADAPTER`.
fn key_owning_block(key: SemanticQueryName) -> TypeInfoParityBlockId {
    use SemanticQueryName::*;
    use TypeInfoParityBlockId::*;
    match key {
        ResolveDecl
        | TypeOf
        | NormalizeUnion
        | NormalizeIntersection
        | ResolvedNamedType
        | ApparentType => U2QueryValueDomain,
        Relate | Instantiate | Conditional => U2RelationInfer,
        IndexedAccess | KeyOf | ProjectMember | ProjectPath => U2IndexedAccess,
        MappedType | TemplateLiteralReduce => U2MappedTemplate,
        ResolveClassSurface => U2ClassSurfaces,
        ResolveEnum => U2Enums,
        ResolveAmbientNamespace => U2JsxFoundations,
        ResolveOverloadSet => U6CallResolve,
        FlowNarrowingAt => U6FlowReturnSubstrate,
        ContextualTypeAt => U6ContextualCallback,
        ResolveMacroPayload => U14MacroAdapter,
    }
}

/// The single block that OWNS (produces) each `MechanismId` (§11.5).
/// Each `block_id` owns exactly one dominant mechanism, so this is the
/// inverse of `BlockContractRow.mechanism_id`.
fn mechanism_owning_block(mech: MechanismId) -> TypeInfoParityBlockId {
    use MechanismId::*;
    use TypeInfoParityBlockId::*;
    match mech {
        LedgerCoverageGate => U0ManifestSubstrate,
        QueryValueDomainFoundation => U2QueryValueDomain,
        WireSurfaceClosure => U8WireSurfaceClosure,
        ExporterPublication => U12Exporter,
        StructuralProjectionDecode => U13Projection,
        RelateCoinductiveScc => U2RelationInfer,
        UtilityGraphReduction => U2Utilities,
        IndexedAccessUnionDistribution => U2IndexedAccess,
        MappedTemplateRemap => U2MappedTemplate,
        ClassSurfaceProjection => U2ClassSurfaces,
        EnumValueTypeDuality => U2Enums,
        ResolveDeclarationAugmentation => U2ModuleAugmentation,
        ResolveAmbientNamespaceJsx => U2JsxFoundations,
        ReturnPathPeekerTwoFrontier => U6FlowReturnSubstrate,
        FlowNarrowingFrameTypeof => U6NarrowTypeof,
        FlowNarrowingFrameEquality => U6NarrowEquality,
        FlowNarrowingFrameTruthiness => U6NarrowTruthiness,
        FlowNarrowingFrameIn => U6NarrowIn,
        FlowNarrowingFrameInstanceof => U6NarrowInstanceof,
        FlowNarrowingFrameDiscriminated => U6NarrowDiscriminated,
        FlowNarrowingFrameSubstitution => U6NarrowSubstitution,
        FlowNarrowingFrameInvalidation => U6NarrowInvalidation,
        PredicateAssertionEffect => U6PredicateAssertion,
        ResolveCallDispatch => U6CallResolve,
        ContextualCallbackInference => U6ContextualCallback,
        ValueInferenceWidening => U6ValueInference,
        AsyncGeneratorCarrier => U6AsyncGenerator,
        CrossFileRouteFact => U6CrossFile,
        LoopClosureFixedPoint => U6LoopClosure,
        CacheFactModelAdmission => U3CacheFactModel,
        ResultDbModeDemandExactness => U10ResultDb,
        PublicSessionFootprintInvalidation => U11PublicRelationSession,
        MacroSurfaceAdapter => U14MacroAdapter,
        CompositeSurfaceFinalLift => U15FinalLift,
    }
}

include!("manifest_data/typeinfo_ignored_test_manifest_rows.rs");
include!("manifest_data/typeinfo_additional_proof_rows.rs");
include!("manifest_data/typeinfo_parity_blocks.rs");

/// `const fn` count of `IgnoredTestRow`s whose `status == Ignored`.
/// This is the DERIVED source of `EXPECTED_TOTAL_IGNORED_COUNT` — it is
/// NOT a frozen literal (§10.5). A block branch that flips its rows
/// `Ignored → Lifted` decrements this automatically in the same branch,
/// so every committed state is count-consistent.
const fn count_ignored_rows(rows: &[IgnoredTestRow]) -> usize {
    let mut count = 0usize;
    let mut i = 0usize;
    while i < rows.len() {
        if matches!(rows[i].status, IgnoreStatus::Ignored) {
            count += 1;
        }
        i += 1;
    }
    count
}

/// Total ignored typeinfo test sites — DERIVED as
/// `count(IgnoredTestRow where status == Ignored)`, NOT a frozen
/// literal (§10.5). It tracks the live ignore set — currently 362,
/// recomputed as blocks lift rows and as same-file overload retention
/// adds new ones; every current `IgnoredTestRow` carries
/// `status: Ignored`.
///
/// Why 362 not 384: the substrate's macro-driven test families emit
/// expanded `#[ignore = "..."]` annotations at their call sites;
/// those expansion sites ARE counted (they are real ignore
/// annotations). What the manifest does NOT count are the
/// `#[ignore = $reason]` patterns INSIDE `macro_rules!` bodies —
/// those describe how the macro expands, not the test sites
/// themselves. The macro-defined raw count includes 22 such
/// in-macro-body lines that are not test sites; the live tree has
/// 362 expanded test-site ignores, which is the number every guard
/// below operates against.
const EXPECTED_TOTAL_IGNORED_COUNT: usize = count_ignored_rows(EXPECTED_IGNORE_MANIFEST);

/// Reason-strings shorter than this are rejected — every
/// `#[ignore = "..."]` must carry a meaningful sentence.
const MIN_REASON_LENGTH: usize = 16;

fn read_dir_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(err) => panic!("read_dir {}: {err}", dir.display()),
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file()
            && path
                .extension()
                .and_then(|e| e.to_str())
                .map(|ext| ext == "rs")
                .unwrap_or(false)
        {
            out.push(path);
        }
    }
    out.sort();
    out
}

/// Extract `(reason, fn_name)` for every literal-string
/// `#[ignore = "..."]` annotation in `source`. The function name is
/// the next `fn <name>` token after the annotation (up to ~5 lines
/// of attribute stacking — `#[test]`, `#[ignore]`, doc-comments).
/// Bare `#[ignore]` (without a reason) is counted in the `bare`
/// return value so the guard rejects it.
///
/// Macro-defined patterns (`#[ignore = $reason]` inside a
/// `macro_rules!` body) are not test sites; they describe the
/// macro's expansion. Each expansion eventually emits a real
/// `#[ignore = "..."]` annotation that the parser counts at its
/// expansion site.
fn extract_ignored_test_sites(source: &str) -> (Vec<(String, String)>, usize) {
    let mut sites = Vec::new();
    let mut bare = 0usize;
    let lines: Vec<&str> = source.lines().collect();
    for (i, raw_line) in lines.iter().enumerate() {
        let line = raw_line.trim();
        if let Some(rest) = line.strip_prefix("#[ignore") {
            let rest = rest.trim_start();
            if let Some(after_eq) = rest.strip_prefix("=") {
                let after_eq = after_eq.trim_start();
                if let Some(after_quote) = after_eq.strip_prefix('"') {
                    if let Some(end) = after_quote.rfind('"') {
                        let reason = after_quote[..end].to_string();
                        // Scan forward for the next `fn <name>` line.
                        let mut fn_name: Option<String> = None;
                        let look_end = (i + 6).min(lines.len());
                        for next_line in lines.iter().take(look_end).skip(i + 1) {
                            if let Some(name) = parse_fn_name(next_line) {
                                fn_name = Some(name);
                                break;
                            }
                        }
                        if let Some(name) = fn_name {
                            sites.push((reason, name));
                        }
                        continue;
                    }
                }
                // Macro-body `#[ignore = $reason]` — skip.
                continue;
            }
            if line.starts_with("#[ignore]") || line.starts_with("#[ignore ") {
                bare += 1;
            }
        }
    }
    (sites, bare)
}

/// Parse the function name from a line of the form
/// `(async? )?(pub )?(async )?fn <name>(`.
fn parse_fn_name(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    let after_async = trimmed.strip_prefix("async ").unwrap_or(trimmed);
    let after_pub = after_async.strip_prefix("pub ").unwrap_or(after_async);
    let after_async = after_pub.strip_prefix("async ").unwrap_or(after_pub);
    let after_const = after_async.strip_prefix("const ").unwrap_or(after_async);
    let after_fn = after_const.strip_prefix("fn ")?;
    let name_end = after_fn
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
        .unwrap_or(after_fn.len());
    if name_end == 0 {
        return None;
    }
    Some(after_fn[..name_end].to_string())
}

#[test]
fn every_ignored_typeinfo_test_carries_a_reason_string() {
    let dir = typeinfo_tests_dir();
    assert!(
        dir.exists(),
        "typeinfo_tests directory must exist at {}",
        dir.display(),
    );
    let mut total_bare = 0usize;
    for path in read_dir_files(&dir) {
        let source = fs::read_to_string(&path).expect("read file");
        let (_sites, bare) = extract_ignored_test_sites(&source);
        if bare > 0 {
            panic!(
                "ignored-test manifest: {} contains {bare} bare `#[ignore]` \
                 annotation(s) without a reason string. Add a structured \
                 reason explaining which substrate change unblocks the test.",
                path.display(),
            );
        }
        total_bare += bare;
    }
    assert_eq!(total_bare, 0);
}

#[test]
fn every_ignore_reason_meets_minimum_quality_bar() {
    let dir = typeinfo_tests_dir();
    let mut violators: Vec<(String, String)> = Vec::new();
    for path in read_dir_files(&dir) {
        let source = fs::read_to_string(&path).expect("read file");
        let (sites, _bare) = extract_ignored_test_sites(&source);
        for (reason, _fn_name) in sites {
            if reason.len() < MIN_REASON_LENGTH {
                violators.push((
                    path.file_name().unwrap().to_string_lossy().into_owned(),
                    reason,
                ));
                continue;
            }
            let lc = reason.to_lowercase();
            let mentions_subject = [
                "typeinfo",
                "graph",
                "narrow",
                "contract",
                "future",
                "publish",
                "support",
                "scenario",
                "macro",
                "resolution",
                "resolve",
                "type",
                "node",
                "carry",
                "infer",
                "shape",
                "lift",
                "regression",
                "ignore",
                "match",
                "expansion",
                "mapped",
                "predicate",
                "instantiation",
                "narrowing",
                "envelope",
                "decl",
                "snapshot",
                "substrate",
                "landing",
            ]
            .iter()
            .any(|needle| lc.contains(needle));
            if !mentions_subject {
                violators.push((
                    path.file_name().unwrap().to_string_lossy().into_owned(),
                    reason,
                ));
            }
        }
    }
    if !violators.is_empty() {
        panic!(
            "ignored-test manifest: {} reason string(s) fail the minimum \
             quality bar:\n  {}",
            violators.len(),
            violators
                .iter()
                .map(|(f, r)| format!("{f}: \"{}\"", r))
                .collect::<Vec<_>>()
                .join("\n  "),
        );
    }
}

/// Collect the live `(file, function)` set from the typeinfo
/// test source tree.
fn collect_live_ignored_sites() -> BTreeSet<(String, String)> {
    let mut out: BTreeSet<(String, String)> = BTreeSet::new();
    for path in read_dir_files(&typeinfo_tests_dir()) {
        let source = fs::read_to_string(&path).expect("read file");
        let (sites, _bare) = extract_ignored_test_sites(&source);
        let file_name = path.file_name().unwrap().to_string_lossy().into_owned();
        for (_reason, fn_name) in sites {
            out.insert((file_name.clone(), fn_name));
        }
    }
    out
}

#[test]
fn every_ignored_typeinfo_test_has_a_manifest_row() {
    let live = collect_live_ignored_sites();
    let manifest: BTreeSet<(String, String)> = EXPECTED_IGNORE_MANIFEST
        .iter()
        .map(|row| (row.file.to_string(), row.function.to_string()))
        .collect();
    let mut missing: Vec<(String, String)> = live.difference(&manifest).cloned().collect();
    missing.sort();
    assert!(
        missing.is_empty(),
        "ignored-test manifest: {} live `#[ignore]` site(s) lack a \
         matching `IgnoredTestRow` in `EXPECTED_IGNORE_MANIFEST`. \
         Add a row naming the closed `TargetSubstrate` substrate and \
         the concrete unblocker. Missing rows:\n  {}",
        missing.len(),
        missing
            .iter()
            .map(|(f, fnm)| format!("{f} :: {fnm}"))
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}

#[test]
fn every_manifest_row_corresponds_to_a_live_ignored_test() {
    let live = collect_live_ignored_sites();
    let mut orphans: Vec<(String, String)> = EXPECTED_IGNORE_MANIFEST
        .iter()
        .map(|row| (row.file.to_string(), row.function.to_string()))
        .filter(|pair| !live.contains(pair))
        .collect();
    orphans.sort();
    assert!(
        orphans.is_empty(),
        "ignored-test manifest: {} `IgnoredTestRow` entries point at \
         tests that no longer exist (or that no longer carry an \
         `#[ignore]` annotation). Remove the stale rows. Orphans:\n  {}",
        orphans.len(),
        orphans
            .iter()
            .map(|(f, fnm)| format!("{f} :: {fnm}"))
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}

#[test]
fn every_manifest_row_has_non_empty_unblocker() {
    let mut violators: Vec<(String, String)> = Vec::new();
    for row in EXPECTED_IGNORE_MANIFEST {
        if row.unblocker.trim().len() < MIN_REASON_LENGTH {
            violators.push((row.function.to_string(), row.unblocker.to_string()));
        }
    }
    assert!(
        violators.is_empty(),
        "ignored-test manifest: {} row(s) have an empty / too-short \
         `unblocker` column. A well-formed manifest row names the \
         concrete substrate change required to lift the ignore. \
         Violators:\n  {}",
        violators.len(),
        violators
            .iter()
            .map(|(f, u)| format!("{f}: \"{u}\""))
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}

/// Reason equality: every manifest row's `unblocker` column MUST
/// match the corresponding live `#[ignore = "..."]` reason string
/// byte-for-byte.
///
/// This guard catches generator regressions where the reason regex
/// truncates an escape-bearing string (the round-3 fix replaced a
/// naive `"([^"]*)"` with the escape-aware
/// `"((?:[^"\\]|\\.)*)"`). Pre-fix the 49 reasons containing
/// embedded `\"` truncated at the first internal quote; the
/// manifest row carried a partial sentence that still passed the
/// non-empty / minimum-length guards but no longer matched the
/// live source. Post-fix every row's `unblocker` equals the live
/// reason exactly.
///
/// The Rust extractor walks the source the same way `extract_sites`
/// in `scripts/gen-typeinfo-ignore-manifest.py` does (substring up
/// to the last `"` on the line). Both parsers operate on the
/// SOURCE bytes — backslash and quote sequences appear literally in
/// the captured reason (the row's stored `unblocker` un-escapes the
/// Rust-literal form back to the same source bytes when the row is
/// loaded).
#[test]
fn every_manifest_row_unblocker_matches_live_ignore_reason() {
    let live_by_pair: BTreeMap<(String, String), String> = {
        let mut acc: BTreeMap<(String, String), String> = BTreeMap::new();
        for path in read_dir_files(&typeinfo_tests_dir()) {
            let source = fs::read_to_string(&path).expect("read file");
            let (sites, _bare) = extract_ignored_test_sites(&source);
            let file_name = path.file_name().unwrap().to_string_lossy().into_owned();
            for (reason, fn_name) in sites {
                acc.insert((file_name.clone(), fn_name), reason);
            }
        }
        acc
    };

    let mut mismatches: Vec<(String, String, String, String)> = Vec::new();
    for row in EXPECTED_IGNORE_MANIFEST {
        let key = (row.file.to_string(), row.function.to_string());
        match live_by_pair.get(&key) {
            None => {
                // Orphan rows are covered by the
                // `every_manifest_row_corresponds_to_a_live_ignored_test`
                // guard; reason equality only applies when the live
                // site exists.
                continue;
            }
            Some(live_reason) => {
                if live_reason != row.unblocker {
                    mismatches.push((
                        row.file.to_string(),
                        row.function.to_string(),
                        row.unblocker.to_string(),
                        live_reason.clone(),
                    ));
                }
            }
        }
    }
    assert!(
        mismatches.is_empty(),
        "ignored-test manifest: {} row(s) have an `unblocker` that \
         does not match the live `#[ignore = \"...\"]` reason. \
         Re-run `python3 scripts/gen-typeinfo-ignore-manifest.py` \
         after editing the source ignore reason — silent drift here \
         usually means the generator regex truncated an escape-bearing \
         reason. Mismatches (file :: fn  manifest=...  live=...):\n  {}",
        mismatches.len(),
        mismatches
            .iter()
            .map(|(f, fnm, m, l)| format!(
                "{f} :: {fnm}\n      manifest={m:?}\n      live    ={l:?}"
            ))
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}

#[test]
fn every_manifest_row_lists_a_valid_substrate() {
    // The closed enum makes invalid substrate names a compile
    // error; this test pins the structural invariant by exercising
    // every variant in the `Debug` formatter, which would panic if
    // the discriminant were ever out of range.
    let mut seen_variants: HashSet<String> = HashSet::new();
    for row in EXPECTED_IGNORE_MANIFEST {
        seen_variants.insert(format!("{:?}", row.substrate));
    }
    // The substrate set is closed and non-empty.
    assert!(!seen_variants.is_empty());
    // At least the FlowNarrowing variant is exercised (narrow_*
    // files alone produce 100+ rows pointing at this substrate);
    // the cardinality below is a sanity floor, not an upper bound.
    assert!(
        seen_variants.contains("FlowNarrowing"),
        "FlowNarrowing substrate must appear in the manifest (the \
         narrow_* files all point at this substrate)",
    );
}

#[test]
fn total_ignored_typeinfo_test_count_matches_expected() {
    let dir = typeinfo_tests_dir();
    let mut total = 0usize;
    for path in read_dir_files(&dir) {
        let source = fs::read_to_string(&path).expect("read file");
        let (sites, _bare) = extract_ignored_test_sites(&source);
        total += sites.len();
    }
    assert_eq!(
        total, EXPECTED_TOTAL_IGNORED_COUNT,
        "total ignored typeinfo test count drifted from documented baseline ({EXPECTED_TOTAL_IGNORED_COUNT})",
    );
}

#[test]
fn manifest_length_matches_documented_total() {
    assert_eq!(
        EXPECTED_IGNORE_MANIFEST.len(),
        EXPECTED_TOTAL_IGNORED_COUNT,
        "`EXPECTED_IGNORE_MANIFEST` row count must equal the documented \
         total {EXPECTED_TOTAL_IGNORED_COUNT}",
    );
}

#[test]
fn per_file_ignored_test_counts_match_manifest() {
    // Per-file partition check: the manifest row count per file
    // must equal the live `#[ignore]` count per file. Keeps the
    // legacy guard's intent (catch additions/removals/drift) while
    // routing through the new row-shaped manifest.
    let dir = typeinfo_tests_dir();
    let mut observed: BTreeMap<String, usize> = BTreeMap::new();
    for path in read_dir_files(&dir) {
        let source = fs::read_to_string(&path).expect("read file");
        let (sites, _bare) = extract_ignored_test_sites(&source);
        if !sites.is_empty() {
            observed.insert(
                path.file_name().unwrap().to_string_lossy().into_owned(),
                sites.len(),
            );
        }
    }

    let mut expected: BTreeMap<String, usize> = BTreeMap::new();
    for row in EXPECTED_IGNORE_MANIFEST {
        *expected.entry(row.file.to_string()).or_default() += 1;
    }

    if observed != expected {
        let mut report = String::new();
        for (name, count) in &expected {
            let actual = observed.get(name).copied().unwrap_or(0);
            if actual != *count {
                report.push_str(&format!("  {name}: expected {count}, observed {actual}\n"));
            }
        }
        for (name, count) in &observed {
            if !expected.contains_key(name) {
                report.push_str(&format!(
                    "  {name}: NEW FILE with {count} ignored tests (add rows to EXPECTED_IGNORE_MANIFEST)\n"
                ));
            }
        }
        panic!(
            "ignored-test manifest drift between EXPECTED_IGNORE_MANIFEST and the \
             live tree:\n{report}\n\
             Update EXPECTED_IGNORE_MANIFEST when intentionally adding or \
             removing ignored tests."
        );
    }
}

// ──────────────────────────────────────────────────────────────────
// Two-table ledger guards (native-typeinfo-parity §10.5, §11.5).
// ──────────────────────────────────────────────────────────────────

fn row_identity(file: &'static str, function: &'static str) -> (String, String) {
    (file.to_string(), function.to_string())
}

/// Build the block prereq adjacency from `TYPEINFO_PARITY_BLOCKS`.
fn build_prereq_map() -> BTreeMap<TypeInfoParityBlockId, Vec<TypeInfoParityBlockId>> {
    TYPEINFO_PARITY_BLOCKS
        .iter()
        .map(|b| (b.block_id, b.prereqs.to_vec()))
        .collect()
}

/// Transitive-prereq closure: is `target` == `from` or a transitive
/// prerequisite of `from`?
fn reaches(
    from: TypeInfoParityBlockId,
    target: TypeInfoParityBlockId,
    prereqs: &BTreeMap<TypeInfoParityBlockId, Vec<TypeInfoParityBlockId>>,
) -> bool {
    if from == target {
        return true;
    }
    let mut seen: BTreeSet<TypeInfoParityBlockId> = BTreeSet::new();
    let mut frontier = vec![from];
    while let Some(cur) = frontier.pop() {
        if !seen.insert(cur) {
            continue;
        }
        if cur == target {
            return true;
        }
        if let Some(edges) = prereqs.get(&cur) {
            frontier.extend(edges.iter().copied());
        }
    }
    false
}

/// The §11.5 per-row prerequisite-consistency checks (checks 2–4) for ONE
/// row's `(block_id, dominant mechanism, consumed mechanisms, consumed
/// keys)`. Returns the list of failure strings (empty == consistent).
///
/// This is the SHARED engine the real guard and the F2/F3 discrimination
/// tests both drive: the discrimination tests prove a row with a
/// deliberately-wrong `block_id` (check 2) or whose block's prereqs do
/// NOT cover its mechanism's keys (check 4) yields a non-empty failure
/// list, while the correct table yields empty.
fn dag_row_consistency_failures(
    what: &str,
    block_id: TypeInfoParityBlockId,
    dominant: MechanismId,
    consumed_mechs: &[MechanismId],
    keys: &[SemanticQueryName],
    prereqs: &BTreeMap<TypeInfoParityBlockId, Vec<TypeInfoParityBlockId>>,
) -> Vec<String> {
    let mut failures: Vec<String> = Vec::new();
    // Check 2: dominant-mechanism owner == block. The mechanism is a
    // ROW-LEVEL fact (derived from capability/`file::function`, NOT from
    // `block_id`), so this is NOT tautological: a mis-assigned `block_id`
    // whose value disagrees with `mechanism_owning_block(mechanism_id)`
    // FAILS here.
    let owner = mechanism_owning_block(dominant);
    if owner != block_id {
        failures.push(format!(
            "{what}: dominant mechanism {dominant:?} is owned by {owner:?}, \
             not the row's block {block_id:?} (check 2)"
        ));
    }
    // Check 3: every consumed mechanism's owner is itself or a prereq.
    for &m in consumed_mechs {
        let m_owner = mechanism_owning_block(m);
        if !reaches(block_id, m_owner, prereqs) {
            failures.push(format!(
                "{what}: consumes mechanism {m:?} owned by {m_owner:?}, which \
                 is NOT block {block_id:?} nor a transitive prerequisite \
                 (check 3); missing prereq edge {block_id:?} -> … -> {m_owner:?}"
            ));
        }
    }
    // Check 4: every consumed key's owner is itself or a prereq. The key
    // set is the FULL set the row's MECHANISM dispatches (no per-block
    // narrowing), so a wrong `block_id` whose prereqs do not cover the
    // mechanism's keys FAILS here.
    for &k in keys {
        let k_owner = key_owning_block(k);
        if !reaches(block_id, k_owner, prereqs) {
            failures.push(format!(
                "{what}: consumes key {k:?} owned by {k_owner:?}, which is NOT \
                 block {block_id:?} nor a transitive prerequisite (check 4); \
                 missing prereq edge {block_id:?} -> … -> {k_owner:?}"
            ));
        }
    }
    failures
}

/// §10.5 — the `IgnoredTestRow` table holds EXACTLY 362 rows (the
/// binding manifest total), DISJOINT from the `AdditionalProofRow`
/// table; no `AdditionalProofRow` participates in the ignored count or
/// bijection, and no `(file, function)` identity appears in both
/// tables. An `IgnoredTestRow` count other than 362, an
/// `AdditionalProofRow` in the ignored set, or a `(file, function)` in
/// both, FAILS.
#[test]
fn ignored_test_row_table_holds_exactly_362_rows() {
    assert_eq!(
        EXPECTED_IGNORE_MANIFEST.len(),
        362,
        "the `IgnoredTestRow` table must hold EXACTLY 362 binding rows \
         (got {}). The total is the source-`#[ignore]` bijective count \
         (§10.5) — U2 Phase B2 lifted `module_features_module_\
         augmentation_merges_plugin_surface` (cross-file relative \
         `declare module` stitch), and Phase B3 lifted \
         `module_features_external_module_augmentation_merges_config` \
         (cross-file EXTERNAL string-literal `declare module` stitch now \
         real).",
        EXPECTED_IGNORE_MANIFEST.len(),
    );

    // The derived count equals 362 (every current row is `Ignored`).
    assert_eq!(
        EXPECTED_TOTAL_IGNORED_COUNT, 362,
        "EXPECTED_TOTAL_IGNORED_COUNT is DERIVED as count(status == \
         Ignored); it must equal 362. Got {}.",
        EXPECTED_TOTAL_IGNORED_COUNT,
    );

    // Disjointness: no `(file, function)` in both tables. A
    // submatrix/additional fixture corresponding to an existing
    // ignored row stays an `IgnoredTestRow`, never duplicated as an
    // `AdditionalProofRow`.
    let ignored: BTreeSet<(String, String)> = EXPECTED_IGNORE_MANIFEST
        .iter()
        .map(|r| row_identity(r.file, r.function))
        .collect();
    let additional: BTreeSet<(String, String)> = ADDITIONAL_PROOF_ROWS
        .iter()
        .map(|r| row_identity(r.file, r.function))
        .collect();
    let overlap: Vec<(String, String)> = ignored.intersection(&additional).cloned().collect();
    assert!(
        overlap.is_empty(),
        "the `IgnoredTestRow` and `AdditionalProofRow` tables must be \
         DISJOINT — a `(file, function)` in both means a coverage fixture \
         was double-counted. Overlap:\n  {}",
        overlap
            .iter()
            .map(|(f, fnm)| format!("{f} :: {fnm}"))
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}

/// §10.5 / §8 — the `AdditionalProofRow` table is the CLOSED set of
/// EXACTLY 7 coverage-only rows. This is a CLOSED-SET guard: it pins the
/// EXACT 7 `(file, function)` identities, each row's `owning_u_block`,
/// and each row's `ProofRequirement` KIND — not just the count + bucket
/// tallies. Swapping one JSX identity, changing an `owning_u_block`, or
/// flipping a proof kind FAILS. None is counted toward
/// `EXPECTED_TOTAL_IGNORED_COUNT` or the bijection.
///
/// The 6 JSX no-new-key submatrix rows (`U2.JSX_FOUNDATIONS`, `RowTestGuard`
/// forward-declarations) + the 1 mapped companion (`U2.MAPPED_TEMPLATE`,
/// `RowTestGuard` forward-declaration consistent with the JSX rows — F6).
#[test]
fn additional_proof_row_table_holds_exactly_7_rows() {
    use TypeInfoParityBlockId::{U2JsxFoundations, U2MappedTemplate};

    // The EXACT closed set: every coverage row's
    // `(file, function, owning_u_block, block_id, RowTestGuard{file,
    // function})`. Each JSX forward-declaration's `RowTestGuard` targets
    // its own `jsx.rs` function; the mapped companion's targets its
    // `mapped_modifiers.rs` function (F6 — RowTestGuard, NOT
    // StructuralGuard).
    let expected: &[(&str, &str, UBlock, TypeInfoParityBlockId)] = &[
        (
            "jsx.rs",
            "jsx_library_managed_attributes_via_ambient_namespace_and_indexed_access",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "jsx.rs",
            "jsx_element_attributes_property_via_ambient_namespace_keyof",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "jsx.rs",
            "jsx_element_children_attribute_via_ambient_namespace_keyof",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "jsx.rs",
            "jsx_intrinsic_attributes_via_ambient_namespace_intersection",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "jsx.rs",
            "jsx_element_class_check_via_resolve_class_surface_and_relate",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "jsx.rs",
            "jsx_import_source_module_namespace_via_existing_resolution",
            UBlock::U2,
            U2JsxFoundations,
        ),
        (
            "mapped_modifiers.rs",
            "mapped_modifier_minus_optional_preserves_explicit_undefined_on_required_property",
            UBlock::U2,
            U2MappedTemplate,
        ),
    ];

    assert_eq!(
        ADDITIONAL_PROOF_ROWS.len(),
        expected.len(),
        "the `AdditionalProofRow` table is CLOSED at exactly {} \
         coverage-only rows (6 JSX no-new-key + 1 mapped companion). \
         Got {}.",
        expected.len(),
        ADDITIONAL_PROOF_ROWS.len(),
    );

    // CLOSED-SET identity match: the actual `(file, function)` set must
    // equal the expected set EXACTLY (no missing, no extra, no swap).
    let actual_ids: BTreeSet<(String, String)> = ADDITIONAL_PROOF_ROWS
        .iter()
        .map(|r| row_identity(r.file, r.function))
        .collect();
    let expected_ids: BTreeSet<(String, String)> = expected
        .iter()
        .map(|(f, fnm, _, _)| (f.to_string(), fnm.to_string()))
        .collect();
    assert_eq!(
        actual_ids,
        expected_ids,
        "the `AdditionalProofRow` `(file, function)` set must EXACTLY \
         equal the closed 7-row set — a swapped/extra/missing identity \
         FAILS. extra={:?} missing={:?}",
        actual_ids.difference(&expected_ids).collect::<Vec<_>>(),
        expected_ids.difference(&actual_ids).collect::<Vec<_>>(),
    );

    // Per-row: owning_u_block + block_id + proof KIND (RowTestGuard
    // pointing at the row's OWN file::function) all match the closed set.
    for (file, function, ublock, block_id) in expected {
        let row = ADDITIONAL_PROOF_ROWS
            .iter()
            .find(|r| r.file == *file && r.function == *function)
            .unwrap_or_else(|| {
                panic!("closed-set row {file}::{function} missing from ADDITIONAL_PROOF_ROWS")
            });
        assert_eq!(
            row.owning_u_block, *ublock,
            "{file}::{function}: owning_u_block must be {ublock:?}, got {:?}",
            row.owning_u_block,
        );
        assert_eq!(
            row.block_id, *block_id,
            "{file}::{function}: block_id must be {block_id:?}, got {:?}",
            row.block_id,
        );
        match row.proof {
            ProofRequirement::RowTestGuard {
                file: gf,
                function: gfn,
            } => {
                assert_eq!(
                    (gf, gfn),
                    (*file, *function),
                    "{file}::{function}: the coverage row is a \
                     FORWARD-DECLARATION `RowTestGuard` that must point at \
                     its OWN future test fn; got RowTestGuard{{{gf}, {gfn}}}",
                );
            }
            other => panic!(
                "{file}::{function}: every AdditionalProofRow proof must be \
                 a `RowTestGuard` forward-declaration (F6 — the mapped \
                 companion is no longer a StructuralGuard); got {other:?}",
            ),
        }
    }

    // No coverage row consumes `ResolveCall` mechanism / dispatch — JSX
    // factory invocation is a U6.CALL_RESOLVE backfill, not a
    // JSX-foundations coverage row (§8).
    for row in ADDITIONAL_PROOF_ROWS {
        assert!(
            !row.consumed_mechanisms
                .contains(&MechanismId::ResolveCallDispatch)
                && row.mechanism_id != MechanismId::ResolveCallDispatch,
            "AdditionalProofRow {}::{} must NOT consume ResolveCall \
             dispatch — JSX factory invocation is a U6.CALL_RESOLVE \
             backfill, not a JSX-foundations coverage row (§8).",
            row.file,
            row.function,
        );
    }
}

/// §11.5 — the block prerequisite DAG is acyclic AND every consumed
/// key / mechanism's owning block is the consuming block itself or a
/// transitive prerequisite of it. Models BOTH the semantic-query-key
/// owner edges AND the block-mechanism dependencies.
///
/// Five checks (§11.5):
/// 1. Block DAG acyclic.
/// 2. Every row's dominant `mechanism_id` is owned by its own
///    `block_id`.
/// 3. Every consumed mechanism's owner is itself or a transitive
///    prerequisite.
/// 4. Every consumed key's owner is itself or a transitive
///    prerequisite.
/// 5. Diagnostic on failure.
#[test]
fn typeinfo_parity_block_dag_is_acyclic_and_consumed_keys_and_mechanisms_are_prereqs() {
    use std::collections::BTreeMap as Map;

    // Build the prereq adjacency from TYPEINFO_PARITY_BLOCKS.
    let prereqs = build_prereq_map();

    // No duplicate `block_id` rows in the contract table.
    assert_eq!(
        prereqs.len(),
        TYPEINFO_PARITY_BLOCKS.len(),
        "TYPEINFO_PARITY_BLOCKS must hold one row per block_id (no \
         duplicate block_id rows)",
    );

    // ── Check 0 (F7): every block REFERENCED anywhere must have a
    //    `BlockContractRow`. A referenced-but-missing block is NOT a
    //    leaf — deleting a referenced contract row (e.g. one that another
    //    block lists in `prereqs`, or that owns a consumed key /
    //    mechanism, or that a row's `block_id` / `owning_u_block` names)
    //    must FAIL the guard, not pass silently. We collect every
    //    referenced `TypeInfoParityBlockId` and assert each has a row.
    let contract_blocks: BTreeSet<TypeInfoParityBlockId> =
        TYPEINFO_PARITY_BLOCKS.iter().map(|b| b.block_id).collect();
    let mut referenced: BTreeSet<TypeInfoParityBlockId> = BTreeSet::new();
    for b in TYPEINFO_PARITY_BLOCKS {
        referenced.insert(b.block_id);
        for &p in b.prereqs {
            referenced.insert(p);
        }
        referenced.insert(mechanism_owning_block(b.mechanism_id));
        for &m in b.consumed_mechanisms {
            referenced.insert(mechanism_owning_block(m));
        }
    }
    for row in EXPECTED_IGNORE_MANIFEST {
        referenced.insert(row.block_id);
        referenced.insert(mechanism_owning_block(row.mechanism_id));
        for &m in row.consumed_mechanisms {
            referenced.insert(mechanism_owning_block(m));
        }
        for &k in row.semantic_queries {
            referenced.insert(key_owning_block(k));
        }
    }
    for row in ADDITIONAL_PROOF_ROWS {
        referenced.insert(row.block_id);
        referenced.insert(mechanism_owning_block(row.mechanism_id));
        for &m in row.consumed_mechanisms {
            referenced.insert(mechanism_owning_block(m));
        }
        for &k in row.semantic_queries {
            referenced.insert(key_owning_block(k));
        }
    }
    let missing_contract: Vec<TypeInfoParityBlockId> =
        referenced.difference(&contract_blocks).copied().collect();
    assert!(
        missing_contract.is_empty(),
        "block-DAG: {} block(s) are REFERENCED (by a prereq edge, a \
         key/mechanism owner, or a row's block_id / owning_u_block) but \
         have NO `BlockContractRow` — a referenced block is not a leaf, it \
         is a missing contract (F7). Deleting a referenced contract row \
         must fail here. Missing: {:?} (check 0)",
        missing_contract.len(),
        missing_contract,
    );

    // ── Check 1: acyclicity (DFS three-colour). ──
    #[derive(Clone, Copy, PartialEq)]
    enum Color {
        White,
        Gray,
        Black,
    }
    fn visit(
        node: TypeInfoParityBlockId,
        prereqs: &Map<TypeInfoParityBlockId, Vec<TypeInfoParityBlockId>>,
        color: &mut Map<TypeInfoParityBlockId, Color>,
        stack: &mut Vec<TypeInfoParityBlockId>,
    ) -> Result<(), Vec<TypeInfoParityBlockId>> {
        color.insert(node, Color::Gray);
        stack.push(node);
        if let Some(edges) = prereqs.get(&node) {
            for &dep in edges {
                match color.get(&dep).copied().unwrap_or(Color::White) {
                    Color::Gray => {
                        let mut cyc = stack.clone();
                        cyc.push(dep);
                        return Err(cyc);
                    }
                    Color::White => visit(dep, prereqs, color, stack)?,
                    Color::Black => {}
                }
            }
        }
        stack.pop();
        color.insert(node, Color::Black);
        Ok(())
    }
    let mut color: Map<TypeInfoParityBlockId, Color> = Map::new();
    for &b in prereqs.keys() {
        if color.get(&b).copied().unwrap_or(Color::White) == Color::White {
            let mut stack = Vec::new();
            if let Err(cyc) = visit(b, &prereqs, &mut color, &mut stack) {
                panic!("block prerequisite DAG has a CYCLE: {:?} (check 1)", cyc);
            }
        }
    }

    // ── Checks 2-4 over every IgnoredTestRow + AdditionalProofRow +
    //    BlockContractRow, via the shared `dag_row_consistency_failures`
    //    engine (the same engine the F2/F3 discrimination tests drive). ──
    let mut failures: Vec<String> = Vec::new();

    for row in EXPECTED_IGNORE_MANIFEST {
        let what = format!("IgnoredTestRow {}::{}", row.file, row.function);
        failures.extend(dag_row_consistency_failures(
            &what,
            row.block_id,
            row.mechanism_id,
            row.consumed_mechanisms,
            row.semantic_queries,
            &prereqs,
        ));
    }
    for row in ADDITIONAL_PROOF_ROWS {
        let what = format!("AdditionalProofRow {}::{}", row.file, row.function);
        failures.extend(dag_row_consistency_failures(
            &what,
            row.block_id,
            row.mechanism_id,
            row.consumed_mechanisms,
            row.semantic_queries,
            &prereqs,
        ));
    }
    for block in TYPEINFO_PARITY_BLOCKS {
        let what = format!("BlockContractRow {:?}", block.block_id);
        // Block-level dominant + consumed mechanisms (check 2/3). Blocks
        // declare no consumed keys directly (keys ride rows).
        failures.extend(dag_row_consistency_failures(
            &what,
            block.block_id,
            block.mechanism_id,
            block.consumed_mechanisms,
            &[],
            &prereqs,
        ));
    }

    assert!(
        failures.is_empty(),
        "block-DAG / consumed-key / consumed-mechanism prerequisite \
         consistency FAILED (§11.5):\n  {}",
        failures.join("\n  "),
    );
}

/// §11.5 — the manifest's `SemanticQueryName` mirror is BIJECTIVE with the
/// live `SemanticQueryKeyTag::ALL` discriminant set. The mirror keys queries
/// by NAME for the block-DAG guard's consumed-key check; if it drifts behind
/// the live key surface, a row could consume a live key the mirror does not
/// name (so `key_owning_block` could not be exercised for it) and the DAG
/// guard's consumed-key prerequisite check would silently never fire for that
/// key — a false pass. This guard pins the two sets equal so that can never
/// happen: a live tag absent from the mirror (or a mirror name with no live
/// tag) FAILS here, naming the exact offenders.
#[test]
fn semantic_query_name_mirror_matches_live_tag_set() {
    let live: BTreeSet<String> = SemanticQueryKeyTag::ALL
        .iter()
        .map(|tag| tag.name().to_string())
        .collect();
    let mirror: BTreeSet<String> = SEMANTIC_QUERY_NAME_ALL
        .iter()
        .map(|name| semantic_query_name_str(*name).to_string())
        .collect();

    let missing_from_mirror: Vec<&String> = live.difference(&mirror).collect();
    let extra_in_mirror: Vec<&String> = mirror.difference(&live).collect();

    assert!(
        missing_from_mirror.is_empty() && extra_in_mirror.is_empty(),
        "the manifest `SemanticQueryName` mirror has drifted from the live \
         `SemanticQueryKeyTag::ALL` set. Extend the single \
         `semantic_query_names!` invocation (which generates the enum, the \
         `SEMANTIC_QUERY_NAME_ALL` witness array, and `semantic_query_name_str` \
         together) and add a `key_owning_block` arm for every added live key in \
         the same change.\n  \
         live tags missing from the mirror: {missing_from_mirror:?}\n  \
         mirror names with no live tag: {extra_in_mirror:?}",
    );

    // Sanity floor: the live set is non-empty and the mirror array has no
    // duplicate names (a duplicated variant would shrink the set and could
    // mask a missing one).
    assert_eq!(
        mirror.len(),
        SEMANTIC_QUERY_NAME_ALL.len(),
        "`SEMANTIC_QUERY_NAME_ALL` contains duplicate variants",
    );
    assert!(
        !live.is_empty(),
        "`SemanticQueryKeyTag::ALL` must be non-empty"
    );
}

/// §11.5 — `key_owning_block` is LIVE authority: the block-DAG guard
/// (`typeinfo_parity_block_dag_is_acyclic_and_consumed_keys_and_mechanisms_are_prereqs`)
/// consumes it to check that every key a row consumes is produced by a prereq
/// block. But several `SemanticQueryName` keys (the apparent-type / class-surface
/// / enum / ambient-namespace / overload-set / flow / contextual reducer keys)
/// appear in NO row's `semantic_queries`, so their `key_owning_block` arms are
/// reached ONLY by compile-time match-exhaustiveness — a WRONG owner
/// (e.g. `ContextualTypeAt => U2QueryValueDomain`) would still COMPILE and every
/// other test would still pass. This test is the CLOSED-SET, DISCRIMINATING pin
/// that catches a mis-mapped owner: it asserts, for EVERY `SemanticQueryName`
/// variant, that `key_owning_block` returns the EXACT owning block the §11.5
/// mechanism-first layering assigns it (the block whose dominant mechanism
/// PRODUCES that key's result). The expected table is the closed source of truth
/// taken from the `key_owning_block` doc comment + the §10.4.1 mechanism→block
/// partition; a wrong arm FAILS this test even though it compiles.
///
/// Closed-set completeness: the expected table's key set is asserted EQUAL to
/// `SEMANTIC_QUERY_NAME_ALL`, so adding a new `SemanticQueryName` variant
/// without a table entry here FAILS the set-equality assertion (in addition to
/// the wildcard-free `key_owning_block` match forcing a new arm to compile).
/// Each expected owner is also asserted to exist in `TYPEINFO_PARITY_BLOCKS`.
#[test]
fn key_owning_block_owner_mapping_is_pinned_closed_set() {
    use SemanticQueryName::*;
    use TypeInfoParityBlockId::*;

    // EXPECTED (key → owning block) — the §11.5 mechanism-first layering.
    // The block whose dominant mechanism PRODUCES the key's result, NOT where
    // the key's shape was first declared. Encoded explicitly so a wrong arm in
    // `key_owning_block` FAILS even when match-exhaustiveness alone passes.
    let expected: &[(SemanticQueryName, TypeInfoParityBlockId)] = &[
        // Foundational decl/value keys + the lib-fact apparent-member lookup
        // (no dedicated reducer block) at U2.QUERY_VALUE_DOMAIN.
        (ResolveDecl, U2QueryValueDomain),
        (TypeOf, U2QueryValueDomain),
        (NormalizeUnion, U2QueryValueDomain),
        (NormalizeIntersection, U2QueryValueDomain),
        (ResolvedNamedType, U2QueryValueDomain),
        (ApparentType, U2QueryValueDomain),
        // Relation / instantiation / conditional at U2.RELATION_INFER.
        (Relate, U2RelationInfer),
        (Instantiate, U2RelationInfer),
        (Conditional, U2RelationInfer),
        // Indexed-access / keyof / member / path at U2.INDEXED_ACCESS.
        (IndexedAccess, U2IndexedAccess),
        (KeyOf, U2IndexedAccess),
        (ProjectMember, U2IndexedAccess),
        (ProjectPath, U2IndexedAccess),
        // Mapped + template-literal reduction at U2.MAPPED_TEMPLATE.
        (MappedType, U2MappedTemplate),
        (TemplateLiteralReduce, U2MappedTemplate),
        // Class-surface projection at U2.CLASS_SURFACES.
        (ResolveClassSurface, U2ClassSurfaces),
        // Enum value/type duality at U2.ENUMS.
        (ResolveEnum, U2Enums),
        // Ambient-namespace (JSX foundation) at U2.JSX_FOUNDATIONS.
        (ResolveAmbientNamespace, U2JsxFoundations),
        // Overload-set / call dispatch at U6.CALL_RESOLVE.
        (ResolveOverloadSet, U6CallResolve),
        // Flow narrowing on the flow-frame substrate at
        // U6.FLOW_RETURN_SUBSTRATE.
        (FlowNarrowingAt, U6FlowReturnSubstrate),
        // Contextual typing at U6.CONTEXTUAL_CALLBACK.
        (ContextualTypeAt, U6ContextualCallback),
        // Macro payload at U14.MACRO_ADAPTER.
        (ResolveMacroPayload, U14MacroAdapter),
    ];

    // DISCRIMINATING per-key pin: a wrong `key_owning_block` arm FAILS here.
    let mut mismatches: Vec<String> = Vec::new();
    for (key, expected_owner) in expected {
        let actual = key_owning_block(*key);
        if actual != *expected_owner {
            mismatches.push(format!(
                "{key:?}: key_owning_block returned {actual:?}, expected {expected_owner:?}",
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "key_owning_block owner mapping diverged from the §11.5 pinned table \
         ({} mismatch(es)):\n  {}",
        mismatches.len(),
        mismatches.join("\n  "),
    );

    // CLOSED-SET completeness: the expected table's key set == the full
    // `SemanticQueryName` mirror set. A newly-added key with no table entry
    // FAILS here (and the wildcard-free `key_owning_block` match also forces a
    // new arm to compile, so an added key cannot silently inherit an owner).
    let expected_keys: BTreeSet<SemanticQueryName> = expected.iter().map(|(k, _)| *k).collect();
    let all_keys: BTreeSet<SemanticQueryName> = SEMANTIC_QUERY_NAME_ALL.iter().copied().collect();
    assert_eq!(
        expected_keys.len(),
        expected.len(),
        "the expected key→owner table contains a duplicate key — each key \
         must be pinned exactly once",
    );
    let missing_from_table: Vec<&SemanticQueryName> = all_keys.difference(&expected_keys).collect();
    let extra_in_table: Vec<&SemanticQueryName> = expected_keys.difference(&all_keys).collect();
    assert!(
        missing_from_table.is_empty() && extra_in_table.is_empty(),
        "the pinned key→owner table is not a closed set over \
         `SEMANTIC_QUERY_NAME_ALL` — add a table entry for every new key (and \
         a `key_owning_block` arm) in the same change.\n  \
         keys missing from the table: {missing_from_table:?}\n  \
         table keys with no mirror variant: {extra_in_table:?}",
    );

    // Each pinned owner must be a real block in the DAG.
    let known_blocks: BTreeSet<TypeInfoParityBlockId> =
        TYPEINFO_PARITY_BLOCKS.iter().map(|b| b.block_id).collect();
    let unknown_owners: Vec<String> = expected
        .iter()
        .filter(|(_, owner)| !known_blocks.contains(owner))
        .map(|(key, owner)| format!("{key:?} → {owner:?} (not in TYPEINFO_PARITY_BLOCKS)"))
        .collect();
    assert!(
        unknown_owners.is_empty(),
        "pinned owner block(s) absent from `TYPEINFO_PARITY_BLOCKS`:\n  {}",
        unknown_owners.join("\n  "),
    );
}

/// §9 / §11.5 — every `BlockContractRow` CARRIES its contract metadata: a
/// non-empty `required_guards` list (the §11.5 done-predicate keys off these
/// labels) and a non-empty `verification_labels` list, with no empty /
/// too-short / duplicated label in either. This is the schema-presence gate;
/// the LANDING-time enforcement (a landed block's required guards are live +
/// green) is the separate `landed_typeinfo_blocks_have_required_guards`
/// done-predicate that lands in a later substrate block. A block row with an
/// empty `required_guards` (or `verification_labels`) FAILS here.
#[test]
fn every_block_contract_row_carries_required_guards() {
    const MIN_LABEL_LENGTH: usize = 8;
    let mut violations: Vec<String> = Vec::new();
    for block in TYPEINFO_PARITY_BLOCKS {
        if block.required_guards.is_empty() {
            violations.push(format!(
                "{:?}: empty `required_guards` — a block contract must name at \
                 least the guard(s) that gate its landing",
                block.block_id,
            ));
        }
        if block.verification_labels.is_empty() {
            violations.push(format!(
                "{:?}: empty `verification_labels` — a block contract must name \
                 the verification commands it runs",
                block.block_id,
            ));
        }
        for g in block.required_guards {
            if g.trim().len() < MIN_LABEL_LENGTH {
                violations.push(format!(
                    "{:?}: required-guard label {g:?} is empty / too short",
                    block.block_id,
                ));
            }
        }
        let unique: BTreeSet<&str> = block.required_guards.iter().copied().collect();
        if unique.len() != block.required_guards.len() {
            violations.push(format!(
                "{:?}: duplicate required-guard label(s) — each guard must appear once",
                block.block_id,
            ));
        }
        for l in block.verification_labels {
            if l.trim().len() < MIN_LABEL_LENGTH {
                violations.push(format!(
                    "{:?}: verification label {l:?} is empty / too short",
                    block.block_id,
                ));
            }
        }
        let unique_labels: BTreeSet<&str> = block.verification_labels.iter().copied().collect();
        if unique_labels.len() != block.verification_labels.len() {
            violations.push(format!(
                "{:?}: duplicate verification label(s) — each label must appear once",
                block.block_id,
            ));
        }
    }
    assert!(
        violations.is_empty(),
        "block contract metadata incomplete ({} violation(s)):\n  {}",
        violations.len(),
        violations.join("\n  "),
    );
}

// ──────────────────────────────────────────────────────────────────
// F2 / F3 / F7 DISCRIMINATION tests — prove the DAG-guard checks are
// genuinely discriminating by feeding deliberately-broken rows through
// the SAME shared engine the real guard uses and asserting they FAIL.
// ──────────────────────────────────────────────────────────────────

/// F2 — proves DAG-guard check 2 (`mechanism_owning_block(mechanism_id)
/// == block_id`) is NOT tautological. Because a row's `mechanism_id` is
/// a ROW-LEVEL fact derived from capability/`file::function` (independent
/// of the `block_id` column), injecting a WRONG `block_id` on a row —
/// one that disagrees with its mechanism's owning block — must FAIL
/// check 2; the correct (`block_id == mechanism_owning_block`) row passes.
#[test]
fn dag_guard_check2_fails_on_block_id_mismatching_its_mechanism() {
    let prereqs = build_prereq_map();

    // Pick a real row and confirm the CORRECT pairing passes check 2.
    let row = EXPECTED_IGNORE_MANIFEST
        .iter()
        .find(|r| r.mechanism_id == MechanismId::RelateCoinductiveScc)
        .expect("manifest must contain a RelateCoinductiveScc row");
    let correct_owner = mechanism_owning_block(row.mechanism_id);
    assert_eq!(
        correct_owner, row.block_id,
        "precondition: the real row's block_id must own its mechanism",
    );
    let clean = dag_row_consistency_failures(
        "correct",
        row.block_id,
        row.mechanism_id,
        &[],
        &[],
        &prereqs,
    );
    assert!(
        clean.is_empty(),
        "the correct (block_id, mechanism_id) pairing must PASS check 2; got {clean:?}",
    );

    // Inject a WRONG block_id (one that does NOT own this mechanism).
    let wrong_block = TypeInfoParityBlockId::U2Utilities;
    assert_ne!(
        wrong_block, correct_owner,
        "test setup: the injected block must differ from the mechanism's owner",
    );
    let broken = dag_row_consistency_failures(
        "injected-wrong-block",
        wrong_block,
        row.mechanism_id,
        &[],
        &[],
        &prereqs,
    );
    assert!(
        broken.iter().any(|f| f.contains("(check 2)")),
        "injecting a block_id that contradicts the row's row-level \
         mechanism MUST FAIL check 2 — if it does not, check 2 is \
         tautological (the F2 defect). Got: {broken:?}",
    );
}

/// F3 — proves DAG-guard check 4 (consumed-key prerequisite) is NOT
/// self-fulfilling. The key set is the FULL set the row's MECHANISM
/// dispatches (no per-block narrowing), so a row whose `block_id`'s
/// prereqs do NOT cover its mechanism's keys must FAIL check 4. A
/// generator that narrowed the key set to the block's already-reachable
/// keys would hide this — that was the F3 defect.
#[test]
fn dag_guard_check4_fails_when_block_prereqs_do_not_cover_mechanism_keys() {
    let prereqs = build_prereq_map();

    // `IndexedAccess` is owned by `U2.INDEXED_ACCESS`. `U2.RELATION_INFER`
    // (prereqs: only `U2.QUERY_VALUE_DOMAIN`) does NOT reach it.
    let indexed_owner = key_owning_block(SemanticQueryName::IndexedAccess);
    assert!(
        !reaches(
            TypeInfoParityBlockId::U2RelationInfer,
            indexed_owner,
            &prereqs,
        ),
        "precondition: U2.RELATION_INFER must NOT reach the IndexedAccess owner",
    );

    // A row placed in U2.RELATION_INFER (mechanism `RelateCoinductiveScc`,
    // owned there) but consuming the full `IndexedAccess` key its
    // mechanism would NOT dispatch from that block must FAIL check 4.
    let broken = dag_row_consistency_failures(
        "block-prereqs-miss-key",
        TypeInfoParityBlockId::U2RelationInfer,
        MechanismId::RelateCoinductiveScc,
        &[],
        &[SemanticQueryName::IndexedAccess],
        &prereqs,
    );
    assert!(
        broken.iter().any(|f| f.contains("(check 4)")),
        "a row whose block's prereqs do not cover a consumed key MUST FAIL \
         check 4 — if a narrowed key set hides this, check 4 is \
         self-fulfilling (the F3 defect). Got: {broken:?}",
    );

    // Sanity: the same key consumed from a block that DOES reach its owner
    // passes (so the guard is not vacuously failing everything).
    let ok = dag_row_consistency_failures(
        "block-prereqs-cover-key",
        TypeInfoParityBlockId::U2IndexedAccess,
        MechanismId::IndexedAccessUnionDistribution,
        &[],
        &[SemanticQueryName::IndexedAccess],
        &prereqs,
    );
    assert!(
        ok.is_empty(),
        "U2.INDEXED_ACCESS consuming IndexedAccess must PASS check 4; got {ok:?}",
    );
}
