//! Architecture guards for the typeinfo wire surface.
//!
//! The wire-side of the typeinfo graph substrate is protobuf-
//! authoritative: Rust DTOs are generated from `.proto` via
//! `prost-build`; TypeScript DTOs are generated from the same
//! `.proto` via the existing protobuf-ts pipeline. `ts-rs` derives
//! are reserved for the audit envelope under `crates/verter_audit`
//! and MUST NOT appear on wire-side typeinfo DTOs. These guards
//! detect a regression where a future contributor reintroduces
//! `ts-rs` on the typeinfo wire-side or hand-edits the generated
//! TypeScript artifact.
//!
//! Discriminating shape: each guard scans a specific source surface
//! and asserts a structural property. Pre-substrate the surfaces do
//! not exist (the typeinfo proto file is the legacy 5-DTO schema,
//! the Rust submodule does not exist) and the scans fail. Post-
//! substrate the scans pass.

use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_root
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR must be `<workspace>/crates/verter_session`")
        .to_path_buf()
}

fn read_workspace_file(rel: &str) -> String {
    let path = workspace_root().join(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "guard requires `{}` to exist and be readable: {err}",
            path.display()
        )
    })
}

#[test]
fn typeinfo_wire_dtos_are_proto_authoritative_with_no_ts_rs_derive() {
    let graph = read_workspace_file("crates/verter_protocol/src/typeinfo/graph.rs");
    // The Rust-side wire surface is a re-export module — every DTO
    // type is `pub use wire::...`, NOT a hand-rolled struct with
    // ts-rs derives.
    assert!(
        !graph.contains("ts_rs::TS"),
        "guard: typeinfo wire DTOs MUST NOT carry `ts_rs::TS` derives — \
         the wire surface is protobuf-authoritative",
    );
    assert!(
        !graph.contains("#[ts(export"),
        "guard: typeinfo wire DTOs MUST NOT carry `#[ts(export, ...)]` \
         attributes — `ts-rs` is reserved for the audit envelope",
    );
    // Sanity: the file actually re-exports from the generated module.
    assert!(
        graph.contains("use crate::verter::v1 as wire;"),
        "guard: typeinfo graph submodule must re-export from the prost-generated `wire` module",
    );
}

#[test]
fn verter_protocol_does_not_depend_on_ts_rs() {
    let cargo = read_workspace_file("crates/verter_protocol/Cargo.toml");
    assert!(
        !cargo.contains("ts-rs"),
        "guard: `verter_protocol/Cargo.toml` MUST NOT declare a `ts-rs` \
         dependency — wire DTOs are protobuf-authoritative; ts-rs lives \
         in `verter_audit`",
    );
}

#[test]
fn typeinfo_pb_ts_carries_protoc_gen_es_header() {
    let ts = read_workspace_file("packages/proto/src/gen/verter/v1/typeinfo_pb.ts");
    assert!(
        ts.contains("// @generated by protoc-gen-es"),
        "guard: `typeinfo_pb.ts` MUST be generated by `protoc-gen-es` — \
         a hand-rolled or edited TS surface loses the regenerator's \
         single source of truth",
    );
    assert!(
        ts.contains("@generated from file verter/v1/typeinfo.proto"),
        "guard: `typeinfo_pb.ts` MUST record `verter/v1/typeinfo.proto` \
         as its source file",
    );
}

#[test]
fn typeinfo_proto_carries_graph_substrate_messages() {
    let proto = read_workspace_file("crates/verter_protocol/proto/verter/v1/typeinfo.proto");
    let required = [
        "message SemanticTypeGraph",
        "message GraphTypeNode",
        "message StructuredTypeExpression",
        "message TypeInfoGraphRequest",
        "message TypeInfoGraphResponse",
        "message TypeInfoRequestError",
        "message FrameworkSurfacePayload",
        "message TypeInfoCapabilityHandshakeRequest",
        "message TypeInfoCapabilityHandshakeResponse",
    ];
    let mut missing = Vec::new();
    for need in required {
        if !proto.contains(need) {
            missing.push(need);
        }
    }
    assert!(
        missing.is_empty(),
        "guard: `typeinfo.proto` MUST declare every typeinfo graph substrate \
         message. Missing: {missing:?}",
    );
}

#[test]
fn typeinfo_request_validation_is_a_separate_module() {
    let typeinfo_mod = read_workspace_file("crates/verter_session/src/typeinfo/mod.rs");
    assert!(
        typeinfo_mod.contains("pub mod request_validation;"),
        "guard: the typeinfo module must expose a `request_validation` \
         submodule so validation runs BEFORE semantic execution",
    );

    let validation =
        read_workspace_file("crates/verter_session/src/typeinfo/request_validation.rs");
    // The validator must NOT call into the resolver or the
    // semantic-query engine. It is a shape-only pass that returns a
    // typed `TypeInfoRequestError`. Strip comment lines first so the
    // module's doc-comment references to `SemanticGraphStore::execute`
    // do not trip the guard — the guard targets actual call sites.
    let code_only: String = validation
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            !trimmed.starts_with("//!") && !trimmed.starts_with("///") && !trimmed.starts_with("//")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let banned_calls = [
        "ProjectSemanticDispatch::execute",
        "SemanticGraphStore::execute",
        "SemanticGraphStore::new",
        "FileArtifactStore::",
        ".project_type_store()",
        ".semantic_graph_store()",
        "ResolverContext::new",
    ];
    let mut hits = Vec::new();
    for word in banned_calls {
        if code_only.contains(word) {
            hits.push(word);
        }
    }
    assert!(
        hits.is_empty(),
        "guard: `request_validation.rs` MUST be a shape-only pass — \
         it cannot reach into the semantic execution layer. Banned \
         call patterns found: {hits:?}",
    );
}
