//! The hub-owned desired editor state and its replay.
//!
//! Every provider-state mutation a caller issues is first recorded here, then
//! forwarded to the serving engine (if any). An establishment or a recovery
//! replays this set — as it is at install time — into the fresh engine before
//! any caller can observe it, so a replayed engine holds exactly what a fresh
//! engine given the same ordered inputs would hold.

use std::collections::btree_map::Entry as BTreeEntry;
use std::collections::hash_map::Entry;
use std::collections::{BTreeMap, HashMap, HashSet};

use super::admission::AdmittedRequest;
use crate::protocol::TypeProviderError;
use crate::traits::{CarrierActivation, CarrierScriptKind, TypeProvider};

/// The provider priority lane a forwarded file mutation uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Lane {
    Foreground,
    Background,
    Normal,
}

/// A provider-agnostic desired-state mutation.
#[derive(Debug)]
pub(super) enum DesiredMutation {
    Open {
        path: String,
        content: String,
    },
    Load {
        path: String,
        content: String,
    },
    Update {
        path: String,
        content: String,
    },
    Close {
        path: String,
    },
    ConfigurePaths {
        base_url: String,
        paths: serde_json::Value,
    },
    UpdateWorkspaceFolders {
        added: Vec<serde_json::Value>,
        removed: Vec<serde_json::Value>,
    },
    RegisterCarrier {
        source_path: String,
        companion_path: String,
        content: String,
        project_file_name: String,
    },
    RegisterCarrierMetadata {
        source_path: String,
        companion_path: String,
        content: String,
        project_file_name: String,
    },
    ActivateCarrier {
        source_path: String,
        companion_path: String,
        project_file_name: String,
        script_kind: CarrierScriptKind,
    },
    ActivateCarriers {
        members: Vec<CarrierActivation>,
    },
}

impl DesiredMutation {
    /// Open, load, or update bytes a successful forward commits.
    pub(super) fn committed_file(&self) -> Option<(&str, &str)> {
        match self {
            Self::Open { path, content }
            | Self::Load { path, content }
            | Self::Update { path, content } => Some((path, content)),
            Self::RegisterCarrier {
                companion_path,
                content,
                ..
            } => Some((companion_path, content)),
            _ => None,
        }
    }

    pub(super) fn closed_path(&self) -> Option<&str> {
        match self {
            Self::Close { path } => Some(path),
            _ => None,
        }
    }

    /// The paths whose crash attribution a successful application invalidates:
    /// the same position against NEW content is a new request.
    pub(super) fn touched_paths(&self) -> Vec<String> {
        match self {
            Self::Open { path, .. }
            | Self::Load { path, .. }
            | Self::Update { path, .. }
            | Self::Close { path } => vec![path.clone()],
            Self::RegisterCarrier { companion_path, .. }
            | Self::RegisterCarrierMetadata { companion_path, .. }
            | Self::ActivateCarrier { companion_path, .. } => vec![companion_path.clone()],
            Self::ActivateCarriers { members } => members
                .iter()
                .map(|member| member.companion_path.clone())
                .collect(),
            Self::ConfigurePaths { .. } | Self::UpdateWorkspaceFolders { .. } => Vec::new(),
        }
    }
}

/// Whether a recorded mutation still has to reach the serving engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Disposition {
    /// Forward it to the serving engine.
    Forward,
    /// The recorded state already covers it and forwarding would regress the
    /// engine: a discovery load of a file the editor holds open. The open
    /// overlay is the content authority, so the disk bytes neither replace the
    /// retained overlay nor reach the engine.
    Shadowed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FileMode {
    Load,
    Open,
}

#[derive(Debug, Clone)]
struct DesiredFile {
    content: String,
    mode: FileMode,
    lane: Lane,
    /// Order the file first became live in; an update keeps it, a close then
    /// reopen takes a new one — the order a fresh engine would have seen.
    first_live: u64,
}

#[derive(Debug, Clone)]
struct DesiredPathConfig {
    base_url: String,
    paths: serde_json::Value,
}

/// A published carrier-companion registration retained across establishments.
///
/// `content` is the carrier's generated bytes kept ONLY for the engine's local
/// position conversion; `project_file_name` is the owning configured project.
/// `script_kind` preserves the EXPLICIT parsing mode of the last explicit
/// activation: replay then re-registers the metadata and re-activates through
/// `activate_carrier_members` with the recorded kind, instead of letting
/// `register_carrier_member`'s path-based inference pick a different parsing
/// mode. `None` covers registrations that were never explicitly activated —
/// their live path was the self-activating `register_carrier_member`, so
/// replay keeps using it. Replay never re-sends content through the file set:
/// the engine-side plugin stays the carrier's content authority.
#[derive(Debug, Clone)]
struct DesiredCarrier {
    source_path: String,
    content: String,
    project_file_name: String,
    active: bool,
    script_kind: Option<CarrierScriptKind>,
}

/// The actor-owned desired editor state: the authority every replay reads.
#[derive(Default)]
pub(super) struct DesiredState {
    files: HashMap<String, DesiredFile>,
    next_first_live: u64,
    path_configs: Vec<DesiredPathConfig>,
    workspace_folders: Vec<serde_json::Value>,
    carriers: BTreeMap<String, DesiredCarrier>,
    admitted: HashSet<String>,
}

impl DesiredState {
    /// Discover the only mutation that must be suppressed before forwarding.
    pub(super) fn disposition(&self, mutation: &DesiredMutation) -> Disposition {
        match mutation {
            DesiredMutation::Load { path, .. }
                if self
                    .files
                    .get(path)
                    .is_some_and(|file| file.mode == FileMode::Open) =>
            {
                Disposition::Shadowed
            }
            _ => Disposition::Forward,
        }
    }

    /// Record a mutation's durable effect.
    pub(super) fn apply(&mut self, mutation: &DesiredMutation, lane: Lane) -> Disposition {
        let disposition = match mutation {
            DesiredMutation::Open { path, content } | DesiredMutation::Update { path, content } => {
                self.record_file(path, content, FileMode::Open, lane)
            }
            DesiredMutation::Load { path, content } => {
                self.record_file(path, content, FileMode::Load, lane)
            }
            DesiredMutation::Close { path } => {
                self.files.remove(path);
                // A closed companion must not be replayed as a carrier: a
                // retracted carrier never re-enters a fresh engine.
                self.carriers.remove(path);
                Disposition::Forward
            }
            DesiredMutation::ConfigurePaths { base_url, paths } => {
                match self
                    .path_configs
                    .iter_mut()
                    .find(|config| &config.base_url == base_url)
                {
                    Some(existing) => existing.paths = paths.clone(),
                    None => self.path_configs.push(DesiredPathConfig {
                        base_url: base_url.clone(),
                        paths: paths.clone(),
                    }),
                }
                Disposition::Forward
            }
            DesiredMutation::UpdateWorkspaceFolders { added, removed } => {
                for folder in removed.iter().chain(added) {
                    if let Some(uri) = folder_uri(folder) {
                        self.workspace_folders
                            .retain(|existing| folder_uri(existing) != Some(uri));
                    }
                }
                self.workspace_folders.extend(added.iter().cloned());
                Disposition::Forward
            }
            DesiredMutation::RegisterCarrier {
                source_path,
                companion_path,
                content,
                project_file_name,
            } => {
                self.carriers.insert(
                    companion_path.clone(),
                    DesiredCarrier {
                        source_path: source_path.clone(),
                        content: content.clone(),
                        project_file_name: project_file_name.clone(),
                        active: true,
                        script_kind: None,
                    },
                );
                Disposition::Forward
            }
            DesiredMutation::RegisterCarrierMetadata {
                source_path,
                companion_path,
                content,
                project_file_name,
            } => {
                match self.carriers.entry(companion_path.clone()) {
                    BTreeEntry::Occupied(mut entry) => {
                        let carrier = entry.get_mut();
                        carrier.source_path = source_path.clone();
                        carrier.content = content.clone();
                        carrier.project_file_name = project_file_name.clone();
                    }
                    BTreeEntry::Vacant(entry) => {
                        entry.insert(DesiredCarrier {
                            source_path: source_path.clone(),
                            content: content.clone(),
                            project_file_name: project_file_name.clone(),
                            active: false,
                            script_kind: None,
                        });
                    }
                }
                Disposition::Forward
            }
            DesiredMutation::ActivateCarrier {
                source_path,
                companion_path,
                project_file_name,
                script_kind,
                ..
            } => {
                self.activate(source_path, companion_path, project_file_name, *script_kind);
                Disposition::Forward
            }
            DesiredMutation::ActivateCarriers { members } => {
                for member in members {
                    self.activate(
                        &member.source_path,
                        &member.companion_path,
                        &member.project_file_name,
                        member.script_kind,
                    );
                }
                Disposition::Forward
            }
        };
        if disposition == Disposition::Forward {
            for path in mutation.touched_paths() {
                self.admitted.remove(&path);
            }
        }
        disposition
    }

    /// Mark successfully applied generated state. A replacement needs a new
    /// serving-epoch admission before any of these units can be written again.
    pub(super) fn record_admitted(
        &mut self,
        mutation: &DesiredMutation,
        admissions: &[AdmittedRequest],
    ) {
        for (path, _) in mutation.touched_paths().into_iter().zip(admissions) {
            self.admitted.insert(path);
        }
    }

    fn replay_admitted(&self, path: &str) -> bool {
        !self.admitted.contains(path)
    }

    /// Once replacement replay has finished, remove old-epoch generated state.
    /// Otherwise a later discovery load could be shadowed by an open overlay
    /// that the replacement never received. Returns exactly what was dropped
    /// so the install can hand it to the issuing tier for a fresh-admission
    /// re-arm — a replacement may not replay admitted state unproven.
    pub(super) fn discard_admitted(&mut self) -> super::admission::DroppedAdmittedState {
        let mut dropped = super::admission::DroppedAdmittedState::default();
        let admitted = std::mem::take(&mut self.admitted);
        let mut paths: Vec<&String> = admitted.iter().collect();
        paths.sort();
        for path in paths {
            if let Some(carrier) = self.carriers.remove(path) {
                dropped
                    .carriers
                    .push(super::admission::DroppedAdmittedCarrier {
                        source_path: carrier.source_path,
                        companion_path: path.clone(),
                        content: carrier.content,
                        project_file_name: carrier.project_file_name,
                        script_kind: if carrier.active {
                            carrier.script_kind
                        } else {
                            None
                        },
                    });
            }
            if self.files.remove(path).is_some() {
                dropped.files.push(path.clone());
            }
        }
        dropped
    }

    fn activate(
        &mut self,
        source_path: &str,
        companion_path: &str,
        project_file_name: &str,
        script_kind: CarrierScriptKind,
    ) {
        if let Some(carrier) = self.carriers.get_mut(companion_path) {
            carrier.source_path = source_path.to_string();
            carrier.project_file_name = project_file_name.to_string();
            carrier.active = true;
            carrier.script_kind = Some(script_kind);
        }
    }

    /// Record a file, preserving `open` > `load`: an opened file is never
    /// downgraded to load-only, and its overlay is never replaced by a
    /// discovery load. Editor updates promote loads to open.
    fn record_file(
        &mut self,
        path: &str,
        content: &str,
        mode: FileMode,
        lane: Lane,
    ) -> Disposition {
        match self.files.entry(path.to_string()) {
            Entry::Occupied(mut entry) => {
                let file = entry.get_mut();
                if mode == FileMode::Load && file.mode == FileMode::Open {
                    return Disposition::Shadowed;
                }
                file.content = content.to_string();
                file.mode = mode;
                file.lane = lane;
            }
            Entry::Vacant(entry) => {
                let first_live = self.next_first_live;
                self.next_first_live += 1;
                entry.insert(DesiredFile {
                    content: content.to_string(),
                    mode,
                    lane,
                    first_live,
                });
            }
        }
        Disposition::Forward
    }

    /// Replay the desired state into a freshly established engine.
    ///
    /// Folders, then path configurations, then the file set in first-live
    /// order on each file's recorded lane and access mode, then carrier
    /// registrations (CONTENTLESS). Any failure fails the replay: an engine
    /// that did not accept the complete desired state is never installed.
    pub(super) async fn replay_into<P>(
        &self,
        shared: &super::Shared<P>,
        serving: &super::Serving<P>,
    ) -> Result<HashSet<String>, TypeProviderError>
    where
        P: TypeProvider + ?Sized,
    {
        let provider = serving.provider.as_ref();
        let mut admissions = Vec::new();
        let mut refused_paths = HashSet::new();
        if !self.workspace_folders.is_empty() {
            provider
                .update_workspace_folders(self.workspace_folders.clone(), Vec::new())
                .await?;
        }
        for config in &self.path_configs {
            provider
                .configure_paths(&config.base_url, config.paths.clone())
                .await?;
        }

        let mut files: Vec<(&String, &DesiredFile)> = self.files.iter().collect();
        files.sort_unstable_by_key(|(_, file)| file.first_live);
        for (path, file) in files {
            if !self.replay_admitted(path) {
                continue;
            }
            let admission = match super::admission::generated_request(
                shared,
                Some(serving),
                path,
                None,
                None,
            ) {
                Ok(admission) => admission,
                // Held bytes are still desired, but excluded/unavailable units
                // never reach this incarnation or become applied receipts.
                Err(_) => {
                    refused_paths.insert(path.clone());
                    continue;
                }
            };
            let replayed = match (file.mode, file.lane) {
                (FileMode::Open, Lane::Foreground) => provider.open_file(path, &file.content),
                (FileMode::Open, Lane::Normal) => provider.open_file_normal(path, &file.content),
                (FileMode::Open, Lane::Background) => {
                    provider.open_file_background(path, &file.content)
                }
                (FileMode::Load, Lane::Foreground) => provider.load_file(path, &file.content),
                (FileMode::Load, Lane::Normal) => provider.load_file_normal(path, &file.content),
                (FileMode::Load, Lane::Background) => {
                    provider.load_file_background(path, &file.content)
                }
            };
            replayed.await.map_err(|error| {
                TypeProviderError::new(format!("replay of {path} failed: {error}"))
            })?;
            if let Some(mut admission) = admission {
                super::admission::refresh_replay_request(shared, serving, path, &mut admission)
                    .map_err(TypeProviderError::admission)?;
                admissions.push((path.as_str(), admission));
            }
        }

        // Carriers replay in two passes, mirroring the live publication →
        // activation sequence. Pass one registers every carrier's metadata
        // (routing + content) — except members registered without an explicit
        // activation, whose live path was the self-activating
        // `register_carrier_member` and whose replay keeps using it. Pass two
        // promotes the explicitly activated frontier through ONE
        // `activate_carrier_members` transaction, each with its RECORDED
        // parsing mode — never `register_carrier_member`'s path-based
        // inference, which would reactivate a recovered carrier in a
        // different parsing mode than the live activation used.
        let mut activations: Vec<CarrierActivation> = Vec::new();
        for (companion_path, carrier) in &self.carriers {
            if !self.replay_admitted(companion_path) {
                continue;
            }
            let mutation = DesiredMutation::RegisterCarrierMetadata {
                source_path: carrier.source_path.clone(),
                companion_path: companion_path.clone(),
                content: String::new(),
                project_file_name: carrier.project_file_name.clone(),
            };
            let requests = match super::admission::generated_mutation_requests(
                shared,
                Some(serving),
                &mutation,
            ) {
                Ok(requests) => requests,
                Err(_) => {
                    refused_paths.insert(companion_path.clone());
                    continue;
                }
            };
            let registration = if carrier.active && carrier.script_kind.is_none() {
                provider.register_carrier_member(
                    &carrier.source_path,
                    companion_path,
                    &carrier.content,
                    &carrier.project_file_name,
                )
            } else {
                provider.register_carrier_metadata(
                    &carrier.source_path,
                    companion_path,
                    &carrier.content,
                    &carrier.project_file_name,
                )
            };
            registration.await.map_err(|error| {
                TypeProviderError::new(format!(
                    "carrier replay of {companion_path} failed: {error}"
                ))
            })?;
            for mut request in requests {
                super::admission::refresh_replay_request(
                    shared,
                    serving,
                    companion_path,
                    &mut request,
                )
                .map_err(TypeProviderError::admission)?;
                admissions.push((companion_path.as_str(), request));
            }
            if let Some(script_kind) = carrier.script_kind {
                activations.push(CarrierActivation {
                    source_path: carrier.source_path.clone(),
                    companion_path: companion_path.clone(),
                    project_file_name: carrier.project_file_name.clone(),
                    script_kind,
                });
            }
        }
        if !activations.is_empty() {
            check_replay_admissions(shared, serving, &mut admissions)?;
            provider
                .activate_carrier_members(&activations)
                .await
                .map_err(|error| {
                    TypeProviderError::new(format!("carrier activation replay failed: {error}"))
                })?;
        }
        check_replay_admissions(shared, serving, &mut admissions)?;
        Ok(refused_paths)
    }

    /// Files a completed replay left on the engine: admitted overlays were
    /// discarded and are not serving content.
    pub(super) fn serving_file_contents(&self) -> Vec<(String, std::sync::Arc<str>)> {
        self.files
            .iter()
            .map(|(path, file)| {
                (
                    path.clone(),
                    std::sync::Arc::<str>::from(file.content.as_str()),
                )
            })
            .chain(self.carriers.iter().map(|(path, carrier)| {
                (
                    path.clone(),
                    std::sync::Arc::<str>::from(carrier.content.as_str()),
                )
            }))
            .collect()
    }
}

fn check_replay_admissions<P: ?Sized>(
    shared: &super::Shared<P>,
    serving: &super::Serving<P>,
    admissions: &mut [(&str, AdmittedRequest)],
) -> Result<(), TypeProviderError> {
    for (path, request) in admissions.iter_mut() {
        super::admission::refresh_replay_request(shared, serving, path, request)
            .map_err(TypeProviderError::admission)?;
    }
    // A later refresh can observe another content edit and evict an earlier
    // warm binding. Installation needs unchanged membership of replayed bytes,
    // not simultaneous content freshness across independent workspace reads.
    for (_, request) in admissions {
        super::admission::check_replay_membership_for_serving(shared, serving, request)
            .map_err(TypeProviderError::admission)?;
    }
    Ok(())
}

fn folder_uri(folder: &serde_json::Value) -> Option<&str> {
    folder.get("uri").and_then(serde_json::Value::as_str)
}

/// Forward a recorded mutation to the serving engine on the requested lane.
pub(super) async fn forward<P>(
    provider: &P,
    mutation: &DesiredMutation,
    lane: Lane,
) -> Result<(), TypeProviderError>
where
    P: TypeProvider + ?Sized,
{
    match mutation {
        DesiredMutation::Open { path, content } => match lane {
            Lane::Foreground => provider.open_file(path, content).await,
            Lane::Background => provider.open_file_background(path, content).await,
            Lane::Normal => provider.open_file_normal(path, content).await,
        },
        DesiredMutation::Load { path, content } => match lane {
            Lane::Foreground => provider.load_file(path, content).await,
            Lane::Background => provider.load_file_background(path, content).await,
            Lane::Normal => provider.load_file_normal(path, content).await,
        },
        DesiredMutation::Update { path, content } => match lane {
            Lane::Foreground => provider.update_file(path, content).await,
            Lane::Background => provider.update_file_background(path, content).await,
            Lane::Normal => provider.update_file_normal(path, content).await,
        },
        DesiredMutation::Close { path } => match lane {
            Lane::Foreground => provider.close_file(path).await,
            Lane::Background => provider.close_file_background(path).await,
            Lane::Normal => provider.close_file_normal(path).await,
        },
        DesiredMutation::ConfigurePaths { base_url, paths } => match lane {
            Lane::Background => {
                provider
                    .configure_paths_background(base_url, paths.clone())
                    .await
            }
            Lane::Foreground | Lane::Normal => {
                provider.configure_paths(base_url, paths.clone()).await
            }
        },
        DesiredMutation::UpdateWorkspaceFolders { added, removed } => match lane {
            Lane::Background => {
                provider
                    .update_workspace_folders_background(added.clone(), removed.clone())
                    .await
            }
            Lane::Foreground | Lane::Normal => {
                provider
                    .update_workspace_folders(added.clone(), removed.clone())
                    .await
            }
        },
        // Carrier registration has no priority lanes; the lane is irrelevant.
        DesiredMutation::RegisterCarrier {
            source_path,
            companion_path,
            content,
            project_file_name,
        } => {
            provider
                .register_carrier_member(source_path, companion_path, content, project_file_name)
                .await
        }
        DesiredMutation::RegisterCarrierMetadata {
            source_path,
            companion_path,
            content,
            project_file_name,
        } => {
            provider
                .register_carrier_metadata(source_path, companion_path, content, project_file_name)
                .await
        }
        DesiredMutation::ActivateCarrier {
            source_path,
            companion_path,
            project_file_name,
            script_kind,
        } => {
            provider
                .activate_carrier_member(
                    source_path,
                    companion_path,
                    project_file_name,
                    *script_kind,
                )
                .await
        }
        DesiredMutation::ActivateCarriers { members } => {
            provider.activate_carrier_members(members).await
        }
    }
}
