//! Vue-specific lint rules (essential + recommended).

mod attribute_order;
mod html_self_closing;
mod multi_word_component_names;
mod no_child_content;
mod no_constant_condition;
mod no_deprecated_scope_attribute;
mod no_deprecated_slot_attribute;
mod no_deprecated_v_bind_sync;
mod no_deprecated_v_on_native_modifier;
mod no_deprecated_v_on_number_modifiers;
mod no_dupe_v_else_if;
mod no_duplicate_attributes;
mod no_reserved_component_names;
mod no_template_key;
mod no_template_target_blank;
mod no_textarea_mustache;
mod no_unused_components;
mod no_unused_props;
mod no_use_v_if_with_v_for;
mod no_useless_template_attrs;
mod no_v_for_index_as_key;
mod no_v_text_v_html_on_component;
mod prefer_true_attribute_shorthand;
mod require_component_is;
mod require_v_for_key;
mod v_bind_style;
mod v_on_style;
mod v_slot_style;
mod valid_v_bind;
mod valid_v_else;
mod valid_v_for;
mod valid_v_if;
mod valid_v_model;
mod valid_v_on;
mod valid_v_once;
mod valid_v_pre;
mod valid_v_show;

pub use attribute_order::AttributeOrder;
pub use html_self_closing::HtmlSelfClosing;
pub use multi_word_component_names::MultiWordComponentNames;
pub use no_child_content::NoChildContent;
pub use no_constant_condition::NoConstantCondition;
pub use no_deprecated_scope_attribute::NoDeprecatedScopeAttribute;
pub use no_deprecated_slot_attribute::NoDeprecatedSlotAttribute;
pub use no_deprecated_v_bind_sync::NoDeprecatedVBindSync;
pub use no_deprecated_v_on_native_modifier::NoDeprecatedVOnNativeModifier;
pub use no_deprecated_v_on_number_modifiers::NoDeprecatedVOnNumberModifiers;
pub use no_dupe_v_else_if::NoDupeVElseIf;
pub use no_duplicate_attributes::NoDuplicateAttributes;
pub use no_reserved_component_names::NoReservedComponentNames;
pub use no_template_key::NoTemplateKey;
pub use no_template_target_blank::NoTemplateTargetBlank;
pub use no_textarea_mustache::NoTextareaMustache;
pub use no_unused_components::NoUnusedComponents;
pub use no_unused_props::NoUnusedProps;
pub use no_use_v_if_with_v_for::NoUseVIfWithVFor;
pub use no_useless_template_attrs::NoUselessTemplateAttrs;
pub use no_v_for_index_as_key::NoVForIndexAsKey;
pub use no_v_text_v_html_on_component::NoVTextVHtmlOnComponent;
pub use prefer_true_attribute_shorthand::PreferTrueAttributeShorthand;
pub use require_component_is::RequireComponentIs;
pub use require_v_for_key::RequireVForKey;
pub use v_bind_style::VBindStyle;
pub use v_on_style::VOnStyle;
pub use v_slot_style::VSlotStyle;
pub use valid_v_bind::ValidVBind;
pub use valid_v_else::ValidVElse;
pub use valid_v_for::ValidVFor;
pub use valid_v_if::ValidVIf;
pub use valid_v_model::ValidVModel;
pub use valid_v_on::ValidVOn;
pub use valid_v_once::ValidVOnce;
pub use valid_v_pre::ValidVPre;
pub use valid_v_show::ValidVShow;
