//! Vue-specific lint rules (essential + recommended).

mod attribute_hyphenation;
mod attribute_order;
mod block_order;
mod conditional_root_complex;
mod html_self_closing;
mod match_component_file_name;
mod multi_word_component_names;
mod no_bare_strings_in_template;
mod no_child_content;
mod no_constant_condition;
mod no_deprecated_data_object_declaration;
mod no_deprecated_delete_set;
mod no_deprecated_destroyed_lifecycle;
mod no_deprecated_dollar_listeners_api;
mod no_deprecated_dollar_scopedslots_api;
mod no_deprecated_events_api;
mod no_deprecated_filter;
mod no_deprecated_functional_template;
mod no_deprecated_html_element_is;
mod no_deprecated_inline_template;
mod no_deprecated_model_definition;
mod no_deprecated_props_default_this;
mod no_deprecated_router_link_tag_prop;
mod no_deprecated_scope_attribute;
mod no_deprecated_slot_attribute;
mod no_deprecated_v_bind_sync;
mod no_deprecated_v_is;
mod no_deprecated_v_on_native_modifier;
mod no_deprecated_v_on_number_modifiers;
mod no_deprecated_vue_config_keycodes;
mod no_dupe_v_else_if;
mod no_duplicate_attr_inheritance;
mod no_duplicate_attributes;
mod no_lone_template;
mod no_multiple_objects_in_class;
mod no_multiple_slot_args;
mod no_mutating_props;
mod no_negated_v_if_condition;
mod no_reserved_component_names;
mod no_root_v_if;
mod no_static_inline_styles;
mod no_template_key;
mod no_template_shadow;
mod no_template_target_blank;
mod no_textarea_mustache;
mod no_undef_properties;
mod no_unused_components;
mod no_unused_props;
mod no_unused_slots;
mod no_unused_vars;
mod no_use_v_if_with_v_for;
mod no_useless_mustaches;
mod no_useless_template_attrs;
mod no_useless_v_bind;
mod no_v_for_index_as_key;
mod no_v_for_template_key_on_child;
mod no_v_text_v_html_on_component;
mod prefer_separate_static_class;
mod prefer_true_attribute_shorthand;
mod prefer_v_bind_shorthand;
mod require_component_is;
mod require_toggle_inside_transition;
mod require_v_for_key;
mod slot_name_casing;
mod this_in_template;
mod use_v_on_exact;
mod v_bind_style;
mod v_for_delimiter_style;
mod v_on_event_hyphenation;
mod v_on_handler_style;
mod v_on_style;
mod v_slot_style;
mod valid_template_root;
mod valid_v_bind;
mod valid_v_cloak;
mod valid_v_else;
mod valid_v_for;
mod valid_v_html;
mod valid_v_if;
mod valid_v_is;
mod valid_v_memo;
mod valid_v_model;
mod valid_v_on;
mod valid_v_once;
mod valid_v_pre;
mod valid_v_show;
mod valid_v_slot;
mod valid_v_text;

mod block_lang;
mod component_name_in_template_casing;
mod custom_event_name_casing;
mod enforce_style_attribute;
mod html_button_has_type;
mod no_empty_component_block;
mod no_undef_components;
mod no_unused_refs;
mod no_v_text_directive;

mod define_model_type_required;
mod no_duplicate_model_modifiers;
mod no_invalid_html_nesting;
mod require_define_slots;
mod required_slot_has_default;

pub use attribute_hyphenation::AttributeHyphenation;
pub use attribute_order::AttributeOrder;
pub use block_order::BlockOrder;
pub use conditional_root_complex::ConditionalRootComplex;
pub use html_self_closing::HtmlSelfClosing;
pub use match_component_file_name::MatchComponentFileName;
pub use multi_word_component_names::MultiWordComponentNames;
pub use no_bare_strings_in_template::NoBareStringsInTemplate;
pub use no_child_content::NoChildContent;
pub use no_constant_condition::NoConstantCondition;
pub use no_deprecated_data_object_declaration::NoDeprecatedDataObjectDeclaration;
pub use no_deprecated_delete_set::NoDeprecatedDeleteSet;
pub use no_deprecated_destroyed_lifecycle::NoDeprecatedDestroyedLifecycle;
pub use no_deprecated_dollar_listeners_api::NoDeprecatedDollarListenersApi;
pub use no_deprecated_dollar_scopedslots_api::NoDeprecatedDollarScopedslotsApi;
pub use no_deprecated_events_api::NoDeprecatedEventsApi;
pub use no_deprecated_filter::NoDeprecatedFilter;
pub use no_deprecated_functional_template::NoDeprecatedFunctionalTemplate;
pub use no_deprecated_html_element_is::NoDeprecatedHtmlElementIs;
pub use no_deprecated_inline_template::NoDeprecatedInlineTemplate;
pub use no_deprecated_model_definition::NoDeprecatedModelDefinition;
pub use no_deprecated_props_default_this::NoDeprecatedPropsDefaultThis;
pub use no_deprecated_router_link_tag_prop::NoDeprecatedRouterLinkTagProp;
pub use no_deprecated_scope_attribute::NoDeprecatedScopeAttribute;
pub use no_deprecated_slot_attribute::NoDeprecatedSlotAttribute;
pub use no_deprecated_v_bind_sync::NoDeprecatedVBindSync;
pub use no_deprecated_v_is::NoDeprecatedVIs;
pub use no_deprecated_v_on_native_modifier::NoDeprecatedVOnNativeModifier;
pub use no_deprecated_v_on_number_modifiers::NoDeprecatedVOnNumberModifiers;
pub use no_deprecated_vue_config_keycodes::NoDeprecatedVueConfigKeycodes;
pub use no_dupe_v_else_if::NoDupeVElseIf;
pub use no_duplicate_attr_inheritance::NoDuplicateAttrInheritance;
pub use no_duplicate_attributes::NoDuplicateAttributes;
pub use no_lone_template::NoLoneTemplate;
pub use no_multiple_objects_in_class::NoMultipleObjectsInClass;
pub use no_multiple_slot_args::NoMultipleSlotArgs;
pub use no_mutating_props::NoMutatingProps;
pub use no_negated_v_if_condition::NoNegatedVIfCondition;
pub use no_reserved_component_names::NoReservedComponentNames;
pub use no_root_v_if::NoRootVIf;
pub use no_static_inline_styles::NoStaticInlineStyles;
pub use no_template_key::NoTemplateKey;
pub use no_template_shadow::NoTemplateShadow;
pub use no_template_target_blank::NoTemplateTargetBlank;
pub use no_textarea_mustache::NoTextareaMustache;
pub use no_undef_properties::NoUndefProperties;
pub use no_unused_components::NoUnusedComponents;
pub use no_unused_props::NoUnusedProps;
pub use no_unused_slots::NoUnusedSlots;
pub use no_unused_vars::NoUnusedVars;
pub use no_use_v_if_with_v_for::NoUseVIfWithVFor;
pub use no_useless_mustaches::NoUselessMustaches;
pub use no_useless_template_attrs::NoUselessTemplateAttrs;
pub use no_useless_v_bind::NoUselessVBind;
pub use no_v_for_index_as_key::NoVForIndexAsKey;
pub use no_v_for_template_key_on_child::NoVForTemplateKeyOnChild;
pub use no_v_text_v_html_on_component::NoVTextVHtmlOnComponent;
pub use prefer_separate_static_class::PreferSeparateStaticClass;
pub use prefer_true_attribute_shorthand::PreferTrueAttributeShorthand;
pub use prefer_v_bind_shorthand::PreferVBindShorthand;
pub use require_component_is::RequireComponentIs;
pub use require_toggle_inside_transition::RequireToggleInsideTransition;
pub use require_v_for_key::RequireVForKey;
pub use slot_name_casing::SlotNameCasing;
pub use this_in_template::ThisInTemplate;
pub use use_v_on_exact::UseVOnExact;
pub use v_bind_style::VBindStyle;
pub use v_for_delimiter_style::VForDelimiterStyle;
pub use v_on_event_hyphenation::VOnEventHyphenation;
pub use v_on_handler_style::VOnHandlerStyle;
pub use v_on_style::VOnStyle;
pub use v_slot_style::VSlotStyle;
pub use valid_template_root::ValidTemplateRoot;
pub use valid_v_bind::ValidVBind;
pub use valid_v_cloak::ValidVCloak;
pub use valid_v_else::ValidVElse;
pub use valid_v_for::ValidVFor;
pub use valid_v_html::ValidVHtml;
pub use valid_v_if::ValidVIf;
pub use valid_v_is::ValidVIs;
pub use valid_v_memo::ValidVMemo;
pub use valid_v_model::ValidVModel;
pub use valid_v_on::ValidVOn;
pub use valid_v_once::ValidVOnce;
pub use valid_v_pre::ValidVPre;
pub use valid_v_show::ValidVShow;
pub use valid_v_slot::ValidVSlot;
pub use valid_v_text::ValidVText;

pub use block_lang::BlockLang;
pub use component_name_in_template_casing::ComponentNameInTemplateCasing;
pub use custom_event_name_casing::CustomEventNameCasing;
pub use enforce_style_attribute::EnforceStyleAttribute;
pub use html_button_has_type::HtmlButtonHasType;
pub use no_empty_component_block::NoEmptyComponentBlock;
pub use no_undef_components::NoUndefComponents;
pub use no_unused_refs::NoUnusedRefs;
pub use no_v_text_directive::NoVTextDirective;

pub use define_model_type_required::DefineModelTypeRequired;
pub use no_duplicate_model_modifiers::NoDuplicateModelModifiers;
pub use no_invalid_html_nesting::NoInvalidHtmlNesting;
pub use require_define_slots::RequireDefineSlots;
pub use required_slot_has_default::RequiredSlotHasDefault;
