/* This file is auto-generated by packages/types/scripts/generate-tsx-attributes.cjs */

/**
 * Maps HTML element types to their corresponding Vue attribute interfaces.
 * Used by ExtractComponentProps to provide proper attribute types for HTML elements.
 *
 */
export type ExtractFromHTMLElement<T> =
  T extends HTMLVideoElement ? import("vue").VideoHTMLAttributes :
  T extends HTMLAudioElement ? import("vue").AudioHTMLAttributes :
  T extends HTMLMediaElement ? import("vue").MediaHTMLAttributes :
  T extends HTMLAnchorElement ? import("vue").AnchorHTMLAttributes :
  T extends HTMLAreaElement ? import("vue").AreaHTMLAttributes :
  T extends HTMLBaseElement ? import("vue").BaseHTMLAttributes :
  T extends HTMLQuoteElement ? import("vue").QuoteHTMLAttributes :
  T extends HTMLButtonElement ? import("vue").ButtonHTMLAttributes :
  T extends HTMLCanvasElement ? import("vue").CanvasHTMLAttributes :
  T extends HTMLTableColElement ? import("vue").ColgroupHTMLAttributes :
  T extends HTMLDetailsElement ? import("vue").DetailsHTMLAttributes :
  T extends HTMLModElement ? import("vue").InsHTMLAttributes :
  T extends HTMLDialogElement ? import("vue").DialogHTMLAttributes :
  T extends HTMLEmbedElement ? import("vue").EmbedHTMLAttributes :
  T extends HTMLFormElement ? import("vue").FormHTMLAttributes :
  T extends HTMLHtmlElement ? import("vue").HtmlHTMLAttributes :
  T extends HTMLIFrameElement ? import("vue").IframeHTMLAttributes :
  T extends HTMLImageElement ? import("vue").ImgHTMLAttributes :
  T extends HTMLInputElement ? import("vue").InputHTMLAttributes :
  T extends HTMLLabelElement ? import("vue").LabelHTMLAttributes :
  T extends HTMLLIElement ? import("vue").LiHTMLAttributes :
  T extends HTMLLinkElement ? import("vue").LinkHTMLAttributes :
  T extends HTMLMapElement ? import("vue").MapHTMLAttributes :
  T extends HTMLMenuElement ? import("vue").MenuHTMLAttributes :
  T extends HTMLMetaElement ? import("vue").MetaHTMLAttributes :
  T extends HTMLMeterElement ? import("vue").MeterHTMLAttributes :
  T extends HTMLObjectElement ? import("vue").ObjectHTMLAttributes :
  T extends HTMLOListElement ? import("vue").OlHTMLAttributes :
  T extends HTMLOptGroupElement ? import("vue").OptgroupHTMLAttributes :
  T extends HTMLOptionElement ? import("vue").OptionHTMLAttributes :
  T extends HTMLOutputElement ? import("vue").OutputHTMLAttributes :
  T extends HTMLParamElement ? import("vue").ParamHTMLAttributes :
  T extends HTMLProgressElement ? import("vue").ProgressHTMLAttributes :
  T extends HTMLScriptElement ? import("vue").ScriptHTMLAttributes :
  T extends HTMLSelectElement ? import("vue").SelectHTMLAttributes :
  T extends HTMLSourceElement ? import("vue").SourceHTMLAttributes :
  T extends HTMLStyleElement ? import("vue").StyleHTMLAttributes :
  T extends HTMLTableElement ? import("vue").TableHTMLAttributes :
  T extends HTMLTextAreaElement ? import("vue").TextareaHTMLAttributes :
  T extends HTMLTableCellElement ? import("vue").ThHTMLAttributes :
  T extends HTMLTimeElement ? import("vue").TimeHTMLAttributes :
  T extends HTMLTrackElement ? import("vue").TrackHTMLAttributes :
  T extends HTMLDataElement ? import("vue").DataHTMLAttributes :
  import("vue").HTMLAttributes;
