/* This file is auto-generated by packages/types/scripts/generate-tsx-attributes.js */
import "vue/jsx";
declare module "vue" {
  interface HTMLAttributes {
    "v-slot"?: (instance: HTMLElement) => any;
  }
  interface AnchorHTMLAttributes {
    "v-slot"?: (instance: HTMLAnchorElement) => any;
  }
  interface AreaHTMLAttributes {
    "v-slot"?: (instance: HTMLAreaElement) => any;
  }
  interface AudioHTMLAttributes {
    "v-slot"?: (instance: HTMLAudioElement) => any;
  }
  interface BaseHTMLAttributes {
    "v-slot"?: (instance: HTMLBaseElement) => any;
  }
  interface BlockquoteHTMLAttributes {
    "v-slot"?: (instance: HTMLQuoteElement) => any;
  }
  interface ButtonHTMLAttributes {
    "v-slot"?: (instance: HTMLButtonElement) => any;
  }
  interface CanvasHTMLAttributes {
    "v-slot"?: (instance: HTMLCanvasElement) => any;
  }
  interface ColHTMLAttributes {
    "v-slot"?: (instance: HTMLTableColElement) => any;
  }
  interface ColgroupHTMLAttributes {
    "v-slot"?: (instance: HTMLTableColElement) => any;
  }
  interface DataHTMLAttributes {
    "v-slot"?: (instance: HTMLDataElement) => any;
  }
  interface DetailsHTMLAttributes {
    "v-slot"?: (instance: HTMLDetailsElement) => any;
  }
  interface DelHTMLAttributes {
    "v-slot"?: (instance: HTMLModElement) => any;
  }
  interface DialogHTMLAttributes {
    "v-slot"?: (instance: HTMLDialogElement) => any;
  }
  interface EmbedHTMLAttributes {
    "v-slot"?: (instance: HTMLEmbedElement) => any;
  }
  interface FieldsetHTMLAttributes {
    "v-slot"?: (instance: HTMLElement) => any;
  }
  interface FormHTMLAttributes {
    "v-slot"?: (instance: HTMLFormElement) => any;
  }
  interface HtmlHTMLAttributes {
    "v-slot"?: (instance: HTMLHtmlElement) => any;
  }
  interface IframeHTMLAttributes {
    "v-slot"?: (instance: HTMLIFrameElement) => any;
  }
  interface ImgHTMLAttributes {
    "v-slot"?: (instance: HTMLImageElement) => any;
  }
  interface InsHTMLAttributes {
    "v-slot"?: (instance: HTMLModElement) => any;
  }
  interface InputHTMLAttributes {
    "v-slot"?: (instance: HTMLInputElement) => any;
  }
  interface KeygenHTMLAttributes {
    "v-slot"?: (instance: HTMLElement) => any;
  }
  interface LabelHTMLAttributes {
    "v-slot"?: (instance: HTMLLabelElement) => any;
  }
  interface LiHTMLAttributes {
    "v-slot"?: (instance: HTMLLIElement) => any;
  }
  interface LinkHTMLAttributes {
    "v-slot"?: (instance: HTMLLinkElement) => any;
  }
  interface MapHTMLAttributes {
    "v-slot"?: (instance: HTMLMapElement) => any;
  }
  interface MenuHTMLAttributes {
    "v-slot"?: (instance: HTMLMenuElement) => any;
  }
  interface MediaHTMLAttributes {
    "v-slot"?: (instance: HTMLMediaElement) => any;
  }
  interface MetaHTMLAttributes {
    "v-slot"?: (instance: HTMLMetaElement) => any;
  }
  interface MeterHTMLAttributes {
    "v-slot"?: (instance: HTMLMeterElement) => any;
  }
  interface QuoteHTMLAttributes {
    "v-slot"?: (instance: HTMLQuoteElement) => any;
  }
  interface ObjectHTMLAttributes {
    "v-slot"?: (instance: HTMLObjectElement) => any;
  }
  interface OlHTMLAttributes {
    "v-slot"?: (instance: HTMLOListElement) => any;
  }
  interface OptgroupHTMLAttributes {
    "v-slot"?: (instance: HTMLOptGroupElement) => any;
  }
  interface OptionHTMLAttributes {
    "v-slot"?: (instance: HTMLOptionElement) => any;
  }
  interface OutputHTMLAttributes {
    "v-slot"?: (instance: HTMLOutputElement) => any;
  }
  interface ParamHTMLAttributes {
    "v-slot"?: (instance: HTMLParamElement) => any;
  }
  interface ProgressHTMLAttributes {
    "v-slot"?: (instance: HTMLProgressElement) => any;
  }
  interface ScriptHTMLAttributes {
    "v-slot"?: (instance: HTMLScriptElement) => any;
  }
  interface SelectHTMLAttributes {
    "v-slot"?: (instance: HTMLSelectElement) => any;
  }
  interface SourceHTMLAttributes {
    "v-slot"?: (instance: HTMLSourceElement) => any;
  }
  interface StyleHTMLAttributes {
    "v-slot"?: (instance: HTMLStyleElement) => any;
  }
  interface TableHTMLAttributes {
    "v-slot"?: (instance: HTMLTableElement) => any;
  }
  interface TextareaHTMLAttributes {
    "v-slot"?: (instance: HTMLTextAreaElement) => any;
  }
  interface TdHTMLAttributes {
    "v-slot"?: (instance: HTMLTableCellElement) => any;
  }
  interface ThHTMLAttributes {
    "v-slot"?: (instance: HTMLTableCellElement) => any;
  }
  interface TimeHTMLAttributes {
    "v-slot"?: (instance: HTMLTimeElement) => any;
  }
  interface TrackHTMLAttributes {
    "v-slot"?: (instance: HTMLTrackElement) => any;
  }
  interface VideoHTMLAttributes {
    "v-slot"?: (instance: HTMLVideoElement) => any;
  }
  interface WebViewHTMLAttributes {
    "v-slot"?: (instance: HTMLElement) => any;
  }
}
