//! Shared expression-plan builder for resolved template expressions.
//!
//! Produces a [`MappedGeneratedText`] — the resolved expression string plus an
//! ordered segment plan marking which byte runs are authored source (mapped)
//! and which are resolver scaffolding (unmapped). This is the single
//! sourcemap-aware analogue of
//! [`build_prefixed_expr`](super::vapor::interpolation::build_prefixed_expr):
//! both walk the same OXC binding data and emit byte-identical text; the flat
//! builder discards positions while the segment builder records them.
//!
//! The flat `build_prefixed_expr` delegates here through a zero-overhead
//! [`StringSink`], so the runtime path and the sourcemap path can never drift in
//! their generated bytes.

use crate::template::code_gen::binding::{is_simple_ident, BindingResolver};
use crate::template::code_gen::types::MappedGeneratedText;
use crate::template::oxc::types::OxcParsedExpression;
use crate::utils::oxc::bindings::keywords::{is_global, is_keyword};

/// Ordered destination for the resolved-expression walk.
///
/// Two implementations: [`StringSink`] (flat string, ignores positions — the
/// runtime `build_prefixed_expr` path) and [`SegmentSink`] (records a
/// [`MappedGeneratedText`] plan). Keeping one walk over two sinks guarantees the
/// flat and segmented builders produce identical generated bytes.
pub(crate) trait ExprSink {
    /// Append authored source text whose first byte is at file offset
    /// `source_start`.
    fn push_source(&mut self, text: &str, source_start: u32);
    /// Append synthetic scaffolding text (binding prefix/suffix, keyword
    /// brackets, shorthand key) that must not map to source.
    fn push_synthetic(&mut self, text: &str);
}

/// Flat-string sink: both pushes append to the buffer; source positions are
/// discarded. Keeps `build_prefixed_expr` free of any segment-plan overhead.
pub(crate) struct StringSink<'a>(pub &'a mut String);

impl ExprSink for StringSink<'_> {
    #[inline]
    fn push_source(&mut self, text: &str, _source_start: u32) {
        self.0.push_str(text);
    }
    #[inline]
    fn push_synthetic(&mut self, text: &str) {
        self.0.push_str(text);
    }
}

/// Segment-recording sink: builds the [`MappedGeneratedText`] plan.
#[derive(Default)]
struct SegmentSink {
    out: MappedGeneratedText,
}

impl ExprSink for SegmentSink {
    #[inline]
    fn push_source(&mut self, text: &str, source_start: u32) {
        self.out.push(text, Some(source_start));
    }
    #[inline]
    fn push_synthetic(&mut self, text: &str) {
        self.out.push(text, None);
    }
}

/// Build the segmented plan for a resolved (possibly compound) expression.
///
/// `.text` is byte-identical to
/// `build_prefixed_expr(expr, inner_start, oxc, resolver, ts_skip_ranges)`.
pub fn build_prefixed_expr_segments(
    expr: &str,
    inner_start: u32,
    oxc: &OxcParsedExpression<'_>,
    resolver: &BindingResolver<'_>,
    ts_skip_ranges: &[(u32, u32)],
) -> MappedGeneratedText {
    let mut sink = SegmentSink::default();
    write_prefixed_expr(&mut sink, expr, inner_start, oxc, resolver, ts_skip_ranges);
    sink.out
}

/// Build the segmented plan for a simple-identifier expression with no OXC
/// binding data (the resolver-only path).
///
/// `.text` is byte-identical to `resolver.resolve_simple_expr(expr)`.
pub fn resolve_simple_expr_segments(
    resolver: &BindingResolver<'_>,
    expr: &str,
    inner_start: u32,
) -> MappedGeneratedText {
    let mut sink = SegmentSink::default();
    write_simple_expr(&mut sink, resolver, expr, inner_start);
    sink.out
}

/// Core resolved-expression walk shared by the flat and segmented builders.
///
/// Mirrors `build_prefixed_expr` exactly: simple identifiers route through
/// [`write_simple_expr`]; compound expressions walk the OXC bindings, emitting
/// each binding's synthetic prefix/suffix around the mapped identifier plus the
/// verbatim source chunks between bindings (with TS-skip ranges removed).
pub(crate) fn write_prefixed_expr<S: ExprSink>(
    sink: &mut S,
    expr: &str,
    inner_start: u32,
    oxc: &OxcParsedExpression<'_>,
    resolver: &BindingResolver<'_>,
    ts_skip_ranges: &[(u32, u32)],
) {
    let Some(bindings) = &oxc.bindings else {
        return write_simple_expr(sink, resolver, expr, inner_start);
    };
    if bindings.bindings.is_empty() {
        return write_simple_expr(sink, resolver, expr, inner_start);
    }

    // Single binding spanning the whole simple identifier → simple resolution.
    // An ignored single binding (v-for/v-slot local) stays a bare mapped
    // identifier with no prefix.
    if bindings.bindings.len() == 1 && is_simple_ident(expr) {
        if bindings.bindings[0].ignore {
            let trim_offset = (expr.len() - expr.trim_start().len()) as u32;
            sink.push_source(expr.trim(), inner_start + trim_offset);
            return;
        }
        return write_simple_expr(sink, resolver, expr, inner_start);
    }

    // Compound walk: insert prefix/suffix at expression-relative offsets.
    let expr_start = inner_start as usize;
    let trim_offset = expr.len() - expr.trim_start().len();
    let trimmed = expr.trim();
    let mut last_end = 0usize;

    // Convert expression-relative skip ranges to trimmed-relative.
    let trimmed_skips: Vec<(usize, usize)> = if ts_skip_ranges.is_empty() {
        Vec::new()
    } else {
        ts_skip_ranges
            .iter()
            .filter_map(|&(s, e)| {
                let ts = (s as usize).saturating_sub(trim_offset);
                let te = (e as usize).saturating_sub(trim_offset);
                if te > ts && ts < trimmed.len() {
                    Some((ts, te.min(trimmed.len())))
                } else {
                    None
                }
            })
            .collect()
    };

    for binding in &bindings.bindings {
        if binding.ignore {
            continue;
        }

        // Convert file-relative pos to expr-trimmed-relative offset.
        let rel_pos = (binding.pos as usize)
            .saturating_sub(expr_start)
            .saturating_sub(trim_offset);

        if rel_pos > trimmed.len() {
            continue; // out of range
        }

        // Verbatim source chunk before this binding, skipping TS-only ranges.
        if rel_pos > last_end {
            push_chunk_with_skips(
                sink,
                trimmed,
                last_end,
                rel_pos,
                &trimmed_skips,
                inner_start,
                trim_offset,
            );
        }

        let prefix = resolver.resolve_prefix(binding.name);
        let suffix = resolver.resolve_suffix(binding.name);

        // Shorthand `{ total }` with a prefix/suffix expands to
        // `{ total: _ctx.total }`. The leading key duplication is synthetic.
        if binding.is_shorthand && (!prefix.is_empty() || !suffix.is_empty()) {
            sink.push_synthetic(binding.name);
            sink.push_synthetic(": ");
        }

        sink.push_synthetic(prefix);
        sink.push_source(binding.name, binding.pos);
        sink.push_synthetic(suffix);

        last_end = rel_pos + binding.name.len();
    }

    // Verbatim source tail after the last binding, skipping TS-only ranges.
    if last_end < trimmed.len() {
        push_chunk_with_skips(
            sink,
            trimmed,
            last_end,
            trimmed.len(),
            &trimmed_skips,
            inner_start,
            trim_offset,
        );
    }
}

/// Resolve a simple identifier (or pass-through) expression into `sink`.
///
/// Mirrors `BindingResolver::resolve_simple_expr` byte-for-byte: the prefix and
/// suffix (or keyword brackets) are synthetic; only the identifier itself maps.
pub(crate) fn write_simple_expr<S: ExprSink>(
    sink: &mut S,
    resolver: &BindingResolver<'_>,
    expr: &str,
    inner_start: u32,
) {
    let trimmed = expr.trim();
    let trim_offset = (expr.len() - expr.trim_start().len()) as u32;
    let name_pos = inner_start + trim_offset;

    if !is_simple_ident(trimmed) {
        // Non-identifier expression passes through verbatim as authored source.
        sink.push_source(trimmed, name_pos);
        return;
    }

    let is_kw = is_keyword(trimmed.as_bytes());

    // Keywords that are not registered bindings, globals, and `$event` pass
    // through unchanged (e.g. `true`, `false`, `window`).
    if (is_kw && resolver.get(trimmed).is_none())
        || is_global(trimmed.as_bytes())
        || trimmed == "$event"
    {
        sink.push_source(trimmed, name_pos);
        return;
    }

    let prefix = resolver.resolve_prefix(trimmed);
    let suffix = resolver.resolve_suffix(trimmed);

    if is_kw && !prefix.is_empty() {
        // Keyword member access uses bracket notation: `$props["class"]`.
        let base = prefix.trim_end_matches('.');
        sink.push_synthetic(base);
        sink.push_synthetic("[\"");
        sink.push_source(trimmed, name_pos);
        sink.push_synthetic("\"]");
        sink.push_synthetic(suffix);
    } else {
        sink.push_synthetic(prefix);
        sink.push_source(trimmed, name_pos);
        sink.push_synthetic(suffix);
    }
}

/// Copy `text[start..end]` into `sink` as authored source, skipping any bytes
/// that overlap the sorted `skips` ranges (TS syntax removed by `force_js`).
/// Each emitted sub-chunk maps to its precise file offset
/// (`inner_start + trim_offset + <offset within trimmed>`).
fn push_chunk_with_skips<S: ExprSink>(
    sink: &mut S,
    text: &str,
    start: usize,
    end: usize,
    skips: &[(usize, usize)],
    inner_start: u32,
    trim_offset: usize,
) {
    let src_of = |off: usize| inner_start + (trim_offset + off) as u32;
    if skips.is_empty() {
        sink.push_source(&text[start..end], src_of(start));
        return;
    }
    let mut pos = start;
    for &(ss, se) in skips {
        if se <= start || ss >= end {
            continue;
        }
        let effective_start = ss.max(start);
        let effective_end = se.min(end);
        if effective_start > pos {
            sink.push_source(&text[pos..effective_start], src_of(pos));
        }
        pos = effective_end;
    }
    if pos < end {
        sink.push_source(&text[pos..end], src_of(pos));
    }
}

#[cfg(test)]
#[path = "expression_tests.rs"]
mod expression_tests;
