//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_001_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("changelog_versions", "/ChangelogVersions.vue", include_str!("fixtures/ChangelogVersions.vue")),
        CorpusCase::new("chat_message", "/ChatMessage.vue", include_str!("fixtures/ChatMessage.vue")),
        CorpusCase::new("chat_messages", "/ChatMessages.vue", include_str!("fixtures/ChatMessages.vue")),
        CorpusCase::new("chat_palette", "/ChatPalette.vue", include_str!("fixtures/ChatPalette.vue")),
        CorpusCase::new("chat_prompt", "/ChatPrompt.vue", include_str!("fixtures/ChatPrompt.vue")),
        CorpusCase::new("chat_prompt_submit", "/ChatPromptSubmit.vue", include_str!("fixtures/ChatPromptSubmit.vue")),
        CorpusCase::new("chat_reasoning", "/ChatReasoning.vue", include_str!("fixtures/ChatReasoning.vue")),
        CorpusCase::new("chat_shimmer", "/ChatShimmer.vue", include_str!("fixtures/ChatShimmer.vue")),
        CorpusCase::new("chat_tool", "/ChatTool.vue", include_str!("fixtures/ChatTool.vue")),
        CorpusCase::new("checkbox", "/Checkbox.vue", include_str!("fixtures/Checkbox.vue")),
        CorpusCase::new("checkbox_group", "/CheckboxGroup.vue", include_str!("fixtures/CheckboxGroup.vue")),
        CorpusCase::new("chip", "/Chip.vue", include_str!("fixtures/Chip.vue")),
        CorpusCase::new("collapsible", "/Collapsible.vue", include_str!("fixtures/Collapsible.vue")),
        CorpusCase::new("color_picker", "/ColorPicker.vue", include_str!("fixtures/ColorPicker.vue")),
        CorpusCase::new("command_palette", "/CommandPalette.vue", include_str!("fixtures/CommandPalette.vue")),
        CorpusCase::new("container", "/Container.vue", include_str!("fixtures/Container.vue")),
    ];
    run_chunk(CASES);
}
