//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_003_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("editor_drag_handle", "/EditorDragHandle.vue", include_str!("fixtures/EditorDragHandle.vue")),
        CorpusCase::new("editor_emoji_menu", "/EditorEmojiMenu.vue", include_str!("fixtures/EditorEmojiMenu.vue")),
        CorpusCase::new("editor_mention_menu", "/EditorMentionMenu.vue", include_str!("fixtures/EditorMentionMenu.vue")),
        CorpusCase::new("editor_suggestion_menu", "/EditorSuggestionMenu.vue", include_str!("fixtures/EditorSuggestionMenu.vue")),
        CorpusCase::new("editor_toolbar", "/EditorToolbar.vue", include_str!("fixtures/EditorToolbar.vue")),
        CorpusCase::new("empty", "/Empty.vue", include_str!("fixtures/Empty.vue")),
        CorpusCase::new("error", "/Error.vue", include_str!("fixtures/Error.vue")),
        CorpusCase::new("field_group", "/FieldGroup.vue", include_str!("fixtures/FieldGroup.vue")),
        CorpusCase::new("file_upload", "/FileUpload.vue", include_str!("fixtures/FileUpload.vue")),
        CorpusCase::new("footer", "/Footer.vue", include_str!("fixtures/Footer.vue")),
        CorpusCase::new("footer_columns", "/FooterColumns.vue", include_str!("fixtures/FooterColumns.vue")),
        CorpusCase::new("form", "/Form.vue", include_str!("fixtures/Form.vue")),
        CorpusCase::new("form_field", "/FormField.vue", include_str!("fixtures/FormField.vue")),
        CorpusCase::new("header", "/Header.vue", include_str!("fixtures/Header.vue")),
        CorpusCase::new("icon", "/Icon.vue", include_str!("fixtures/Icon.vue")),
        CorpusCase::new("input", "/Input.vue", include_str!("fixtures/Input.vue")),
    ];
    run_chunk(CASES);
}
