//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_002_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("context_menu", "/ContextMenu.vue", include_str!("fixtures/ContextMenu.vue")),
        CorpusCase::new("context_menu_content", "/ContextMenuContent.vue", include_str!("fixtures/ContextMenuContent.vue")),
        CorpusCase::new("dashboard_group", "/DashboardGroup.vue", include_str!("fixtures/DashboardGroup.vue")),
        CorpusCase::new("dashboard_navbar", "/DashboardNavbar.vue", include_str!("fixtures/DashboardNavbar.vue")),
        CorpusCase::new("dashboard_panel", "/DashboardPanel.vue", include_str!("fixtures/DashboardPanel.vue")),
        CorpusCase::new("dashboard_resize_handle", "/DashboardResizeHandle.vue", include_str!("fixtures/DashboardResizeHandle.vue")),
        CorpusCase::new("dashboard_search", "/DashboardSearch.vue", include_str!("fixtures/DashboardSearch.vue")),
        CorpusCase::new("dashboard_search_button", "/DashboardSearchButton.vue", include_str!("fixtures/DashboardSearchButton.vue")),
        CorpusCase::new("dashboard_sidebar", "/DashboardSidebar.vue", include_str!("fixtures/DashboardSidebar.vue")),
        CorpusCase::new("dashboard_sidebar_collapse", "/DashboardSidebarCollapse.vue", include_str!("fixtures/DashboardSidebarCollapse.vue")),
        CorpusCase::new("dashboard_sidebar_toggle", "/DashboardSidebarToggle.vue", include_str!("fixtures/DashboardSidebarToggle.vue")),
        CorpusCase::new("dashboard_toolbar", "/DashboardToolbar.vue", include_str!("fixtures/DashboardToolbar.vue")),
        CorpusCase::new("drawer", "/Drawer.vue", include_str!("fixtures/Drawer.vue")),
        CorpusCase::new("dropdown_menu", "/DropdownMenu.vue", include_str!("fixtures/DropdownMenu.vue")),
        CorpusCase::new("dropdown_menu_content", "/DropdownMenuContent.vue", include_str!("fixtures/DropdownMenuContent.vue")),
        CorpusCase::new("editor", "/Editor.vue", include_str!("fixtures/Editor.vue")),
    ];
    run_chunk(CASES);
}
