//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_002_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("select_menu", "/SelectMenu.vue", include_str!("fixtures/SelectMenu.vue")),
        CorpusCase::new("tree", "/Tree.vue", include_str!("fixtures/Tree.vue")),
        CorpusCase::new("chat_messages", "/ChatMessages.vue", include_str!("fixtures/ChatMessages.vue")),
        CorpusCase::new("calendar", "/Calendar.vue", include_str!("fixtures/Calendar.vue")),
        CorpusCase::new("input_time", "/InputTime.vue", include_str!("fixtures/InputTime.vue")),
        CorpusCase::new("textarea", "/Textarea.vue", include_str!("fixtures/Textarea.vue")),
        CorpusCase::new("changelog_version", "/ChangelogVersion.vue", include_str!("fixtures/ChangelogVersion.vue")),
        CorpusCase::new("toast", "/Toast.vue", include_str!("fixtures/Toast.vue")),
        CorpusCase::new("context_menu", "/ContextMenu.vue", include_str!("fixtures/ContextMenu.vue")),
        CorpusCase::new("editor_drag_handle", "/EditorDragHandle.vue", include_str!("fixtures/EditorDragHandle.vue")),
        CorpusCase::new("progress", "/Progress.vue", include_str!("fixtures/Progress.vue")),
        CorpusCase::new("footer_columns", "/FooterColumns.vue", include_str!("fixtures/FooterColumns.vue")),
        CorpusCase::new("pin_input", "/PinInput.vue", include_str!("fixtures/PinInput.vue")),
        CorpusCase::new("page_anchors", "/PageAnchors.vue", include_str!("fixtures/PageAnchors.vue")),
        CorpusCase::new("avatar", "/Avatar.vue", include_str!("fixtures/Avatar.vue")),
        CorpusCase::new("prose_prompt", "/prose/Prompt.vue", include_str!("fixtures/prose/Prompt.vue")),
        CorpusCase::new("avatar_group", "/AvatarGroup.vue", include_str!("fixtures/AvatarGroup.vue")),
        CorpusCase::new("blog_posts", "/BlogPosts.vue", include_str!("fixtures/BlogPosts.vue")),
        CorpusCase::new("dashboard_sidebar_toggle", "/DashboardSidebarToggle.vue", include_str!("fixtures/DashboardSidebarToggle.vue")),
        CorpusCase::new("page_aside", "/PageAside.vue", include_str!("fixtures/PageAside.vue")),
        CorpusCase::new("page", "/Page.vue", include_str!("fixtures/Page.vue")),
        CorpusCase::new("prose_h3", "/prose/H3.vue", include_str!("fixtures/prose/H3.vue")),
        CorpusCase::new("prose_field_group", "/prose/FieldGroup.vue", include_str!("fixtures/prose/FieldGroup.vue")),
        CorpusCase::new("page_columns", "/PageColumns.vue", include_str!("fixtures/PageColumns.vue")),
        CorpusCase::new("page_body", "/PageBody.vue", include_str!("fixtures/PageBody.vue")),
        CorpusCase::new("prose_badge", "/prose/Badge.vue", include_str!("fixtures/prose/Badge.vue")),
        CorpusCase::new("prose_tr", "/prose/Tr.vue", include_str!("fixtures/prose/Tr.vue")),
        CorpusCase::new("prose_p", "/prose/P.vue", include_str!("fixtures/prose/P.vue")),
        CorpusCase::new("theme", "/Theme.vue", include_str!("fixtures/Theme.vue")),
        CorpusCase::new("prose_callout_caution", "/prose/callout/Caution.vue", include_str!("fixtures/prose/callout/Caution.vue")),
    ];
    run_chunk(CASES);
}
