//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_007_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("listbox", "/Listbox.vue", include_str!("fixtures/Listbox.vue")),
        CorpusCase::new("context_menu_content", "/ContextMenuContent.vue", include_str!("fixtures/ContextMenuContent.vue")),
        CorpusCase::new("scroll_area", "/ScrollArea.vue", include_str!("fixtures/ScrollArea.vue")),
        CorpusCase::new("input_tags", "/InputTags.vue", include_str!("fixtures/InputTags.vue")),
        CorpusCase::new("tabs", "/Tabs.vue", include_str!("fixtures/Tabs.vue")),
        CorpusCase::new("switch", "/Switch.vue", include_str!("fixtures/Switch.vue")),
        CorpusCase::new("pin_input", "/PinInput.vue", include_str!("fixtures/PinInput.vue")),
        CorpusCase::new("page_cta", "/PageCTA.vue", include_str!("fixtures/PageCTA.vue")),
        CorpusCase::new("avatar_group", "/AvatarGroup.vue", include_str!("fixtures/AvatarGroup.vue")),
        CorpusCase::new("chip", "/Chip.vue", include_str!("fixtures/Chip.vue")),
        CorpusCase::new("page", "/Page.vue", include_str!("fixtures/Page.vue")),
        CorpusCase::new("link_base", "/LinkBase.vue", include_str!("fixtures/LinkBase.vue")),
        CorpusCase::new("prose_accordion_item", "/prose/AccordionItem.vue", include_str!("fixtures/prose/AccordionItem.vue")),
        CorpusCase::new("prose_badge", "/prose/Badge.vue", include_str!("fixtures/prose/Badge.vue")),
        CorpusCase::new("color_mode_color_mode_image", "/color-mode/ColorModeImage.vue", include_str!("fixtures/color-mode/ColorModeImage.vue")),
    ];
    run_chunk(CASES);
}
