//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_004_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("input_date", "/InputDate.vue", include_str!("fixtures/InputDate.vue")),
        CorpusCase::new("input_menu", "/InputMenu.vue", include_str!("fixtures/InputMenu.vue")),
        CorpusCase::new("input_number", "/InputNumber.vue", include_str!("fixtures/InputNumber.vue")),
        CorpusCase::new("input_tags", "/InputTags.vue", include_str!("fixtures/InputTags.vue")),
        CorpusCase::new("input_time", "/InputTime.vue", include_str!("fixtures/InputTime.vue")),
        CorpusCase::new("kbd", "/Kbd.vue", include_str!("fixtures/Kbd.vue")),
        CorpusCase::new("link", "/Link.vue", include_str!("fixtures/Link.vue")),
        CorpusCase::new("link_base", "/LinkBase.vue", include_str!("fixtures/LinkBase.vue")),
        CorpusCase::new("listbox", "/Listbox.vue", include_str!("fixtures/Listbox.vue")),
        CorpusCase::new("main", "/Main.vue", include_str!("fixtures/Main.vue")),
        CorpusCase::new("marquee", "/Marquee.vue", include_str!("fixtures/Marquee.vue")),
        CorpusCase::new("modal", "/Modal.vue", include_str!("fixtures/Modal.vue")),
        CorpusCase::new("navigation_menu", "/NavigationMenu.vue", include_str!("fixtures/NavigationMenu.vue")),
        CorpusCase::new("overlay_provider", "/OverlayProvider.vue", include_str!("fixtures/OverlayProvider.vue")),
        CorpusCase::new("page", "/Page.vue", include_str!("fixtures/Page.vue")),
        CorpusCase::new("page_anchors", "/PageAnchors.vue", include_str!("fixtures/PageAnchors.vue")),
    ];
    run_chunk(CASES);
}
