//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_001_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("navigation_menu", "/NavigationMenu.vue", include_str!("fixtures/NavigationMenu.vue")),
        CorpusCase::new("dropdown_menu_content", "/DropdownMenuContent.vue", include_str!("fixtures/DropdownMenuContent.vue")),
        CorpusCase::new("context_menu_content", "/ContextMenuContent.vue", include_str!("fixtures/ContextMenuContent.vue")),
        CorpusCase::new("link", "/Link.vue", include_str!("fixtures/Link.vue")),
        CorpusCase::new("input_number", "/InputNumber.vue", include_str!("fixtures/InputNumber.vue")),
        CorpusCase::new("input_tags", "/InputTags.vue", include_str!("fixtures/InputTags.vue")),
        CorpusCase::new("prose_code_tree", "/prose/CodeTree.vue", include_str!("fixtures/prose/CodeTree.vue")),
        CorpusCase::new("tabs", "/Tabs.vue", include_str!("fixtures/Tabs.vue")),
        CorpusCase::new("accordion", "/Accordion.vue", include_str!("fixtures/Accordion.vue")),
        CorpusCase::new("form_field", "/FormField.vue", include_str!("fixtures/FormField.vue")),
        CorpusCase::new("chat_tool", "/ChatTool.vue", include_str!("fixtures/ChatTool.vue")),
        CorpusCase::new("tooltip", "/Tooltip.vue", include_str!("fixtures/Tooltip.vue")),
        CorpusCase::new("slider", "/Slider.vue", include_str!("fixtures/Slider.vue")),
        CorpusCase::new("dashboard_navbar", "/DashboardNavbar.vue", include_str!("fixtures/DashboardNavbar.vue")),
        CorpusCase::new("prose_code_group", "/prose/CodeGroup.vue", include_str!("fixtures/prose/CodeGroup.vue")),
        CorpusCase::new("prose_tabs", "/prose/Tabs.vue", include_str!("fixtures/prose/Tabs.vue")),
        CorpusCase::new("dashboard_panel", "/DashboardPanel.vue", include_str!("fixtures/DashboardPanel.vue")),
        CorpusCase::new("prose_code_collapse", "/prose/CodeCollapse.vue", include_str!("fixtures/prose/CodeCollapse.vue")),
        CorpusCase::new("prose_accordion", "/prose/Accordion.vue", include_str!("fixtures/prose/Accordion.vue")),
        CorpusCase::new("prose_callout", "/prose/Callout.vue", include_str!("fixtures/prose/Callout.vue")),
        CorpusCase::new("field_group", "/FieldGroup.vue", include_str!("fixtures/FieldGroup.vue")),
        CorpusCase::new("prose_h2", "/prose/H2.vue", include_str!("fixtures/prose/H2.vue")),
        CorpusCase::new("prose_h1", "/prose/H1.vue", include_str!("fixtures/prose/H1.vue")),
        CorpusCase::new("prose_steps", "/prose/Steps.vue", include_str!("fixtures/prose/Steps.vue")),
        CorpusCase::new("main", "/Main.vue", include_str!("fixtures/Main.vue")),
        CorpusCase::new("prose_th", "/prose/Th.vue", include_str!("fixtures/prose/Th.vue")),
        CorpusCase::new("prose_thead", "/prose/Thead.vue", include_str!("fixtures/prose/Thead.vue")),
        CorpusCase::new("color_mode_color_mode_image", "/color-mode/ColorModeImage.vue", include_str!("fixtures/color-mode/ColorModeImage.vue")),
        CorpusCase::new("prose_hr", "/prose/Hr.vue", include_str!("fixtures/prose/Hr.vue")),
    ];
    run_chunk(CASES);
}
