//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_008_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("form", "/Form.vue", include_str!("fixtures/Form.vue")),
        CorpusCase::new("chat_messages", "/ChatMessages.vue", include_str!("fixtures/ChatMessages.vue")),
        CorpusCase::new("calendar", "/Calendar.vue", include_str!("fixtures/Calendar.vue")),
        CorpusCase::new("slideover", "/Slideover.vue", include_str!("fixtures/Slideover.vue")),
        CorpusCase::new("breadcrumb", "/Breadcrumb.vue", include_str!("fixtures/Breadcrumb.vue")),
        CorpusCase::new("chat_message", "/ChatMessage.vue", include_str!("fixtures/ChatMessage.vue")),
        CorpusCase::new("page_hero", "/PageHero.vue", include_str!("fixtures/PageHero.vue")),
        CorpusCase::new("page_anchors", "/PageAnchors.vue", include_str!("fixtures/PageAnchors.vue")),
        CorpusCase::new("editor_emoji_menu", "/EditorEmojiMenu.vue", include_str!("fixtures/EditorEmojiMenu.vue")),
        CorpusCase::new("prose_collapsible", "/prose/Collapsible.vue", include_str!("fixtures/prose/Collapsible.vue")),
        CorpusCase::new("kbd", "/Kbd.vue", include_str!("fixtures/Kbd.vue")),
        CorpusCase::new("chat_palette", "/ChatPalette.vue", include_str!("fixtures/ChatPalette.vue")),
        CorpusCase::new("main", "/Main.vue", include_str!("fixtures/Main.vue")),
        CorpusCase::new("prose_li", "/prose/Li.vue", include_str!("fixtures/prose/Li.vue")),
        CorpusCase::new("overlay_provider", "/OverlayProvider.vue", include_str!("fixtures/OverlayProvider.vue")),
    ];
    run_chunk(CASES);
}
