//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_003_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("command_palette", "/CommandPalette.vue", include_str!("fixtures/CommandPalette.vue")),
        CorpusCase::new("editor", "/Editor.vue", include_str!("fixtures/Editor.vue")),
        CorpusCase::new("prose_code_tree", "/prose/CodeTree.vue", include_str!("fixtures/prose/CodeTree.vue")),
        CorpusCase::new("drawer", "/Drawer.vue", include_str!("fixtures/Drawer.vue")),
        CorpusCase::new("progress", "/Progress.vue", include_str!("fixtures/Progress.vue")),
        CorpusCase::new("footer_columns", "/FooterColumns.vue", include_str!("fixtures/FooterColumns.vue")),
        CorpusCase::new("prose_code_group", "/prose/CodeGroup.vue", include_str!("fixtures/prose/CodeGroup.vue")),
        CorpusCase::new("pricing_plans", "/PricingPlans.vue", include_str!("fixtures/PricingPlans.vue")),
        CorpusCase::new("dashboard_sidebar_toggle", "/DashboardSidebarToggle.vue", include_str!("fixtures/DashboardSidebarToggle.vue")),
        CorpusCase::new("marquee", "/Marquee.vue", include_str!("fixtures/Marquee.vue")),
        CorpusCase::new("dashboard_resize_handle", "/DashboardResizeHandle.vue", include_str!("fixtures/DashboardResizeHandle.vue")),
        CorpusCase::new("prose_a", "/prose/A.vue", include_str!("fixtures/prose/A.vue")),
        CorpusCase::new("prose_strong", "/prose/Strong.vue", include_str!("fixtures/prose/Strong.vue")),
        CorpusCase::new("prose_em", "/prose/Em.vue", include_str!("fixtures/prose/Em.vue")),
    ];
    run_chunk(CASES);
}
