//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_000_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("accordion", "/Accordion.vue", include_str!("fixtures/Accordion.vue")),
        CorpusCase::new("alert", "/Alert.vue", include_str!("fixtures/Alert.vue")),
        CorpusCase::new("app", "/App.vue", include_str!("fixtures/App.vue")),
        CorpusCase::new("auth_form", "/AuthForm.vue", include_str!("fixtures/AuthForm.vue")),
        CorpusCase::new("avatar", "/Avatar.vue", include_str!("fixtures/Avatar.vue")),
        CorpusCase::new("avatar_group", "/AvatarGroup.vue", include_str!("fixtures/AvatarGroup.vue")),
        CorpusCase::new("badge", "/Badge.vue", include_str!("fixtures/Badge.vue")),
        CorpusCase::new("banner", "/Banner.vue", include_str!("fixtures/Banner.vue")),
        CorpusCase::new("blog_post", "/BlogPost.vue", include_str!("fixtures/BlogPost.vue")),
        CorpusCase::new("blog_posts", "/BlogPosts.vue", include_str!("fixtures/BlogPosts.vue")),
        CorpusCase::new("breadcrumb", "/Breadcrumb.vue", include_str!("fixtures/Breadcrumb.vue")),
        CorpusCase::new("button", "/Button.vue", include_str!("fixtures/Button.vue")),
        CorpusCase::new("calendar", "/Calendar.vue", include_str!("fixtures/Calendar.vue")),
        CorpusCase::new("card", "/Card.vue", include_str!("fixtures/Card.vue")),
        CorpusCase::new("carousel", "/Carousel.vue", include_str!("fixtures/Carousel.vue")),
        CorpusCase::new("changelog_version", "/ChangelogVersion.vue", include_str!("fixtures/ChangelogVersion.vue")),
    ];
    run_chunk(CASES);
}
