//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_006_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("pricing_plan", "/PricingPlan.vue", include_str!("fixtures/PricingPlan.vue")),
        CorpusCase::new("pricing_plans", "/PricingPlans.vue", include_str!("fixtures/PricingPlans.vue")),
        CorpusCase::new("pricing_table", "/PricingTable.vue", include_str!("fixtures/PricingTable.vue")),
        CorpusCase::new("progress", "/Progress.vue", include_str!("fixtures/Progress.vue")),
        CorpusCase::new("radio_group", "/RadioGroup.vue", include_str!("fixtures/RadioGroup.vue")),
        CorpusCase::new("scroll_area", "/ScrollArea.vue", include_str!("fixtures/ScrollArea.vue")),
        CorpusCase::new("select", "/Select.vue", include_str!("fixtures/Select.vue")),
        CorpusCase::new("select_menu", "/SelectMenu.vue", include_str!("fixtures/SelectMenu.vue")),
        CorpusCase::new("separator", "/Separator.vue", include_str!("fixtures/Separator.vue")),
        CorpusCase::new("sidebar", "/Sidebar.vue", include_str!("fixtures/Sidebar.vue")),
        CorpusCase::new("skeleton", "/Skeleton.vue", include_str!("fixtures/Skeleton.vue")),
        CorpusCase::new("slideover", "/Slideover.vue", include_str!("fixtures/Slideover.vue")),
        CorpusCase::new("slider", "/Slider.vue", include_str!("fixtures/Slider.vue")),
        CorpusCase::new("stepper", "/Stepper.vue", include_str!("fixtures/Stepper.vue")),
        CorpusCase::new("switch", "/Switch.vue", include_str!("fixtures/Switch.vue")),
        CorpusCase::new("table", "/Table.vue", include_str!("fixtures/Table.vue")),
    ];
    run_chunk(CASES);
}
