//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! One nextest process covering several hermetic logical corpus rows.
//! Worker pools are shared; every row gets a fresh host and semantic state.

use super::chunk_harness::{run_chunk, CorpusCase};

#[test]
fn corpus_audit_chunk_011_produces_audit_records_or_documents_skips() {
    #[rustfmt::skip]
    const CASES: &[CorpusCase] = &[
        CorpusCase::new("prose_callout_note", "/prose/callout/Note.vue", include_str!("fixtures/prose/callout/Note.vue")),
        CorpusCase::new("prose_callout_tip", "/prose/callout/Tip.vue", include_str!("fixtures/prose/callout/Tip.vue")),
        CorpusCase::new("prose_callout_warning", "/prose/callout/Warning.vue", include_str!("fixtures/prose/callout/Warning.vue")),
    ];
    run_chunk(CASES);
}
