//! Vapor interpolation code generation.
//!
//! `{{ expr }}` in Vapor mode:
//! 1. The caller (`VaporCodeGen::visit_interpolation`) appends a single space
//!    placeholder to the parent's HTML buffer, once per coalesced text run
//!    (on the run's first interpolation) — never here.
//! 2. The expression is wrapped in `_toDisplayString(expr)` and recorded as a
//!    dynamic text part.
//! 3. The parent element is marked as having dynamic text, which triggers
//!    `_txt()` creation and `_renderEffect(() => _setText(...))` in the output.

use crate::ast::types::InterpolationNode;
use crate::code_transform::SegmentAnchor;
use crate::template::code_gen::binding::BindingResolver;
use crate::template::code_gen::expression::build_prefixed_expr_segments;
use crate::template::code_gen::shared::helpers::{self, VaporHelper};
use crate::template::code_gen::types::{
    CodeGenOutput, VaporCounters, VaporElementState, VaporTextPart,
};
use crate::template::oxc::types::OxcParsedExpression;

/// Process an interpolation node in Vapor mode.
///
/// - The HTML space placeholder for the enclosing DOM text run is the
///   CALLER's responsibility (`VaporCodeGen::visit_interpolation`) — exactly
///   one space per coalesced run, emitted on the run's first interpolation,
///   collapsing any static text already written for that run. This function
///   never touches the HTML buffer.
/// - Wraps the expression in `_toDisplayString()`.
/// - Uses OXC binding data for compound expressions, falling back to
///   `resolve_simple_expr` for single identifiers.
/// - Records the dynamic text part on `parent` and allocates its text node ref.
#[allow(clippy::too_many_arguments)]
pub fn process_interpolation<'a>(
    interp: &InterpolationNode,
    source: &str,
    oxc: &OxcParsedExpression<'_>,
    resolver: &BindingResolver<'_>,
    parent: &mut VaporElementState<'a>,
    counters: &mut VaporCounters,
    out: &mut CodeGenOutput<'a>,
) {
    // Extract expression content (untrimmed — build_prefixed_expr handles trimming internally
    // and needs the raw range to correctly compute binding offsets relative to inner_start)
    let expr = &source[interp.inner_start as usize..interp.inner_end as usize];

    // Build the segmented plan (`.text` is byte-identical to
    // `build_prefixed_expr`'s flat output — see `expression.rs`'s module
    // doc) so the interpolation identifier's own authored anchor survives
    // into the render function's segmented overwrite.
    let prefixed_segments =
        build_prefixed_expr_segments(expr, interp.inner_start, oxc, resolver, &[]);
    let mut buf =
        String::with_capacity(helpers::TO_DISPLAY_STRING.len() + prefixed_segments.text.len() + 2);
    buf.push_str(helpers::TO_DISPLAY_STRING);
    buf.push('(');
    let wrap_offset = buf.len() as u32;
    buf.push_str(&prefixed_segments.text);
    buf.push(')');

    // Translate the plan's source-bearing segments into anchors relative to
    // THIS part's own text start (shifted past the `_toDisplayString(` wrap).
    let anchors: Vec<SegmentAnchor> = prefixed_segments
        .segments
        .iter()
        .filter_map(|seg| {
            seg.source_start.map(|source_pos| SegmentAnchor {
                content_offset: wrap_offset + seg.generated_start,
                length: seg.generated_end - seg.generated_start,
                source_pos,
            })
        })
        .collect();

    // Record dynamic text part (bump-allocated)
    parent.text_parts.push(VaporTextPart::Dynamic(
        out.alloc_str(&buf),
        out.alloc_segment_anchors(&anchors),
    ));

    // Ensure text node ref is allocated
    parent.ensure_text_ref(counters);

    // Record import
    out.add_vapor_import(VaporHelper::ToDisplayString);
}

/// Build a prefixed expression string using OXC binding extraction data.
///
/// For compound expressions (e.g., `a + b.x`), walks the extracted bindings
/// and inserts the correct prefix/suffix at each identifier's position.
/// For simple identifiers, falls back to `resolve_simple_expr`.
///
/// When `ts_skip_ranges` is non-empty, skips the specified byte ranges
/// (expression-relative) from verbatim chunks. Used by `force_js` to strip
/// TypeScript syntax from directive expressions without re-parsing.
pub(crate) fn build_prefixed_expr(
    expr: &str,
    inner_start: u32,
    oxc: &OxcParsedExpression<'_>,
    resolver: &BindingResolver<'_>,
    ts_skip_ranges: &[(u32, u32)],
) -> String {
    use crate::template::code_gen::expression::{write_prefixed_expr, StringSink};

    // Pre-size to the original heuristic (one prefix/suffix budget per binding)
    // so the flat path keeps its allocation profile; the shared walk discards
    // segment positions through `StringSink`, so generated bytes are identical
    // to the segmented `build_prefixed_expr_segments`.
    let extra = oxc.bindings.as_ref().map_or(0, |b| b.bindings.len() * 8);
    let mut result = String::with_capacity(expr.len() + extra);
    let mut sink = StringSink(&mut result);
    write_prefixed_expr(&mut sink, expr, inner_start, oxc, resolver, ts_skip_ranges);
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::template::oxc::types::Dynamism;
    use rustc_hash::FxHashMap;

    fn make_parent() -> VaporElementState<'static> {
        VaporElementState::new()
    }

    fn make_resolver_empty() -> BindingResolver<'static> {
        BindingResolver::new(FxHashMap::default(), false)
    }

    fn make_resolver_with_ctx() -> BindingResolver<'static> {
        BindingResolver::new(FxHashMap::default(), false)
    }

    fn make_empty_oxc() -> OxcParsedExpression<'static> {
        OxcParsedExpression {
            offset: 0,
            expression: None,
            multi_statement: false,
            errors: None,
            bindings: None,
            ide_recovery_scope: Vec::new(),
            dynamism: Dynamism::Static,
        }
    }

    #[test]
    fn interpolation_records_dynamic_part() {
        let alloc = oxc_allocator::Allocator::default();
        let mut out = CodeGenOutput::new(&alloc);
        let mut parent = make_parent();
        let mut counters = VaporCounters::default();
        let resolver = make_resolver_with_ctx();

        let interp = InterpolationNode {
            start: 0,
            end: 9,
            inner_start: 3,
            inner_end: 6,
        };
        let oxc = make_empty_oxc();
        process_interpolation(
            &interp,
            "{{ msg }}",
            &oxc,
            &resolver,
            &mut parent,
            &mut counters,
            &mut out,
        );

        assert_eq!(parent.text_parts.len(), 1);
        assert!(parent.text_parts[0].is_dynamic());
        assert!(parent.text_parts[0].to_js().contains("_toDisplayString"));
        assert!(parent.text_parts[0].to_js().contains("_ctx.msg"));
    }

    #[test]
    fn interpolation_allocates_text_ref() {
        let alloc = oxc_allocator::Allocator::default();
        let mut out = CodeGenOutput::new(&alloc);
        let mut parent = make_parent();
        let mut counters = VaporCounters::default();
        let resolver = make_resolver_empty();

        let interp = InterpolationNode {
            start: 0,
            end: 9,
            inner_start: 3,
            inner_end: 6,
        };
        let oxc = make_empty_oxc();
        process_interpolation(
            &interp,
            "{{ msg }}",
            &oxc,
            &resolver,
            &mut parent,
            &mut counters,
            &mut out,
        );

        assert_eq!(parent.text_node_ref, Some(0));
        // The text ref shares the node counter — no separate `x` counter.
        assert_eq!(counters.n, 1);
    }

    #[test]
    fn interpolation_adds_import() {
        let alloc = oxc_allocator::Allocator::default();
        let mut out = CodeGenOutput::new(&alloc);
        let mut parent = make_parent();
        let mut counters = VaporCounters::default();
        let resolver = make_resolver_empty();

        let interp = InterpolationNode {
            start: 0,
            end: 9,
            inner_start: 3,
            inner_end: 6,
        };
        let oxc = make_empty_oxc();
        process_interpolation(
            &interp,
            "{{ msg }}",
            &oxc,
            &resolver,
            &mut parent,
            &mut counters,
            &mut out,
        );

        assert!(out.vapor_imports().has(VaporHelper::ToDisplayString));
    }

    #[test]
    fn compound_expression_not_prefixed() {
        let resolver = make_resolver_empty();
        let result = resolver.resolve_simple_expr("a + b");
        assert_eq!(result, "a + b"); // Compound expressions pass through
    }
}
