//! The svelte component-name scope-view conformance matrix.
//!
//! This is the SINGLE authority tying [`SvelteScopeProjection`] to
//! svelte@[`SVELTE_ORACLE_VERSION`]. It has two independent halves:
//!
//! 1. A SOURCE-DERIVED handler rail over svelte's own `remove_typescript_nodes` visitor
//!    inventory: the OXC-parsed `const visitors` handler set is set-equal to the
//!    [`HandlerCoverage`] rows (bijection), every handler body carries a fingerprint
//!    drift tripwire, and every handler names ≥1 corpus AXIS it is exercised by.
//!
//! 2. An ORACLE-DERIVED name-parity matrix. The committed corpus
//!    (`tests/fixtures/svelte/name_parity_corpus.json`) is GENERATED by
//!    `scripts/gen-svelte-name-parity-corpus.mjs`, which plants an identifier per
//!    construct, sets `name=<planted identifier>`, runs the PINNED svelte compiler
//!    OFFLINE, and records SVELTE'S OWN outcome (the emitted component-function name, a
//!    reject code, or — for a construct svelte CRASHES uncoded on, e.g. a lone class index
//!    signature — a `crash` outcome). The emitted-name pins therefore come from svelte itself, NOT from
//!    reading the projection's output — so a projection that drops a reserved name REDs
//!    against svelte's own outcome instead of matching a stale hand-authored value (the
//!    prior hand-pinned three-set matrix was self-confirming: a buggy projection plus a
//!    matching wrong pin both passed).
//!
//! For a svelte-COMPILE row the matrix asserts Verter's observable name derivation
//! equals svelte's emitted name (the deconfliction UNION, oracle-derived). A svelte-
//! REJECT row carries NO svelte name (svelte emits no component), so name-parity is
//! VACUOUS: Verter's disposition is characterized SEPARATELY and honestly (a defensive
//! erase, or a preserved known-gap) with an EXACT reserved-set observation — a Verter/OXC
//! CHARACTERIZATION, never a svelte-parity claim. A svelte-CRASH row (a construct svelte
//! crashes uncoded on — e.g. a lone class index signature) is VACUOUS the same way: Verter
//! does NOT crash — it defensively erases the construct, characterized separately. The
//! `<T>x` angle assertion is a svelte-compile row Verter FAIL-CLOSES on (the shared
//! `SourceType::tsx()` reparse rejects it).
//!
//! Hermetic by default: the matrix consumes ONLY the vendored source + the committed
//! corpus + the production projection (no live svelte at test time, per the Testing-
//! Hermeticity rule). An optional `svelte-oracle`-gated freshness rail re-runs the
//! generator's `--check` against the installed pinned compiler.

use super::*;
use crate::svelte::parser::parse_svelte;
use crate::svelte::runtime::client_imports::UserImportSlot;
use crate::svelte::runtime::client_surface_imports::classify_script_imports_from_sources;
use crate::svelte::runtime::naming::derive_component_name;
use crate::svelte::runtime::{compile_client, ClientCompileError, SvelteRuntimeOptions};
use oxc_ast::ast::{BindingPattern, ObjectPropertyKind, Program, PropertyKey};
use oxc_span::Span;
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

/// The vendored svelte transformation source, embedded HERMETICALLY (no filesystem
/// read at run time, no `node_modules` dependency).
const VENDORED_REMOVE_TS_NODES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/svelte/remove_typescript_nodes.5.56.3.js"
));

/// The projection source, embedded for the exhaustive-no-soft-carrier rail.
const PROJECTION_SOURCE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/svelte/runtime/component_scope_facts.rs"
));

/// The committed ORACLE-derived name-parity corpus (svelte's own outcomes), embedded
/// HERMETICALLY. Generated by `scripts/gen-svelte-name-parity-corpus.mjs`.
const NAME_PARITY_CORPUS_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/svelte/name_parity_corpus.json"
));

// ─────────────────────────────────────────────────────────────────────────────
// The committed corpus (svelte oracle) — pins come from REAL svelte, never the
// projection.
// ─────────────────────────────────────────────────────────────────────────────

#[derive(serde::Deserialize)]
struct NameParityCorpus {
    svelte_oracle_version: String,
    rows: Vec<CorpusRow>,
}

#[derive(serde::Deserialize)]
struct CorpusRow {
    axis: String,
    source: String,
    requested_name: String,
    outcome: CorpusOutcome,
}

#[derive(serde::Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
enum CorpusOutcome {
    /// svelte compiled: `emitted_name` is the component function name svelte emitted
    /// (`function <NAME>($$anchor)`) for `requested_name` — the bare name (not reserved)
    /// or `<name>_1` (reserved).
    Compile { emitted_name: String },
    /// svelte hard-errored with diagnostic `code`.
    Reject { code: String },
    /// svelte CRASHED uncoded (an uncoded `TypeError`, NOT a typed diagnostic — e.g. a lone
    /// class index signature). name-parity is vacuous; the matrix asserts Verter's
    /// disposition (Verter does not crash — it defensively erases the construct).
    Crash,
}

/// The fixed bare NEGATIVE-CONTROL name the generator probes for every compile
/// construct — absent from every source, so svelte always emits it bare. Its presence
/// as a bare row per source discriminates a reserved planted name (→ `_1`) from a non-
/// reserved one, so an over-reserving projection turns it into `Zz9Unrelated_1` and REDs.
const NEGATIVE_CONTROL: &str = "Zz9Unrelated";

fn load_corpus() -> NameParityCorpus {
    serde_json::from_str(NAME_PARITY_CORPUS_JSON)
        .expect("name_parity_corpus.json must be valid JSON (run the generator)")
}

// ─────────────────────────────────────────────────────────────────────────────
// Verter dispositions per axis — how Verter's OBSERVABLE behavior is characterized
// against an oracle row.
// ─────────────────────────────────────────────────────────────────────────────

/// The Verter disposition of a svelte-COMPILE axis.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum CompileDisposition {
    /// `derive_component_name(requested_name)` == the oracle's `emitted_name` for every
    /// row of this axis (the deconfliction UNION, oracle-derived). The DEFAULT for a
    /// svelte-compile axis.
    NameParity,
    /// svelte compiles + reserves the inner runtime reference, but Verter FAIL-CLOSES
    /// before projection: the shared `SourceType::tsx()` reparse rejects the `<T>x` angle
    /// assertion as JSX, so `build_component_scope_facts` returns `Err`. Name-parity is
    /// not asserted (there is no derived name to compare).
    VerterFailClosed,
}

/// The Verter disposition of a svelte-REJECT axis (svelte emits no component/name, so
/// this is a Verter/OXC CHARACTERIZATION, never a svelte-parity claim).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum RejectDisposition {
    /// Verter's projection DEFENSIVELY erases the svelte-hard-error construct, so the
    /// planted probe name(s) are NOT fabricated into the reserved set.
    DefensiveErase,
    /// Verter's projection PRESERVES the construct (a known reject-parity gap — svelte
    /// rejects the whole component; Verter does not).
    PreservedGap,
}

/// The explicit non-`NameParity` COMPILE axes. A svelte-compile axis absent here is
/// `NameParity`; a svelte-reject axis MUST instead appear in [`REJECT_CHARACTERIZATIONS`].
const COMPILE_DISPOSITION_OVERRIDES: &[(&str, CompileDisposition)] =
    &[("type_assertion_angle", CompileDisposition::VerterFailClosed)];

/// The EXACT Verter observation for each svelte-REJECT axis. `exact_conflicts` is the
/// COMPLETE `name_conflicts` set Verter's projection produces for the source — a
/// Verter/OXC characterization pinned so a LEAKED name REDs (exact-observation: not just `!contains`).
/// `erased_probes` are the planted names svelte would reserve if it compiled but Verter
/// must NOT fabricate (asserted absent, with a clearer message than the exact-set check).
struct RejectCharacterization {
    axis: &'static str,
    disposition: RejectDisposition,
    exact_conflicts: &'static [&'static str],
    erased_probes: &'static [&'static str],
}

const REJECT_CHARACTERIZATIONS: &[RejectCharacterization] = &[
    // EVERY enum is a svelte hard error (the `TSEnumDeclaration` handler is
    // unconditional). Verter erases the whole enum statement → nothing reserved.
    RejectCharacterization {
        axis: "enum_declare_ambient",
        disposition: RejectDisposition::DefensiveErase,
        exact_conflicts: &[],
        erased_probes: &["AmbientE"],
    },
    RejectCharacterization {
        axis: "enum_plain",
        disposition: RejectDisposition::DefensiveErase,
        exact_conflicts: &[],
        erased_probes: &["PlainE"],
    },
    // A value namespace is a svelte hard error. Verter erases the whole namespace.
    RejectCharacterization {
        axis: "namespace_value",
        disposition: RejectDisposition::DefensiveErase,
        exact_conflicts: &[],
        erased_probes: &["ValueNs", "V"],
    },
    // An `accessor` field is a svelte hard error. Verter keeps the class (reserves `AP`)
    // and drops the accessor member (its computed key `[P]` never binds).
    RejectCharacterization {
        axis: "class_accessor_field",
        disposition: RejectDisposition::DefensiveErase,
        exact_conflicts: &["AP"],
        erased_probes: &["P"],
    },
    // A ctor param-property is a svelte hard error. Verter keeps the class (reserves
    // `PP`) and drops the param-property parameter (`X` never binds).
    RejectCharacterization {
        axis: "class_param_property",
        disposition: RejectDisposition::DefensiveErase,
        exact_conflicts: &["PP"],
        erased_probes: &["X"],
    },
    // A decorator is a svelte hard error; Verter's projection PRESERVES it — the
    // decorated class reserves `Foo` and the decorator expression `dec` is a free
    // reference. A known reject-parity gap, asserted as ACTUAL behavior (NO svelte parity).
    RejectCharacterization {
        axis: "decorator",
        disposition: RejectDisposition::PreservedGap,
        exact_conflicts: &["Foo", "dec"],
        erased_probes: &[],
    },
    // A default export is illegal in a svelte component; Verter's projection PRESERVES
    // the named default-export class, reserving `Named`. A known reject-parity gap.
    RejectCharacterization {
        axis: "export_default_class",
        disposition: RejectDisposition::PreservedGap,
        exact_conflicts: &["Named"],
        erased_probes: &[],
    },
];

fn reject_characterization(axis: &str) -> Option<&'static RejectCharacterization> {
    REJECT_CHARACTERIZATIONS.iter().find(|r| r.axis == axis)
}

/// The EXACT Verter `name_conflicts` observation for each svelte-CRASH axis. svelte CRASHES
/// uncoded (an uncoded `TypeError`, not a typed diagnostic — e.g. a lone class index
/// signature), so name-parity is VACUOUS. Verter does NOT crash: its projection defensively
/// erases the construct and reserves EXACTLY these names (a leaked name REDs). A Verter/OXC
/// characterization, NEVER a svelte-parity claim.
const CRASH_CHARACTERIZATIONS: &[(&str, &[&str])] = &[("class_index_signature", &["C"])];

fn crash_characterization(axis: &str) -> Option<&'static [&'static str]> {
    CRASH_CHARACTERIZATIONS
        .iter()
        .find(|(a, _)| *a == axis)
        .map(|(_, c)| *c)
}

fn compile_disposition(axis: &str) -> CompileDisposition {
    COMPILE_DISPOSITION_OVERRIDES
        .iter()
        .find(|(a, _)| *a == axis)
        .map(|(_, d)| *d)
        .unwrap_or(CompileDisposition::NameParity)
}

// ─────────────────────────────────────────────────────────────────────────────
// The source-derived handler rail: every svelte `remove_typescript_nodes` handler ⟺
// one coverage row ⟺ ≥1 corpus axis, with a body-fingerprint drift tripwire.
// ─────────────────────────────────────────────────────────────────────────────

/// One svelte handler's coverage: its `remove_typescript_nodes` handler name, a
/// fingerprint of its vendored body (drift tripwire), and the corpus AXIS/axes exercising
/// it. The parity assertion itself lives in the oracle-derived corpus (svelte's own
/// emitted-name pins); this rail only proves every handler is REPRESENTED by a committed
/// corpus axis (no silent gap), so a handler with no exercising construct fails HARD.
struct HandlerCoverage {
    handler: &'static str,
    oracle_body_fingerprint: &'static str,
    axes: &'static [&'static str],
}

const HANDLER_COVERAGE: &[HandlerCoverage] = &[
    HandlerCoverage {
        handler: "_",
        oracle_body_fingerprint: "e88c35125e4b5574",
        axes: &["const_type_annotation"],
    },
    HandlerCoverage {
        handler: "Decorator",
        oracle_body_fingerprint: "348ca52b024cf7e5",
        axes: &["decorator"],
    },
    HandlerCoverage {
        handler: "ImportDeclaration",
        oracle_body_fingerprint: "f75af6a36043fde9",
        axes: &["import_default", "import_type_named"],
    },
    HandlerCoverage {
        handler: "ExportNamedDeclaration",
        oracle_body_fingerprint: "6bc76175bdde24b2",
        axes: &["export_const", "export_type_alias"],
    },
    HandlerCoverage {
        handler: "ExportDefaultDeclaration",
        oracle_body_fingerprint: "752d203f7c5a1d85",
        axes: &["export_default_class"],
    },
    HandlerCoverage {
        handler: "ExportAllDeclaration",
        oracle_body_fingerprint: "752d203f7c5a1d85",
        axes: &["export_star_as_ns", "export_type_star"],
    },
    HandlerCoverage {
        handler: "TSInterfaceDeclaration",
        oracle_body_fingerprint: "20187ce8dd25cb6d",
        axes: &["interface_decl"],
    },
    HandlerCoverage {
        handler: "TSTypeAliasDeclaration",
        oracle_body_fingerprint: "20187ce8dd25cb6d",
        axes: &["type_alias"],
    },
    HandlerCoverage {
        handler: "TSEnumDeclaration",
        oracle_body_fingerprint: "0b02f6d133430f6e",
        axes: &["enum_declare_ambient", "enum_plain"],
    },
    HandlerCoverage {
        handler: "TSModuleDeclaration",
        oracle_body_fingerprint: "f0e66724e890ddfc",
        axes: &["namespace_type_only", "namespace_value"],
    },
    HandlerCoverage {
        handler: "TSDeclareFunction",
        oracle_body_fingerprint: "20187ce8dd25cb6d",
        axes: &["function_lone_overload"],
    },
    HandlerCoverage {
        handler: "VariableDeclaration",
        oracle_body_fingerprint: "dce1002fe37225c7",
        axes: &["const_value", "declare_const"],
    },
    HandlerCoverage {
        handler: "ClassDeclaration",
        oracle_body_fingerprint: "3b9e6bfb4b3cc5cf",
        axes: &["class_decl", "declare_class"],
    },
    HandlerCoverage {
        handler: "TSAsExpression",
        oracle_body_fingerprint: "1a85d54f1309dfa8",
        axes: &["as_expression"],
    },
    HandlerCoverage {
        handler: "TSSatisfiesExpression",
        oracle_body_fingerprint: "1a85d54f1309dfa8",
        axes: &["satisfies_expression"],
    },
    HandlerCoverage {
        handler: "TSNonNullExpression",
        oracle_body_fingerprint: "1a85d54f1309dfa8",
        axes: &["non_null_expression"],
    },
    HandlerCoverage {
        handler: "TSTypeAssertion",
        oracle_body_fingerprint: "1a85d54f1309dfa8",
        axes: &["type_assertion_angle"],
    },
    HandlerCoverage {
        handler: "TSInstantiationExpression",
        oracle_body_fingerprint: "1a85d54f1309dfa8",
        axes: &["instantiation_expression"],
    },
    HandlerCoverage {
        handler: "ClassExpression",
        oracle_body_fingerprint: "3b6cd108b0eac40e",
        axes: &["class_expression"],
    },
    // `ClassBody` drops a `declare` field (covered by `class_declare_field`); it ALSO
    // erases a type-only index signature (`class_index_signature`) — svelte CRASHES uncoded
    // on a lone class index signature, so its corpus row is a `crash` outcome, and the
    // erasure itself is additionally proven by the AST-shape test
    // [`class_index_signature_is_erased_by_projection`].
    HandlerCoverage {
        handler: "ClassBody",
        oracle_body_fingerprint: "dc37d0d2b9752335",
        axes: &["class_declare_field", "class_index_signature"],
    },
    HandlerCoverage {
        handler: "MethodDefinition",
        oracle_body_fingerprint: "a4a2752574ad4279",
        axes: &["abstract_method"],
    },
    HandlerCoverage {
        handler: "PropertyDefinition",
        oracle_body_fingerprint: "9e016faecabb383c",
        axes: &["class_computed_field", "class_accessor_field"],
    },
    HandlerCoverage {
        handler: "TSParameterProperty",
        oracle_body_fingerprint: "d8b48da1ab731084",
        axes: &["class_param_property"],
    },
    HandlerCoverage {
        handler: "FunctionExpression",
        oracle_body_fingerprint: "a143a209ae0399c4",
        axes: &["function_expression_this"],
    },
    HandlerCoverage {
        handler: "FunctionDeclaration",
        oracle_body_fingerprint: "a143a209ae0399c4",
        axes: &["function_declaration_this"],
    },
];

/// The workspace root (`CARGO_MANIFEST_DIR` is `crates/verter_compiler`).
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates/")
        .parent()
        .expect("repo root")
        .to_path_buf()
}

/// Slice `source` at `span`. When `source` is `'static` the returned slice is `'static`.
fn span_slice(source: &str, span: Span) -> &str {
    &source[span.start as usize..span.end as usize]
}

/// Normalize a handler body for fingerprinting: LF-normalize line endings (cross-
/// platform), keeping every content byte significant so a one-character edit trips the
/// tripwire.
fn normalize(body: &str) -> String {
    body.replace("\r\n", "\n")
}

/// A dependency-free, cross-platform-stable FNV-1a 64-bit fingerprint (16 hex chars).
fn fnv1a_hex(bytes: &[u8]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in bytes {
        hash ^= u64::from(b);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Parse the vendored `const visitors = {...}` object with OXC and return, per handler,
/// a fingerprint of its normalized body source. The two aliased handlers
/// (`FunctionExpression` / `FunctionDeclaration` → `remove_this_param`) resolve to the
/// helper's body, so their fingerprints reflect the helper.
fn extract_handler_bodies() -> BTreeMap<String, String> {
    let alloc = Allocator::default();
    let program = reparse_module(&alloc, VENDORED_REMOVE_TS_NODES)
        .expect("vendored remove_typescript_nodes.js must parse cleanly under tsx");

    // The `remove_this_param` helper body (the alias target).
    let mut this_param_body: Option<&str> = None;
    for stmt in &program.body {
        if let Statement::FunctionDeclaration(func) = stmt {
            if func.id.as_ref().map(|id| id.name.as_str()) == Some("remove_this_param") {
                this_param_body = Some(span_slice(VENDORED_REMOVE_TS_NODES, func.span));
            }
        }
    }
    let this_param_body =
        this_param_body.expect("`remove_this_param` helper not found in vendored source");

    // The `const visitors = { ... }` object expression.
    let visitors = program
        .body
        .iter()
        .find_map(|stmt| {
            let Statement::VariableDeclaration(vd) = stmt else {
                return None;
            };
            let decl = vd.declarations.first()?;
            let BindingPattern::BindingIdentifier(id) = &decl.id else {
                return None;
            };
            if id.name.as_str() != "visitors" {
                return None;
            }
            match decl.init.as_ref()? {
                Expression::ObjectExpression(obj) => Some(obj),
                _ => None,
            }
        })
        .expect("`const visitors = {...}` object not found in vendored source");

    let mut out = BTreeMap::new();
    for property in &visitors.properties {
        let ObjectPropertyKind::ObjectProperty(prop) = property else {
            panic!("unexpected spread element in the visitors object");
        };
        let PropertyKey::StaticIdentifier(key) = &prop.key else {
            panic!("unexpected non-identifier visitor handler key");
        };
        let name = key.name.as_str().to_string();
        let body = match &prop.value {
            // `FunctionExpression: remove_this_param` / `FunctionDeclaration: remove_this_param`.
            Expression::Identifier(id) if id.name.as_str() == "remove_this_param" => {
                this_param_body
            }
            // A method-shorthand handler — its value is the function expression.
            other => span_slice(VENDORED_REMOVE_TS_NODES, other.span()),
        };
        let previous = out.insert(name.clone(), fnv1a_hex(normalize(body).as_bytes()));
        assert!(
            previous.is_none(),
            "duplicate visitor handler `{name}` in vendored source"
        );
    }
    out
}

/// Run the production scope-facts path over an instance-only `source`.
fn run_result(source: &str) -> Result<ComponentScopeFacts, UserImportSlot> {
    let alloc = Allocator::default();
    let imports = classify_script_imports_from_sources(None, Some(source));
    let template_decls = FxHashSet::default();
    let exprs = ExprArena::new();
    build_component_scope_facts(
        &alloc,
        None,
        Some(source),
        &imports,
        &template_decls,
        &exprs,
    )
}

/// Run the production path and require clean facts.
fn run(source: &str) -> ComponentScopeFacts {
    run_result(source)
        .unwrap_or_else(|slot| panic!("expected clean facts for {source:?}, got Err({slot:?})"))
}

/// An options carrier with an explicit `name` override (the deconfliction input).
fn opts_named(name: &str) -> SvelteRuntimeOptions {
    SvelteRuntimeOptions {
        filename: Some("App.svelte".to_string()),
        name: Some(name.to_string()),
        ..Default::default()
    }
}

/// Verter's OBSERVABLE derived component-function name for `requested_name` over
/// `source` — `derive_component_name(name, name_conflicts)`, the production derivation.
fn derived_name(source: &str, requested_name: &str) -> String {
    derive_component_name(&opts_named(requested_name), &run(source).name_conflicts())
}

/// Assert a fact SET equals the pinned exact set (complete equality, not `contains`).
fn assert_set_eq(actual: &FxHashSet<String>, expected: &[&str], source: &str, label: &str) {
    let actual_sorted: BTreeSet<&str> = actual.iter().map(String::as_str).collect();
    let expected_sorted: BTreeSet<&str> = expected.iter().copied().collect();
    assert_eq!(
        actual_sorted, expected_sorted,
        "{label} mismatch for source {source:?}"
    );
}

/// Wrap a script snippet in a minimal instance-script component. Verter's PUBLIC client
/// compile fails closed on a `<script lang="ts">` body (TypeScript emit is unsupported),
/// so the full-compile E2E rails drive a PLAIN `<script>` and use JS-compatible sources
/// (a JS snippet's `name` deconfliction is identical to the corpus's `lang="ts"` wrap —
/// the reserved surface is the same). The exhaustive TS name-parity is proven at the
/// scope-facts level (which DOES reparse TS), the rails prove the client-emit wiring.
fn wrap_component(source: &str) -> String {
    format!("<script>{source}</script><div></div>")
}

/// Drive Verter's PUBLIC client compile with an explicit `name`, returning the emitted
/// module code (or the fail-closed error).
fn compile_component(source: &str, name: &str) -> Result<String, ClientCompileError> {
    let wrapped = wrap_component(source);
    let alloc = Allocator::default();
    let parsed = parse_svelte(&wrapped);
    let opts = opts_named(name);
    compile_client(&wrapped, &parsed, &opts, &alloc, false, false).map(|module| module.code)
}

/// Extract the emitted component-function name from client JS: the `function <NAME>(`
/// whose first parameter is `$$anchor` (svelte-5 client component signature).
fn emitted_component_name(js: &str) -> Option<String> {
    for marker in ["export default function ", "function "] {
        let mut from = 0;
        while let Some(rel) = js[from..].find(marker) {
            let start = from + rel + marker.len();
            let rest = &js[start..];
            if let Some(paren) = rest.find('(') {
                let name = rest[..paren].trim();
                let after = rest[paren + 1..].trim_start();
                if after.starts_with("$$anchor") && !name.is_empty() {
                    return Some(name.to_string());
                }
            }
            from = start;
        }
    }
    None
}

// ─────────────────────────────────────────────────────────────────────────────
// (1) Handler rail — bijection + fingerprint tripwire + corpus-axis coverage.
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn svelte_handlers_biject_with_coverage_rows() {
    let parsed: BTreeSet<String> = extract_handler_bodies().into_keys().collect();
    assert!(
        parsed.len() >= 20,
        "parsed only {} svelte handlers — the parser or source shape changed: {parsed:?}",
        parsed.len()
    );

    let mut seen = BTreeSet::new();
    for coverage in HANDLER_COVERAGE {
        assert!(
            seen.insert(coverage.handler),
            "duplicate HandlerCoverage row for handler `{}`",
            coverage.handler
        );
        assert!(
            !coverage.axes.is_empty(),
            "HandlerCoverage row `{}` names no corpus axis",
            coverage.handler
        );
    }

    let committed: BTreeSet<String> = HANDLER_COVERAGE
        .iter()
        .map(|c| c.handler.to_string())
        .collect();
    let missing: Vec<_> = parsed.difference(&committed).collect();
    assert!(
        missing.is_empty(),
        "Svelte scope-view drift: svelte@{SVELTE_ORACLE_VERSION} `remove_typescript_nodes` \
         handler(s) {missing:?} have NO HandlerCoverage row. Every svelte handler — at EVERY \
         nesting level — must map to ≥1 committed corpus axis."
    );
    let stale: Vec<_> = committed.difference(&parsed).collect();
    assert!(
        stale.is_empty(),
        "Svelte scope-view drift: HandlerCoverage row(s) {stale:?} name a handler absent from \
         svelte's current source — reconcile the table with the pinned release."
    );

    // Every axis a handler claims must be a committed corpus axis (no phantom coverage).
    let corpus_axes: BTreeSet<String> = load_corpus().rows.into_iter().map(|r| r.axis).collect();
    let mut orphan = Vec::new();
    for coverage in HANDLER_COVERAGE {
        for axis in coverage.axes {
            if !corpus_axes.contains(*axis) {
                orphan.push(format!("{} → {axis}", coverage.handler));
            }
        }
    }
    assert!(
        orphan.is_empty(),
        "HandlerCoverage rows name corpus axes absent from the committed corpus (a dropped \
         generator construct — run `node scripts/gen-svelte-name-parity-corpus.mjs`):\n{}",
        orphan.join("\n")
    );

    // Conversely, every corpus axis must be claimed by ≥1 handler (no orphan axis).
    let covered_axes: BTreeSet<&str> = HANDLER_COVERAGE
        .iter()
        .flat_map(|c| c.axes.iter().copied())
        .collect();
    let uncovered: Vec<_> = corpus_axes
        .iter()
        .filter(|a| !covered_axes.contains(a.as_str()))
        .collect();
    assert!(
        uncovered.is_empty(),
        "committed corpus axes {uncovered:?} are not claimed by any HandlerCoverage row"
    );
}

#[test]
fn handler_body_fingerprints_are_current() {
    // A DRIFT TRIPWIRE over the normalized vendored handler bodies — NOT a behavioral
    // oracle. It cannot prove the pinned expectations are correct; it proves the vendored
    // source did not change under the committed fingerprints.
    let computed = extract_handler_bodies();
    let mut mismatches = Vec::new();
    for coverage in HANDLER_COVERAGE {
        let got = computed.get(coverage.handler).unwrap_or_else(|| {
            panic!(
                "handler `{}` has no body in the vendored source",
                coverage.handler
            )
        });
        if got != coverage.oracle_body_fingerprint {
            mismatches.push(format!(
                "    {} => committed {:?} but computed {:?}",
                coverage.handler, coverage.oracle_body_fingerprint, got
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "Svelte handler body fingerprints drifted (DRIFT TRIPWIRE). Re-verify the projection \
         against the changed handler bodies, then update the committed fingerprints:\n{}",
        mismatches.join("\n")
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (2) The ORACLE-derived name-parity matrix.
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn corpus_pins_the_locked_svelte_oracle() {
    let corpus = load_corpus();
    assert_eq!(
        corpus.svelte_oracle_version, SVELTE_ORACLE_VERSION,
        "the committed name-parity corpus pins svelte@{} but the projection anchor is \
         svelte@{SVELTE_ORACLE_VERSION} — regenerate the corpus after re-pinning svelte",
        corpus.svelte_oracle_version
    );
    assert!(
        !corpus.rows.is_empty(),
        "the name-parity corpus must not be empty"
    );
}

#[test]
fn every_corpus_axis_has_a_consistent_verter_disposition() {
    // The corpus (svelte oracle) and the Verter disposition tables must agree on each
    // row's KIND across the observable svelte outcomes: a svelte-COMPILE axis is
    // `NameParity` or `VerterFailClosed` (the `<T>x` fail-closed row) and never carries a
    // reject characterization; a svelte-REJECT axis MUST carry a reject characterization
    // (and no compile override); a svelte-CRASH axis MUST carry a crash characterization
    // (and no reject characterization).
    let mut failures = Vec::new();
    for row in load_corpus().rows {
        match &row.outcome {
            CorpusOutcome::Compile { .. } => {
                if reject_characterization(&row.axis).is_some() {
                    failures.push(format!(
                        "axis `{}` is a svelte-COMPILE row but carries a reject characterization",
                        row.axis
                    ));
                }
            }
            CorpusOutcome::Reject { .. } => {
                if reject_characterization(&row.axis).is_none() {
                    failures.push(format!(
                        "axis `{}` is a svelte-REJECT row but has NO reject characterization \
                         (its Verter disposition must be characterized honestly)",
                        row.axis
                    ));
                }
                if compile_disposition(&row.axis) != CompileDisposition::NameParity {
                    // A compile override on a reject axis would be nonsensical.
                    failures.push(format!(
                        "axis `{}` is a svelte-REJECT row but also has a compile disposition override",
                        row.axis
                    ));
                }
            }
            CorpusOutcome::Crash => {
                if crash_characterization(&row.axis).is_none() {
                    failures.push(format!(
                        "axis `{}` is a svelte-CRASH row but has NO crash characterization \
                         (its Verter disposition must be characterized honestly)",
                        row.axis
                    ));
                }
                if reject_characterization(&row.axis).is_some() {
                    failures.push(format!(
                        "axis `{}` is a svelte-CRASH row but also carries a reject characterization",
                        row.axis
                    ));
                }
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn name_parity_rows_match_the_svelte_oracle() {
    // The core anti-self-confirming assertion: for every svelte-COMPILE row whose axis is
    // `NameParity`, Verter's OBSERVABLE derived name equals svelte's OWN emitted name. The
    // emitted-name pins came from the pinned svelte compiler, so a projection that drops a
    // reserved name (e.g. `export * as ns`) REDs here against svelte's `ns_1`.
    let mut failures = Vec::new();
    for row in load_corpus().rows {
        let CorpusOutcome::Compile { emitted_name } = &row.outcome else {
            continue;
        };
        if compile_disposition(&row.axis) != CompileDisposition::NameParity {
            continue;
        }
        let got = derived_name(&row.source, &row.requested_name);
        if &got != emitted_name {
            failures.push(format!(
                "axis `{}` source {:?} name={:?}: svelte emits {emitted_name:?} but Verter \
                 derived {got:?}",
                row.axis, row.source, row.requested_name
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "name-parity divergences from the svelte@{SVELTE_ORACLE_VERSION} oracle:\n{}",
        failures.join("\n")
    );
}

#[test]
fn negative_control_stays_bare_for_every_name_parity_source() {
    // Discrimination: every `NameParity` source has a bare NEGATIVE-CONTROL row in the
    // corpus (svelte emits it bare) AND Verter derives it bare. An over-reserving
    // projection would turn `Zz9Unrelated` into `Zz9Unrelated_1` and RED — so a reserved
    // name (→ `_1`) is genuinely distinguished from a non-reserved one.
    let mut sources_with_control = BTreeSet::new();
    let mut name_parity_sources = BTreeSet::new();
    let mut failures = Vec::new();
    for row in load_corpus().rows {
        let CorpusOutcome::Compile { emitted_name } = &row.outcome else {
            continue;
        };
        if compile_disposition(&row.axis) != CompileDisposition::NameParity {
            continue;
        }
        name_parity_sources.insert(row.source.clone());
        if row.requested_name == NEGATIVE_CONTROL {
            sources_with_control.insert(row.source.clone());
            assert_eq!(
                emitted_name, NEGATIVE_CONTROL,
                "the negative control must be bare in the oracle for source {:?}",
                row.source
            );
            let got = derived_name(&row.source, NEGATIVE_CONTROL);
            if got != NEGATIVE_CONTROL {
                failures.push(format!(
                    "source {:?}: Verter over-reserved the negative control → {got:?}",
                    row.source
                ));
            }
        }
    }
    let missing: Vec<_> = name_parity_sources
        .difference(&sources_with_control)
        .collect();
    assert!(
        missing.is_empty(),
        "these name-parity sources are missing their bare negative-control discrimination row \
         (regenerate the corpus): {missing:?}"
    );
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn verter_fail_closed_rows_refuse_before_projection() {
    // The `<T>x` angle assertion: svelte compiles it, but the shared `SourceType::tsx()`
    // reparse rejects it as JSX, so Verter fail-closes (`build_component_scope_facts` →
    // `Err`) — never a fabricated name. Asserted once per fail-closed source.
    let mut asserted = 0usize;
    let mut seen = BTreeSet::new();
    for row in load_corpus().rows {
        if compile_disposition(&row.axis) != CompileDisposition::VerterFailClosed {
            continue;
        }
        if !seen.insert(row.source.clone()) {
            continue;
        }
        assert!(
            run_result(&row.source).is_err(),
            "axis `{}` source {:?} must FAIL CLOSED under the tsx reparse (Err), not produce facts",
            row.axis,
            row.source
        );
        asserted += 1;
    }
    assert!(
        asserted > 0,
        "expected ≥1 Verter-fail-closed axis in the corpus (the `<T>x` angle assertion)"
    );
}

#[test]
fn reject_axes_characterize_verter_disposition_exactly() {
    // svelte REJECTS these sources (no component, no name), so name-parity is VACUOUS.
    // Verter's disposition is characterized HONESTLY with an EXACT reserved-set
    // observation (exact-observation: a LEAKED name REDs, not merely `!contains(probe)`). This is a
    // Verter/OXC CHARACTERIZATION, NEVER a svelte-parity claim.
    let mut reject_axes_seen = BTreeSet::new();
    for row in load_corpus().rows {
        let CorpusOutcome::Reject { code } = &row.outcome else {
            continue;
        };
        // svelte recorded a real diagnostic code for the reject (not an empty/crash record).
        assert!(
            !code.is_empty(),
            "svelte-reject axis `{}` has an empty reject code",
            row.axis
        );
        let characterization = reject_characterization(&row.axis).unwrap_or_else(|| {
            panic!(
                "svelte-reject axis `{}` has no reject characterization",
                row.axis
            )
        });
        reject_axes_seen.insert(row.axis.clone());

        let facts = run(&row.source);
        let conflicts = facts.name_conflicts();
        // EXACT observation — the complete reserved set (a leak of any OTHER name REDs).
        assert_set_eq(
            &conflicts,
            characterization.exact_conflicts,
            &row.source,
            "name_conflicts (Verter reject-disposition characterization)",
        );
        // Defensive-erase probes: the svelte-reserved names Verter must NOT fabricate.
        for probe in characterization.erased_probes {
            assert!(
                !conflicts.contains(*probe),
                "axis `{}` ({:?}): svelte hard-errors, so Verter must DEFENSIVELY erase `{probe}` \
                 (not fabricate it into the reserved set); got {conflicts:?}",
                row.axis,
                row.source
            );
        }
        match characterization.disposition {
            RejectDisposition::PreservedGap => assert!(
                !characterization.exact_conflicts.is_empty(),
                "a PreservedGap axis `{}` must reserve the preserved construct's name(s)",
                row.axis
            ),
            RejectDisposition::DefensiveErase => assert!(
                !characterization.erased_probes.is_empty(),
                "a DefensiveErase axis `{}` must name ≥1 defensively-erased probe",
                row.axis
            ),
        }
    }
    // Every characterization row corresponds to a real svelte-reject corpus row.
    for characterization in REJECT_CHARACTERIZATIONS {
        assert!(
            reject_axes_seen.contains(characterization.axis),
            "REJECT_CHARACTERIZATIONS row `{}` is not a (rejected) corpus axis — remove it",
            characterization.axis
        );
    }
}

#[test]
fn crash_axes_characterize_verter_disposition_exactly() {
    // svelte CRASHES uncoded on these sources (an uncoded `TypeError`, NOT a typed
    // diagnostic — e.g. a lone class index signature), so there is no component/name and
    // name-parity is VACUOUS. Verter does NOT crash: `build_component_scope_facts` succeeds
    // (the projection defensively erases the construct) and reserves EXACTLY
    // `exact_conflicts` — a LEAKED name REDs. A Verter/OXC characterization, NEVER a svelte
    // claim (the AST-shape erasure is proven by `class_index_signature_is_erased_by_projection`).
    let mut crash_axes_seen = BTreeSet::new();
    for row in load_corpus().rows {
        let CorpusOutcome::Crash = &row.outcome else {
            continue;
        };
        let exact_conflicts = crash_characterization(&row.axis).unwrap_or_else(|| {
            panic!(
                "svelte-crash axis `{}` has no crash characterization",
                row.axis
            )
        });
        crash_axes_seen.insert(row.axis.clone());
        let facts = run(&row.source);
        assert_set_eq(
            &facts.name_conflicts(),
            exact_conflicts,
            &row.source,
            "name_conflicts (Verter crash-disposition characterization)",
        );
    }
    for (axis, _) in CRASH_CHARACTERIZATIONS {
        assert!(
            crash_axes_seen.contains(*axis),
            "CRASH_CHARACTERIZATIONS row `{axis}` is not a (crashed) corpus axis — remove it"
        );
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// (2b) Full-compile E2E rails — prove production wiring (not just derive_component_name)
//      per Verter-observable outcome class.
// ─────────────────────────────────────────────────────────────────────────────

/// Look up a compile row's oracle emitted name for `(axis, requested_name)`.
fn oracle_emitted(axis: &str, requested_name: &str) -> String {
    for row in load_corpus().rows {
        if row.axis == axis && row.requested_name == requested_name {
            if let CorpusOutcome::Compile { emitted_name } = row.outcome {
                return emitted_name;
            }
        }
    }
    panic!("no compile corpus row for axis `{axis}` name `{requested_name}`");
}

#[test]
fn e2e_name_parity_emit_matches_oracle() {
    // Outcome class: Verter EMITS a deconflicted component function name. `import Foo from
    // "m"` is BOTH a committed corpus row (`import_default` → `Foo_1`) AND a §1.2-core
    // instance-script item the PUBLIC client compile emits, so the full compile is driven
    // end-to-end and the emitted name is asserted against the svelte ORACLE pin directly
    // (proving production wiring, not just `derive_component_name`).
    let js = compile_component("import Foo from \"m\";", "Foo")
        .expect("an import component must compile");
    let emitted = emitted_component_name(&js)
        .unwrap_or_else(|| panic!("no component function name in emitted client JS:\n{js}"));
    assert_eq!(
        emitted,
        oracle_emitted("import_default", "Foo"),
        "the emitted name must equal the svelte oracle pin"
    );
    assert_eq!(
        emitted, "Foo_1",
        "the reserved import local `Foo` must deconflict to `Foo_1`"
    );
    // NEGATIVE: the un-deconflicted `Foo` must NOT be emitted.
    assert!(
        !js.contains("function Foo($$anchor"),
        "the reserved name `Foo` must be deconflicted, not emitted bare"
    );
}

#[test]
fn e2e_fail_closed_refuses_through_public_compile() {
    // Outcome class: Verter REFUSES. The `<T>x` angle assertion fails the shared tsx
    // reparse, so the public client compile fail-closes rather than emitting a fabricated,
    // un-deconflicted module.
    let result = compile_component("const ta = <Foo>realX;", "ta");
    assert!(
        result.is_err(),
        "the `<T>x` fail-closed component must refuse through the public compile, got Ok"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (3) exact-observation — projected-AST-shape assertions the reserved-set alone cannot discriminate.
// ─────────────────────────────────────────────────────────────────────────────

/// The kind name of an expression, for the pre/post-projection carrier assertions.
fn expr_kind_name(expr: &Expression<'_>) -> &'static str {
    match expr {
        Expression::TSAsExpression(_) => "TSAsExpression",
        Expression::TSSatisfiesExpression(_) => "TSSatisfiesExpression",
        Expression::TSNonNullExpression(_) => "TSNonNullExpression",
        Expression::TSInstantiationExpression(_) => "TSInstantiationExpression",
        Expression::TSTypeAssertion(_) => "TSTypeAssertion",
        Expression::Identifier(_) => "Identifier",
        _ => "other",
    }
}

/// The init expression kind of the first `const X = <init>;` statement of a program.
fn first_const_init_kind(program: &Program<'_>) -> &'static str {
    let Statement::VariableDeclaration(vd) = &program.body[0] else {
        panic!("expected a leading variable declaration");
    };
    let init = vd.declarations[0]
        .init
        .as_ref()
        .expect("the const has an initializer");
    expr_kind_name(init)
}

#[test]
fn ts_expression_carriers_are_present_pre_projection_and_unwrapped_post() {
    // HARDENED carrier assertion (replacing the prior `source.contains(carrier)` substring
    // check): parse the source and assert the intended OXC wrapper node is PRESENT before
    // projection, then GONE (unwrapped to its inner Identifier) after projection — so a
    // case cannot be vacuous. (`<T>x` is excluded: it fail-closes under the tsx reparse and
    // is covered by [`verter_fail_closed_rows_refuse_before_projection`].)
    let cases = [
        ("const av = inner as Ty;", "TSAsExpression"),
        ("const sv = other satisfies Ty;", "TSSatisfiesExpression"),
        ("const nn = thing!;", "TSNonNullExpression"),
        ("const iv = generic<Ty>;", "TSInstantiationExpression"),
    ];
    for (source, wrapper) in cases {
        let alloc = Allocator::default();
        let pre = reparse_module(&alloc, source)
            .unwrap_or_else(|| panic!("carrier source {source:?} must parse under tsx"));
        assert_eq!(
            first_const_init_kind(&pre),
            wrapper,
            "pre-projection carrier for {source:?} must be {wrapper}"
        );
        let alloc2 = Allocator::default();
        let post = project_source_for_test(&alloc2, source)
            .unwrap_or_else(|| panic!("carrier source {source:?} must project"));
        assert_eq!(
            first_const_init_kind(&post),
            "Identifier",
            "post-projection {source:?} must unwrap the TS carrier to its inner Identifier"
        );
    }
}

/// Count the `TSIndexSignature` members across all top-level class declarations.
fn count_class_index_signatures(program: &Program<'_>) -> usize {
    let mut count = 0;
    for stmt in &program.body {
        if let Statement::ClassDeclaration(class) = stmt {
            for element in &class.body.body {
                if matches!(element, ClassElement::TSIndexSignature(_)) {
                    count += 1;
                }
            }
        }
    }
    count
}

#[test]
fn class_index_signature_is_erased_by_projection() {
    // exact-observation: a type-only class index signature binds NO value name, so the reserved set
    // alone cannot discriminate whether the projection erased it. Assert the AST SHAPE
    // instead — present pre-projection, absent post-projection. Flipping
    // `class_element_is_scope_erased`'s `ClassElement::TSIndexSignature(_) => true` to
    // `=> false` leaves the member in the projected body and REDs the post-count. (svelte
    // itself CRASHES uncoded on a lone class index signature — recorded as the
    // `class_index_signature` `crash` corpus row; this AST-shape test ADDITIONALLY proves
    // the erasure the reserved set alone cannot discriminate.)
    let source = "class C { [k: string]: number }";
    let alloc = Allocator::default();
    let pre = reparse_module(&alloc, source).expect("index-signature class parses under tsx");
    assert_eq!(
        count_class_index_signatures(&pre),
        1,
        "pre-projection the class body carries exactly one index signature"
    );
    let alloc2 = Allocator::default();
    let post = project_source_for_test(&alloc2, source).expect("index-signature class projects");
    assert_eq!(
        count_class_index_signatures(&post),
        0,
        "post-projection the index signature must be erased (flip \
         `TSIndexSignature(_) => true` to `=> false` to see this RED)"
    );
    // The class name still survives projection (only the type-only member is erased).
    let facts = run(source);
    assert_set_eq(
        &facts.name_conflicts(),
        &["C"],
        source,
        "name_conflicts (class survives; index signature erased)",
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (4) `declared_roots` — Verter/OXC `is_pure` CHARACTERIZATION (regression lock).
//     This is Verter/OXC behavior, NOT svelte parity. The real consumers are
//     `client_plan` / `client_surface` (the `is_pure` scope resolution).
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn declared_roots_characterization_is_stable() {
    // Verter/OXC behavior, NOT svelte parity: the top-level declared-root set the `is_pure`
    // resolution reads. A nested binding (a class-expression id, a fn param) is NOT a
    // top-level root; an erased TS declaration contributes none; and the `export * as ns`
    // re-export name — which the deconfliction reserves — is deliberately NOT a
    // referenceable module-local root, so it stays OUT of this set.
    let cases: &[(&str, &[&str])] = &[
        ("const cv = 1;", &["cv"]),
        ("import Foo from \"m\";", &["Foo"]),
        ("class Cls {}", &["Cls"]),
        // `fd` is a top-level root; the `b` param is a nested binding.
        ("function fd(this: ThisT, b) { return b; }", &["fd"]),
        // `ce` is a top-level root; `NamedCe` binds only in the class-expression scope.
        ("const ce = class NamedCe {};", &["ce"]),
        // An erased pure-TS declaration contributes no root.
        ("interface Iface { n: number }", &[]),
        // `ns` is reserved by the deconfliction but is NOT a referenceable module-local
        // root — the discriminating characterization of the `export * as ns` fix.
        ("export * as ns from \"m\";", &[]),
    ];
    for (source, expected) in cases {
        let facts = run(source);
        assert_set_eq(facts.declared_roots(), expected, source, "declared_roots");
    }
    // The `export * as ns` name IS in the deconfliction domain even though it is not a
    // declared root (the two sets are distinct — the fix targets only the former).
    let ns_facts = run("export * as ns from \"m\";");
    assert!(
        ns_facts.name_conflicts().contains("ns"),
        "`export * as ns` must reserve `ns` in the deconfliction domain"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (5) Oracle-version anchor + no-soft-carrier rail (kept verbatim).
// ─────────────────────────────────────────────────────────────────────────────

/// Every `svelte@<version>` package KEY in `pnpm-lock.yaml` (a 2-space-indented
/// `svelte@<version>:` line, distinct from `svelte-check@…` / `@sveltejs/…`; a peer-
/// dependency suffix `svelte@<version>(…)` is stripped).
fn locked_svelte_versions(lock: &str) -> Vec<String> {
    let mut versions = Vec::new();
    for line in lock.lines() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("svelte@") || !trimmed.ends_with(':') {
            continue;
        }
        let rest = &trimmed["svelte@".len()..];
        let Some(end) = rest.find(['(', ':']) else {
            continue;
        };
        let version = rest[..end].to_string();
        if !versions.contains(&version) {
            versions.push(version);
        }
    }
    versions
}

#[test]
fn oracle_version_matches_locked_svelte() {
    let lock_path = workspace_root().join("pnpm-lock.yaml");
    let lock = std::fs::read_to_string(&lock_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", lock_path.display()));
    let locked = locked_svelte_versions(&lock);
    assert!(
        !locked.is_empty(),
        "no `svelte@<version>` package key found in pnpm-lock.yaml — cannot verify the scope-view \
         oracle pin"
    );
    assert!(
        locked.iter().all(|v| v == SVELTE_ORACLE_VERSION),
        "Svelte scope-view drift: SVELTE_ORACLE_VERSION = {SVELTE_ORACLE_VERSION:?} does NOT match \
         the svelte version(s) pinned in pnpm-lock.yaml ({locked:?}). A svelte bump requires re-\
         verifying the projection against the new release, re-vendoring the source, regenerating \
         the name-parity corpus, and bumping this anchor + the vendored fixture name."
    );
}

/// OPTIONAL provenance rail (gated under the `svelte-oracle` feature): the vendored
/// `.js` matches the installed svelte source (LF-normalized). The DEFAULT run consumes
/// ONLY the vendored source, so this never runs in the canonical suite.
#[cfg(feature = "svelte-oracle")]
#[test]
fn vendored_matches_installed_when_present() {
    let installed_path = workspace_root()
        .join("node_modules")
        .join(".pnpm")
        .join(format!("svelte@{SVELTE_ORACLE_VERSION}"))
        .join("node_modules")
        .join("svelte")
        .join("src")
        .join("compiler")
        .join("phases")
        .join("1-parse")
        .join("remove_typescript_nodes.js");
    let Ok(installed) = std::fs::read_to_string(&installed_path) else {
        // node_modules not installed — the vendored snapshot is authoritative.
        return;
    };
    let norm = |s: &str| s.replace("\r\n", "\n");
    assert_eq!(
        norm(VENDORED_REMOVE_TS_NODES),
        norm(&installed),
        "Svelte scope-view drift: the vendored remove_typescript_nodes snapshot diverged from the \
         installed svelte source at {}. Re-vendor and re-verify the projection.",
        installed_path.display()
    );
}

/// FRESHNESS rail (gated under the `svelte-oracle` feature): re-run the name-parity
/// generator's `--check` through the PINNED compiler. A zero exit means the committed
/// corpus is still byte-identical to a fresh regeneration (so svelte's outcomes have not
/// drifted). Opting into `--features svelte-oracle` asserts the live toolchain is present,
/// so a missing / failing node run is a HARD failure (never a silent skip). This is the
/// SAME gating as the parse-parity generator's freshness rail.
#[cfg(feature = "svelte-oracle")]
#[test]
fn pinned_compiler_still_yields_every_committed_name_parity_row() {
    let root = workspace_root();
    let script = root.join("scripts/gen-svelte-name-parity-corpus.mjs");
    assert!(
        script.exists(),
        "name-parity generator missing: {}",
        script.display()
    );
    let output = std::process::Command::new("node")
        .arg(&script)
        .arg("--check")
        .current_dir(&root)
        .output()
        .expect("run gen-svelte-name-parity-corpus.mjs --check (node must be on PATH)");
    assert!(
        output.status.success(),
        "the committed name-parity corpus drifted from the pinned svelte@{SVELTE_ORACLE_VERSION} \
         compiler:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

#[test]
fn projection_source_has_no_soft_carrier() {
    assert!(
        !PROJECTION_SOURCE.contains("_ =>"),
        "Svelte scope-view drift: a `_ =>` wildcard arm appeared in component_scope_facts.rs. The \
         projection's Statement / Expression / Declaration / ClassElement classifiers must stay \
         exhaustive so a new OXC TS carrier breaks the build instead of slipping through."
    );
    assert!(
        !PROJECTION_SOURCE.contains(".accessibility.is_some("),
        "Svelte scope-view drift: a soft `.accessibility.is_some()` check reappeared in \
         formal_parameter_is_scope_erased — use an EXHAUSTIVE match over TSAccessibility so a new \
         accessibility variant forces a decision."
    );
    for line in PROJECTION_SOURCE.lines() {
        assert!(
            !(line.contains("matches!(") && line.contains("accessibility")),
            "Svelte scope-view drift: a soft `matches!` over accessibility reappeared in \
             component_scope_facts.rs: {line}"
        );
    }
}
