//! Mapped generated-code carriers for the native Svelte runtime backend.
//!
//! Source-derived fragments retain byte ranges as they move through planning and
//! emission. The final module is lowered once through [`CodeTransform`], which is
//! the repository's source-map authority. Synthesized scaffolding is represented
//! only by unmapped text and therefore cannot inherit a preceding authored map.

use std::ops::{Deref, DerefMut};

use oxc_allocator::Allocator;

use crate::code_transform::{CodeTransform, SourceMapOptions};

use super::{ClientCompileError, GeneratedSourceMapInvalidReason};

/// A generated byte range corresponding to an authored source token/range.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct SourceMapping {
    pub(super) generated_start: u32,
    pub(super) generated_end: u32,
    pub(super) source_start: u32,
}

/// One generated fragment plus its authored mapping ranges.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(super) struct MappedCode {
    text: String,
    mappings: Vec<SourceMapping>,
}

impl MappedCode {
    pub(super) fn unmapped(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            mappings: Vec::new(),
        }
    }

    pub(super) fn from_parts(text: String, mappings: Vec<SourceMapping>) -> Self {
        debug_assert!(mappings.iter().all(|mapping| {
            mapping.generated_start < mapping.generated_end
                && mapping.generated_end as usize <= text.len()
        }));
        Self { text, mappings }
    }

    pub(super) fn as_str(&self) -> &str {
        &self.text
    }

    pub(super) fn into_string(self) -> String {
        self.text
    }

    pub(super) fn into_parts(self) -> (String, Vec<SourceMapping>) {
        (self.text, self.mappings)
    }

    pub(super) fn push_unmapped(&mut self, text: &str) {
        self.text.push_str(text);
    }

    pub(super) fn push_mapped(&mut self, fragment: &Self) {
        let generated_base = self.text.len() as u32;
        self.text.push_str(&fragment.text);
        self.mappings
            .extend(fragment.mappings.iter().map(|mapping| SourceMapping {
                generated_start: generated_base + mapping.generated_start,
                generated_end: generated_base + mapping.generated_end,
                source_start: mapping.source_start,
            }));
    }

    pub(super) fn wrapped(mut self, prefix: &str, suffix: &str) -> Self {
        if prefix.is_empty() && suffix.is_empty() {
            return self;
        }
        let shift = prefix.len() as u32;
        for mapping in &mut self.mappings {
            mapping.generated_start += shift;
            mapping.generated_end += shift;
        }
        let mut text = String::with_capacity(prefix.len() + self.text.len() + suffix.len());
        text.push_str(prefix);
        text.push_str(&self.text);
        text.push_str(suffix);
        self.text = text;
        self
    }

    pub(super) fn with_source_offset(mut self, source_offset: u32) -> Self {
        for mapping in &mut self.mappings {
            mapping.source_start += source_offset;
        }
        self
    }

    pub(super) fn mappings(&self) -> &[SourceMapping] {
        &self.mappings
    }
}

impl Deref for MappedCode {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.text
    }
}

/// The whole client-module accumulator. Existing synthesis-only emitters can
/// continue to write through its `String` deref; mapping-sensitive paths call
/// [`Self::push_mapped`] so provenance is retained explicitly.
#[derive(Debug, Default)]
pub(super) struct SvelteRuntimeOutput {
    text: String,
    mappings: Vec<SourceMapping>,
}

impl SvelteRuntimeOutput {
    pub(super) fn push_mapped(&mut self, fragment: &MappedCode) {
        let generated_base = self.text.len() as u32;
        self.text.push_str(fragment.as_str());
        self.mappings
            .extend(fragment.mappings().iter().map(|mapping| SourceMapping {
                generated_start: generated_base + mapping.generated_start,
                generated_end: generated_base + mapping.generated_end,
                source_start: mapping.source_start,
            }));
    }

    pub(super) fn into_mapped_code(self) -> MappedCode {
        MappedCode::from_parts(self.text, self.mappings)
    }

    /// Finish the module and optionally build its map from the same accumulated
    /// ranges. Generated bytes are identical with map demand on or off.
    pub(super) fn finish(
        self,
        source: &str,
        filename: Option<&str>,
        want_source_map: bool,
        allocator: &Allocator,
    ) -> Result<(String, Option<String>), ClientCompileError> {
        if !want_source_map {
            return Ok((self.text, None));
        }

        let mut transform = CodeTransform::new(source, allocator);
        if !source.is_empty() {
            transform.remove(0, source.len() as u32);
        }

        let mut mappings = self.mappings;
        mappings.sort_by_key(|mapping| (mapping.generated_start, mapping.generated_end));

        let mut items = Vec::with_capacity(mappings.len() * 2 + 1);
        let mut cursor = 0usize;
        for mapping in mappings {
            let start = mapping.generated_start as usize;
            let end = mapping.generated_end as usize;
            let invalid = if start == end {
                Some(GeneratedSourceMapInvalidReason::EmptyGeneratedRange)
            } else if start > self.text.len() || end > self.text.len() {
                Some(GeneratedSourceMapInvalidReason::GeneratedRangeOutOfBounds)
            } else if !self.text.is_char_boundary(start) || !self.text.is_char_boundary(end) {
                Some(GeneratedSourceMapInvalidReason::GeneratedRangeNotUtf8Boundary)
            } else if start < cursor {
                Some(GeneratedSourceMapInvalidReason::OverlappingGeneratedRanges)
            } else {
                let source_start = mapping.source_start as usize;
                if source_start >= source.len() {
                    Some(GeneratedSourceMapInvalidReason::SourceOffsetOutOfBounds)
                } else if !source.is_char_boundary(source_start) {
                    Some(GeneratedSourceMapInvalidReason::SourceOffsetNotUtf8Boundary)
                } else {
                    None
                }
            };
            if let Some(reason) = invalid {
                return Err(ClientCompileError::GeneratedSourceMapInvalid { reason });
            }
            if cursor < start {
                let content = allocator.alloc_str(&self.text[cursor..start]);
                items.push((0, None, content));
            }
            let content = allocator.alloc_str(&self.text[start..end]);
            items.push((0, Some((mapping.source_start, 0)), content));
            cursor = end;
        }
        if cursor < self.text.len() {
            let content = allocator.alloc_str(&self.text[cursor..]);
            items.push((0, None, content));
        }
        transform.batch_prepend_left_with_source_map(&items);

        let code = transform.build_string();
        if code != self.text {
            return Err(ClientCompileError::GeneratedSourceMapInvalid {
                reason: GeneratedSourceMapInvalidReason::GeneratedCodeChanged,
            });
        }
        let map_name = filename.map_or("(unknown)", map_basename);
        let source_map = transform.generate_map_json(SourceMapOptions {
            source: Some(map_name),
            file: Some(map_name),
            include_content: true,
        });
        Ok((code, Some(source_map)))
    }
}

impl Deref for SvelteRuntimeOutput {
    type Target = String;

    fn deref(&self) -> &Self::Target {
        &self.text
    }
}

impl DerefMut for SvelteRuntimeOutput {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.text
    }
}

fn map_basename(filename: &str) -> &str {
    filename.rsplit(['/', '\\']).next().unwrap_or(filename)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::svelte::runtime::{ClientCompileError, GeneratedSourceMapInvalidReason};

    #[test]
    fn overlapping_generated_ranges_fail_closed_with_a_typed_reason() {
        let output = SvelteRuntimeOutput {
            text: "abcd".to_string(),
            mappings: vec![
                SourceMapping {
                    generated_start: 0,
                    generated_end: 3,
                    source_start: 0,
                },
                SourceMapping {
                    generated_start: 2,
                    generated_end: 4,
                    source_start: 2,
                },
            ],
        };
        let allocator = Allocator::default();

        assert_eq!(
            output.finish("abcd", Some("App.svelte"), true, &allocator),
            Err(ClientCompileError::GeneratedSourceMapInvalid {
                reason: GeneratedSourceMapInvalidReason::OverlappingGeneratedRanges,
            })
        );
    }
}
