//! Typed source-space coordinates.
//!
//! Two coordinate spaces never share a representation: one GENERATED
//! fragment's own coordinate space ([`FragmentOffset`]/[`FragmentRange`],
//! wired into [`super::fragment::PlacementSlot::Hole`] — a hole offset
//! cannot compile against an assembled-space one), and the final ASSEMBLED
//! artifact's coordinate space ([`AssembledOffset`], wired into
//! [`super::compose::ComposedOutput`]'s placement report). A function that
//! would need to accept a bare `u32`/`Range<u32>` plus a separate "which
//! space" tag is the shape these wrappers exist to make impossible.
//!
//! An AUTHORED-source coordinate wrapper (`Original*`) does not exist here:
//! no [`super::fragment::Fragment`] field currently carries "this
//! fragment's own bytes came from original offset Y" as a fact, so a
//! wrapper for it would be unused scaffolding claiming an invariant
//! nothing enforces. [`SourceSpaceKind::Original`] stays as the space TAG
//! a fragment declares itself in (a fragment moved verbatim from authored
//! source, no codegen pass in between) — add the coordinate wrapper back
//! when a real producer needs to carry an authored-space offset across
//! this boundary.

use std::ops::Range;

use super::fragment::FragmentId;

/// Which space a coordinate lives in — carried for diagnostics only; the
/// typed wrappers below are the actual guard, not this tag.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceSpaceKind {
    Original,
    GeneratedFragment,
    AssembledOutput,
}

/// A byte offset into one GENERATED fragment's own coordinate space —
/// meaningless without knowing which fragment it came from, so the
/// fragment identity travels with the offset rather than being implied by
/// call-site context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FragmentOffset {
    pub fragment: FragmentId,
    pub offset: u32,
}

/// A byte range into one GENERATED fragment's own coordinate space. Used
/// by [`super::fragment::PlacementSlot::Hole`] — a hole is always a range
/// inside its owner's own generated bytes, never an assembled-space one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FragmentRange {
    pub fragment: FragmentId,
    pub range: Range<u32>,
}

/// A byte offset into the final ASSEMBLED artifact — where one
/// contributing fragment's bytes begin in the composed output. Used by
/// [`super::compose::ComposedOutput::fragment_starts_at`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct AssembledOffset(pub u32);

#[cfg(test)]
mod tests {
    use super::*;

    /// Compile-time proof, not a runtime assertion: a [`FragmentOffset`]
    /// and an [`AssembledOffset`] are distinct types, so the only way this
    /// function compiles is if the caller passed the matching space.
    fn accepts_only_fragment_offset(offset: FragmentOffset) -> u32 {
        offset.offset
    }

    #[test]
    fn fragment_and_assembled_offsets_are_distinct_types() {
        let fragment_offset = FragmentOffset {
            fragment: FragmentId(0),
            offset: 5,
        };
        assert_eq!(accepts_only_fragment_offset(fragment_offset), 5);
        // `accepts_only_fragment_offset(AssembledOffset(5))` — left
        // uncommented, this is a compile error, which is the invariant
        // this type split exists to enforce.
        let assembled = AssembledOffset(5);
        assert_eq!(assembled.0, 5);
    }
}
