//! Provider-only carrier import projection.
//!
//! TypeScript projects that explicitly enable `allowImportingTsExtensions`
//! consume authored `.vue`/`.svelte` specifiers through the framework plugin.
//! Every other project receives the `.verter.ts` compatibility specifier in
//! the generated provider buffer. Compiler output remains unchanged.

use std::sync::Arc;

use oxc_allocator::Allocator;
use oxc_span::SourceType;
use verter_compiler::code_transform::CodeTransform;
use verter_semantic::analysis::{build_script_analysis_with_scope, AnalysisScope};
use verter_workspace::workspace_snapshot::{ConfiguredOwnerResolution, ProjectPayload};
use verter_workspace::{FilesystemWorkspace, WorkspaceRead, CARRIER_API_VIRTUAL_SUFFIX};

use crate::documents::line_index::LineIndex;
use crate::documents::provider_projection::TransformedBufferMap;
use crate::project_resolver::{ResolvePhase, ResolveRequest, ResolveRequestKind};

/// The exact bytes a provider holds for a carrier companion, together with the
/// generated→provider map that describes *those* bytes.
///
/// The pair is INDIVISIBLE by construction: the fields are private to this
/// module, so the only way to obtain one is to ask the preparer, and no consumer
/// can pair a content with a map prepared for different bytes. That hazard was
/// real — a recorder once stamped raw compiler bytes alongside the projected
/// buffer's map, so the recorded content hash never matched the receipt's and
/// every provider-backed feature silently fell back to Verter-native results.
///
/// Both halves come out of ONE [`CodeTransform`] build: the transform emits the
/// bytes AND the geometry the map is derived from, so there is no second model
/// of the same edits to drift from.
#[derive(Clone, Debug)]
pub(crate) struct PreparedCarrierProviderContent {
    content: Arc<str>,
    rewrites: TransformedBufferMap,
}

impl PreparedCarrierProviderContent {
    /// The exact bytes the provider holds.
    pub(crate) fn content(&self) -> &Arc<str> {
        &self.content
    }

    /// The generated→provider map describing EXACTLY [`Self::content`].
    pub(crate) fn rewrites(&self) -> &TransformedBufferMap {
        &self.rewrites
    }

    /// A surface delivered with NO post-compile projection: the provider holds
    /// the generated bytes verbatim, so the identity map describes them exactly.
    /// Used for the provider paths that carry no carrier companion
    /// classification (nothing to project).
    pub(crate) fn unprojected(
        content: Arc<str>,
        _encoding: tower_lsp_server::ls_types::PositionEncodingKind,
    ) -> Self {
        Self {
            content,
            rewrites: TransformedBufferMap::identity(),
        }
    }
}

/// A prepared carrier surface plus the adjacent `@verter/types` declaration
/// overlay it depends on, when the projection created one.
pub(crate) struct PreparedCarrierProviderSurface {
    prepared: PreparedCarrierProviderContent,
    virtual_verter_types_path: Option<String>,
}

impl PreparedCarrierProviderSurface {
    #[cfg(test)]
    pub(crate) fn prepared(&self) -> &PreparedCarrierProviderContent {
        &self.prepared
    }

    pub(crate) fn into_prepared(self) -> PreparedCarrierProviderContent {
        self.prepared
    }

    /// The adjacent overlay path this surface's imports now point at, when the
    /// projection virtualized `@verter/types`.
    pub(crate) fn virtual_verter_types_path(&self) -> Option<&str> {
        self.virtual_verter_types_path.as_deref()
    }
}

fn owner_resolves_verter_types(
    workspace: Option<&FilesystemWorkspace>,
    canonical_id: &str,
) -> bool {
    let resolved = workspace
        .and_then(FilesystemWorkspace::load_published)
        .and_then(|published| {
            let workspace = workspace?;
            published.snapshot.resolver.resolve_with_reader(
                workspace,
                &ResolveRequest {
                    importer_id: canonical_id.to_string(),
                    specifier: "@verter/types".to_string(),
                    kind: ResolveRequestKind::TypeImport,
                    phase: ResolvePhase::ProviderGraph,
                },
            )
        });
    if resolved.is_some() {
        return true;
    }

    let mut current = std::path::Path::new(canonical_id).parent();
    while let Some(directory) = current {
        let manifest = directory.join("node_modules/@verter/types/package.json");
        let exists = workspace.map_or_else(
            || manifest.is_file(),
            |workspace| workspace.file_exists(&manifest.to_string_lossy().replace('\\', "/")),
        );
        if exists {
            return true;
        }
        current = directory.parent();
    }
    false
}

/// Prepare the complete provider surface for a carrier companion in ONE pass:
/// the carrier-import compatibility projection and — when `virtualize_verter_types`
/// is set and the owner cannot resolve the package — the adjacent `@verter/types`
/// declaration overlay. The relative overlay specifier lets tsgo resolve the
/// off-disk document through its normal overlay probe without writing into
/// node_modules.
///
/// Both rewrite families land in the SAME mapper, so a consumer never has to
/// recover a projection the preparer already performed.
pub(crate) fn prepare_carrier_provider_surface(
    workspace: Option<&FilesystemWorkspace>,
    canonical_id: &str,
    provider_path: &str,
    generated: &str,
    encoding: tower_lsp_server::ls_types::PositionEncodingKind,
    virtualize_verter_types: bool,
) -> PreparedCarrierProviderSurface {
    // BOTH the import specifier and the overlay path derive from the ONE
    // descriptor naming authority — never a locally-formatted string — so the
    // published sidecar can never drift from what `classify_carrier_companion`
    // recognizes (the drift that silently dropped the sidecar from the SHARED
    // overlay). Round-trip-guarded by
    // `published_provider_paths_classify_as_companions_of_their_carrier`.
    let verter_types_specifier = (virtualize_verter_types
        && !owner_resolves_verter_types(workspace, canonical_id))
    .then(|| verter_session::framework::descriptor::verter_types_import_specifier(provider_path))
    .flatten();

    let (prepared, rewrote_verter_types) = prepare_carrier_provider_imports_with_verter_types(
        workspace,
        canonical_id,
        generated,
        encoding,
        verter_types_specifier.as_deref(),
    );
    PreparedCarrierProviderSurface {
        prepared,
        // The overlay is only a live dependency when an import actually points at
        // it; a carrier that never mentions `@verter/types` needs no overlay file.
        // The path derivation shares the specifier derivation's fail-closed
        // basename predicate, so `rewrote_verter_types` (a specifier existed and
        // was written into the carrier) implies the overlay path derives too — a
        // rewrite can never point at an overlay this refuses to name.
        virtual_verter_types_path: rewrote_verter_types
            .then(|| {
                verter_session::framework::descriptor::verter_types_sidecar_path(provider_path)
            })
            .flatten(),
    }
}

/// Whether every exact configured owner explicitly permits authored carrier
/// extension imports. Missing, false, bootstrap, and unowned all use the
/// compatibility projection.
pub(crate) fn configured_owners_allow_authored_carrier_specifiers(
    snapshot: &verter_workspace::WorkspaceSnapshot,
    canonical_id: &str,
) -> bool {
    let owner_allows = |id: verter_workspace::workspace_snapshot::ProjectId| {
        matches!(
            &snapshot.project(id).payload,
            ProjectPayload::Configured { compiler_options, .. }
                if compiler_options.allow_importing_ts_extensions
        )
    };

    match snapshot.configured_owner_resolution_for_file(canonical_id) {
        ConfiguredOwnerResolution::Unique(owner) => owner_allows(owner),
        ConfiguredOwnerResolution::Ambiguous(owners) => {
            !owners.is_empty() && owners.into_iter().all(owner_allows)
        }
        ConfiguredOwnerResolution::None => false,
    }
}

pub(crate) fn prepare_carrier_provider_imports(
    workspace: Option<&FilesystemWorkspace>,
    canonical_id: &str,
    generated: &str,
    encoding: tower_lsp_server::ls_types::PositionEncodingKind,
) -> PreparedCarrierProviderContent {
    prepare_carrier_provider_imports_with_verter_types(
        workspace,
        canonical_id,
        generated,
        encoding,
        None,
    )
    .0
}

/// Returns the prepared surface plus whether an `@verter/types` reference was
/// actually redirected onto `verter_types_specifier` (the caller publishes the
/// adjacent overlay only when something imports it).
fn prepare_carrier_provider_imports_with_verter_types(
    workspace: Option<&FilesystemWorkspace>,
    canonical_id: &str,
    generated: &str,
    encoding: tower_lsp_server::ls_types::PositionEncodingKind,
    verter_types_specifier: Option<&str>,
) -> (PreparedCarrierProviderContent, bool) {
    let published = workspace.and_then(FilesystemWorkspace::load_published);
    let rewrite_carrier_imports = !published.as_ref().is_some_and(|published| {
        published.ownership_ready
            && configured_owners_allow_authored_carrier_specifiers(
                &published.snapshot,
                canonical_id,
            )
    });
    if !rewrite_carrier_imports && verter_types_specifier.is_none() {
        return (
            PreparedCarrierProviderContent {
                content: Arc::from(generated),
                rewrites: TransformedBufferMap::identity(),
            },
            false,
        );
    }

    let allocator = Allocator::new();
    let analysis = build_script_analysis_with_scope(
        generated,
        SourceType::tsx(),
        &allocator,
        AnalysisScope::IMPORTS,
    );
    let mut replacements = Vec::new();
    let mut rewrote_verter_types = false;
    for reference in analysis.module_references {
        if reference.analyzability != verter_semantic::analysis::ModuleReferenceAnalyzability::Exact
        {
            continue;
        }
        let Some(specifier) = reference.literal_specifier.as_deref() else {
            continue;
        };
        let provider_specifier = if specifier == "@verter/types" {
            let Some(provider_specifier) = verter_types_specifier else {
                continue;
            };
            rewrote_verter_types = true;
            provider_specifier.to_owned()
        } else {
            if !rewrite_carrier_imports {
                continue;
            }
            let resolved = published.as_ref().and_then(|published| {
                let workspace = workspace?;
                published.snapshot.resolver.resolve_with_reader(
                    workspace,
                    &ResolveRequest {
                        importer_id: canonical_id.to_string(),
                        specifier: specifier.to_string(),
                        kind: if reference.is_type_only {
                            ResolveRequestKind::TypeImport
                        } else {
                            ResolveRequestKind::EsmImport
                        },
                        phase: ResolvePhase::ProviderGraph,
                    },
                )
            });
            match resolved {
                Some(resolved) if verter_workspace::path_is_carrier(&resolved.source_id) => {
                    resolved.provider_specifier
                }
                _ if verter_workspace::path_is_carrier(specifier) => {
                    format!("{specifier}{CARRIER_API_VIRTUAL_SUFFIX}")
                }
                _ => continue,
            }
        };
        let start = reference.expr_span.start as usize;
        let end = reference.expr_span.end as usize;
        let Some(original) = generated.get(start..end) else {
            continue;
        };
        let replacement = crate::server::server_utils::quote_wrapped_specifier(
            &reference.raw_text,
            &provider_specifier,
        );
        if original != replacement {
            replacements.push((start, end, replacement));
        }
    }
    replacements.sort_by_key(|replacement| replacement.0);

    // ONE `CodeTransform` owns the edits. It emits the delivered bytes AND the
    // output geometry the generated→provider map is derived from, so the buffer
    // and its map come from the same chunk walk and cannot describe different
    // edits. (Editing the built string and maintaining a compensating mapper
    // alongside it is exactly the desync `CodeTransform` exists to prevent.)
    let mut transform = CodeTransform::new(generated, &allocator);
    for (start, end, replacement) in &replacements {
        transform.overwrite(*start as u32, *end as u32, replacement);
    }
    let (content, source_ranges) = transform.build_string_with_source_ranges();

    let Some(rewrites) = TransformedBufferMap::from_transform_geometry(
        &LineIndex::new(generated, encoding.clone()),
        &LineIndex::new(&content, encoding),
        &source_ranges,
    ) else {
        // The transform produced bytes this line-column model cannot describe
        // (an edit crossing a line boundary). Fail closed: deliver the compiler
        // bytes UNPROJECTED with the identity map rather than a buffer whose
        // positions would silently mislead every provider-backed feature.
        return (
            PreparedCarrierProviderContent {
                content: Arc::from(generated),
                rewrites: TransformedBufferMap::identity(),
            },
            false,
        );
    };

    (
        PreparedCarrierProviderContent {
            content: Arc::from(content),
            rewrites,
        },
        rewrote_verter_types,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use verter_span::TsPosition;

    #[test]
    fn non_true_policy_rewrites_only_framework_carriers_and_tracks_columns() {
        let source = "import C from './C.vue'; import x from './x.ts'; void C; void x;\n";
        let prepared = prepare_carrier_provider_imports(
            None,
            "/ws/App.vue",
            source,
            tower_lsp_server::ls_types::PositionEncodingKind::UTF16,
        );
        assert!(prepared.content().contains("'./C.vue.verter.ts'"));
        assert!(prepared.content().contains("'./x.ts'"));

        let original_semicolon = source.find("; import x").unwrap() as u32;
        assert_eq!(
            prepared
                .rewrites()
                .generated_to_provider(TsPosition::new(0, original_semicolon))
                .unwrap()
                .character,
            original_semicolon + CARRIER_API_VIRTUAL_SUFFIX.len() as u32
        );
    }

    /// A position AFTER the rewritten specifiers on a rewritten import line must
    /// map onto the byte the DELIVERED buffer actually holds there.
    ///
    /// The expected column is read out of the produced provider bytes, not
    /// asserted as a constant, so the map is checked against the buffer itself.
    /// That is the whole point of letting ONE `CodeTransform` emit both: an
    /// implementation that edits the built string out of band and keeps a
    /// separate model of those edits (`content.replace(…)` beside a hand-
    /// maintained column table) can drift by a character and mis-map every
    /// position after the rewrite — which is a hover landing on the wrong token
    /// and a go-to-definition landing in the wrong place.
    ///
    /// TWO same-line rewrites, because a single one cannot expose an accumulator
    /// that drifts only from the second rewrite onward.
    #[test]
    fn positions_after_same_line_rewrites_land_on_the_delivered_bytes() {
        let generated = "import A from './A.vue'; import B from './B.vue'; void A; void B;\n";
        let prepared = prepare_carrier_provider_imports(
            None,
            "/ws/App.vue",
            generated,
            tower_lsp_server::ls_types::PositionEncodingKind::UTF16,
        );
        let provider = prepared.content().to_string();
        assert!(provider.contains("'./A.vue.verter.ts'"));
        assert!(provider.contains("'./B.vue.verter.ts'"));

        // `void A;` sits after BOTH rewrites on the same line, so its true
        // provider column is wherever the delivered bytes put it.
        let generated_column = generated.find("void A;").expect("fixture token") as u32;
        let provider_column = provider.find("void A;").expect("delivered token") as u32;
        assert_ne!(
            generated_column, provider_column,
            "both specifier rewrites lengthen the line, so the tail must shift"
        );
        assert_eq!(
            prepared
                .rewrites()
                .generated_to_provider(TsPosition::new(0, generated_column))
                .expect("a position after the rewrites maps into the provider buffer")
                .character,
            provider_column,
            "the map must land on the column the delivered buffer actually holds"
        );
        assert_eq!(
            prepared
                .rewrites()
                .provider_to_generated(TsPosition::new(0, provider_column))
                .expect("the provider position maps back")
                .character,
            generated_column,
            "the inverse hop must return the authored column"
        );

        // Inside replacement text there is no faithful per-character origin:
        // fail closed rather than hand back a plausible-looking neighbour.
        let inside_replacement = provider.find(".verter.ts").expect("rewritten text") as u32;
        assert!(
            prepared
                .rewrites()
                .provider_to_generated(TsPosition::new(0, inside_replacement))
                .is_none(),
            "a position inside a rewritten specifier must not map"
        );
    }

    /// The carrier-import projection and the `@verter/types` overlay redirect are
    /// prepared in ONE pass, so the SINGLE returned mapper describes the SINGLE
    /// returned buffer — including the column shift the overlay specifier
    /// introduces. Recovering either half separately (re-parsing delivered bytes
    /// to reconstruct the mapping) is what let a content/mapper pair diverge.
    #[test]
    fn one_pass_surface_maps_columns_past_both_rewrite_families() {
        let generated = "import C from './C.vue';\nimport type { X } from '@verter/types';\nconst value: X = {} as X; void C;\n";
        let surface = prepare_carrier_provider_surface(
            None,
            "/ws/App.vue",
            "/ws/App.vue.tsx",
            generated,
            tower_lsp_server::ls_types::PositionEncodingKind::UTF16,
            true,
        );

        let provider = surface.prepared().content().to_string();
        assert!(provider.contains("'./C.vue.verter.ts'"));
        assert!(provider.contains("'./App.vue.tsx.__verter_types'"));
        assert!(!provider.contains("'@verter/types'"));
        assert_eq!(
            surface.virtual_verter_types_path(),
            Some("/ws/App.vue.tsx.__verter_types.d.ts"),
            "an import that now points at the overlay makes it a live dependency"
        );

        // The overlay rewrite is on line 1; a position after it on that line must
        // map through the SAME mapper the buffer was produced with.
        let generated_column = generated.lines().nth(1).unwrap().find("from").unwrap() as u32;
        let provider_column = provider.lines().nth(1).unwrap().find("from").unwrap() as u32;
        assert_eq!(
            generated_column, provider_column,
            "the rewrite is to the right of `from`, so this column is unshifted"
        );
        let tail_generated = generated.lines().nth(1).unwrap().len() as u32 - 1;
        let tail_provider = provider.lines().nth(1).unwrap().len() as u32 - 1;
        assert_ne!(
            tail_generated, tail_provider,
            "the overlay specifier is longer than `@verter/types`, so the line end shifts"
        );
        assert_eq!(
            surface
                .prepared()
                .rewrites()
                .generated_to_provider(TsPosition::new(1, tail_generated))
                .expect("the line-end position maps into the provider buffer")
                .character,
            tail_provider
        );
        assert_eq!(
            surface
                .prepared()
                .rewrites()
                .provider_to_generated(TsPosition::new(1, tail_provider))
                .expect("the provider position maps back")
                .character,
            tail_generated
        );
    }

    /// A carrier that never mentions `@verter/types` gets NO overlay dependency,
    /// even on the engine that virtualizes it.
    #[test]
    fn surface_without_verter_types_import_publishes_no_overlay() {
        let surface = prepare_carrier_provider_surface(
            None,
            "/ws/App.vue",
            "/ws/App.vue.tsx",
            "import C from './C.vue'; void C;\n",
            tower_lsp_server::ls_types::PositionEncodingKind::UTF16,
            true,
        );
        assert_eq!(surface.virtual_verter_types_path(), None);
        assert!(surface.prepared().content().contains("'./C.vue.verter.ts'"));
    }
}
