//! Policy/output types for the Svelte CSS pipeline — the css output mode,
//! the keyframes rename lists, and the per-`<style>` scope-plan side table.
//! The grammar itself (selector/rule/declaration node shapes) lives entirely
//! in the shared `verter_css_syntax::StyleSyntaxIr`; this module owns no
//! competing tree.

use verter_span::Span;

use crate::svelte::runtime::ir::NodeId;

/// The css output mode of one component — the official `css` compile axis
/// combined with the custom-element rule (`inject_styles = css === 'injected'
/// || is_custom_element`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CssMode {
    /// The default `css: 'external'` mode — the scoped CSS is emitted as a
    /// separate artifact.
    External,
    /// The `css: 'injected'` / custom-element mode — the scoped CSS is
    /// injected by the component at runtime.
    Injected,
}

/// One LOCAL `@keyframes` name — a member of the scope-RENAME list (the
/// official `analysis.css.keyframes` entry).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyframeName {
    /// The keyframes name exactly as the official analysis records it (the
    /// raw trimmed prelude text, comments stripped).
    pub name: String,
    /// The span of the name token inside the at-rule prelude (the region the
    /// renderer prefixes with `<hash>-`).
    pub name_span: Span,
}

/// One `-global-`-prefixed `@keyframes` name — EXCLUDED from the rename list;
/// the renderer strips the `-global-` prefix instead.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GlobalKeyframeName {
    /// The name WITHOUT the `-global-` prefix.
    pub name: String,
    /// The span of the FULL prefixed name token inside the at-rule prelude
    /// (the first 8 bytes are the `-global-` prefix the renderer removes).
    pub name_span: Span,
}

/// The per-`<style>` scope plan — the ONE shared fact table the scope-class
/// injection sites and the css emitter read. PROVEN BY CONSTRUCTION: a value
/// of this type exists ONLY when the css body parsed + analyzed, the
/// selector-to-template matcher (`css-prune.js` port) proved EVERY
/// selector⇄template relation (the used/scoped verdicts fed
/// [`facts`](Self::facts) and [`css_code`](Self::css_code) are authoritative),
/// and the scoped render succeeded — every failure mode is the typed
/// [`StylePlanFailure`](super::StylePlanFailure) `Err` of
/// [`complete_style_scope_plan`](super::complete_style_scope_plan); the type
/// carries no unprovable state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvenStyleScopePlan {
    /// The scope hash (`svelte-<djb2>` over the official css-hash input).
    pub hash: String,
    /// The rendered scoped stylesheet (the official `css.code`): the css body
    /// with scope classes applied, `:global(...)` unwrapped, unused/empty
    /// rules comment-pruned (external) or REMOVED (injected — the official
    /// `inject_styles && !dev` minified render), and local `@keyframes`
    /// renamed — produced by
    /// [`render_stylesheet`](super::render::render_stylesheet) from the
    /// matcher-verdict-bearing analysis, mode-faithfully per
    /// [`mode`](Self::mode).
    /// MAY legitimately be empty — the OFFICIAL empty render of an empty /
    /// all-global-pruned stylesheet (`compiled.css.code = ''`), never a
    /// failure sentinel.
    pub css_code: String,
    /// The css source-map JSON for [`css_code`](Self::css_code) (the official
    /// `css.map`) — `Some` ONLY when the plan build was asked for it
    /// (`want_source_map`), generated by the render from the SAME shared
    /// transform that produced the code. Its mappings point rendered css
    /// positions back to the ORIGINAL component source.
    pub source_map: Option<String>,
    /// The CSS BODY span in the original component source.
    pub css_body_span: Span,
    /// The LOCAL `@keyframes` rename list (the official
    /// `analysis.css.keyframes`), source order.
    pub keyframes: Vec<KeyframeName>,
    /// The `-global-`-prefixed `@keyframes` names (prefix-strip list), source
    /// order.
    pub global_keyframes: Vec<GlobalKeyframeName>,
    /// Whether the component's css includes GLOBAL css (the official
    /// `analysis.css.has_global`).
    pub has_global: bool,
    /// The css output mode.
    pub mode: CssMode,
    /// The PROVEN template-side matcher facts (the official `css-prune.js`
    /// `prune(stylesheet, elements)` per-element scope marks).
    pub facts: MatchedTemplateFacts,
}

/// The template-side facts a proven match produces — the official
/// `element.metadata.scoped` marks, keyed by runtime-IR node id.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MatchedTemplateFacts {
    /// The template elements at least one used selector might apply to (the
    /// elements that receive the scope class).
    pub scoped: rustc_hash::FxHashSet<NodeId>,
}

/// The narrow scope-class INJECTION view of a proven style plan — the ONE
/// `(hash, scoped-element set)` fact pair EVERY scope-class injection site
/// reads: the static skeleton bake, the `$.set_class` value/`css_hash`
/// threading, and the spread `$.attribute_effect` hash argument. All sites
/// derive from the same [`ProvenStyleScopePlan`] via
/// [`scope_facts`](ProvenStyleScopePlan::scope_facts), so the sites cannot
/// disagree on the hash or on which elements are scoped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssScopeFacts {
    /// The scope hash (`svelte-<djb2>`).
    pub hash: String,
    /// The scoped template elements (the matcher's per-element scope marks).
    pub scoped: rustc_hash::FxHashSet<NodeId>,
}

impl CssScopeFacts {
    /// The scope hash for one element: `Some(hash)` when `node` is scoped,
    /// `None` otherwise — the per-element read both injection sites share.
    #[must_use]
    pub fn hash_for(&self, node: NodeId) -> Option<&str> {
        self.scoped.contains(&node).then_some(self.hash.as_str())
    }
}

impl ProvenStyleScopePlan {
    /// The scope-injection facts of the plan. A constructed plan ALWAYS has
    /// proven facts (unprovable inputs never construct a plan — they fail the
    /// build with a typed [`StylePlanFailure`](super::StylePlanFailure)), so
    /// this projection is total.
    #[must_use]
    pub fn scope_facts(&self) -> CssScopeFacts {
        CssScopeFacts {
            hash: self.hash.clone(),
            scoped: self.facts.scoped.clone(),
        }
    }
}
