// @generated by verter — DO NOT EDIT BY HAND.
//
// Mirror of the Rust framework-adapter virtual-file naming column
// (`crates/verter_session/src/framework/descriptor.rs`). The descriptor
// table is the single authority; this file is rendered from it and
// byte-pinned by `virtual_file_naming_ts_freshness`. Regenerate via that
// test's update path after any descriptor-row change.
//
// Keyed by the closed wire `FrameworkTag` name (`as_str_name`) for component
// carriers, plus `SVELTE_RUNE_MODULE` for the standalone rune-module naming.
// Suffix policies append to the FULL carrier canonical (e.g. `App.vue` + `.ts`
// => `App.vue.ts`); a `selfFile` policy means the file serves its own path.

export interface VirtualPathNone {
  kind: "none";
}

export interface VirtualPathSelfFile {
  kind: "selfFile";
}

export interface VirtualPathSuffix {
  kind: "suffix";
  suffix: string;
}

export interface VirtualPathJsxConditional {
  kind: "jsxConditional";
  jsx: string;
  nonJsx: string;
}

export type VirtualPathPolicy =
  | VirtualPathNone
  | VirtualPathSelfFile
  | VirtualPathSuffix
  | VirtualPathJsxConditional;

export interface DeclarationSurfaceNone {
  kind: "none";
}

export interface DeclarationSurfaceExtensionMiddleTs {
  kind: "extensionMiddleTs";
}

export type DeclarationSurface = DeclarationSurfaceNone | DeclarationSurfaceExtensionMiddleTs;

export interface VirtualFileNaming {
  carrierExtension: string | null;
  ide: VirtualPathPolicy;
  importSurface: VirtualPathPolicy;
  testingApiSuffix: string | null;
  sidecarSuffixes: string[];
  declarationSurface: DeclarationSurface;
}

export const VIRTUAL_FILE_NAMING: Readonly<Record<string, VirtualFileNaming>> = {
  FRAMEWORK_TAG_VUE: {
    carrierExtension: ".vue",
    ide: { kind: "jsxConditional", jsx: ".jsx", nonJsx: ".tsx" },
    importSurface: { kind: "suffix", suffix: ".verter.ts" },
    testingApiSuffix: ".__verter_test.ts",
    sidecarSuffixes: [],
    declarationSurface: { kind: "extensionMiddleTs" },
  },
  FRAMEWORK_TAG_SVELTE: {
    carrierExtension: ".svelte",
    ide: { kind: "jsxConditional", jsx: ".jsx", nonJsx: ".tsx" },
    importSurface: { kind: "suffix", suffix: ".verter.ts" },
    testingApiSuffix: null,
    sidecarSuffixes: [],
    declarationSurface: { kind: "extensionMiddleTs" },
  },
  SVELTE_RUNE_MODULE: {
    carrierExtension: ".svelte.ts",
    ide: { kind: "selfFile" },
    importSurface: { kind: "selfFile" },
    testingApiSuffix: null,
    sidecarSuffixes: [],
    declarationSurface: { kind: "none" },
  },
};
