//! The PARSER-STRICTNESS PARITY MATRIX — the generated-corpus gate proving Verter's
//! forgiving parser fails closed exactly where the official `svelte@5.56.3` STRICT
//! parser rejects, and never over-rejects what official accepts.
//!
//! The corpus (`tests/svelte_oracle_corpus/parse_parity/`) is GENERATED by
//! `scripts/gen-svelte-parse-parity-corpus.mjs`: a deterministic enumeration of
//! malformed-and-accepted markup across the parser's perturbation axes (text/raw-token,
//! open tags, close tags, attributes, script/style, comments) PLUS the MECHANICAL
//! finite-axis enumerators (the full `REGEX_NTH_OF` An+B matrix, the `read/style.js`
//! parse-entry code set, the `<svelte:options customElement>` value + source-order
//! arbitration space, the open-tag duplicate-timing forms, and the script-`lang` finite
//! forms), each wrapped in a §1.2 scaffold, with the pinned compiler's disposition recorded
//! per fixture as `{ "disposition", "official_code", "core", "axis" }`. The enumerated axes
//! are the mechanical coverage contract: the generated `manifest.json` lists `required_axes`,
//! and a Rust COVERAGE gate (below) asserts every required axis has ≥1 committed row, so the
//! corpus cannot silently lose a finite axis to a hand-audit gap.
//!
//! DEFAULT (hermetic, committed-metadata-only — no `node` at test time) gates:
//! - REJECTED ⇒ Verter returns NO `Main` AND the refusal carries the EXACT official
//!   code: a parser-strictness / close-tag-violation row fails closed as an
//!   `OfficialReject` whose `official_code` equals the committed `official_code`; a row
//!   owned by a DIFFERENT refusal path (an official-accepted-but-non-core feature that
//!   official nonetheless rejects, e.g. `<svelte:nope>` → `svelte_meta_invalid_tag`,
//!   owned by the unsupported-feature path) is an EXPLICIT, audited per-row exception
//!   asserting fail-closed-without-`Main` only. This exact-code assertion is what forces
//!   every leaked / mis-coded recovery point to actually be fixed.
//! - ACCEPTED + `core` ⇒ Verter EMITS a `Main` (the §1.2-core positive control). The
//!   strict gate must neither over-reject it as malformed NOR drop it as unsupported.
//! - ACCEPTED + NON-core ⇒ Verter does NOT refuse via `ParserStrictness` (it may fail
//!   closed as an unsupported FEATURE — a top-level / nested `<style>`, a non-allowlisted
//!   attribute — but never for being malformed).
//!
//! Plus the FRESHNESS gate (behind `svelte-oracle`): the pinned compiler STILL yields
//! each committed fixture's recorded disposition + official code.
//!
//! The "no accepted-invalid leak" property is proven STRUCTURALLY (every rejected row
//! emits no `Main`, asserted by the rejected-row gate over the whole corpus) — there is
//! NO `KNOWN_ACCEPTED_INVALID` allowlist / escape hatch.

use std::fs;
use std::path::PathBuf;

use oxc_allocator::Allocator;
use verter_compiler::svelte::parser::parse_svelte;
use verter_compiler::svelte::runtime::{
    compile_client, ClientCompileError, CoreOfficialValidationRule, SvelteRuntimeOptions,
};

/// The parse-parity corpus root.
fn parse_parity_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/svelte_oracle_corpus/parse_parity")
}

/// One committed parse-parity row: the fixture basename, its `.svelte` source, the
/// official disposition (`accepted` / `rejected`), the recorded official code (empty for
/// an accepted row), the §1.2-core classification (`core`: an ACCEPTED-core fixture must
/// emit a `Main`; an ACCEPTED non-core one fails closed as an unsupported feature), and the
/// finite-axis tag (`axis`) the coverage gate keys on.
struct ParityRow {
    name: String,
    source: String,
    accepted: bool,
    official_code: String,
    core: bool,
    axis: String,
}

/// Load every parse-parity row (`<name>.svelte` + `<name>.json`), sorted by name,
/// skipping the top-level `manifest.json`. Panics on a malformed metadata file — the
/// corpus is a closed, generator-owned contract.
fn load_parity_corpus() -> Vec<ParityRow> {
    let dir = parse_parity_dir();
    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read parse-parity corpus dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "svelte").unwrap_or(false))
        .map(|p| p.file_stem().unwrap().to_string_lossy().into_owned())
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "the parse-parity corpus must not be empty: {} (run \
         `node scripts/gen-svelte-parse-parity-corpus.mjs`)",
        dir.display()
    );

    names
        .into_iter()
        .map(|name| {
            let source = fs::read_to_string(dir.join(format!("{name}.svelte")))
                .unwrap_or_else(|e| panic!("read {name}.svelte: {e}"));
            let json_text = fs::read_to_string(dir.join(format!("{name}.json")))
                .unwrap_or_else(|e| panic!("read {name}.json: {e}"));
            let disposition = json_string_field(&json_text, "disposition")
                .unwrap_or_else(|| panic!("{name}.json: missing `disposition` field"));
            let official_code = json_string_field(&json_text, "official_code")
                .unwrap_or_else(|| panic!("{name}.json: missing `official_code` field"));
            let core = json_bool_field(&json_text, "core")
                .unwrap_or_else(|| panic!("{name}.json: missing `core` field"));
            let axis = json_string_field(&json_text, "axis")
                .unwrap_or_else(|| panic!("{name}.json: missing `axis` field"));
            let accepted = match disposition.as_str() {
                "accepted" => true,
                "rejected" => false,
                other => panic!("{name}.json: invalid disposition `{other}`"),
            };
            ParityRow {
                name,
                source,
                accepted,
                official_code,
                core,
                axis,
            }
        })
        .collect()
}

/// Extract a `"key": "value"` string field from a flat metadata JSON object (no JSON
/// crate in the test binary — the metadata is a closed, generator-authored flat object).
fn json_string_field(json_text: &str, key: &str) -> Option<String> {
    let needle = format!("\"{key}\"");
    let after_key = &json_text[json_text.find(&needle)? + needle.len()..];
    let after_colon = &after_key[after_key.find(':')? + 1..];
    let open = after_colon.find('"')? + 1;
    let rest = &after_colon[open..];
    let close = rest.find('"')?;
    Some(rest[..close].to_string())
}

/// Extract a `"key": true|false` boolean field from a flat metadata JSON object. Reads
/// the token after the colon up to the next `,` / `}` and matches `true` / `false`.
fn json_bool_field(json_text: &str, key: &str) -> Option<bool> {
    let needle = format!("\"{key}\"");
    let after_key = &json_text[json_text.find(&needle)? + needle.len()..];
    let after_colon = &after_key[after_key.find(':')? + 1..];
    let token: String = after_colon
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_alphabetic())
        .collect();
    match token.as_str() {
        "true" => Some(true),
        "false" => Some(false),
        _ => None,
    }
}

/// Compile a parse-parity row source through the client backend.
fn compile(source: &str) -> Result<String, ClientCompileError> {
    let alloc = Allocator::default();
    let parsed = parse_svelte(source);
    let opts = SvelteRuntimeOptions {
        filename: Some("App.svelte".to_string()),
        ..Default::default()
    };
    compile_client(source, &parsed, &opts, &alloc, false).map(|m| m.code)
}

/// Whether a `compile_client` result is a `ParserStrictness` refusal.
fn is_parser_strictness_refusal(result: &Result<String, ClientCompileError>) -> bool {
    matches!(
        result,
        Err(ClientCompileError::OfficialReject(rejection))
            if rejection.rule == CoreOfficialValidationRule::ParserStrictness
    )
}

/// Whether a `compile_client` result is ANY exact-code official reject — an
/// [`ClientCompileError::OfficialReject`] carrying an exact upstream code. An officially-ACCEPTED
/// input must NEVER receive one (it would be a FABRICATED exact-code reject of an input upstream
/// accepts — the parity-bar violation); for an unsupported feature Verter must fail closed through
/// the unsupported-feature channel instead, never an `OfficialReject`.
fn is_official_reject(result: &Result<String, ClientCompileError>) -> bool {
    matches!(result, Err(ClientCompileError::OfficialReject(_)))
}

/// The EXPLICIT, audited set of REJECTED parse-parity rows that fail closed through a
/// refusal path OTHER than an `OfficialReject` carrying the official code — each because
/// official rejects the input for a reason Verter owns on a different rail. A row here
/// asserts ONLY "no `Main`" (it is not held to the exact-code `OfficialReject`
/// assertion); every other rejected row MUST be an `OfficialReject` whose `official_code`
/// equals the committed code.
///
/// This list is NOT a leniency escape hatch — every entry still fails closed (no `Main`);
/// it only records WHICH refusal owner is responsible so the exact-code gate stays
/// discriminating for the parser-strictness / close-tag-violation families.
const NON_OFFICIAL_REJECT_ROWS: &[(&str, &str)] = &[
    // `<svelte:nope>` is well-formed markup the parser ACCEPTS; official rejects it as an
    // invalid `<svelte:*>` meta tag (`svelte_meta_invalid_tag`), and Verter fails it
    // closed via the unsupported-feature path (a `<svelte:*>` special element), NOT the
    // official-reject gate. So it carries no `OfficialReject.official_code`.
    (
        "011_open_tag_invalid_svelte_special",
        "official rejects an invalid <svelte:*> meta tag; Verter owns it on the \
         unsupported-feature rail",
    ),
];

/// Whether a rejected row is an audited non-`OfficialReject` exception.
fn is_non_official_reject_exception(name: &str) -> bool {
    NON_OFFICIAL_REJECT_ROWS.iter().any(|(n, _)| *n == name)
}

// ─────────────────────────────────────────────────────────────────────────────
// (1) DEFAULT hermetic gate — REJECTED rows fail closed (no `Main`) AND carry the
//     EXACT official code (unless an audited non-`OfficialReject` exception).
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn every_official_rejected_row_fails_closed_with_exact_official_code() {
    let mut failures = Vec::new();
    for row in load_parity_corpus() {
        if row.accepted {
            continue;
        }
        let result = compile(&row.source);
        match &result {
            // An emitted `Main` is always a leak — official rejects this input.
            Ok(js) => failures.push(format!(
                "{}: official REJECTS this ({}), but Verter emitted a Main:\n{js}",
                row.name, row.official_code
            )),
            Err(ClientCompileError::OfficialReject(rejection)) => {
                // The refusal MUST carry the exact committed official code — this is the
                // assertion that forces a leaked / mis-coded recovery point to be fixed.
                if rejection.official_code != row.official_code {
                    failures.push(format!(
                        "{}: refused as {:?} carrying `{}`, but the committed official code \
                         is `{}`",
                        row.name, rejection.rule, rejection.official_code, row.official_code
                    ));
                }
            }
            Err(_other) => {
                // A non-`OfficialReject` refusal (an unsupported feature) is acceptable
                // ONLY for an audited exception row; otherwise the row must classify as an
                // exact-code `OfficialReject`.
                if !is_non_official_reject_exception(&row.name) {
                    failures.push(format!(
                        "{}: official REJECTS this ({}) but Verter refused through a \
                         non-OfficialReject path (no exact official code) and the row is not \
                         an audited NON_OFFICIAL_REJECT_ROWS exception",
                        row.name, row.official_code
                    ));
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "the parse-parity corpus has rejected-row failures (a leak, a wrong official code, \
         or an un-audited non-OfficialReject refusal):\n{}",
        failures.join("\n\n")
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (2) DEFAULT hermetic gate — ACCEPTED rows: core ⇒ emits a `Main`; non-core ⇒ never
//     over-rejected as malformed (may fail closed as an unsupported feature).
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn every_accepted_core_row_emits_a_main_and_no_accepted_row_is_over_rejected() {
    let mut failures = Vec::new();
    for row in load_parity_corpus() {
        if !row.accepted {
            continue;
        }
        let result = compile(&row.source);
        // An official-ACCEPTED input must NEVER receive ANY exact-code official reject (a
        // FABRICATED reject of an input upstream accepts — the parity-bar violation). This is
        // STRICTER than the parser-strictness-only check: an officially-accepted-but-unsupported
        // form (a clean nth-of CSS selector, a TS-grammar script) must fail closed through the
        // unsupported-FEATURE channel, NOT an `OfficialReject` on ANY rail (parser-strictness,
        // style-body-parse, options, …). True for BOTH core and non-core accepts.
        if is_official_reject(&result) {
            failures.push(format!(
                "{}: official ACCEPTS this, but Verter emitted an exact-code OfficialReject — a \
                 fabricated reject of an officially-accepted input (must fail closed as an \
                 unsupported feature instead): {result:?}",
                row.name
            ));
            continue;
        }
        // (Subsumed by the broader check above, but kept as a clearer-message guard for the
        // parser-strictness over-rejection specifically.)
        if is_parser_strictness_refusal(&result) {
            failures.push(format!(
                "{}: official ACCEPTS this, but Verter rejected it as a parser-strictness \
                 (malformed) error — an over-rejection",
                row.name
            ));
            continue;
        }
        if row.core {
            // A §1.2-core accept MUST emit a `Main` — neither over-rejected nor dropped as
            // unsupported. (This is the assertion that catches an accepted-core control
            // silently failing closed, e.g. a non-allowlisted attribute slipping in.)
            if let Err(err) = &result {
                failures.push(format!(
                    "{}: official ACCEPTS this §1.2-core fixture, but Verter did not emit a \
                     Main (refused: {err:?})",
                    row.name
                ));
            }
        }
        // A NON-core accept may emit a `Main` OR fail closed as an unsupported FEATURE —
        // both are fine (only the parser-strictness over-rejection above is forbidden).
    }
    assert!(
        failures.is_empty(),
        "the parse-parity corpus has accepted-row failures (an over-rejection, or a \
         §1.2-core accept that did not emit a Main):\n{}",
        failures.join("\n")
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (3) The "no accepted-invalid leak" property is STRUCTURAL (no allowlist escape hatch).
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn no_rejected_row_leaks_a_main() {
    // The architect's bar, proven STRUCTURALLY (not by a constant): iterate every
    // official-`rejected` fixture and assert NONE emits a `Main`. This is the real
    // "no accepted-invalid" guarantee — it FAILS if a leak is reintroduced (a recovery
    // point that emits a divergent module), with no `KNOWN_ACCEPTED_INVALID` escape hatch.
    let mut leaks = Vec::new();
    let mut rejected_seen = 0usize;
    for row in load_parity_corpus() {
        if row.accepted {
            continue;
        }
        rejected_seen += 1;
        if let Ok(js) = compile(&row.source) {
            leaks.push(format!("{}: leaked a Main:\n{js}", row.name));
        }
    }
    assert!(
        rejected_seen > 0,
        "expected the parse-parity corpus to contain rejected rows"
    );
    assert!(
        leaks.is_empty(),
        "official-rejected fixtures that leaked a Main (no accepted-invalid escape hatch \
         exists):\n{}",
        leaks.join("\n\n")
    );
}

#[test]
fn non_official_reject_exception_rows_are_real_rejected_rows() {
    // Every audited NON_OFFICIAL_REJECT_ROWS entry must name a REAL rejected corpus row
    // (a stale exception that no longer corresponds to a rejected fixture is removed) —
    // the exception list must not silently outlive its row.
    let corpus = load_parity_corpus();
    let mut stale = Vec::new();
    for (name, _reason) in NON_OFFICIAL_REJECT_ROWS {
        let matches = corpus.iter().any(|r| &r.name == name && !r.accepted);
        if !matches {
            stale.push(*name);
        }
    }
    assert!(
        stale.is_empty(),
        "these NON_OFFICIAL_REJECT_ROWS entries are not (rejected) corpus rows — remove \
         them:\n{}",
        stale.join("\n")
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (3b) COVERAGE gate — every REQUIRED finite axis (declared in the generated
//      `manifest.json`'s `required_axes`) is present in at least one committed fixture's
//      `axis` metadata, so the corpus cannot silently lose a finite axis to a hand-audit
//      gap. (The generator also asserts this at write/`--check` time; the Rust gate
//      enforces it on the committed corpus the default hermetic run reads.)
// ─────────────────────────────────────────────────────────────────────────────

/// The `required_axes` string-array from the generated `manifest.json` — the finite-axis
/// coverage contract. Reads the flat `"required_axes": [ "a", "b", … ]` array without a JSON
/// crate (the manifest is a closed, generator-authored object).
fn required_axes_from_manifest() -> Vec<String> {
    let manifest_path = parse_parity_dir().join("manifest.json");
    let text = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest_path.display()));
    let needle = "\"required_axes\"";
    let after_key = &text[text
        .find(needle)
        .unwrap_or_else(|| panic!("manifest.json: missing `required_axes`"))
        + needle.len()..];
    let open = after_key
        .find('[')
        .unwrap_or_else(|| panic!("manifest.json: `required_axes` is not an array"));
    let close = after_key[open..]
        .find(']')
        .unwrap_or_else(|| panic!("manifest.json: `required_axes` array is unterminated"))
        + open;
    after_key[open + 1..close]
        .split(',')
        .map(|s| s.trim().trim_matches('"').to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

#[test]
fn every_required_finite_axis_has_at_least_one_committed_row() {
    let corpus = load_parity_corpus();
    let required = required_axes_from_manifest();
    assert!(
        !required.is_empty(),
        "manifest.json `required_axes` must not be empty — the coverage contract is missing"
    );
    let mut missing = Vec::new();
    for axis in &required {
        let count = corpus.iter().filter(|r| &r.axis == axis).count();
        if count == 0 {
            missing.push(axis.clone());
        }
    }
    assert!(
        missing.is_empty(),
        "these REQUIRED finite axes have NO committed parse-parity rows (a dropped enumerator — \
         the corpus silently lost a finite axis; run \
         `node scripts/gen-svelte-parse-parity-corpus.mjs`):\n{}",
        missing.join("\n")
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// (4) FRESHNESS gate (svelte-oracle) — the pinned compiler STILL yields each row's
//     recorded disposition + official code (the corpus has not drifted).
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(feature = "svelte-oracle")]
mod freshness {
    use super::*;
    use std::collections::BTreeMap;
    use std::process::Command;

    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("crate is <ws>/crates/verter_compiler")
            .to_path_buf()
    }

    /// Re-run the parse-parity generator in `--check` mode through the PINNED compiler.
    /// A zero exit means every committed fixture's disposition + official code is still
    /// byte-identical to a fresh regeneration (so the corpus has not drifted from the
    /// pinned `svelte@5.56.3`). Opting into `--features svelte-oracle` asserts the live
    /// toolchain is present, so a missing / failing node run is a HARD failure (never a
    /// silent skip).
    #[test]
    fn pinned_compiler_still_yields_every_committed_disposition() {
        let root = workspace_root();
        let script = root.join("scripts/gen-svelte-parse-parity-corpus.mjs");
        assert!(
            script.exists(),
            "parse-parity generator missing: {}",
            script.display()
        );
        let output = Command::new("node")
            .arg(&script)
            .arg("--check")
            .current_dir(&root)
            .output()
            .expect("run gen-svelte-parse-parity-corpus.mjs --check (node must be on PATH)");
        assert!(
            output.status.success(),
            "the committed parse-parity corpus drifted from the pinned svelte@5.56.3 \
             compiler:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }

    /// Independently of the generator's `--check`, re-derive each fixture's disposition
    /// directly through the pinned compiler and confirm it matches the committed
    /// metadata (a second, fixture-granular freshness oracle).
    #[test]
    fn pinned_compiler_disposition_matches_each_committed_row() {
        let oracle = run_disposition_oracle();
        let mut wrong = Vec::new();
        for row in load_parity_corpus() {
            let expected = if row.accepted {
                "ACCEPT".to_string()
            } else {
                row.official_code.clone()
            };
            match oracle.get(&row.name) {
                Some(actual) if *actual == expected => {}
                Some(actual) => wrong.push(format!(
                    "{}: committed `{expected}`, but the pinned compiler yields `{actual}`",
                    row.name
                )),
                None => wrong.push(format!(
                    "{}: no oracle outcome (corpus/oracle mismatch)",
                    row.name
                )),
            }
        }
        assert!(
            wrong.is_empty(),
            "parse-parity rows that drifted from the pinned svelte@5.56.3 compiler:\n{}",
            wrong.join("\n")
        );
    }

    /// Compile every committed `.svelte` fixture through the pinned compiler via the
    /// reject oracle's sibling disposition script, returning `{ name → code | "ACCEPT" }`.
    fn run_disposition_oracle() -> BTreeMap<String, String> {
        let root = workspace_root();
        let script = root.join("scripts/svelte-parse-parity-oracle.mjs");
        assert!(
            script.exists(),
            "parse-parity oracle missing: {}",
            script.display()
        );
        let output = Command::new("node")
            .arg(&script)
            .current_dir(&root)
            .output()
            .expect(
                "run svelte-parse-parity-oracle.mjs (node must be on PATH under svelte-oracle)",
            );
        assert!(
            output.status.success(),
            "svelte-parse-parity-oracle.mjs failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        let stdout = String::from_utf8(output.stdout).expect("oracle stdout is utf8");
        parse_oracle_json(&stdout)
    }

    /// Parse the oracle's flat `{ "name": "code" }` JSON object (no JSON crate).
    fn parse_oracle_json(text: &str) -> BTreeMap<String, String> {
        let mut map = BTreeMap::new();
        let body = text
            .trim()
            .trim_start_matches('{')
            .trim_end_matches('}')
            .trim();
        if body.is_empty() {
            return map;
        }
        for entry in body.split(",\n") {
            let entry = entry.trim().trim_end_matches(',');
            if entry.is_empty() {
                continue;
            }
            let (k, v) = entry.split_once(':').expect("oracle entry has a colon");
            let key = k.trim().trim_matches('"').to_string();
            let val = v.trim().trim_matches('"').to_string();
            map.insert(key, val);
        }
        map
    }
}
