/**
 * Route-specific product gaps observed in the last full pre-repair matrix
 * (GitHub Actions run 33338079553).
 *
 * This is intentionally static and exact: a newly failing row, a changed issue
 * classification, or a gap on a different provider route remains fatal. Passing
 * rows do not have to keep failing. The confidence invalidation row is omitted
 * deliberately because it is a regression sentinel, not an accepted gap.
 */

export type ProductGapManifest = Readonly<Record<string, string>>;

const KNOWN_PRODUCT_GAPS_BY_ROUTE: Readonly<Record<string, ProductGapManifest>> = {
  "ecosystem-parity@shared-tsgo": {
    "eco.svelte.lib-alias.hover": "ISSUE-eco-svelte-lib-hover",
  },
  "ecosystem-parity@tsgo": {},
  "ecosystem-parity@tsserver": {},
  "mixed-parity@shared-tsgo": {
    "mixed.cross-import.vue-imports-svelte": "ISSUE-mixed-cross-import",
    "mixed.svelte.root.hover": "ISSUE-mixed-svelte-hover",
    "mixed.vue.entry.clean": "ISSUE-mixed-vue-entry",
  },
  "mixed-parity@tsgo": {
    "mixed.cross-import.vue-imports-svelte": "ISSUE-mixed-cross-import",
    "mixed.vue.entry.clean": "ISSUE-mixed-vue-entry",
  },
  "mixed-parity@tsserver": {
    "mixed.cross-import.vue-imports-svelte": "ISSUE-mixed-cross-import",
    "mixed.svelte.root.hover": "ISSUE-mixed-svelte-hover",
    "mixed.vue.entry.clean": "ISSUE-mixed-vue-entry",
  },
  "multi-root-parity@shared-tsgo": {},
  "multi-root-parity@tsgo": {},
  "multi-root-parity@tsserver": {},
  "svelte-parity@shared-tsgo": {
    "confidence.multi-file.open.definitions-authored": "ISSUE-svelte-confidence-multi-file",
    "depth.mapping.event-handler-hover-range": "ISSUE-depth-mapping-event",
    "depth.mapping.slot-prop-hover-range": "ISSUE-depth-mapping-slot",
    "depth.rename.script-and-markup.min-two-edits": "ISSUE-depth-rename-apply",
    "generic.event-handler.infers-from-options": "ISSUE-svelte-generic-event-infer",
    "generic.expect-error.structural": "ISSUE-svelte-generic-expect-error",
    "generic.hover.event-payload-matches-options": "ISSUE-svelte-generic-hover-event",
    "generic.hover.field-multi-prop-number-chain": "ISSUE-svelte-generic-hover-field",
    "generic.hover.slot-prop-inferred-number": "ISSUE-svelte-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-svelte-generic-hover-slot-str",
    "generic.infer.bad-mismatched-props-events": "ISSUE-svelte-generic-infer-bad",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-svelte-generic-multi-prop",
    "generic.slot.wrong-method-on-inferred-type": "ISSUE-svelte-generic-slot-wrong",
    "ide.def.event-attr-to-handler": "ISSUE-svelte-ide-def-event",
    "ide.def.event-name-to-emit-or-prop": "ISSUE-svelte-ide-def-event-name",
    "ide.def.prop-attr-to-child": "ISSUE-svelte-ide-def-prop-attr",
    "ide.def.slot-name": "ISSUE-svelte-ide-def-slot-name",
    "ide.def.slot-prop": "ISSUE-svelte-ide-def-slot-prop",
    "ide.hover.directive-doc": "ISSUE-svelte-ide-hover-directive-doc",
    "ide.hover.slot-name": "ISSUE-svelte-ide-hover-slot-name",
    "ide.hover.slot-prop-pattern": "ISSUE-svelte-ide-hover-slot-prop-pattern",
    "intrinsic.clean-diagnostics": "ISSUE-svelte-intrinsic-elements-clean",
    "intrinsic.tag-hover.div-is-concrete-interface": "ISSUE-svelte-intrinsic-element-hover",
    "intrinsic.type-definition.div-not-any": "ISSUE-svelte-intrinsic-type-definition",
    "js.wrong-prop-type.errors": "ISSUE-svelte-js-wrong-prop",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "lsp.type-definition.binding": "ISSUE-lsp-type-definition",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "shared.document-symbols.present": "ISSUE-shared-document-symbols",
    "shared.find.definition-then-refs-consistency": "ISSUE-find-def-refs-consistency",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.js-jsdoc.dom-event.member-definition": "ISSUE-js-dom-event-jsdoc",
    "shared.js-jsdoc.dom-event.parameter-hover-concrete": "ISSUE-js-dom-event-jsdoc",
    "shared.js-lax.dom-event.unannotated-remains-any": "ISSUE-js-lax-dom-event-non-inference",
    "shared.js.dom-event.classic-or-legacy-not-contextual":
      "ISSUE-dom-event-over-inference-boundary",
    "shared.js.dom-event.unannotated-checked-remains-any": "ISSUE-js-dom-event-non-inference",
    "shared.js.hover.typed-markup": "ISSUE-js-hover-markup",
    "shared.js.references.script-and-markup": "ISSUE-js-references",
    "shared.js.rename.from-markup": "ISSUE-js-rename-markup",
    "shared.js.rename.from-script": "ISSUE-js-rename-script",
    "shared.lifecycle.external-ts-create-delete": "ISSUE-lifecycle-external-ts",
    "shared.mapping.hover-range.template-binding": "ISSUE-mapping-hover-range-template",
    "shared.mapping.hover-range.template-member": "ISSUE-mapping-hover-range-member",
    "shared.perf.hover.warm-budget": "ISSUE-perf-hover",
    "shared.rename.from-markup.applies": "ISSUE-shared-rename-from-markup",
    "shared.rename.from-script.applies": "ISSUE-shared-rename-apply",
    "shared.style.id.references": "ISSUE-style-id-references",
    "shared.ts.dom-event.classic-or-legacy-not-contextual":
      "ISSUE-dom-event-over-inference-boundary",
    "shared.ts.dom-event.member-definition": "ISSUE-ts-dom-event-definition",
    "shared.ts.dom-event.parameter-hover-concrete": "ISSUE-ts-dom-event-hover",
    "shared.ts.rename.from-script": "ISSUE-ts-rename-script",
    "shared.typing.definition-after-newline-insert": "ISSUE-typing-definition-after-edit",
    "shared.typing.hover-survives-edit-storm": "ISSUE-typing-hover-after-edit",
    "shared.typing.rapid-toggle-save-dirty": "ISSUE-typing-rapid-edit",
    "shared.typing.recovery-after-broken-expression": "ISSUE-typing-recovery",
    "shared.typing.undo-preserves-hover": "ISSUE-typing-undo",
    "slots.local.definition-to-destructure": "ISSUE-svelte-slots-local-def",
    "slots.local.hover-typed": "ISSUE-svelte-slots-local-hover",
    "svelte.control.each-item-hover": "ISSUE-svelte-each-hover",
    "svelte.control.if-branch": "ISSUE-svelte-if-narrowing",
    "svelte.definition.child-prop-attr": "ISSUE-svelte-prop-attr-definition",
    "svelte.definition.markup-to-script": "ISSUE-svelte-markup-definition",
    "svelte.diagnostic.state-interpolation-clean": "ISSUE-svelte-state-interpolation-diagnostic",
    "svelte.feature.await.then-hover": "ISSUE-svelte-await",
    "svelte.feature.bind-value.definition": "ISSUE-svelte-bind-value",
    "svelte.feature.bind-value.hover": "ISSUE-svelte-bind-value-hover",
    "svelte.feature.effect.clean": "ISSUE-svelte-effect",
    "svelte.feature.snippet.param-hover": "ISSUE-svelte-snippet",
    "svelte.hover.child-prop-attr": "ISSUE-svelte-prop-attr-hover",
    "svelte.hover.typed-markup": "ISSUE-svelte-markup-hover",
    "svelte.intellisense.if.narrowing.hover": "ISSUE-svelte-if-narrowing-intellisense",
    "svelte.intrinsic.button-type-literal-clean": "ISSUE-svelte-button-type-literal",
    "svelte.public-surface.no-secret-internal-on-component-hover":
      "ISSUE-svelte-public-surface-leak",
    "svelte.runes.derived-hover": "ISSUE-svelte-derived-hover",
    "svelte.runes.state-hover": "ISSUE-svelte-state-hover",
    "svelte.ts.dom-event.button-current-target": "ISSUE-svelte-dom-event-current-target",
    "testing-api.svelte.no-testing-virtual-and-spec-stays-public":
      "ISSUE-svelte-testing-api-no-virtual",
    "testing-api.svelte.spec-and-public-same-isolation": "ISSUE-svelte-testing-api-isolation",
  },
  "svelte-parity@tsgo": {
    "depth.rename.script-and-markup.min-two-edits": "ISSUE-depth-rename-apply",
    "generic.event-handler.infers-from-options": "ISSUE-svelte-generic-event-infer",
    "generic.expect-error.structural": "ISSUE-svelte-generic-expect-error",
    "generic.hover.slot-prop-inferred-number": "ISSUE-svelte-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-svelte-generic-hover-slot-str",
    "generic.infer.bad-mismatched-props-events": "ISSUE-svelte-generic-infer-bad",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-svelte-generic-multi-prop",
    "generic.slot.wrong-method-on-inferred-type": "ISSUE-svelte-generic-slot-wrong",
    "intrinsic.clean-diagnostics": "ISSUE-svelte-intrinsic-elements-clean",
    "intrinsic.type-definition.div-not-any": "ISSUE-svelte-intrinsic-type-definition",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.document-highlights.binding": "ISSUE-lsp-document-highlights",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "shared.find.definition-then-refs-consistency": "ISSUE-find-def-refs-consistency",
    "shared.find.function.cross-region": "ISSUE-find-function",
    "shared.find.js.exact-min-set": "ISSUE-find-js-exact",
    "shared.find.ts.exact-min-set": "ISSUE-find-ts-exact",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.js.references.script-and-markup": "ISSUE-js-references",
    "shared.js.rename.from-markup": "ISSUE-js-rename-markup",
    "shared.js.rename.from-script": "ISSUE-js-rename-script",
    "shared.lifecycle.external-ts-create-delete": "ISSUE-lifecycle-external-ts",
    "shared.rename.from-markup.applies": "ISSUE-shared-rename-from-markup",
    "shared.rename.from-script.applies": "ISSUE-shared-rename-apply",
    "shared.rename.js.function": "ISSUE-rename-js-function",
    "shared.rename.ts.markup-origin": "ISSUE-rename-ts-markup",
    "shared.style.id.references": "ISSUE-style-id-references",
    "shared.ts.rename.from-script": "ISSUE-ts-rename-script",
    "shared.workspace-symbols.find-binding": "ISSUE-shared-workspace-symbols",
    "svelte.matrix.directives.style-color.hover": "ISSUE-svelte-matrix-style-color",
    "svelte.matrix.events.handler.def": "ISSUE-svelte-matrix-events-handler",
    "svelte.matrix.js.refs": "ISSUE-svelte-matrix-js-refs",
    "svelte.matrix.mapping.clean": "ISSUE-svelte-matrix-mapping-clean",
    "svelte.matrix.strict-rest.clean": "ISSUE-svelte-matrix-strict-rest-clean",
    "svelte.references.script-and-markup": "ISSUE-svelte-references",
    "strict.svelte.rest-props-opt-in": "ISSUE-svelte-strict-rest-props",
    "svelte.control.each-item-hover": "ISSUE-svelte-each-hover",
    "svelte.control.if-branch": "ISSUE-svelte-if-narrowing",
    "svelte.definition.child-prop-attr": "ISSUE-svelte-prop-attr-definition",
    "svelte.intrinsic.button-type-literal-clean": "ISSUE-svelte-button-type-literal",
  },
  "svelte-parity@tsserver": {
    "depth.rename.script-and-markup.min-two-edits": "ISSUE-depth-rename-apply",
    "generic.defaulted-t-string.no-annotation": "ISSUE-svelte-generic-default",
    "generic.event-handler.infers-from-options": "ISSUE-svelte-generic-event-infer",
    "generic.expect-error.structural": "ISSUE-svelte-generic-expect-error",
    "generic.hover.slot-prop-inferred-number": "ISSUE-svelte-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-svelte-generic-hover-slot-str",
    "generic.infer.bad-mismatched-props-events": "ISSUE-svelte-generic-infer-bad",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-svelte-generic-multi-prop",
    "generic.slot.wrong-method-on-inferred-type": "ISSUE-svelte-generic-slot-wrong",
    "intrinsic.type-definition.div-not-any": "ISSUE-svelte-intrinsic-type-definition",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "shared.find.ts.exact-min-set": "ISSUE-find-ts-exact",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.style.id.references": "ISSUE-style-id-references",
    "shared.ts.dom-event.classic-or-legacy-not-contextual":
      "ISSUE-dom-event-over-inference-boundary",
    "shared.workspace-symbols.find-binding": "ISSUE-shared-workspace-symbols",
    "svelte.matrix.directives.style-color.hover": "ISSUE-svelte-matrix-style-color",
    "svelte.matrix.events.handler.def": "ISSUE-svelte-matrix-events-handler",
    "svelte.matrix.js.refs": "ISSUE-svelte-matrix-js-refs",
    "svelte.control.each-item-hover": "ISSUE-svelte-each-hover",
    "svelte.control.if-branch": "ISSUE-svelte-if-narrowing",
    "svelte.definition.child-prop-attr": "ISSUE-svelte-prop-attr-definition",
  },
  "vue-parity@shared-tsgo": {
    "confidence.cross-file.wrong-prop-type": "ISSUE-vue-confidence-cross-file",
    "confidence.definition.never-virtual-for-daily-and-strict": "ISSUE-vue-confidence-no-virtual",
    "confidence.generic-list.wrong-selected-id": "ISSUE-vue-confidence-generic",
    "depth.mapping.slot-prop-hover-range": "ISSUE-depth-mapping-slot",
    "generic.event-handler.infers-from-options": "ISSUE-vue-generic-event-infer",
    "generic.expect-error.structural": "ISSUE-vue-generic-expect-error",
    "generic.hover.event-payload-matches-options": "ISSUE-vue-generic-hover-event",
    "generic.hover.field-multi-prop-number-chain": "ISSUE-vue-generic-hover-field",
    "generic.hover.slot-prop-inferred-number": "ISSUE-vue-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-vue-generic-hover-slot-str",
    "generic.infer.bad-mismatched-props-events": "ISSUE-vue-generic-infer-bad",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-vue-generic-multi-prop",
    "generic.slot.wrong-method-on-inferred-type": "ISSUE-vue-generic-slot-wrong",
    "ide.def.slot-prop": "ISSUE-vue-ide-def-slot-prop",
    "ide.hover.slot-prop-pattern": "ISSUE-vue-ide-hover-slot-prop-pattern",
    "intrinsic.tag-hover.div-is-concrete-interface": "ISSUE-vue-intrinsic-element-hover",
    "intrinsic.type-definition.div-not-any": "ISSUE-vue-intrinsic-type-definition",
    "js.wrong-prop-type.errors": "ISSUE-vue-js-wrong-prop",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "lsp.type-definition.binding": "ISSUE-lsp-type-definition",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "shared.code-action.apply.organize-imports": "ISSUE-code-action-apply-organize",
    "shared.code-action.organize-imports-available": "ISSUE-product-organize-imports",
    "shared.document-symbols.present": "ISSUE-shared-document-symbols",
    "shared.find.definition-then-refs-consistency": "ISSUE-find-def-refs-consistency",
    "shared.find.function.cross-region": "ISSUE-find-function",
    "shared.find.js.exact-min-set": "ISSUE-find-js-exact",
    "shared.find.ts.exact-min-set": "ISSUE-find-ts-exact",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.js-jsdoc.dom-event.member-definition": "ISSUE-js-dom-event-jsdoc",
    "shared.js-jsdoc.dom-event.parameter-hover-concrete": "ISSUE-js-dom-event-jsdoc",
    "shared.js-lax.dom-event.unannotated-remains-any": "ISSUE-js-lax-dom-event-non-inference",
    "shared.js.dom-event.classic-or-legacy-not-contextual":
      "ISSUE-dom-event-over-inference-boundary",
    "shared.js.dom-event.unannotated-checked-remains-any": "ISSUE-js-dom-event-non-inference",
    "shared.js.hover.typed-markup": "ISSUE-js-hover-markup",
    "shared.js.references.script-and-markup": "ISSUE-js-references",
    "shared.js.rename.from-markup": "ISSUE-js-rename-markup",
    "shared.js.rename.from-script": "ISSUE-js-rename-script",
    "shared.lifecycle.external-ts-create-delete": "ISSUE-lifecycle-external-ts",
    "shared.mapping.hover-range.template-member": "ISSUE-mapping-hover-range-member",
    "shared.rename.from-markup.applies": "ISSUE-shared-rename-from-markup",
    "shared.rename.from-script.applies": "ISSUE-shared-rename-apply",
    "shared.rename.js.function": "ISSUE-rename-js-function",
    "shared.rename.ts.markup-origin": "ISSUE-rename-ts-markup",
    "shared.style.id.references": "ISSUE-style-id-references",
    "shared.ts.dom-event.classic-or-legacy-not-contextual":
      "ISSUE-dom-event-over-inference-boundary",
    "shared.ts.dom-event.member-definition": "ISSUE-ts-dom-event-definition",
    "shared.ts.dom-event.parameter-hover-concrete": "ISSUE-ts-dom-event-hover",
    "shared.ts.rename.from-script": "ISSUE-ts-rename-script",
    "slots.expect-error.structural": "ISSUE-vue-slots-expect-error",
    "slots.local.definition-to-destructure": "ISSUE-vue-slots-local-def",
    "slots.local.hover-typed": "ISSUE-vue-slots-local-hover",
    "slots.matrix-positive.legacy-hover": "ISSUE-vue-matrix-slots-clean",
    "slots.wrong-names-or-missing-bindings.errors": "ISSUE-vue-slots-wrong-names",
    "slots.wrong-prop-usage.errors": "ISSUE-vue-slots-wrong-props",
    "strict.unknown-prop.must-fail": "ISSUE-vue-strict-unknown-prop",
    "strict.vue.fragment-unknown-flagged": "ISSUE-vue-fragment-fallthrough",
    "testing-api.vue.spec-sees-setup-bindings": "ISSUE-vue-testing-api-spec-bindings",
    "testing-api.vue.spec-vs-public-diagnostic-split": "ISSUE-vue-testing-api-diagnostic-split",
    "type-neg.expect-error.props-and-handlers": "ISSUE-vue-type-neg-expect-error",
    "type-neg.legacy.bad-prop-parent-still-errors": "ISSUE-vue-bad-prop-diagnostic",
    "type-neg.live.wrong-directive-or-attr-types": "ISSUE-vue-type-neg-directives",
    "type-neg.live.wrong-event-handlers": "ISSUE-vue-type-neg-events",
    "type-neg.live.wrong-prop-types": "ISSUE-vue-type-neg-props",
    "vue.control.v-for-item-hover": "ISSUE-vue-vfor-hover",
    "vue.control.v-if-narrowing": "ISSUE-vue-vif-narrowing",
    "vue.diagnostics.bad-prop-type": "ISSUE-vue-bad-prop-diagnostic",
    "vue.diagnostics.unresolved-markup-name": "ISSUE-vue-markup-unresolved",
    "vue.fallthrough.fragment-extra-flagged": "ISSUE-vue-fragment-fallthrough",
    "vue.feature.define-expose.clean": "ISSUE-vue-define-expose",
    "vue.feature.dual-script.hover": "ISSUE-vue-dual-script",
    "vue.feature.options-api.hover": "ISSUE-vue-options-api",
    "vue.generic.prop-type-param": "ISSUE-vue-generic-sfc",
    "vue.intellisense.v-if.narrowing.hover": "ISSUE-vue-vif-narrowing-intellisense",
    "vue.macro.defineEmits.event-attr": "ISSUE-vue-defineEmits-event-hover",
    "vue.macro.defineModel.named": "ISSUE-vue-defineModel-navigation",
    "vue.macro.defineProps.hover": "ISSUE-vue-defineProps-hover",
    "vue.macro.defineSlots.slot-local": "ISSUE-vue-defineSlots-locals",
    "vue.macro.withDefaults.optional-prop": "ISSUE-vue-withDefaults",
  },
  "vue-parity@tsgo": {
    "confidence.cross-file.wrong-prop-type": "ISSUE-vue-confidence-cross-file",
    "confidence.definition.never-virtual-for-daily-and-strict": "ISSUE-vue-confidence-no-virtual",
    "confidence.generic-list.wrong-selected-id": "ISSUE-vue-confidence-generic",
    "generic.event-handler.infers-from-options": "ISSUE-vue-generic-event-infer",
    "generic.expect-error.structural": "ISSUE-vue-generic-expect-error",
    "generic.hover.field-multi-prop-number-chain": "ISSUE-vue-generic-hover-field",
    "generic.hover.slot-prop-inferred-number": "ISSUE-vue-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-vue-generic-hover-slot-str",
    "generic.infer.bad-mismatched-props-events": "ISSUE-vue-generic-infer-bad",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-vue-generic-multi-prop",
    "generic.slot.wrong-method-on-inferred-type": "ISSUE-vue-generic-slot-wrong",
    "intrinsic.type-definition.div-not-any": "ISSUE-vue-intrinsic-type-definition",
    "js.wrong-prop-type.errors": "ISSUE-vue-js-wrong-prop",
    "vue.matrix.js.refs.bump": "ISSUE-vue-matrix-js-refs",
    "vue.matrix.style-bind.accent.def": "ISSUE-vue-matrix-style-bind-def",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "shared.code-action.apply.organize-imports": "ISSUE-code-action-apply-organize",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.lifecycle.external-ts-create-delete": "ISSUE-lifecycle-external-ts",
    "shared.rename.from-markup.applies": "ISSUE-shared-rename-from-markup",
    "shared.rename.from-script.applies": "ISSUE-shared-rename-apply",
    "shared.style.id.references": "ISSUE-style-id-references",
    "shared.workspace-symbols.find-binding": "ISSUE-shared-workspace-symbols",
    "slots.wrong-names-or-missing-bindings.errors": "ISSUE-vue-slots-wrong-names",
    "slots.wrong-prop-usage.errors": "ISSUE-vue-slots-wrong-props",
    "strict.unknown-prop.must-fail": "ISSUE-vue-strict-unknown-prop",
    "strict.vue.fragment-unknown-flagged": "ISSUE-vue-fragment-fallthrough",
    "testing-api.vue.spec-sees-setup-bindings": "ISSUE-vue-testing-api-spec-bindings",
    "testing-api.vue.spec-vs-public-diagnostic-split": "ISSUE-vue-testing-api-diagnostic-split",
    "type-neg.legacy.bad-prop-parent-still-errors": "ISSUE-vue-bad-prop-diagnostic",
    "type-neg.live.wrong-directive-or-attr-types": "ISSUE-vue-type-neg-directives",
    "type-neg.live.wrong-event-handlers": "ISSUE-vue-type-neg-events",
    "type-neg.live.wrong-prop-types": "ISSUE-vue-type-neg-props",
    "vue.diagnostics.bad-prop-type": "ISSUE-vue-bad-prop-diagnostic",
    "vue.diagnostics.unresolved-markup-name": "ISSUE-vue-markup-unresolved",
    "vue.fallthrough.fragment-extra-flagged": "ISSUE-vue-fragment-fallthrough",
    "vue.macro.defineModel.named": "ISSUE-vue-defineModel-navigation",
  },
  "vue-parity@tsserver": {
    "confidence.definition.never-virtual-for-daily-and-strict": "ISSUE-vue-confidence-no-virtual",
    "depth.mapping.slot-prop-hover-range": "ISSUE-depth-mapping-slot",
    "generic.defaulted-t-string.no-annotation": "ISSUE-vue-generic-default",
    "generic.expect-error.structural": "ISSUE-vue-generic-expect-error",
    "generic.hover.field-multi-prop-number-chain": "ISSUE-vue-generic-hover-field",
    "generic.hover.slot-prop-inferred-number": "ISSUE-vue-generic-hover-slot-num",
    "generic.hover.slot-prop-inferred-string": "ISSUE-vue-generic-hover-slot-str",
    "generic.multi-prop-linkage.field-format-change": "ISSUE-vue-generic-multi-prop",
    "ide.auto-import.symbol-accept": "ISSUE-vue-symbol-auto-import",
    "intrinsic.type-definition.div-not-any": "ISSUE-vue-intrinsic-type-definition",
    "lsp.document-format.carrier": "ISSUE-lsp-document-format",
    "lsp.semantic-tokens.kinds": "ISSUE-lsp-semantic-tokens",
    "lsp.signature-help.script-call": "ISSUE-lsp-signature-help",
    "product.extract-component.command": "ISSUE-product-extract-component",
    "vue.matrix.js.refs.bump": "ISSUE-vue-matrix-js-refs",
    "vue.matrix.style-bind.accent.def": "ISSUE-vue-matrix-style-bind-def",
    "shared.code-action.apply.organize-imports": "ISSUE-code-action-apply-organize",
    "shared.inlay-hints.script-region": "ISSUE-product-inlay-hints",
    "shared.workspace-symbols.find-binding": "ISSUE-shared-workspace-symbols",
    "strict.vue.fragment-unknown-flagged": "ISSUE-vue-fragment-fallthrough",
    "testing-api.vue.spec-sees-setup-bindings": "ISSUE-vue-testing-api-spec-bindings",
    "testing-api.vue.spec-vs-public-diagnostic-split": "ISSUE-vue-testing-api-diagnostic-split",
    "vue.fallthrough.fragment-extra-flagged": "ISSUE-vue-fragment-fallthrough",
    "vue.intellisense.symbol.auto-import-accept": "ISSUE-vue-symbol-auto-import",
    "vue.macro.defineModel.named": "ISSUE-vue-defineModel-navigation",
  },
};

export function knownProductGapsForRoute(
  fixture: string,
  typeProvider: string,
  requiredTestIds?: readonly string[],
): ProductGapManifest {
  const gaps = KNOWN_PRODUCT_GAPS_BY_ROUTE[`${fixture}@${typeProvider}`] ?? {};
  if (!requiredTestIds) return gaps;
  const required = new Set(requiredTestIds);
  return Object.fromEntries(Object.entries(gaps).filter(([id]) => required.has(id)));
}

export const KNOWN_PRODUCT_GAP_ROUTE_KEYS = Object.freeze(
  Object.keys(KNOWN_PRODUCT_GAPS_BY_ROUTE).sort(),
);
