import {
  CallHierarchyIncomingCall,
  CallHierarchyItem,
  CallHierarchyOutgoingCall,
  CancellationToken,
  CodeAction,
  CodeActionContext,
  Color,
  ColorInformation,
  ColorPresentation,
  CompletionContext,
  CompletionItem,
  CompletionList,
  DefinitionLink,
  Diagnostic,
  FoldingRange,
  FormattingOptions,
  Hover,
  LinkedEditingRanges,
  Location,
  Position,
  Range,
  ReferenceContext,
  SelectionRange,
  SemanticTokens,
  SignatureHelp,
  SignatureHelpContext,
  SymbolInformation,
  TextDocumentContentChangeEvent,
  TextDocumentIdentifier,
  TextEdit,
  WorkspaceEdit,
  InlayHint,
} from "vscode-languageserver";
import { performance } from "node:perf_hooks";

export class PluginHost implements LSProvider, OnWatchFileChanges {}
