// THE U6 flow-return shape corpus table.
//
// APPEND-ONLY. Adding a shape is ONE `Row` literal appended here; every
// lane is driven from it by the shared drivers in the parent module.
// Nothing else in the tree changes.
//
// The `checker` column is what tsgo 7.0.0-dev.20260526.1 prints for the
// row's `probe` under `--noEmit --strict --ignoreConfig`; it is verified
// live by `corpus_checker_column_matches_tsgo` whenever the pinned binary
// is resolvable.

/// THE corpus.
pub(crate) const CORPUS: &[Row] = &[

    // ── A: structural spread ─────────────────────────────────────────
    Row { id: "A01_spread_call_key", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A02_spread_only", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A03_two_spreads", script: "function a() { return { label: \"x\" } }\nfunction b() { return { n: 1 } }\nfunction makeProps() { return { ...a(), ...b() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A04_arrow_const_spread", script: "const arrowConst = () => ({ label: \"x\" })\nfunction makeProps() { return { ...arrowConst(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A05_module_const_spread", script: "const mc = { label: \"x\" }\nfunction makeProps() { return { ...mc, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A06_plain_literal", script: "function makeProps() { return { label: \"x\", n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A07_nested_spread", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { a: { ...base() }, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ a: { label: string; }; n: number; }", runtime: Runtime::Emitted { has: &["a: { type: Object", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("a", NodeShape::ObjectSpreadProgram), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["a", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A08_cross_file_spread", aux: "export function base() { return { label: \"x\" } }\n", script: "import { base } from \"./A08_cross_file_spread__aux\"\nfunction makeProps() { return { ...base(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A09_iife_spread", script: "function makeProps() { return { ...(() => ({ label: \"x\" }))(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A10_spread_literal_arm", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), ...{ n: 1 } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A11_spread_empty_literal", script: "function makeProps() { return { ...{}, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ n: number; }", runtime: Runtime::Emitted { has: &["n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // Key OVERRIDE, spread FIRST: the later literal key wins (`label: number`).
    Row { id: "A12_override_after", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), label: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: number; }", runtime: Runtime::Emitted { has: &["label: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // Key OVERRIDE, spread LAST: the SPREAD wins (`label: string`); tsgo also reports TS2783 on the shadowed literal key.
    Row { id: "A13_override_before", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { label: 1, ...base() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // Two spreads, same key: the LAST spread wins.
    Row { id: "A14_two_spreads_same_key", script: "function a() { return { label: \"x\" } }\nfunction b() { return { label: 1 } }\nfunction makeProps() { return { ...a(), ...b() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: number; }", runtime: Runtime::Emitted { has: &["label: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // A method member rides the spread program as a Function-constructor prop.
    Row { id: "A15_method_member", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), m() { return 1 } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; m(): number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "m: { type: Function"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "m"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // A GETTER member publishes its RETURN type (`g: number`), not an accessor shell.
    Row { id: "A16_getter_member", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), get g() { return 1 } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; g: number; }", runtime: Runtime::Emitted { has: &["g: { type: Number", "label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["g", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A17_param_spread", script: "function makeProps(p: { label: string }) { return { ...p, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "A18_local_const_spread", script: "function makeProps() { const lc = { label: \"x\" }; return { ...lc, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── B: leaf-fallback spread (call-sourced vs identifier-sourced) ──
    // A COMPUTED key beside a CALL-sourced spread lowers as its own value position: the whole surface publishes, matching the IDENTIFIER-sourced twin B07_computed_after_ident.
    Row { id: "B01_computed_after_call", script: "const k = \"c\"\nfunction base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), [k]: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; c: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["c: { type: Number", "label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["c", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // KNOWN OWED — the module publishes now, but the NUMERIC literal key is still dropped. Identical residue to the identifier-sourced twin B09_numeric_key_ident.
    Row { id: "B02_numeric_key_after_call", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), 1: 2 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; 1: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::KnownOwed { owed_absent: &["1: {"], note: "The module is no longer refused — the CALL-sourced spread contributes and the surface publishes — but the NUMERIC literal key is still SILENTLY DROPPED: `{ label }` for a checker type of `{ label: string; 1: number }`. The IDENTIFIER-sourced twin B09_numeric_key_ident drops it identically, so what remains owed is the numeric-key SPELLING, not the callee source." }, ..Row::BLANK },
    // `as const` over a CALL-sourced spread publishes the same surface as the IDENTIFIER-sourced twin B10_as_const_ident. NOTE: no lane in this corpus observes `readonly` or literal preservation — a Vue props option, a spread-program graph node and a Svelte prop-name set can express neither — so agreement here is over the MEMBER SET and the CONSTRUCTORS. The unpicked-up `readonly` on a spread-contributed member under a const assertion is real and is invisible to every column this row drives.
    Row { id: "B03_as_const_call", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), n: 1 } as const }", probe: "ReturnType<typeof makeProps>", checker: "{ readonly label: string; readonly n: 1; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `as const` over a CALL-sourced spread-only literal publishes its member set. Same `readonly` caveat as B03_as_const_call.
    Row { id: "B04_as_const_spread_only", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base() } as const }", probe: "ReturnType<typeof makeProps>", checker: "{ readonly label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `satisfies object` over a CALL-sourced spread contributes a member policy instead of swallowing the literal: the surface publishes and the non-contextual target leaves `n` widened, exactly as the checker types it.
    Row { id: "B05_satisfies_object", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), n: 1 } satisfies object }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // A COMPUTED key after TWO CALL-sourced spreads: both spread arms and the computed key survive into the published surface.
    Row { id: "B06_two_calls_computed", script: "const k = \"c\"\nfunction base() { return { label: \"x\" } }\nfunction b2() { return { m: true } }\nfunction makeProps() { return { ...base(), ...b2(), [k]: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; m: boolean; c: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["c: { type: Number", "label: { type: String", "m: { type: Boolean"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["c", "label", "m"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // The IDENTIFIER-sourced twin of B01_computed_after_call. It was the row that proved the refusal was callee-source-specific rather than an unknowable key domain, and both spellings now publish the same shape.
    Row { id: "B07_computed_after_ident", script: "const k = \"c\"\nconst mc = { label: \"x\" }\nfunction makeProps() { return { ...mc, [k]: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; c: number; }", runtime: Runtime::Emitted { has: &["c: { type: Number", "label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["c", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // The computed key BEFORE an identifier-sourced spread — the ordering twin of B07_computed_after_ident.
    Row { id: "B08_computed_before_ident", script: "const k = \"c\"\nconst mc = { label: \"x\" }\nfunction makeProps() { return { [k]: 1, ...mc } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; c: number; }", runtime: Runtime::Emitted { has: &["c: { type: Number", "label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["c", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // KNOWN OWED — a numeric literal key is dropped from the published surface. The CALL-sourced twin B02_numeric_key_after_call now drops it identically.
    Row { id: "B09_numeric_key_ident", script: "const mc = { label: \"x\" }\nfunction makeProps() { return { ...mc, 1: 2 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; 1: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::KnownOwed { owed_absent: &["1: {"], note: "A NUMERIC literal key beside an identifier-sourced spread is SILENTLY DROPPED (`{ label }` for a checker type of `{ label: string; 1: number }`) — a missing declared prop, not a conservative answer." }, ..Row::BLANK },
    // The IDENTIFIER-sourced twin of B03_as_const_call — both spellings publish the same member set, with the same `readonly`/literal blind spot in every lane.
    Row { id: "B10_as_const_ident", script: "const mc = { label: \"x\" }\nfunction makeProps() { return { ...mc, n: 1 } as const }", probe: "ReturnType<typeof makeProps>", checker: "{ readonly label: string; readonly n: 1; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── C: intersection / heritage ───────────────────────────────────
    // The clean-helper control for the intersection family.
    Row { id: "C01_intersection_clean", script: "function makeProps() { return { label: \"x\" } }", macro_call: "defineProps<ReturnType<typeof makeProps> & { extra: string }>()", probe: "ReturnType<typeof makeProps> & { extra: string }", checker: "{ label: string; } & { extra: string; }", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["label: { type: String", "extra: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["extra", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // A degraded MEMBER inside an intersection arm: the member set is complete and one member's type is erased. This is the CORRECT degraded shape — contrast C11_props_intersection_unmodelled_arm, where a whole unmodelled ARM is silently dropped.
    Row { id: "C02_intersection_degraded", script: "class Box { readonly tag = \"box\" }\nfunction makeProps() { const f = () => new Box(); return { label: \"x\", made: f() } }", macro_call: "defineProps<ReturnType<typeof makeProps> & { extra: string }>()", probe: "ReturnType<typeof makeProps> & { extra: string }", checker: "{ label: string; made: Box; } & { extra: string; }", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["label: { type: String", "made: { type: null", "extra: { type: String"], hasnt: &["label: { type: null", "extra: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("made", NodeShape::OpaqueUnmodeledPosition)], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["extra", "label", "made"]), verdict: Verdict::Degraded("the unmodelled MEMBER publishes the typed marker (`type: null`); every sibling stays exact"), ..Row::BLANK },
    // The clean-helper control for the emits intersection.
    Row { id: "C03_emits_intersection_clean", script: "function makeEmits() { return { evA: (p: string) => true } }", macro_call: "defineEmits<ReturnType<typeof makeEmits> & { evB: (n: number) => void }>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits> & { evB: (n: number) => void }", checker: "{ evA: (p: string) => boolean; } & { evB: (n: number) => void; }", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["\"evB\"", "\"evA\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::Object, members: &[("evA", NodeShape::Other)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA", "evB"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // KNOWN OWED — an unmodelled intersection ARM is silently dropped instead of failing closed.
    Row { id: "C04_emits_intersection_degraded", script: "class Box { readonly evA = (p: string) => true }\nfunction makeEmits() { return new Box() }", macro_call: "defineEmits<ReturnType<typeof makeEmits> & { evB: (n: number) => void }>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits> & { evB: (n: number) => void }", checker: "Box & { evB: (n: number) => void; }", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["\"evB\""], hasnt: &[] }/*owed:"\"\"evA\"\""*/, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["evB"]), verdict: Verdict::KnownOwed { owed_absent: &["\"evA\""], note: "The intersection arm whose flow return is WHOLLY unmodelled (`Box`) is SILENTLY DROPPED: `emits: [\"evB\"]` is published for a component whose checker type also declares `evA`. Every `@evA` listener then falls through to `$attrs`. The flow lane DOES report `Opaque(UnmodeledPosition)` + `UnmodeledPosition` for the arm — the information exists and the reducer discards it." }, ..Row::BLANK },
    // `withDefaults` over an intersection — the clean control.
    Row { id: "C05_withdefaults_intersection_clean", script: "function makeProps() { return { label: \"x\" } }", macro_call: "withDefaults(defineProps<ReturnType<typeof makeProps> & { extra?: string }>(), { extra: \"z\" })", probe: "ReturnType<typeof makeProps> & { extra?: string }", checker: "{ label: string; } & { extra?: string | undefined; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Emitted { has: &["label: { type: String", "extra: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["extra", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `withDefaults` over a degraded intersection: the default rides through untouched.
    Row { id: "C06_withdefaults_intersection_degraded", script: "class Box { readonly tag = \"box\" }\nfunction makeProps() { const f = () => new Box(); return { label: \"x\", made: f() } }", macro_call: "withDefaults(defineProps<ReturnType<typeof makeProps> & { extra?: string }>(), { extra: \"z\" })", probe: "ReturnType<typeof makeProps> & { extra?: string }", checker: "{ label: string; made: Box; } & { extra?: string | undefined; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Emitted { has: &["label: { type: String", "made: { type: null", "extra: { type: String"], hasnt: &["label: { type: null", "extra: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("made", NodeShape::OpaqueUnmodeledPosition)], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["extra", "label", "made"]), verdict: Verdict::Degraded("the unmodelled member publishes the typed marker; the defaulted member keeps its constructor and its `default`"), ..Row::BLANK },
    // `interface Props extends ReturnType<typeof f>` — the heritage form of C01_intersection_clean. The checker prints the interface NAME; its member expansion is row C09_heritage_members_clean's checker column.
    Row { id: "C07_heritage_extends_clean", script: "function makeProps() { return { label: \"x\" } }\ninterface Props extends ReturnType<typeof makeProps> { extra: string }", macro_call: "defineProps<Props>()", probe: "Props", checker: "Props", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["label: { type: String", "extra: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["extra", "label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // The heritage form of C02_intersection_degraded.
    Row { id: "C08_heritage_extends_degraded", script: "class Box { readonly tag = \"box\" }\nfunction makeProps() { const f = () => new Box(); return { label: \"x\", made: f() } }\ninterface Props extends ReturnType<typeof makeProps> { extra: string }", macro_call: "defineProps<Props>()", probe: "Props", checker: "Props", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["label: { type: String", "made: { type: null", "extra: { type: String"], hasnt: &["label: { type: null", "extra: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("made", NodeShape::OpaqueUnmodeledPosition)], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["extra", "label", "made"]), verdict: Verdict::Degraded("the unmodelled member publishes the typed marker through the heritage clause"), ..Row::BLANK },

    // ── D: degradation shapes ────────────────────────────────────────
    // The reference DEGRADED SUCCESS: a marker at one interior POSITION. Vue drives Boolean casting, `default` factories and dev validation off `type`, so erasing a SIBLING's constructor would be a runtime behaviour change.
    Row { id: "D01_helper_new", script: "class Box { readonly tag = \"box\" }\nfunction makeProps() { const f = () => new Box(); return { label: \"x\", made: f() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; made: Box; }", runtime: Runtime::Emitted { has: &["label: { type: String", "made: { type: null"], hasnt: &["label: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("made", NodeShape::OpaqueUnmodeledPosition)], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["label", "made"]), verdict: Verdict::Degraded("the one member the substrate could not type carries `type: null`; every modelled sibling keeps its real constructor"), ..Row::BLANK },
    // UNVERIFIED frame (parameter reassignment). The degradation is a property of the FRAME, so it applies to every member; attributing it per member by intersecting slot reads is FAIL-OPEN.
    Row { id: "D02_param_reassign", script: "function makeProps(seed: string) { seed = \"y\"; return { label: seed } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Emitted { has: &["label: { type: null"], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::UnappliedWriteEffect, candidates: 0 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::Degraded("the COMPLETE member set publishes with validation off (`type: null`) — the names are known and the types are not"), ..Row::BLANK },
    // UNVERIFIED frame (a conditional `var`). The degradation is a property of the FRAME, so it applies to every member; attributing it per member by intersecting slot reads is FAIL-OPEN.
    Row { id: "D03_conditional_var", script: "function makeProps(k: boolean) { var v = 1; if (k) { v = 2 } return { label: \"x\", n: v } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: null", "n: { type: null"], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("n", NodeShape::Primitive)], degradation: Degr::UnappliedWriteEffect, candidates: 0 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::Degraded("the COMPLETE member set publishes with validation off (`type: null`) — the names are known and the types are not"), ..Row::BLANK },
    // UNVERIFIED frame (a destructured-parameter write). The degradation is a property of the FRAME, so it applies to every member; attributing it per member by intersecting slot reads is FAIL-OPEN.
    Row { id: "D04_destructured_param_write", script: "function makeProps({ seed }: { seed: string }) { seed = \"y\"; return { label: seed, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: null", "n: { type: null"], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::OpaqueUnmodeledPosition), ("n", NodeShape::Primitive)], degradation: Degr::UnappliedWriteEffect, candidates: 0 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::Degraded("the COMPLETE member set publishes with validation off (`type: null`) — the names are known and the types are not"), ..Row::BLANK },
    // A return-bearing LOOP is the designed NO-VALUE outcome: the root has no member set, so publishing `props: {}` would declare a props-less component and send every binding to `$attrs`.
    Row { id: "D05_loop_return", script: "function makeProps() { for (let i = 0; i < 1; i++) { return { label: \"x\" } } return { label: \"y\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::FailsClosed, ..Row::BLANK },
    // KNOWN OWED — a `switch` with object-literal returns deletes the module.
    Row { id: "D06_switch_return", script: "function makeProps(v: number) { switch (v) { case 1: return { label: \"a\" }; default: return { label: \"b\" } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "A `switch` whose arms each return an object literal produces NO VALUE and the module is deleted. tsgo joins the arms to `{ label: string }`. The existing flow fixture covers `switch` returning PRIMITIVES only, which is why this arm was never reached." }, ..Row::BLANK },
    // KNOWN OWED — the `try` twin of D06_switch_return.
    Row { id: "D07_try_return", script: "function makeProps() { try { return { label: \"a\" } } finally { } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "The `try`/`finally` twin of D06_switch_return — same NO-VALUE outcome, same deletion." }, ..Row::BLANK },
    // KNOWN OWED — overloaded callee: refused at runtime AND the TSX lane faults.
    Row { id: "D08_overloaded_callee", script: "function base(a: string): { label: string };\nfunction base(a: number): { label: string };\nfunction base(a: any) { return { label: \"x\" } }\nfunction makeProps() { return { ...base(1), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", owner: Owner::U6CallResolve, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::UnrepresentableCallee, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {", "n: {"], note: "A spread whose source is an OVERLOADED callee degrades `UnrepresentableCallee`, the runtime lane refuses, AND the TSX lane FAULTS — the whole file loses its type-check surface for a program tsgo types as `{ label: string; n: number }`." }, ..Row::BLANK },
    // A CLASS-INSTANCE spread source: the literal's key set is unknown (the instance carries a whole prototype surface), so the root fails closed. Refusing is loud; publishing `{ n }` alone would be a surface missing a declared prop.
    Row { id: "D09_new_spread", script: "class Box { readonly label = \"x\" }\nfunction makeProps() { return { ...new Box(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: \"x\"; n: number; }", runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::FailsClosed, ..Row::BLANK },
    // KNOWN OWED — the TSX lane FAULTS. Contrast D09_new_spread (the same shape inline), which projects. The existing 5-row TSX test covers neither.
    Row { id: "D10_callee_new_spread_only", script: "class Box { readonly label = \"x\" }\nfunction base() { return new Box() }\nfunction makeProps() { return { ...base() } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: \"x\"; }", owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "The same fact ONE CALL away. The runtime refusal matches D09_new_spread and is designed; the TSX lane FAULT is not — it deletes the whole file's type-check surface for a program tsgo types as `{ label: \"x\" }`." }, ..Row::BLANK },
    // KNOWN OWED — the TSX lane FAULTS.
    Row { id: "D11_callee_new_spread_key", script: "class Box { readonly label = \"x\" }\nfunction base() { return new Box() }\nfunction makeProps() { return { ...base(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: \"x\"; n: number; }", owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "The D10_callee_new_spread_only shape with a sibling key — same runtime refusal, same TSX fault." }, ..Row::BLANK },

    // ── E: fail-closed controls ──────────────────────────────────────
    // FAIL-CLOSED at runtime (correct) but the TSX lane FAULTS (owed).
    Row { id: "E01_spread_any", script: "declare const x: any\nfunction makeProps() { return { ...x, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "any", checker_is_any: true, owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "Spreading `any` is `any` to the checker too, so the RUNTIME refusal is exactly right — there is no key set to publish. The TSX lane FAULT is the debt: the file loses its whole type-check surface. Note the FLOW lane produces a CLEAN `ObjectSpreadProgram` with a WARM candidate — the fail-closed happens downstream at projection, not in the flow substrate." }, ..Row::BLANK },
    // FAIL-CLOSED at runtime (defensible) but the TSX lane FAULTS (owed).
    Row { id: "E02_spread_index_signature", script: "function makeProps() { return { ...({} as Record<string, string>), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ n: number; }", owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "Spreading a `Record<string, string>` refuses. The checker's `{ n: number }` is the TYPE, but the runtime VALUE carries an unknown key set that a Vue props object cannot express, so refusing is defensible. The TSX lane FAULT is not." }, ..Row::BLANK },
    // FAIL-CLOSED at runtime (correct) but the TSX lane FAULTS (owed).
    Row { id: "E03_spread_array", script: "function makeProps() { return { ...[1, 2], n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ length: number; toString(): string; toLocaleString(): string; toLocaleString(locales: string | string[], options?: Intl.NumberFormatOptions & Intl.DateTimeFormatOptions): string; pop(): number | undefined; ... 37 more ...; n: number; }", owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "Spreading an ARRAY refuses; the checker's answer is the whole `Array` prototype surface plus `n`, which is not a props surface. The TSX lane FAULT is the debt." }, ..Row::BLANK },
    // An OPTIONAL-CHAIN spread source may be `undefined`, so the key set is conditional; the root fails closed.
    Row { id: "E04_spread_optional_chain", script: "function base(): { x?: { label: string } } { return {} }\nfunction makeProps() { return { ...base()?.x } }", probe: "ReturnType<typeof makeProps>", checker: "{ label?: string | undefined; }", runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::FailsClosed, ..Row::BLANK },
    // An AUTHORED empty surface: `props: {}` is CORRECT here — the component genuinely declares no props. This is the control that separates `an authored empty` from `a degradation that erased the members`, which must refuse (D05_loop_return/D09_new_spread).
    Row { id: "E05_empty_literal", script: "function makeProps() { return {} }", probe: "ReturnType<typeof makeProps>", checker: "{}", runtime: Runtime::Emitted { has: &[], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // An UNVERIFIED frame whose member set is empty: still `props: {}`. An unverified frame says the member TYPES may be wrong, never that members are missing.
    Row { id: "E06_write_then_empty", script: "function makeProps(seed: string) { seed = \"y\"; return {} }", probe: "ReturnType<typeof makeProps>", checker: "{}", runtime: Runtime::Emitted { has: &[], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── F: other macros (framework-owned) ────────────────────────────
    // `withDefaults` — the default rides onto the member the substrate typed, and the union member erases conservatively.
    Row { id: "F01_withdefaults", script: "function makeProps() { return { label: \"x\", extra: undefined as string | undefined } }", macro_call: "withDefaults(defineProps<ReturnType<typeof makeProps>>(), { label: \"z\" })", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; extra: string | undefined; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Emitted { has: &["label: { type: String", "extra: { type: null"], hasnt: &["label: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("extra", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["extra", "label"]), verdict: Verdict::Degraded("the `string | undefined` member has no single runtime constructor and publishes `type: null`; the defaulted member keeps `type: String` AND its `default`"), ..Row::BLANK },
    // `defineModel<T>()` publishes Vue's OWN `modelValue` / `modelModifiers` pair, not `T`'s members — that is the macro's contract, not a divergence.
    Row { id: "F02_definemodel", script: "function makeModel() { return { label: \"x\" } }", macro_call: "const m = defineModel<ReturnType<typeof makeModel>>()", probe: "ReturnType<typeof makeModel>", checker: "{ label: string; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Emitted { has: &["modelValue: { type: Object", "modelModifiers: {"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeModel", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `defineSlots` has NO runtime option surface at all — the module emits and declares no `props`. `Runtime::NoOption` pins exactly that, so a future change that starts emitting a slots option fails here.
    Row { id: "F03_defineslots", script: "function makeSlots() { return { default: (p: { n: number }) => null } }", macro_call: "defineSlots<ReturnType<typeof makeSlots>>()", probe: "ReturnType<typeof makeSlots>", checker: "{ default: (p: { n: number; }) => null; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::NoOption, tsx: Tsx::Projects, flow: Flow::Result { function: "makeSlots", node: NodeShape::Object, members: &[("default", NodeShape::Other)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["default"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `defineProps({ ...base3() })` — a RUNTIME-form macro referencing a locally-declared binding is `XInvalidMacroScopeReference`, Vue's own hoisting rule. The TSX fault is the SAME diagnostic (the file genuinely does not compile), so it is not a separate debt.
    Row { id: "F04_defineprops_runtime_spread", script: "function base3() { return { label: String } }", macro_call: "defineProps({ ...base3() })", probe: "ReturnType<typeof base3>", checker: "{ label: StringConstructor; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Diagnostic("XInvalidMacroScopeReference"), tsx: Tsx::Faults("XInvalidMacroScopeReference"), flow: Flow::Result { function: "base3", node: NodeShape::Object, members: &[("label", NodeShape::OpaqueOther)], degradation: Degr::UnresolvedValue, candidates: 0 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // The `defineOptions` twin of F04_defineprops_runtime_spread — same rule, same diagnostic.
    Row { id: "F05_defineoptions_runtime_spread", script: "function base4() { return { name: \"X\" } }", macro_call: "defineOptions({ ...base4() })", option_key: "name: ", probe: "ReturnType<typeof base4>", checker: "{ name: string; }", owner: Owner::FrameworkOnly, subject: Subject::FrameworkOnly, runtime: Runtime::Diagnostic("XInvalidMacroScopeReference"), tsx: Tsx::Faults("XInvalidMacroScopeReference"), flow: Flow::Result { function: "base4", node: NodeShape::Object, members: &[("name", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["name"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // PATH PROJECTION `ReturnType<typeof f>["label"]`: only the `label` hop loads and the published member carries its real constructor.
    Row { id: "F06_path_projection", script: "function base() { return { label: \"x\" } }\nfunction makeProps() { return { ...base(), n: 1 } }", macro_call: "defineProps<{ only: ReturnType<typeof makeProps>[\"label\"] }>()", probe: "ReturnType<typeof makeProps>[\"label\"]", checker: "string", owner: Owner::U2IndexedAccess, runtime: Runtime::Emitted { has: &["only: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Skip, verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── G: emits ─────────────────────────────────────────────────────
    // The spread-contributed event and the direct one must BOTH survive: `emits: []` for a component that declares emits sends every listener silently through to `$attrs`.
    Row { id: "G01_emits_spread_key", script: "function base() { return { evA: (p: string) => true } }\nfunction makeEmits() { return { ...base(), evB: (n: number) => true } }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{ evA: (p: string) => boolean; evB: (n: number) => boolean; }", runtime: Runtime::Emitted { has: &["\"evA\"", "\"evB\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA", "evB"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "G02_emits_spread_only", script: "function base() { return { evA: (p: string) => true } }\nfunction makeEmits() { return { ...base() } }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{ evA: (p: string) => boolean; }", runtime: Runtime::Emitted { has: &["\"evA\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // The emits twin of D09_new_spread — a class-instance spread source fails closed at the root.
    Row { id: "G03_emits_new_spread", script: "class Box { readonly evA = (p: string) => true }\nfunction makeEmits() { return { ...new Box(), evB: (n: number) => true } }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{ evA: (p: string) => boolean; evB: (n: number) => boolean; }", runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::FailsClosed, ..Row::BLANK },
    // The cross-file spread twin of G01_emits_spread_key.
    Row { id: "G04_emits_cross_file", aux: "export function base() { return { evA: (p: string) => true } }\n", script: "import { base } from \"./G04_emits_cross_file__aux\"\nfunction makeEmits() { return { ...base(), evB: (n: number) => true } }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{ evA: (p: string) => boolean; evB: (n: number) => boolean; }", runtime: Runtime::Emitted { has: &["\"evA\"", "\"evB\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA", "evB"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // An AUTHORED empty emits surface: `emits: []` is correct because the component declares none.
    Row { id: "G05_emits_empty", script: "function makeEmits() { return {} }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{}", runtime: Runtime::Emitted { has: &[], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::Object, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "G06_emits_plain", script: "function makeEmits() { return { evA: (p: string) => true, evB: (n: number) => true } }", macro_call: "defineEmits<ReturnType<typeof makeEmits>>()", option_key: "emits: ", probe: "ReturnType<typeof makeEmits>", checker: "{ evA: (p: string) => boolean; evB: (n: number) => boolean; }", runtime: Runtime::Emitted { has: &["\"evA\"", "\"evB\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::Object, members: &[("evA", NodeShape::Other), ("evB", NodeShape::Other)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA", "evB"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── C: intersection / heritage ───────────────────────────────────
    // KNOWN OWED — `{ [K in keyof Props]: Props[K] }` over a flow-return heritage clause publishes ZERO props.
    Row { id: "C09_heritage_members_clean", script: "function makeProps() { return { label: \"x\" } }\ninterface Props extends ReturnType<typeof makeProps> { extra: string }", macro_call: "defineProps<{ [K in keyof Props]: Props[K] }>()", probe: "{ [K in keyof Props]: Props[K] }", checker: "{ label: string; extra: string; }", owner: Owner::U2MappedTemplate, runtime: Runtime::Emitted { has: &[], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {", "extra: {"], note: "A mapped type over a heritage interface whose clause is a flow return publishes an EMPTY props object for a FULLY MODELLED, FULLY CLEAN shape (checker: `{ label: string; extra: string }`). This is total surface loss on a clean row — every bound attribute falls through to `$attrs`." }, ..Row::BLANK },
    // KNOWN OWED — the degraded twin of C09_heritage_members_clean deletes the module.
    Row { id: "C10_heritage_members_degraded", script: "class Box { readonly tag = \"box\" }\nfunction makeProps() { const f = () => new Box(); return { label: \"x\", made: f() } }\ninterface Props extends ReturnType<typeof makeProps> { extra: string }", macro_call: "defineProps<{ [K in keyof Props]: Props[K] }>()", probe: "{ [K in keyof Props]: Props[K] }", checker: "{ label: string; made: Box; extra: string; }", owner: Owner::U2MappedTemplate, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("made", NodeShape::OpaqueUnmodeledPosition)], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {", "made: {", "extra: {"], note: "The degraded twin of C09_heritage_members_clean REFUSES the module outright. tsgo types it as an ordinary object." }, ..Row::BLANK },
    // KNOWN OWED — the props twin of C04_emits_intersection_degraded. This is the shape the 15 existing `ReturnType<typeof …>` tests structurally could not reach: NONE of them uses `&` or `extends`.
    Row { id: "C11_props_intersection_unmodelled_arm", script: "class Box { readonly label = \"x\" }\nfunction makeProps() { return new Box() }", macro_call: "defineProps<ReturnType<typeof makeProps> & { extra: string }>()", probe: "ReturnType<typeof makeProps> & { extra: string }", checker: "Box & { extra: string; }", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["extra: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["extra"]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "The PROPS twin of C04_emits_intersection_degraded: the intersection arm whose flow return is wholly unmodelled is SILENTLY DROPPED. `props: { extra }` is published for a checker type of `Box & { extra: string }`, so the declared `label` prop is missing from the surface entirely." }, ..Row::BLANK },
    // KNOWN OWED — the heritage twin of C11_props_intersection_unmodelled_arm.
    Row { id: "C12_heritage_unmodelled_clause", script: "class Box { readonly label = \"x\" }\nfunction makeProps() { return new Box() }\ninterface Props extends ReturnType<typeof makeProps> { extra: string }", macro_call: "defineProps<Props>()", probe: "Props", checker: "Props", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["extra: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::OpaqueUnmodeledPosition, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["extra"]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "The HERITAGE twin of C11_props_intersection_unmodelled_arm: `interface Props extends ReturnType<typeof f>` where the clause's flow return is wholly unmodelled drops the whole clause and publishes only the interface's own members." }, ..Row::BLANK },
    // `interface Ev extends ReturnType<typeof makeEmits>` — the emits heritage control.
    Row { id: "C13_emits_heritage_clean", script: "function makeEmits() { return { evA: (p: string) => true } }\ninterface Ev extends ReturnType<typeof makeEmits> { evB: (n: number) => void }", macro_call: "defineEmits<Ev>()", option_key: "emits: ", probe: "Ev", checker: "Ev", owner: Owner::SharedTypeResolution, runtime: Runtime::Emitted { has: &["\"evA\"", "\"evB\""], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeEmits", node: NodeShape::Object, members: &[("evA", NodeShape::Other)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["evA", "evB"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },

    // ── N: NARROWING — plain TypeScript semantics, no framework column ──
    // NARROWING, owned by U6.NARROW_TYPEOF (not yet implemented).
    Row { id: "N01_typeof_guard_ternary", script: "function makeProps(u: string | number) { return { label: typeof u === \"string\" ? u : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A `typeof` guard in a conditional expression. tsgo narrows the true arm to `string`, so the member is `string`; anything wider means the guard did not apply. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_TYPEOF (not yet implemented).
    Row { id: "N02_typeof_guard_block", script: "function makeProps(u: string | number) { let label = \"z\"; if (typeof u === \"string\") { label = u } return { label } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::UnappliedWriteEffect, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A `typeof` guard around a BLOCK assignment. The narrowed value reaches the member through a local write, which is where a guard most often stops applying. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_TYPEOF (not yet implemented).
    Row { id: "N03_truthiness_guard", script: "function makeProps(u: string | undefined) { return { label: u ? u : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A TRUTHINESS guard over `string | undefined` — narrowing with no `typeof` operator at all. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_LATTICE (not yet implemented).
    Row { id: "N04_discriminated_union", script: "type A = { kind: \"a\"; a: string }\ntype B = { kind: \"b\"; b: number }\nfunction makeProps(u: A | B) { return { label: u.kind === \"a\" ? u.a : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowLattice, demand: Demand::Narrowing(NarrowBlock::NarrowLattice), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::UnresolvedValue, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A DISCRIMINATED-UNION guard on `u.kind`. The lattice must select one arm; selecting neither, or both, widens the member. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_LATTICE (not yet implemented).
    Row { id: "N05_in_operator_guard", script: "function makeProps(u: { a: string } | { b: number }) { return { label: \"a\" in u ? u.a : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowLattice, demand: Demand::Narrowing(NarrowBlock::NarrowLattice), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::UnresolvedValue, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "An `in`-operator guard over a union of object types. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_TYPEOF (not yet implemented).
    Row { id: "N06_instanceof_guard", script: "class Box { readonly tag = \"box\" }\nfunction makeProps(u: Box | string) { return { label: u instanceof Box ? u.tag : u } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::UnresolvedValue, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "An `instanceof` guard over a class/primitive union. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING CONTROL — a branch JOIN that legitimately WIDENS. The checker says `string | number` and the substrate agrees, so this row is NOT owed. It exists so a narrowing fix cannot OVER-narrow undetected: every other N row fails while the guard is unimplemented, and a change that made them pass by collapsing every join would fail HERE. A guard-shaped row can never catch that.
    Row { id: "N07_branch_join_widens", script: "function makeProps(f: boolean) { const v = f ? 1 : \"s\"; return { label: v } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string | number; }", owner: Owner::U6NarrowLattice, demand: Demand::Narrowing(NarrowBlock::NarrowLattice), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_SUBSTITUTION (not yet implemented).
    Row { id: "N08_predicate_across_call", script: "function isStr(x: unknown): x is string { return typeof x === \"string\" }\nfunction makeProps(u: string | number) { return { label: isStr(u) ? u : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowSubstitution, demand: Demand::Narrowing(NarrowBlock::NarrowSubstitution), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A USER-DEFINED type predicate applied ACROSS a call boundary — the canonical place a guard stops applying. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_INVALIDATION (not yet implemented).
    Row { id: "N09_narrow_then_write", script: "function makeProps(u: string | number) { let v = u; if (typeof v === \"string\") { v = v.trim() } return { label: typeof v === \"string\" ? v : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowInvalidation, demand: Demand::Narrowing(NarrowBlock::NarrowInvalidation), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::UnappliedWriteEffect, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A narrowed local read after an INTERVENING WRITE. The write must re-enter the lattice rather than discard or freeze the narrowing. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_SUBSTITUTION (not yet implemented).
    Row { id: "N10_assertion_signature", script: "function assertStr(x: unknown): asserts x is string { }\nfunction makeProps(u: string | number) { assertStr(u); return { label: u } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowSubstitution, demand: Demand::Narrowing(NarrowBlock::NarrowSubstitution), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "An ASSERTION signature: the narrowing has no syntactic guard at the use site at all. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_INVALIDATION (not yet implemented).
    Row { id: "N11_narrow_survives_call", script: "function touch() { }\nfunction makeProps(u: string | number) { return { label: typeof u === \"string\" ? (touch(), u) : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowInvalidation, demand: Demand::Narrowing(NarrowBlock::NarrowInvalidation), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A narrowing that must SURVIVE an intervening call to an unrelated function. A substrate that invalidates on any call widens here. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },
    // NARROWING, owned by U6.NARROW_TYPEOF (not yet implemented).
    Row { id: "N12_literal_union_narrow", script: "function makeProps(u: \"a\" | \"b\" | 1) { return { label: u === 1 ? \"z\" : u } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "An equality guard over a LITERAL union: `u === 1` removes the numeric arm and leaves the two string literals, which widen to `string`. PINNED OWED: the owning block is not implemented, so this row records the checker's answer alongside today's substrate answer. When the block lands and this row starts MATCHING the checker, the corpus FAILS and forces the row to be reclassified — that is how the narrowing blocks inherit a fence on day one instead of writing one on day thirty." }, ..Row::BLANK },

    // ── H: shapes added after the harness froze ──────────────────────
    // KNOWN OWED — a generic callee's instantiated member is erased.
    Row { id: "H01_generic_callee_spread", script: "function base<T>(v: T) { return { label: \"x\", carried: v } }\nfunction makeProps() { return { ...base(1), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; carried: number; n: number; }", owner: Owner::U6CallResolve, runtime: Runtime::Emitted { has: &["carried: { type: null", "label: { type: String", "n: { type: Number"], hasnt: &["label: { type: null", "n: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["carried", "label", "n"]), verdict: Verdict::KnownOwed { owed_absent: &["carried: { type: Number"], note: "A GENERIC callee's type argument is not substituted into the spread source: the member instantiated at `number` publishes the typed marker instead of its constructor. tsgo resolves the parameter to `number`." }, ..Row::BLANK },
    // FAIL-CLOSED at runtime (defensible); the TSX lane FAULTS (owed).
    Row { id: "H02_union_spread_source", script: "function base(f: boolean) { return f ? { label: \"x\" } : { n: 1 } }\nfunction makeProps() { return { ...base(true), m: 2 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n?: undefined; m: number; } | { label?: undefined; n: number; m: number; }", owner: Owner::SharedCompilePipeline, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "A UNION spread source. The runtime REFUSAL is defensible (each arm contributes a different key set, and an object surface cannot say 'one of these two key sets'). The TSX lane FAULT is the debt." }, ..Row::BLANK },
    // A SELF-RECURSIVE helper as the spread source: the recursion discharges against the annotated return and the surface publishes intact.
    Row { id: "H03_self_recursive_helper", script: "function base(n: number): { label: string } { return n > 0 ? base(n - 1) : { label: \"x\" } }\nfunction makeProps() { return { ...base(2), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    Row { id: "N13_nested_property_guard", script: "function makeProps(u: { v: string | number }) { return { label: typeof u.v === \"string\" ? u.v : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::UnresolvedValue, candidates: 0 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A `typeof` guard on a NESTED PROPERTY reference rather than a bare binding. PINNED OWED: the owning block is not implemented." }, ..Row::BLANK },
    Row { id: "N14_negated_typeof_guard", script: "function makeProps(u: string | number) { return { label: typeof u !== \"string\" ? \"z\" : u } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6NarrowTypeof, demand: Demand::Narrowing(NarrowBlock::NarrowTypeof), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union)], degradation: Degr::None, candidates: 1 }, verdict: Verdict::KnownOwed { owed_absent: &[], note: "A NEGATED `typeof` guard: the narrowed value is in the FALSE arm. PINNED OWED: the owning block is not implemented." }, ..Row::BLANK },

    // ── X: adversarial axes the landed families never reached ─────────
    // A typeof-guarded conditional as the SPREAD SOURCE, where BOTH arms declare the same key set. tsgo joins it to `{ label: string; n: number }`; the substrate refuses the module AND the TSX lane faults. The H02_union_spread_source refusal rationale ("each arm contributes a different key set") does not apply here, so even the refusal is owed, not only the fault.
    Row { id: "X01_spread_narrow_arm_source", script: "function makeProps(u: string | number) { return { ...(typeof u === \"string\" ? { label: u } : { label: \"z\" }), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {", "n: {"], note: "A typeof-guarded conditional spread source whose arms declare the SAME key set (`{ label }` both ways). tsgo joins to `{ label: string; n: number }`; the substrate refuses the module and the TSX lane faults, deleting the whole file's type-check surface." }, ..Row::BLANK },
    // A typeof-narrowed member BESIDE a spread in the same return. The guard does not apply, so the member publishes BOTH constructors where the checker says `string` — a published surface WIDER than the checker, not an erased one. The spread-program node has no member visibility, so the runtime constructors are the tripwire.
    Row { id: "X02_spread_with_narrow_member", script: "function base() { return { m: true } }\nfunction makeProps(u: string | number) { return { ...base(), label: typeof u === \"string\" ? u : \"z\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ m: boolean; label: string; }", owner: Owner::U6NarrowTypeof, runtime: Runtime::Emitted { has: &["label: { type: [String, Number]", "m: { type: Boolean"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "m"]), verdict: Verdict::KnownOwed { owed_absent: &["label: { type: String,"], note: "The narrowed member publishes `[String, Number]` where the checker says `label: string` — the guard beside a spread does not apply, and the published surface is wider than the checker rather than erased. When the owning block lands, the single-constructor needle appears and this row fails — the intended reclassification signal." }, ..Row::BLANK },
    // The member-visible twin of X02_spread_with_narrow_member: an Object root pins the un-narrowed member as `Union` next to a spread-program sibling.
    Row { id: "X03_narrow_member_spread_sibling", script: "function base() { return { x: 1 } }\nfunction makeProps(u: string | number) { return { label: typeof u === \"string\" ? u : \"z\", extra: { ...base() } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; extra: { x: number; }; }", owner: Owner::U6NarrowTypeof, runtime: Runtime::Emitted { has: &["label: { type: [String, Number]", "extra: { type: Object"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Union), ("extra", NodeShape::ObjectSpreadProgram)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["extra", "label"]), verdict: Verdict::KnownOwed { owed_absent: &["label: { type: String,"], note: "The pinned `Union` member is the graph-level tripwire for the unapplied guard; the runtime `[String, Number]` constructor pair is the consumer-level one. A spread sibling does not shield the narrowing from applying — the checker types the member `string` regardless." }, ..Row::BLANK },
    // try/catch where BOTH arms return an object literal: NO VALUE, module deleted. Extends the D07_try_return family to a catch-arm join.
    Row { id: "X04_try_catch_join", script: "function makeProps(f: boolean) { try { if (f) { throw new Error() } return { label: \"a\" } } catch { return { label: \"b\" } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "try/catch with an object-literal return in BOTH arms produces NO VALUE and the module is deleted. tsgo joins the arms to `{ label: string }`." }, ..Row::BLANK },
    // Return inside `catch` with a fallthrough return after the block: the try arm does NOT return, so the join is catch-return vs post-block return — a different control-flow shape reaching the same NO-VALUE outcome as X04_try_catch_join.
    Row { id: "X05_catch_return_fallthrough", script: "function makeProps() { try { throw new Error(\"x\") } catch { return { label: \"c\" } } return { label: \"d\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "A `catch` return joined against a fallthrough return after the try/catch produces NO VALUE and the module is deleted. tsgo joins to `{ label: string }`." }, ..Row::BLANK },
    // An IIFE as the WHOLE return value — the A09_iife_spread callee shape without the spread.
    Row { id: "X06_iife_return", script: "function makeProps() { return (() => ({ label: \"x\", n: 1 }))() }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // Return through a LOCAL arrow binding — the A04_arrow_const_spread callee one scope deeper, with no spread.
    Row { id: "X07_local_arrow_return", script: "function makeProps() { const inner = () => ({ label: \"x\", n: 1 }); return inner() }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // THREE instantiation sites of one generic callee in a single file. The H01_generic_callee_spread erasure is STABLE across them: `carried` publishes the typed marker and does NOT leak `String` from the sibling instantiation — a clean non-substitution, not a torn cache.
    Row { id: "X08_generic_two_instantiations", script: "function pick<T>(v: T) { return { carried: v } }\nconst first = pick(\"s\")\nconst second = pick(1)\nfunction makeProps() { return { ...pick(1), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ carried: number; n: number; }", owner: Owner::U6CallResolve, runtime: Runtime::Emitted { has: &["carried: { type: null", "n: { type: Number"], hasnt: &["n: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["carried", "n"]), verdict: Verdict::KnownOwed { owed_absent: &["carried: { type: Number"], note: "The generic callee's type argument is not substituted at ANY of three instantiation sites; the instantiated member erases identically to the single-site H01_generic_callee_spread shape, and no cross-site leak appears. tsgo resolves `carried` to `number`." }, ..Row::BLANK },
    // KNOWN OWED — a generic callee's result returned WHOLE: the flow lane computes the member EXACTLY and the runtime lane still erases it, with no degradation signalled. The semantic answer is right and dies on the way to the consumer.
    Row { id: "X09_generic_wrap_return", script: "function wrap<T>(v: T) { return { box: v } }\nfunction makeProps() { return wrap(\"x\") }", probe: "ReturnType<typeof makeProps>", checker: "{ box: string; }", owner: Owner::U6CallResolve, runtime: Runtime::Emitted { has: &["box: { type: null"], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("box", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["box"]), verdict: Verdict::KnownOwed { owed_absent: &["box: { type: String"], note: "The flow lane resolves the generic instantiation to `Primitive` (checker: `box: string`, warm candidate, no degradation) and the runtime lane STILL publishes `type: null` — a silent consumer-reach erasure on a clean flow result, unlike the D01_helper_new shape where the erasure is signalled by a typed degradation." }, ..Row::BLANK },
    // Destructured parameter defaults combined with conditional returns: the union join publishes the COMPLETE merged member set with every type erased, `n` correctly optional.
    Row { id: "X10_destructured_default_conditional", script: "function makeProps({ label = \"x\", n }: { label?: string; n?: number }) { if (n) { return { label, n } } return { label } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; } | { n?: undefined; label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: null", "n: { type: null"], hasnt: &[] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Union, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::Degraded("the destructured-default + conditional-return join publishes the merged member set (`label` required, `n` optional) with both types erased (`type: null`); the flow lane keeps the unreduced Union with a typed UnmodeledPosition, and the Svelte twin serves only the shared member"), ..Row::BLANK },
    // Return through a class STATIC METHOD call.
    Row { id: "X11_class_static_method_return", script: "class Box { static build() { return { label: \"x\" } } }\nfunction makeProps() { return Box.build() }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // A class GETTER read into the return: the member set is complete and the getter's type is erased with a typed UnresolvedValue.
    Row { id: "X12_class_getter_member", script: "class Box { get label() { return \"x\" } }\nfunction makeProps() { const b = new Box(); return { label: b.label, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", runtime: Runtime::Emitted { has: &["label: { type: null", "n: { type: Number"], hasnt: &["n: { type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::OpaqueOther), ("n", NodeShape::Primitive)], degradation: Degr::UnresolvedValue, candidates: 0 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::Degraded("the class-getter member erases to the typed marker (`type: null`, UnresolvedValue); the sibling keeps its constructor and the member set is complete"), ..Row::BLANK },
    // An authored `__proto__` entry IS a type member to the checker, and the substrate publishes it identically. Whether a component should declare a prop literally named `__proto__` is framework POLICY, outside this corpus's TypeScript-semantics subject.
    Row { id: "X13_proto_entry", script: "function makeProps() { return { __proto__: { label: \"x\" }, n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ __proto__: { label: string; }; n: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["__proto__: { type: Object", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("__proto__", NodeShape::Object), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["__proto__", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // KNOWN OWED — a get/set PAIR in the returned literal surfaces as TWO members with the same key; the lone-getter control A16_getter_member publishes fine. The projection refuses the module as duplicate-public-name AND the TSX lane faults.
    Row { id: "X14_accessor_pair", script: "function makeProps() { return { get g(): string { return \"s\" }, set g(v: string | number) { }, n: 2 } }", probe: "ReturnType<typeof makeProps>", checker: "{ get g(): string; set g(v: string | number); n: number; }", runtime: Runtime::Refused, tsx: Tsx::Faults("XUnavailableMacroSemanticResult"), flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("g", NodeShape::Other), ("n", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["g", "g", "n"]), verdict: Verdict::KnownOwed { owed_absent: &["g: { type: String"], note: "An asymmetric get/set pair (checker: `{ get g(): string; set g(v: string | number); n: number }`) surfaces as a DUPLICATE member key, so the module is refused as duplicate-public-name and the TSX lane faults — the file loses its type-check surface for a program the checker types. The repaired shape is one `g` member carrying the getter's return type." }, ..Row::BLANK },
    // A labelled block with `break` plus two object-literal returns: NO VALUE, module deleted.
    Row { id: "X15_labelled_block_return", script: "function makeProps(f: boolean) { blk: { if (f) { break blk } return { label: \"a\" } } return { label: \"b\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "A labelled block with `break` between two object-literal returns produces NO VALUE and the module is deleted. tsgo joins to `{ label: string }`." }, ..Row::BLANK },
    // Switch FALLTHROUGH (empty `case 1` falls into `case 2`) with object-literal returns: the shared-continuation shape reaches the same NO-VALUE outcome as the per-arm D06_switch_return shape.
    Row { id: "X16_switch_fallthrough", script: "function makeProps(v: number) { switch (v) { case 1: case 2: return { label: \"a\" }; default: return { label: \"b\" } } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", owner: Owner::U6ValueInference, runtime: Runtime::Refused, tsx: Tsx::Projects, flow: Flow::NoValue, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &["label: {"], note: "A switch fallthrough whose continuation returns an object literal produces NO VALUE and the module is deleted. tsgo joins to `{ label: string }`." }, ..Row::BLANK },
    // Self-recursion where the function's OWN annotated return feeds itself through a spread. The runtime lane publishes the exact surface; the flow lane conservatively reports an unreduced Union with UnmodeledPosition and nothing warms — pinned as measured; a lane-consistency fix re-pins this row.
    Row { id: "X17_self_recursive_spread", script: "function makeProps(d: number): { label: string } { if (d > 0) { return { ...makeProps(d - 1) } } return { label: \"y\" } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; }", runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Union, members: &[], degradation: Degr::UnmodeledPosition, candidates: 0 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // KNOWN OWED — an async function's return is `Promise<{ label: string }>` to the checker; the substrate silently UNWRAPS it and publishes the inner object as props — a fabricated surface for a type that is not object-like. The pin fails the moment the lane starts refusing or models the wrapper.
    Row { id: "X18_async_return", script: "async function makeProps() { return { label: \"x\" } }", probe: "ReturnType<typeof makeProps>", checker: "Promise<{ label: string; }>", runtime: Runtime::Emitted { has: &["label: { type: String"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Primitive)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label"]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "Async return wrapping is not modelled: the flow lane unwraps the `Promise` and the macro lane publishes the inner object as a props surface, where the checker types the return as `Promise<{ label: string }>` — not an object-like props type. The designed answer is a refusal; today the surface is fabricated relative to the checker." }, ..Row::BLANK },
    // KNOWN OWED — a generator return is correctly rejected by the macro lane (XInvalidMacroType, no props option), but the TSX lane FAULTS and deletes the file's whole type-check surface. Same consumer-reach debt class as E01_spread_any.
    Row { id: "X19_generator_yield", script: "function* makeProps() { yield { label: \"x\" } }", probe: "ReturnType<typeof makeProps>", checker: "Generator<{ label: string; }, void, unknown>", owner: Owner::SharedCompilePipeline, runtime: Runtime::Diagnostic("XInvalidMacroType"), tsx: Tsx::Faults("XInvalidMacroType"), flow: Flow::Result { function: "makeProps", node: NodeShape::Primitive, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&[]), verdict: Verdict::KnownOwed { owed_absent: &[], note: "The macro lane's rejection is correct — `Generator<{ label: string }, void, unknown>` is not an object-like props type — but the TSX lane faults with the same code and the file loses its type-check surface for a program the checker types." }, ..Row::BLANK },
    // `as const` on the SPREAD SOURCE's return. The checker keeps the literal `\"x\"` (spreading strips `readonly` but preserves the literal); every lane here widens to constructors, so agreement is over the member set — the same unpicked-up-literal blind spot B03_as_const_call records.
    Row { id: "X20_as_const_spread_source", script: "function base() { return { label: \"x\" } as const }\nfunction makeProps() { return { ...base(), n: 1 } }", probe: "ReturnType<typeof makeProps>", checker: "{ label: \"x\"; n: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::ObjectSpreadProgram, members: &[], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
    // `satisfies Record<string, string | number>` on a PLAIN return (no spread): the substrate keeps `Literal` member nodes that widen to the same constructors the checker prints.
    Row { id: "X21_satisfies_plain_return", script: "function makeProps() { return { label: \"x\", n: 1 } satisfies Record<string, string | number> }", probe: "ReturnType<typeof makeProps>", checker: "{ label: string; n: number; }", owner: Owner::U6ValueInference, runtime: Runtime::Emitted { has: &["label: { type: String", "n: { type: Number"], hasnt: &["type: null"] }, tsx: Tsx::Projects, flow: Flow::Result { function: "makeProps", node: NodeShape::Object, members: &[("label", NodeShape::Literal), ("n", NodeShape::Literal)], degradation: Degr::None, candidates: 1 }, svelte: Svelte::Props(&["label", "n"]), verdict: Verdict::MatchesChecker, ..Row::BLANK },
];
