export * from "./setup";
export type {
	ReturnMacros,
	RegularMacros,
	MacroReturnType,
	MacroReturnObject,
	MacroReturn,
	CreateMacroReturn,
	OmitMacroReturn,
	ExtractMacroReturn,
	ExtractMacro,
	ExtractTemplateRef,
	ExtractMacroProps,
	ExtractPropsFromMacro,
	ExtractEmits,
	MacroToEmitValue,
	ExtractSlots,
	SlotsToSlotType,
	ExtractOptions,
	MacroOptionsToOptions,
	ExtractModel,
	MacroToModelType,
	MacroToModelRecord,
	ExtractExpose,
	ExposeToVueExposeKey,
	NormaliseMacroReturn,
	NormalisedMacroReturn,
} from "./setup";
export { createMacroReturn } from "./setup";