//! Generated by scripts/gen-corpus-audit-tests.mjs. Do not edit.
//!
//! Stitches every per-component corpus test file into one cargo
//! integration test target so `cargo test -p verter_session
//! --test corpus_audit_tests` discovers every generated slug.

#[path = "component_meta_audit_corpus/accordion.rs"]
mod accordion;
#[path = "component_meta_audit_corpus/alert.rs"]
mod alert;
#[path = "component_meta_audit_corpus/app.rs"]
mod app;
#[path = "component_meta_audit_corpus/auth_form.rs"]
mod auth_form;
#[path = "component_meta_audit_corpus/avatar.rs"]
mod avatar;
#[path = "component_meta_audit_corpus/avatar_group.rs"]
mod avatar_group;
#[path = "component_meta_audit_corpus/badge.rs"]
mod badge;
#[path = "component_meta_audit_corpus/banner.rs"]
mod banner;
#[path = "component_meta_audit_corpus/blog_post.rs"]
mod blog_post;
#[path = "component_meta_audit_corpus/blog_posts.rs"]
mod blog_posts;
#[path = "component_meta_audit_corpus/breadcrumb.rs"]
mod breadcrumb;
#[path = "component_meta_audit_corpus/button.rs"]
mod button;
#[path = "component_meta_audit_corpus/calendar.rs"]
mod calendar;
#[path = "component_meta_audit_corpus/card.rs"]
mod card;
#[path = "component_meta_audit_corpus/carousel.rs"]
mod carousel;
#[path = "component_meta_audit_corpus/changelog_version.rs"]
mod changelog_version;
#[path = "component_meta_audit_corpus/changelog_versions.rs"]
mod changelog_versions;
#[path = "component_meta_audit_corpus/chat_message.rs"]
mod chat_message;
#[path = "component_meta_audit_corpus/chat_messages.rs"]
mod chat_messages;
#[path = "component_meta_audit_corpus/chat_palette.rs"]
mod chat_palette;
#[path = "component_meta_audit_corpus/chat_prompt.rs"]
mod chat_prompt;
#[path = "component_meta_audit_corpus/chat_prompt_submit.rs"]
mod chat_prompt_submit;
#[path = "component_meta_audit_corpus/chat_reasoning.rs"]
mod chat_reasoning;
#[path = "component_meta_audit_corpus/chat_shimmer.rs"]
mod chat_shimmer;
#[path = "component_meta_audit_corpus/chat_tool.rs"]
mod chat_tool;
#[path = "component_meta_audit_corpus/checkbox.rs"]
mod checkbox;
#[path = "component_meta_audit_corpus/checkbox_group.rs"]
mod checkbox_group;
#[path = "component_meta_audit_corpus/chip.rs"]
mod chip;
#[path = "component_meta_audit_corpus/collapsible.rs"]
mod collapsible;
#[path = "component_meta_audit_corpus/color_mode_color_mode_avatar.rs"]
mod color_mode_color_mode_avatar;
#[path = "component_meta_audit_corpus/color_mode_color_mode_button.rs"]
mod color_mode_color_mode_button;
#[path = "component_meta_audit_corpus/color_mode_color_mode_image.rs"]
mod color_mode_color_mode_image;
#[path = "component_meta_audit_corpus/color_mode_color_mode_select.rs"]
mod color_mode_color_mode_select;
#[path = "component_meta_audit_corpus/color_mode_color_mode_switch.rs"]
mod color_mode_color_mode_switch;
#[path = "component_meta_audit_corpus/color_picker.rs"]
mod color_picker;
#[path = "component_meta_audit_corpus/command_palette.rs"]
mod command_palette;
#[path = "component_meta_audit_corpus/container.rs"]
mod container;
#[path = "component_meta_audit_corpus/content_content_navigation.rs"]
mod content_content_navigation;
#[path = "component_meta_audit_corpus/content_content_search.rs"]
mod content_content_search;
#[path = "component_meta_audit_corpus/content_content_search_button.rs"]
mod content_content_search_button;
#[path = "component_meta_audit_corpus/content_content_surround.rs"]
mod content_content_surround;
#[path = "component_meta_audit_corpus/content_content_toc.rs"]
mod content_content_toc;
#[path = "component_meta_audit_corpus/context_menu.rs"]
mod context_menu;
#[path = "component_meta_audit_corpus/context_menu_content.rs"]
mod context_menu_content;
#[path = "component_meta_audit_corpus/dashboard_group.rs"]
mod dashboard_group;
#[path = "component_meta_audit_corpus/dashboard_navbar.rs"]
mod dashboard_navbar;
#[path = "component_meta_audit_corpus/dashboard_panel.rs"]
mod dashboard_panel;
#[path = "component_meta_audit_corpus/dashboard_resize_handle.rs"]
mod dashboard_resize_handle;
#[path = "component_meta_audit_corpus/dashboard_search.rs"]
mod dashboard_search;
#[path = "component_meta_audit_corpus/dashboard_search_button.rs"]
mod dashboard_search_button;
#[path = "component_meta_audit_corpus/dashboard_sidebar.rs"]
mod dashboard_sidebar;
#[path = "component_meta_audit_corpus/dashboard_sidebar_collapse.rs"]
mod dashboard_sidebar_collapse;
#[path = "component_meta_audit_corpus/dashboard_sidebar_toggle.rs"]
mod dashboard_sidebar_toggle;
#[path = "component_meta_audit_corpus/dashboard_toolbar.rs"]
mod dashboard_toolbar;
#[path = "component_meta_audit_corpus/drawer.rs"]
mod drawer;
#[path = "component_meta_audit_corpus/dropdown_menu.rs"]
mod dropdown_menu;
#[path = "component_meta_audit_corpus/dropdown_menu_content.rs"]
mod dropdown_menu_content;
#[path = "component_meta_audit_corpus/editor.rs"]
mod editor;
#[path = "component_meta_audit_corpus/editor_drag_handle.rs"]
mod editor_drag_handle;
#[path = "component_meta_audit_corpus/editor_emoji_menu.rs"]
mod editor_emoji_menu;
#[path = "component_meta_audit_corpus/editor_mention_menu.rs"]
mod editor_mention_menu;
#[path = "component_meta_audit_corpus/editor_suggestion_menu.rs"]
mod editor_suggestion_menu;
#[path = "component_meta_audit_corpus/editor_toolbar.rs"]
mod editor_toolbar;
#[path = "component_meta_audit_corpus/empty.rs"]
mod empty;
#[path = "component_meta_audit_corpus/error.rs"]
mod error;
#[path = "component_meta_audit_corpus/field_group.rs"]
mod field_group;
#[path = "component_meta_audit_corpus/file_upload.rs"]
mod file_upload;
#[path = "component_meta_audit_corpus/footer.rs"]
mod footer;
#[path = "component_meta_audit_corpus/footer_columns.rs"]
mod footer_columns;
#[path = "component_meta_audit_corpus/form.rs"]
mod form;
#[path = "component_meta_audit_corpus/form_field.rs"]
mod form_field;
#[path = "component_meta_audit_corpus/header.rs"]
mod header;
#[path = "component_meta_audit_corpus/icon.rs"]
mod icon;
#[path = "component_meta_audit_corpus/input.rs"]
mod input;
#[path = "component_meta_audit_corpus/input_date.rs"]
mod input_date;
#[path = "component_meta_audit_corpus/input_menu.rs"]
mod input_menu;
#[path = "component_meta_audit_corpus/input_number.rs"]
mod input_number;
#[path = "component_meta_audit_corpus/input_tags.rs"]
mod input_tags;
#[path = "component_meta_audit_corpus/input_time.rs"]
mod input_time;
#[path = "component_meta_audit_corpus/kbd.rs"]
mod kbd;
#[path = "component_meta_audit_corpus/link.rs"]
mod link;
#[path = "component_meta_audit_corpus/link_base.rs"]
mod link_base;
#[path = "component_meta_audit_corpus/listbox.rs"]
mod listbox;
#[path = "component_meta_audit_corpus/locale_locale_select.rs"]
mod locale_locale_select;
#[path = "component_meta_audit_corpus/main.rs"]
mod main;
#[path = "component_meta_audit_corpus/marquee.rs"]
mod marquee;
#[path = "component_meta_audit_corpus/modal.rs"]
mod modal;
#[path = "component_meta_audit_corpus/navigation_menu.rs"]
mod navigation_menu;
#[path = "component_meta_audit_corpus/overlay_provider.rs"]
mod overlay_provider;
#[path = "component_meta_audit_corpus/page.rs"]
mod page;
#[path = "component_meta_audit_corpus/page_anchors.rs"]
mod page_anchors;
#[path = "component_meta_audit_corpus/page_aside.rs"]
mod page_aside;
#[path = "component_meta_audit_corpus/page_body.rs"]
mod page_body;
#[path = "component_meta_audit_corpus/page_card.rs"]
mod page_card;
#[path = "component_meta_audit_corpus/page_columns.rs"]
mod page_columns;
#[path = "component_meta_audit_corpus/page_cta.rs"]
mod page_cta;
#[path = "component_meta_audit_corpus/page_feature.rs"]
mod page_feature;
#[path = "component_meta_audit_corpus/page_grid.rs"]
mod page_grid;
#[path = "component_meta_audit_corpus/page_header.rs"]
mod page_header;
#[path = "component_meta_audit_corpus/page_hero.rs"]
mod page_hero;
#[path = "component_meta_audit_corpus/page_links.rs"]
mod page_links;
#[path = "component_meta_audit_corpus/page_list.rs"]
mod page_list;
#[path = "component_meta_audit_corpus/page_logos.rs"]
mod page_logos;
#[path = "component_meta_audit_corpus/page_section.rs"]
mod page_section;
#[path = "component_meta_audit_corpus/pagination.rs"]
mod pagination;
#[path = "component_meta_audit_corpus/pin_input.rs"]
mod pin_input;
#[path = "component_meta_audit_corpus/popover.rs"]
mod popover;
#[path = "component_meta_audit_corpus/pricing_plan.rs"]
mod pricing_plan;
#[path = "component_meta_audit_corpus/pricing_plans.rs"]
mod pricing_plans;
#[path = "component_meta_audit_corpus/pricing_table.rs"]
mod pricing_table;
#[path = "component_meta_audit_corpus/progress.rs"]
mod progress;
#[path = "component_meta_audit_corpus/prose_a.rs"]
mod prose_a;
#[path = "component_meta_audit_corpus/prose_accordion.rs"]
mod prose_accordion;
#[path = "component_meta_audit_corpus/prose_accordion_item.rs"]
mod prose_accordion_item;
#[path = "component_meta_audit_corpus/prose_badge.rs"]
mod prose_badge;
#[path = "component_meta_audit_corpus/prose_blockquote.rs"]
mod prose_blockquote;
#[path = "component_meta_audit_corpus/prose_callout.rs"]
mod prose_callout;
#[path = "component_meta_audit_corpus/prose_callout_caution.rs"]
mod prose_callout_caution;
#[path = "component_meta_audit_corpus/prose_callout_note.rs"]
mod prose_callout_note;
#[path = "component_meta_audit_corpus/prose_callout_tip.rs"]
mod prose_callout_tip;
#[path = "component_meta_audit_corpus/prose_callout_warning.rs"]
mod prose_callout_warning;
#[path = "component_meta_audit_corpus/prose_card.rs"]
mod prose_card;
#[path = "component_meta_audit_corpus/prose_card_group.rs"]
mod prose_card_group;
#[path = "component_meta_audit_corpus/prose_code.rs"]
mod prose_code;
#[path = "component_meta_audit_corpus/prose_code_collapse.rs"]
mod prose_code_collapse;
#[path = "component_meta_audit_corpus/prose_code_group.rs"]
mod prose_code_group;
#[path = "component_meta_audit_corpus/prose_code_icon.rs"]
mod prose_code_icon;
#[path = "component_meta_audit_corpus/prose_code_preview.rs"]
mod prose_code_preview;
#[path = "component_meta_audit_corpus/prose_code_tree.rs"]
mod prose_code_tree;
#[path = "component_meta_audit_corpus/prose_collapsible.rs"]
mod prose_collapsible;
#[path = "component_meta_audit_corpus/prose_em.rs"]
mod prose_em;
#[path = "component_meta_audit_corpus/prose_field.rs"]
mod prose_field;
#[path = "component_meta_audit_corpus/prose_field_group.rs"]
mod prose_field_group;
#[path = "component_meta_audit_corpus/prose_h1.rs"]
mod prose_h1;
#[path = "component_meta_audit_corpus/prose_h2.rs"]
mod prose_h2;
#[path = "component_meta_audit_corpus/prose_h3.rs"]
mod prose_h3;
#[path = "component_meta_audit_corpus/prose_h4.rs"]
mod prose_h4;
#[path = "component_meta_audit_corpus/prose_hr.rs"]
mod prose_hr;
#[path = "component_meta_audit_corpus/prose_icon.rs"]
mod prose_icon;
#[path = "component_meta_audit_corpus/prose_img.rs"]
mod prose_img;
#[path = "component_meta_audit_corpus/prose_kbd.rs"]
mod prose_kbd;
#[path = "component_meta_audit_corpus/prose_li.rs"]
mod prose_li;
#[path = "component_meta_audit_corpus/prose_ol.rs"]
mod prose_ol;
#[path = "component_meta_audit_corpus/prose_p.rs"]
mod prose_p;
#[path = "component_meta_audit_corpus/prose_pre.rs"]
mod prose_pre;
#[path = "component_meta_audit_corpus/prose_prompt.rs"]
mod prose_prompt;
#[path = "component_meta_audit_corpus/prose_script.rs"]
mod prose_script;
#[path = "component_meta_audit_corpus/prose_steps.rs"]
mod prose_steps;
#[path = "component_meta_audit_corpus/prose_strong.rs"]
mod prose_strong;
#[path = "component_meta_audit_corpus/prose_table.rs"]
mod prose_table;
#[path = "component_meta_audit_corpus/prose_tabs.rs"]
mod prose_tabs;
#[path = "component_meta_audit_corpus/prose_tabs_item.rs"]
mod prose_tabs_item;
#[path = "component_meta_audit_corpus/prose_tbody.rs"]
mod prose_tbody;
#[path = "component_meta_audit_corpus/prose_td.rs"]
mod prose_td;
#[path = "component_meta_audit_corpus/prose_th.rs"]
mod prose_th;
#[path = "component_meta_audit_corpus/prose_thead.rs"]
mod prose_thead;
#[path = "component_meta_audit_corpus/prose_tr.rs"]
mod prose_tr;
#[path = "component_meta_audit_corpus/prose_ul.rs"]
mod prose_ul;
#[path = "component_meta_audit_corpus/radio_group.rs"]
mod radio_group;
#[path = "component_meta_audit_corpus/scroll_area.rs"]
mod scroll_area;
#[path = "component_meta_audit_corpus/select.rs"]
mod select;
#[path = "component_meta_audit_corpus/select_menu.rs"]
mod select_menu;
#[path = "component_meta_audit_corpus/separator.rs"]
mod separator;
#[path = "component_meta_audit_corpus/sidebar.rs"]
mod sidebar;
#[path = "component_meta_audit_corpus/skeleton.rs"]
mod skeleton;
#[path = "component_meta_audit_corpus/slideover.rs"]
mod slideover;
#[path = "component_meta_audit_corpus/slider.rs"]
mod slider;
#[path = "component_meta_audit_corpus/stepper.rs"]
mod stepper;
#[path = "component_meta_audit_corpus/switch.rs"]
mod switch;
#[path = "component_meta_audit_corpus/table.rs"]
mod table;
#[path = "component_meta_audit_corpus/tabs.rs"]
mod tabs;
#[path = "component_meta_audit_corpus/textarea.rs"]
mod textarea;
#[path = "component_meta_audit_corpus/theme.rs"]
mod theme;
#[path = "component_meta_audit_corpus/timeline.rs"]
mod timeline;
#[path = "component_meta_audit_corpus/toast.rs"]
mod toast;
#[path = "component_meta_audit_corpus/toaster.rs"]
mod toaster;
#[path = "component_meta_audit_corpus/tooltip.rs"]
mod tooltip;
#[path = "component_meta_audit_corpus/tree.rs"]
mod tree;
#[path = "component_meta_audit_corpus/user.rs"]
mod user;
