//! Provider-neutral oracles over a generated check: the exact-diagnostic
//! oracle the paired real-provider tests apply to tsserver and tsgo results,
//! and the mapping oracle the compiler tests apply to the `CodeTransform`
//! mappings.

use super::fixtures::{Expected, Fixture};
use super::seam::{GeneratedCheck, Mapping, Span};

/// One error-severity diagnostic as a provider reported it, in generated
/// byte offsets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProviderDiagnostic {
    pub code: u32,
    pub start: u32,
    pub end: u32,
    pub message: String,
}

/// The fixture's diagnostics, exactly: every diagnostic carrying authored
/// bytes maps to an expected `(code, authored span)` and every expected one
/// is reported, with multiplicity. A diagnostic carrying no authored byte
/// (inside synthetic scaffolding) must repeat the code of an expected one —
/// a re-narrowing copy of a reference that is itself reported — so the check
/// never adds a kind of error the authored template does not have.
pub fn check_exact(
    fixture: &Fixture,
    check: &GeneratedCheck,
    diagnostics: &[ProviderDiagnostic],
) -> Result<(), String> {
    let mut mapped = Vec::new();
    let mut unmapped = Vec::new();
    for diagnostic in diagnostics {
        match check.authored_extent(diagnostic.start..diagnostic.end) {
            Some(authored) => mapped.push(Expected {
                code: diagnostic.code,
                authored,
            }),
            None => unmapped.push(diagnostic),
        }
    }
    mapped.sort();
    let describe = |items: &[Expected]| -> String {
        items
            .iter()
            .map(|e| {
                format!(
                    "TS{}@{}..{} `{}`",
                    e.code,
                    e.authored.start,
                    e.authored.end,
                    &fixture.source[e.authored.start as usize..e.authored.end as usize]
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    if mapped != fixture.expected {
        return Err(format!(
            "{}: mapped diagnostics differ\n  expected: [{}]\n  reported: [{}]\n  all: {diagnostics:?}",
            fixture.name,
            describe(&fixture.expected),
            describe(&mapped)
        ));
    }
    if let Some(stray) = unmapped
        .iter()
        .find(|d| !fixture.expected.iter().any(|e| e.code == d.code))
    {
        return Err(format!(
            "{}: an unmapped diagnostic is not a copy of an authored one: {stray:?}",
            fixture.name
        ));
    }
    Ok(())
}

/// Every mapping carries authored bytes verbatim, mappings are disjoint and
/// ordered, every authored span the plan names is emitted exactly once with
/// the same bytes, and no generated byte outside a mapping claims authored
/// provenance (synthetic scaffolding stays unmapped).
pub fn check_mappings(
    source: &str,
    check: &GeneratedCheck,
    authored: &[Span],
) -> Result<(), String> {
    let mut previous_end = 0;
    for mapping in &check.mappings {
        let Mapping {
            generated,
            source: from,
        } = *mapping;
        if generated.start < previous_end {
            return Err(format!("mapping {mapping:?} overlaps its predecessor"));
        }
        previous_end = generated.end;
        let generated_text = check
            .code
            .get(generated.start as usize..generated.end as usize);
        let source_text = source.get(from.start as usize..from.end as usize);
        if generated_text.is_none() || generated_text != source_text {
            return Err(format!(
                "mapping {mapping:?} carries {generated_text:?} but its source is {source_text:?}"
            ));
        }
    }
    for span in authored {
        let mut covered = 0;
        let mut offset = span.start;
        while offset < span.end {
            let generated = check.generated_offsets(offset);
            if generated.len() != 1 {
                return Err(format!(
                    "authored byte {offset} of {span:?} is emitted {} times",
                    generated.len()
                ));
            }
            covered += 1;
            offset += 1;
        }
        if covered != span.len() {
            return Err(format!("authored span {span:?} is not fully emitted"));
        }
    }
    Ok(())
}
