//! Contract, linear-growth and mapping checks for the flow-transparent
//! callback check, on source-backed fixtures. The semantic (provider) side of
//! the same fixtures runs in `verter_lsp`'s paired real-provider lanes.

use super::builder::{build_plan, BuildError, PlanContext};
use super::fixtures::{self, Fixture, Root, MATRIX_SIZES};
use super::generator::{generate, generate_with, GuardStrategy, HELPERS};
use super::oracle::check_mappings;
use super::seam::{
    Branch, BranchKind, Callback, CallbackFunction, CheckPlan, FrameBinding, GeneratedCheck,
    GuardSite, Item, Mapping, Piece, PlanError, ResolvedExpr, ScopeKey, Span,
};
use crate::template::code_gen::binding::BindingType;

/// The deepest fixtures nest a few hundred template levels; the template
/// parse recurses per level, so they run on a thread with room for it.
fn with_stack<T: Send + 'static>(run: impl FnOnce() -> T + Send + 'static) -> T {
    std::thread::Builder::new()
        .stack_size(64 << 20)
        .spawn(run)
        .expect("spawn the fixture thread")
        .join()
        .expect("the fixture thread completed")
}

fn walk<'p>(items: &'p [Item], visit: &mut impl FnMut(&'p Item)) {
    for item in items {
        visit(item);
        match item {
            Item::Chain(chain) => {
                for branch in &chain.branches {
                    walk(&branch.items, visit);
                }
            }
            Item::Frame(frame) => walk(&frame.items, visit),
            Item::Callback(_) | Item::Expr(_) => {}
        }
    }
}

fn callbacks(plan: &CheckPlan) -> Vec<&Callback> {
    let mut out = Vec::new();
    walk(&plan.items, &mut |item| {
        if let Item::Callback(callback) = item {
            out.push(callback);
        }
    });
    out
}

fn ref_texts(plan: &CheckPlan) -> Vec<Vec<String>> {
    callbacks(plan)
        .iter()
        .map(|callback| callback.outer_refs.iter().map(|r| r.text.clone()).collect())
        .collect()
}

fn expr_spans(expr: &ResolvedExpr, out: &mut Vec<Span>) {
    out.extend(expr.pieces.iter().filter_map(|piece| match piece {
        Piece::Authored(span) => Some(*span),
        Piece::Synthetic(_) => None,
    }));
}

/// Every authored span a plan carries into the check.
fn authored_spans(plan: &CheckPlan) -> Vec<Span> {
    let mut out = Vec::new();
    walk(&plan.items, &mut |item| match item {
        Item::Chain(chain) => {
            for branch in &chain.branches {
                if let Some(condition) = &branch.condition {
                    expr_spans(condition, &mut out);
                }
            }
        }
        Item::Frame(frame) => match &frame.binding {
            FrameBinding::VFor {
                aliases, source, ..
            } => {
                out.push(*aliases);
                expr_spans(source, &mut out);
            }
            FrameBinding::Slot { pattern, .. } => out.push(*pattern),
        },
        Item::Callback(callback) => match &callback.function {
            CallbackFunction::Authored { expr, .. } => expr_spans(expr, &mut out),
            CallbackFunction::Handler { body, .. } => expr_spans(body, &mut out),
        },
        Item::Expr(expr) => expr_spans(&expr.expr, &mut out),
    });
    out
}

fn rendered_len(expr: &ResolvedExpr) -> usize {
    expr.pieces
        .iter()
        .map(|piece| match piece {
            Piece::Authored(span) => span.len() as usize,
            Piece::Synthetic(text) => text.len(),
        })
        .sum()
}

/// The stated algorithmic bound on generated bytes: helpers, declarations
/// and header once; per chain 16 bytes, per branch 16 bytes plus its
/// resolved condition; per frame 64 bytes plus its aliases or pattern,
/// resolved source and contract; per value 32 bytes plus its contract; per
/// callback 64 bytes plus its contract and resolved function; per outer
/// reference 160 bytes plus three copies of its text. Path length appears
/// nowhere: a branch, frame or callback costs the same at any depth.
fn byte_bound(plan: &CheckPlan) -> usize {
    let mut bound = HELPERS.len() + plan.declarations.len() + plan.parameters.len() + 40;
    walk(&plan.items, &mut |item| {
        bound += match item {
            Item::Chain(chain) => {
                16 + chain
                    .branches
                    .iter()
                    .map(|b| 16 + b.condition.as_ref().map_or(0, rendered_len))
                    .sum::<usize>()
            }
            Item::Frame(frame) => match &frame.binding {
                FrameBinding::VFor {
                    aliases, source, ..
                } => 64 + aliases.len() as usize + rendered_len(source),
                FrameBinding::Slot { pattern, contract } => {
                    64 + pattern.len() as usize + contract.len()
                }
            },
            Item::Callback(callback) => {
                let function = match &callback.function {
                    CallbackFunction::Authored { expr, .. } => rendered_len(expr),
                    CallbackFunction::Handler { parameters, body } => {
                        parameters.len() + rendered_len(body)
                    }
                };
                64 + callback.contract.len()
                    + function
                    + callback
                        .outer_refs
                        .iter()
                        .map(|outer| 160 + 3 * outer.text.len())
                        .sum::<usize>()
            }
            Item::Expr(expr) => {
                32 + expr.contract.as_ref().map_or(0, String::len) + rendered_len(&expr.expr)
            }
        }
    });
    bound
}

// ── Executable integration contract ──────────────────────────────

#[test]
fn every_semantic_fixture_plans_and_generates_from_its_source() {
    for fixture in fixtures::semantic_suite() {
        let (plan, work) = fixture.plan().unwrap();
        let check = generate(&plan, &fixture.source).unwrap();

        let mut conditions = 0;
        walk(&plan.items, &mut |item| {
            if let Item::Chain(chain) = item {
                conditions += chain
                    .branches
                    .iter()
                    .filter(|b| b.condition.is_some())
                    .count() as u64;
            }
        });
        assert_eq!(work.conditions_resolved, conditions, "{}", fixture.name);
        assert_eq!(check.work.conditions, conditions, "{}", fixture.name);
        assert_eq!(
            work.callbacks as usize, fixture.authored_callbacks,
            "{}",
            fixture.name
        );
        assert_eq!(
            check.layout.callbacks.len(),
            fixture.authored_callbacks,
            "{}: every authored callback is emitted",
            fixture.name
        );
        check_mappings(&fixture.source, &check, &authored_spans(&plan))
            .unwrap_or_else(|e| panic!("{}: {e}", fixture.name));
        assert!(
            check.layout.total_bytes <= byte_bound(&plan),
            "{}",
            fixture.name
        );
    }
}

#[test]
fn the_plan_carries_every_callback_and_scope_shape() {
    let fixture = fixtures::contextual(Root::MutableProperty, false);
    let contextual = fixture.plan().unwrap().0;
    let shapes: Vec<&str> = callbacks(&contextual)
        .iter()
        .map(|callback| match &callback.function {
            CallbackFunction::Authored {
                guard: GuardSite::Expression { .. },
                ..
            } => "expression body",
            CallbackFunction::Authored {
                expr,
                guard: GuardSite::Block { .. },
            } => {
                if fixture.source[expr.span.start as usize..].starts_with("function") {
                    "function expression"
                } else {
                    "block body"
                }
            }
            CallbackFunction::Handler { parameters, .. } => {
                assert_eq!(parameters, "$event");
                "generated handler"
            }
        })
        .collect();
    for shape in [
        "expression body",
        "block body",
        "function expression",
        "generated handler",
    ] {
        assert!(shapes.contains(&shape), "missing {shape}: {shapes:?}");
    }

    let lexical = fixtures::lexical(Root::MutableProperty).plan().unwrap().0;
    let mut bindings = Vec::new();
    walk(&lexical.items, &mut |item| {
        if let Item::Frame(frame) = item {
            bindings.push(match &frame.binding {
                FrameBinding::VFor { arity, .. } => format!("v-for/{arity}"),
                FrameBinding::Slot { .. } => "v-slot".to_string(),
            });
        }
    });
    assert_eq!(bindings, ["v-for/1", "v-for/2", "v-slot"]);

    // A chain nested inside a branch, and a chain member that carries its own
    // `v-for` (the frame opens inside the branch, after its condition).
    let nested = fixtures::deep_positives(3, false).plan().unwrap().0;
    let Item::Chain(outer) = &nested.items[0] else {
        panic!("the outermost level is a chain")
    };
    assert!(matches!(outer.branches[0].items[1], Item::Chain(_)));
    let lifted = fixtures::mapping().plan().unwrap().0;
    let Item::Chain(member_with_v_for) = &lifted.items[1] else {
        panic!("the second element is its own chain")
    };
    assert!(matches!(
        member_with_v_for.branches[0].items[0],
        Item::Frame(_)
    ));
}

#[test]
fn outer_refs_follow_template_and_callback_lexical_identity() {
    let refs = ref_texts(&fixtures::lexical(Root::MutableProperty).plan().unwrap().0);
    // `v-for` alias: the alias and its member chain, every prefix first.
    assert_eq!(
        refs[0],
        ["take", "item", "__props.u", "item!.label", "__props.u!.a"]
    );
    // Destructured alias and index: plain template locals.
    assert_eq!(
        refs[1],
        ["take", "label", "index", "__props.u", "__props.u!.a"]
    );
    // Slot parameter.
    assert_eq!(
        refs[2],
        ["take", "row", "__props.u", "row!.note", "__props.u!.a"]
    );
    // A callback-local const is not an outer reference.
    assert_eq!(refs[3], ["__props.u", "take", "__props.u!.a"]);
    // A parameter shadowing the narrowed root is not the root.
    assert_eq!(refs[4], ["takeNumber"]);

    // A nested authored closure reads in its own flow: nothing inside it is
    // an outer reference of the callback.
    let refs = ref_texts(&fixtures::mutation_and_nested_closure().plan().unwrap().0);
    assert_eq!(refs[0], ["take", "__props.note"]);
    assert!(refs[1].is_empty(), "{:?}", refs[1]);
    assert_eq!(refs[2], ["take", "__props.note"]);
}

fn branches(plan: &mut CheckPlan) -> &mut Vec<Branch> {
    match &mut plan.items[0] {
        Item::Chain(chain) => &mut chain.branches,
        _ => panic!("the fixture opens with its chain"),
    }
}

#[test]
fn planted_branch_faults_are_refused() {
    let fixture = fixtures::flat_chain(Root::MutableProperty, 5, false);
    let source = &fixture.source;
    let plan = fixture.plan().unwrap().0;
    assert!(generate(&plan, source).is_ok());
    let first = branches(&mut plan.clone())[0].key;
    assert_eq!(branches(&mut plan.clone())[1].kind, BranchKind::ElseIf);

    let mut missing_link = plan.clone();
    branches(&mut missing_link)[2].predecessor = None;
    assert!(matches!(
        generate(&missing_link, source),
        Err(PlanError::PredecessorMismatch { found: None, .. })
    ));

    let mut wrong_link = plan.clone();
    branches(&mut wrong_link)[3].predecessor = Some(first);
    assert!(matches!(
        generate(&wrong_link, source),
        Err(PlanError::PredecessorMismatch { found: Some(found), .. }) if found == first
    ));

    let mut missing_condition = plan.clone();
    branches(&mut missing_condition)[1].condition = None;
    assert!(matches!(
        generate(&missing_condition, source),
        Err(PlanError::MissingCondition { .. })
    ));

    let mut else_condition = plan.clone();
    let condition = branches(&mut else_condition)[0].condition.clone();
    branches(&mut else_condition)[4].condition = condition;
    assert!(matches!(
        generate(&else_condition, source),
        Err(PlanError::ElseWithCondition { .. })
    ));

    let mut headless = plan.clone();
    branches(&mut headless).remove(0);
    branches(&mut headless)[0].predecessor = None;
    assert!(matches!(
        generate(&headless, source),
        Err(PlanError::ChainMustOpenWithIf { .. })
    ));

    let mut reordered = plan.clone();
    branches(&mut reordered).swap(3, 4);
    assert!(generate(&reordered, source).is_err());

    let mut stray_branch = plan.clone();
    branches(&mut stray_branch)[1].scope = ScopeKey(99);
    assert!(matches!(
        generate(&stray_branch, source),
        Err(PlanError::ScopeMismatch { .. })
    ));
}

fn first_branch_callback(plan: &mut CheckPlan, index: usize) -> &mut Callback {
    let Item::Chain(chain) = &mut plan.items[0] else {
        panic!("the fixture opens with its chain")
    };
    let Item::Callback(callback) = &mut chain.branches[0].items[index] else {
        panic!("item {index} of the first branch is a callback")
    };
    callback
}

#[test]
fn planted_context_faults_are_refused() {
    let fixture = fixtures::lexical(Root::MutableProperty);
    let plan = fixture.plan().unwrap().0;
    let source = &fixture.source;

    // A callback inside the `v-for` frame claimed by the root scope.
    let mut wrong_scope = plan.clone();
    let root = wrong_scope.root;
    let Item::Chain(chain) = &mut wrong_scope.items[0] else {
        panic!()
    };
    let Item::Frame(frame) = &mut chain.branches[0].items[0] else {
        panic!()
    };
    let Item::Chain(inner) = &mut frame.items[0] else {
        panic!()
    };
    let Item::Callback(callback) = &mut inner.branches[0].items[0] else {
        panic!()
    };
    callback.scope = root;
    assert!(matches!(
        generate(&wrong_scope, source),
        Err(PlanError::ScopeMismatch { .. })
    ));

    // A frame linked to the wrong parent scope.
    let mut wrong_parent = plan.clone();
    let Item::Chain(chain) = &mut wrong_parent.items[0] else {
        panic!()
    };
    let Item::Frame(frame) = &mut chain.branches[0].items[0] else {
        panic!()
    };
    frame.parent = frame.scope;
    assert!(matches!(
        generate(&wrong_parent, source),
        Err(PlanError::FrameParentMismatch { .. })
    ));

    // An outer reference taken from another callback.
    let mut foreign_ref = plan.clone();
    let other = callbacks(&plan)[4].outer_refs[0].clone();
    first_branch_callback(&mut foreign_ref, 3)
        .outer_refs
        .push(other);
    assert!(matches!(
        generate(&foreign_ref, source),
        Err(PlanError::OuterRefOutsideCallback { .. })
    ));

    // A callback with no contract.
    let mut no_contract = plan.clone();
    first_branch_callback(&mut no_contract, 3).contract.clear();
    assert!(matches!(
        generate(&no_contract, source),
        Err(PlanError::MissingContract { .. })
    ));

    // The same authored callback planned twice.
    let mut duplicated = plan.clone();
    let Item::Chain(chain) = &mut duplicated.items[0] else {
        panic!()
    };
    let copy = chain.branches[0].items[3].clone();
    chain.branches[0].items.push(copy);
    assert!(matches!(
        generate(&duplicated, source),
        Err(PlanError::AuthoredOverlap { .. })
    ));

    // A template whose callback has no contextual contract is not planned.
    let refused = build_plan(
        "<template><i @click=\"() => take(1)\"></i></template>",
        &PlanContext {
            declarations: "",
            parameters: "()",
            bindings: &[("take", BindingType::SetupConst)],
            contracts: &[],
        },
    );
    assert_eq!(
        refused.unwrap_err(),
        BuildError::MissingContract {
            key: "@click".into()
        }
    );
}

// ── Linear representation ────────────────────────────────────────

#[derive(Debug, Clone, Copy)]
struct Sample {
    n: usize,
    bytes: u64,
    helper_and_declaration_bytes: u64,
    transform_ops: u64,
    outer_refs: u64,
    conditions: u64,
    predecessor_links: u64,
    scope_links: u64,
    callbacks: u64,
    resolved_conditions: u64,
}

fn sample(
    fixture: &Fixture,
    n: usize,
    strategy: GuardStrategy,
) -> (Sample, CheckPlan, GeneratedCheck) {
    let (plan, work) = fixture.plan().unwrap();
    let check = generate_with(&plan, &fixture.source, strategy).unwrap();
    let sample = Sample {
        n,
        bytes: check.layout.total_bytes as u64,
        helper_and_declaration_bytes: (check.layout.helper_bytes + check.layout.declaration_bytes)
            as u64,
        transform_ops: check.work.transform_ops,
        outer_refs: check.work.outer_refs,
        conditions: check.work.conditions,
        predecessor_links: check.work.predecessor_links,
        scope_links: check.work.scope_links,
        callbacks: check.work.callbacks,
        resolved_conditions: work.conditions_resolved,
    };
    (sample, plan, check)
}

/// At most `limit` growth per doubling of the fixture size.
fn growth(samples: &[Sample], metric: fn(&Sample) -> u64, limit: f64) -> Result<(), String> {
    for pair in samples.windows(2) {
        let (small, large) = (&pair[0], &pair[1]);
        assert_eq!(large.n, small.n * 2, "samples double");
        let ratio = metric(large) as f64 / metric(small).max(1) as f64;
        if ratio > limit {
            return Err(format!(
                "{} → {}: {} → {} grows {ratio:.3}x",
                small.n,
                large.n,
                metric(small),
                metric(large)
            ));
        }
    }
    Ok(())
}

type Metric = (&'static str, fn(&Sample) -> u64);

const METRICS: [Metric; 9] = [
    ("generated bytes", |s| s.bytes),
    ("helper and declaration bytes", |s| {
        s.helper_and_declaration_bytes
    }),
    ("transform operations", |s| s.transform_ops),
    ("outer references", |s| s.outer_refs),
    ("emitted conditions", |s| s.conditions),
    ("predecessor links", |s| s.predecessor_links),
    ("scope links", |s| s.scope_links),
    ("callbacks", |s| s.callbacks),
    ("resolved conditions", |s| s.resolved_conditions),
];

#[test]
fn chains_and_nested_scopes_grow_linearly() {
    with_stack(|| {
        for shape in ["flat", "nested"] {
            let mut samples = Vec::new();
            for &n in &MATRIX_SIZES {
                let fixture = match shape {
                    "flat" => fixtures::flat_matrix(n, 1, false),
                    _ => fixtures::nested_matrix(n, false),
                };
                let (sample, plan, check) = sample(&fixture, n, GuardStrategy::Snapshot);
                assert_eq!(check.layout.callbacks.len(), n, "{}", fixture.name);
                assert_eq!(sample.callbacks, n as u64, "{}", fixture.name);
                assert!(
                    check
                        .layout
                        .callbacks
                        .iter()
                        .all(|site| site.outer_refs > 0),
                    "{}: every callback re-narrows what it reads",
                    fixture.name
                );
                assert_eq!(check.layout.helper_bytes, HELPERS.len());
                let bound = byte_bound(&plan);
                assert!(
                    check.layout.total_bytes <= bound,
                    "{}: {} bytes exceed the stated bound {bound}",
                    fixture.name,
                    check.layout.total_bytes
                );
                samples.push(sample);
            }
            for (name, metric) in METRICS {
                growth(&samples, metric, 2.2)
                    .unwrap_or_else(|e| panic!("{shape} {name}: {e}\n{samples:#?}"));
            }
        }
    });
}

#[test]
fn callback_count_scales_without_path_expansion() {
    with_stack(|| {
        let mut samples = Vec::new();
        for (index, callbacks) in [1, 2, 4, 8].into_iter().enumerate() {
            let fixture = fixtures::flat_matrix(256, callbacks, false);
            let (mut sample, _, check) = sample(&fixture, 1 << index, GuardStrategy::Snapshot);
            sample.bytes -= sample.helper_and_declaration_bytes;
            // A callback costs the same at the second branch as at the last:
            // no byte of a callback depends on how many branches precede it.
            let sites: Vec<u32> = check
                .layout
                .callbacks
                .iter()
                .map(|site| site.generated.len() - 3 * site.authored.len())
                .collect();
            let (min, max) = (sites.iter().min().unwrap(), sites.iter().max().unwrap());
            assert!(
                max - min <= 8,
                "{}: callback sizes {min}..{max}",
                fixture.name
            );
            samples.push(sample);
        }
        growth(&samples, |s| s.bytes, 2.2).unwrap();
        growth(&samples, |s| s.outer_refs, 2.2).unwrap();
    });
}

#[test]
fn restored_path_replay_fails_the_growth_oracle() {
    with_stack(|| {
        for shape in ["flat", "nested"] {
            let mut samples = Vec::new();
            for &n in &MATRIX_SIZES[..3] {
                let fixture = match shape {
                    "flat" => fixtures::flat_matrix(n, 1, false),
                    _ => fixtures::nested_matrix(n, false),
                };
                samples.push(sample(&fixture, n, GuardStrategy::ReplayPath).0);
            }
            assert!(
                growth(&samples, |s| s.bytes, 2.2).is_err(),
                "{shape}: replaying the path into every callback must fail the oracle: {samples:#?}"
            );
        }
    });
}

// ── Mappings ─────────────────────────────────────────────────────

#[test]
fn mappings_are_exact_for_moved_and_non_ascii_authored_bytes() {
    let fixture = fixtures::mapping();
    let (plan, _) = fixture.plan().unwrap();
    let check = generate(&plan, &fixture.source).unwrap();
    check_mappings(&fixture.source, &check, &authored_spans(&plan)).unwrap();

    let mut after_non_ascii = 0;
    for expected in &fixture.expected {
        let generated = check.generated_offsets(expected.authored.start);
        assert_eq!(generated.len(), 1, "{expected:?}");
        let at = generated[0] as usize;
        assert_eq!(
            &check.code[at..at + expected.authored.len() as usize],
            &fixture.source[expected.authored.start as usize..expected.authored.end as usize]
        );
        let line = fixture.source[..expected.authored.start as usize]
            .lines()
            .last()
            .unwrap_or_default();
        if !line.is_ascii() {
            // The generated line differs in both byte and UTF-16 position.
            assert_ne!(at, expected.authored.start as usize);
            after_non_ascii += 1;
        }
    }
    assert_eq!(
        after_non_ascii, 2,
        "two reported identifiers follow non-ASCII text"
    );

    // `<li v-for="item in items" v-if="…">`: the condition is authored after
    // the `v-for` but emitted before it, and both keep exact mappings.
    let v_for = fixture.source.find("item in items").unwrap() as u32;
    let condition = fixture.source.rfind("u.kind === 'a'").unwrap() as u32;
    assert!(v_for < condition);
    let v_for_at = check.generated_offsets(v_for)[0];
    let condition_at = check.generated_offsets(condition)[0];
    assert!(condition_at < v_for_at, "the condition is moved ahead");

    // Synthetic scaffolding carries no authored provenance.
    for synthetic in [
        "__props.",
        "__VerterFlow.",
        "__verter_o0",
        "throw 0",
        "if (",
    ] {
        for (at, _) in check.code.match_indices(synthetic) {
            for offset in at..at + synthetic.len() {
                assert_eq!(
                    check.source_offset(offset as u32),
                    None,
                    "{synthetic} at {at}"
                );
            }
        }
    }
}

#[test]
fn a_perturbed_mapping_fails_the_mapping_oracle() {
    let fixture = fixtures::mapping();
    let (plan, _) = fixture.plan().unwrap();
    let check = generate(&plan, &fixture.source).unwrap();
    let spans = authored_spans(&plan);
    check_mappings(&fixture.source, &check, &spans).unwrap();

    for index in [0, check.mappings.len() / 2, check.mappings.len() - 1] {
        let mut shifted = check.clone();
        let Mapping { generated, source } = shifted.mappings[index];
        shifted.mappings[index] = Mapping {
            generated,
            source: Span::new(source.start + 1, source.end + 1),
        };
        assert!(
            check_mappings(&fixture.source, &shifted, &spans).is_err(),
            "shifting mapping {index} must be detected"
        );
    }
    let mut dropped = check.clone();
    dropped.mappings.remove(1);
    assert!(check_mappings(&fixture.source, &dropped, &spans).is_err());
}
