[package]
name = "verter_core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vue 3 SFC compiler - transforms Vue Single File Components to render functions with TypeScript support"
repository.workspace = true
documentation = "https://github.com/pikax/verter"
homepage.workspace = true
authors.workspace = true
keywords = ["vue", "compiler", "sfc", "typescript", "codegen"]
categories = ["compilers", "template-engine"]

[features]
bench = []
dhat-heap = []
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath", "hotpath/hotpath-alloc"]

[dependencies]
verter_span = { path = "../verter_span" }
hotpath = { version = "0.13", optional = true }
bitflags = "2"
memchr = "2.7.6"
rustc-hash = { workspace = true }
smallvec = "1.13"
lazy_static = "1.5"
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }
oxc_diagnostics = "0.117.0"
bumpalo = { version = "3.15.0", features = ["collections"] }
serde = { workspace = true }
serde_repr = "0.1"
serde_json = { workspace = true }
allocator-api2 = "0.4.0"
oxc_sourcemap = "6.0.2"
base64 = "0.22"
sha2 = { workspace = true }
hex = "0.4"
lightningcss = { workspace = true }
phf = { version = "0.13", features = ["macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1"

[dev-dependencies]
dhat = "0.3"
