// The `TscResponse` carrier and its labeled-rendering selectors.
//
// A PRIVATE child module on purpose. Rust privacy is per-module INCLUDING
// descendants, so a field declared directly in `crate::types` stays readable
// from every sibling item and test module in `types.rs` — the raw-read wall
// would have an inside. Housing the fields and the sole from-parts
// constructor here means even `types.rs` itself crosses a real privacy
// boundary: a raw `code` / `ts_carrier_code` read or a struct-literal
// construction from ANYWHERE outside this module — the rest of `crate::types`
// included — is E0616 / E0451. The compile-fail fixture
// `tests/cases/compile-fail/tsc_response_raw_field_read_outside_child_module.rs`
// pins exactly that sibling position; it `include!`s THIS file, so the proof
// and the production source cannot drift. Keep this module minimal: the
// struct, its fields, `new`, and the selector impls — nothing else.
//
// (Header comments are deliberately `//`, not `//!`: the fixture splices this
// file into a block module, where spliced inner attributes are rejected.)

use std::sync::Arc;

/// Response from [`VerterHost::get_public_api`](crate::VerterHost::get_public_api).
///
/// Contains minimal TypeScript declarations generated by macro-only extraction
/// (defineProps, defineEmits, defineModel, defineOptions). No template
/// compilation is performed.
#[derive(Debug, Clone)]
pub struct TscResponse {
    /// The generated TSC code in the DIALECT-labeled rendering (JSDoc widening
    /// for a widened JavaScript Options-API stub). PRIVATE to this child
    /// module on purpose: raw access let a consumer writing to a
    /// TypeScript-labeled path pick the JSDoc rendering, whose types a `.ts`
    /// ScriptKind silently ignores. Every read from outside this module —
    /// sibling code in `crate::types` included — goes through one of the
    /// named selectors below, so the channel choice is explicit at every call
    /// site and a new consumer cannot reach an unlabeled default.
    code: Arc<str>,
    /// See [`Self::ts_labeled_code`]. `None` means `code` serves both
    /// labelings (every producer except the widened JavaScript Options stub).
    ts_carrier_code: Option<Arc<str>>,
    /// JSON source map (always present — embedded inline in the code).
    pub source_map: Option<Arc<str>>,
    /// The dialect of the DIALECT-labeled rendering — the ScriptKind a
    /// consumer naming its companion file FROM the dialect must label it with,
    /// because TypeScript decides both what to typecheck AND how to parse from
    /// a file's extension.
    ///
    /// This is the dialect of the code the surface CARRIES, not the carrier's
    /// authored language: a surface built only from generated declarations is
    /// TypeScript whatever the component was written in, while the Vue
    /// Options-API stub passes the authored `<script>` body through verbatim
    /// and reports that body's dialect. See
    /// [`verter_compiler::tsc::TscOutput::dialect`] for the per-producer table.
    pub dialect: verter_compiler::tsc::SfcScriptDialect,
}

impl TscResponse {
    /// The only constructor: both renderings enter together, so no consumer
    /// can build a response that is missing the channel its destination needs.
    #[must_use]
    pub fn new(
        code: Arc<str>,
        source_map: Option<Arc<str>>,
        dialect: verter_compiler::tsc::SfcScriptDialect,
        ts_carrier_code: Option<Arc<str>>,
    ) -> Self {
        Self {
            code,
            ts_carrier_code,
            source_map,
            dialect,
        }
    }

    /// The bytes for a companion at `companion_path`, selected by the path's
    /// EXTENSION — the same syntactic fact TypeScript itself keys parsing on
    /// (mirroring the LSP's `script_kind_for_path` authority): a `.js` /
    /// `.jsx` / `.mjs` / `.cjs` destination takes the dialect-labeled
    /// rendering, anything else the TypeScript-labeled one (the conservative
    /// default, as an unrecognised extension parses as TS).
    ///
    /// This is the selector every publisher that HOLDS its destination path
    /// uses, so the rendering follows the destination by construction — a
    /// future dialect-named companion path would select correctly with no
    /// call-site change.
    #[must_use]
    pub fn code_for_companion_path(&self, companion_path: &str) -> &Arc<str> {
        let javascript_labeled = companion_path.ends_with(".js")
            || companion_path.ends_with(".jsx")
            || companion_path.ends_with(".mjs")
            || companion_path.ends_with(".cjs");
        if javascript_labeled {
            self.dialect_labeled_code()
        } else {
            self.ts_labeled_code()
        }
    }

    /// The bytes a TypeScript-LABELED destination must take: the TS-carrier
    /// rendering when the surface needed a distinct one (a widened JavaScript
    /// Options-API stub, whose dialect-labeled rendering spells its widening
    /// in JSDoc — honored only in JavaScript-flavored files), otherwise the
    /// shared rendering. For path-less consumers whose destination is
    /// TypeScript-labeled by contract: the FFI wire (every FFI consumer
    /// stores this surface at a fixed `.verter.ts`-shaped path), delivery
    /// identity, and any presentation of the TYPE surface.
    #[must_use]
    pub fn ts_labeled_code(&self) -> &Arc<str> {
        self.ts_carrier_code.as_ref().unwrap_or(&self.code)
    }

    /// The bytes for a destination NAMED FROM [`Self::dialect`] (the
    /// `verter-tsc` CLI's `{name}.vue.{dialect.extension()}` stub): the
    /// dialect-labeled rendering. Path-keyed selection would be circular for
    /// this consumer — the path is derived from the dialect — so the choice is
    /// named instead.
    #[must_use]
    pub fn dialect_labeled_code(&self) -> &Arc<str> {
        &self.code
    }
}
