/**
 * The Verter DX scenario model: the serializable {@link Scenario} types and closed
 * enumerations ({@link ./model}) plus the trust-boundary {@link validateScenario}
 * ({@link ./validate}).
 */

export {
  BASELINE_REQUIREMENTS,
  CONFIDENCE_LEVELS,
  CONFIDENCE_RANK,
  DEFAULT_BASELINES,
  EDIT_STEP_KINDS,
  INVARIANT_ASSERTIONS,
  KNOWN_CAPABILITY_REQUIREMENTS,
  MAPPING_POLICIES,
  MAPPING_POLICY_CONFIDENCE_CEILING,
  OPERATIONAL_METHODS,
  PROBE_METHODS,
  REQUIRED_DRIVERS,
  REQUIRED_DRIVER_LABELS,
  SEMANTIC_DIMENSIONS,
  confidenceWithinCeiling,
  effectiveConfidence,
  isBaselineRequirement,
  isConfidence,
  isEditStepKind,
  isInvariantAssertion,
  isKnownCapabilityRequirement,
  isMappingPolicy,
  isOperationalMethod,
  isProbeMethod,
  isRequiredDriver,
  isSemanticDimension,
  mappingPolicyConfidenceCeiling,
  mappingPolicyRequiresSourceMap,
  methodSupportsDimension,
  methodSupportsInvariant,
  type BaselineRequirement,
  type CapabilityRequirement,
  type Confidence,
  type DeleteStep,
  type EditStep,
  type EditStepKind,
  type InsertStep,
  type Invariant,
  type InvariantAssertion,
  type KnownCapabilityRequirement,
  type LatencyThresholds,
  type MappingPolicy,
  type OperationalMethod,
  type Probe,
  type ProbeMethod,
  type RecoveryThresholds,
  type ReplaceStep,
  type RequiredDriver,
  type Scenario,
  type ScenarioBaselines,
  type ScenarioThresholds,
  type SemanticDimension,
} from "./model.js";

export {
  SCENARIO_ERROR_CODES,
  validateScenario,
  type ScenarioErrorCode,
  type ScenarioValidationError,
  type ScenarioValidationResult,
} from "./validate.js";
