import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, "../src/tsx");
const distDir = path.join(__dirname, "../dist");

const TSX_FILE = path.join(srcDir, "tsx.tsx");
const ATTR_FILE = path.join(srcDir, "tsx.attributes.ts");

function ensureDist() {
  if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });
}

function readFile(file) {
  if (!fs.existsSync(file)) {
    console.error(`[build-tsx] Missing file: ${file}`);
    process.exit(1);
  }
  return fs.readFileSync(file, "utf-8");
}

function stripAttributesImport(code) {
  // Remove: import "./tsx.attributes"; (with optional semicolon/whitespace)
  return code.replace(/^\s*import\s+["']\.\/tsx\.attributes["'];?\s*$/m, "");
}

function mergeTsx() {
  const attributes = readFile(ATTR_FILE);
  const tsx = readFile(TSX_FILE);

  const tsxWithoutImport = stripAttributesImport(tsx).trimStart();

  // Place attributes first, then components tsx types, then main tsx
  const merged = `${attributes.trim()}\n\n${tsxWithoutImport.trim()}\n`;
  return merged;
}

function writeDistFiles(merged) {
  ensureDist();

  // Write merged TS content
  const tsOut = path.join(distDir, "tsx.ts");
  fs.writeFileSync(tsOut, merged, "utf-8");

  // Write string export JS + d.ts
  const escaped = merged
    .replace(/`/g, "\\`")
    .replace(/\\/g, "\\\\")
    .replace(/\$\{/g, "\\${");
  const jsOut = path.join(distDir, "tsx-string-export.js");
  const dtsOut = path.join(distDir, "tsx-string-export.d.ts");

  const js = `// Generated by scripts/build-tsx.mjs\nconst verterTsx = \`${escaped}\`;\nexport default verterTsx;\n`;
  const dts = `declare const verterTsx: string;\nexport default verterTsx;\n`;

  fs.writeFileSync(jsOut, js, "utf-8");
  fs.writeFileSync(dtsOut, dts, "utf-8");
}

function main() {
  const merged = mergeTsx();
  writeDistFiles(merged);
  console.log(
    "✓ Built tsx merged outputs: dist/tsx.ts and dist/tsx-string-export.js"
  );
}

main();
