#![deny(missing_docs)]
//! Renderer for the generated TypeScript virtual-file naming mirror.
//!
//! The Rust [`FrameworkAdapterDescriptor`] table (the
//! [`VirtualFileNaming`] column) is the SINGLE authority for an adapter's
//! IDE / API / testing-API / sidecar virtual-file suffixes. The committed
//! TypeScript module `packages/typescript-plugin/src/generated/virtual-file-naming.ts`
//! is a GENERATED, BYTE-PINNED mirror of that column — the LSP / ts-plugin
//! naming derivations consume it (the consumer rewiring is a later
//! vertical; this lands the column + the mirror + the freshness pin).
//!
//! [`render_virtual_file_naming_ts`] renders the canonical TS module text
//! from the descriptor rows; the freshness test
//! (`crates/verter_session/tests/.../virtual_file_naming_ts_freshness.rs`)
//! byte-compares the committed file against this render, so a hand-edit or
//! a descriptor-row change without a regen fails the gate.

use crate::framework::descriptor::{
    vue_descriptor, FrameworkAdapterDescriptor, IdeSuffixPolicy, VirtualFileNaming,
};

/// The committed path of the generated mirror, relative to the workspace
/// root. The freshness test and any regen path reference this one place.
pub const VIRTUAL_FILE_NAMING_TS_PATH: &str =
    "packages/typescript-plugin/src/generated/virtual-file-naming.ts";

/// Every adapter descriptor that carries a virtual-file naming column, in
/// a deterministic order. Adding an adapter row here (and regenerating)
/// is the only way to extend the mirror.
fn descriptors_with_naming() -> Vec<FrameworkAdapterDescriptor> {
    vec![vue_descriptor()]
}

/// Render the canonical TypeScript mirror module from the descriptor
/// table. The output is deterministic and oxfmt-stable (two-space
/// indent, double quotes, trailing newline) so the byte-pin holds.
#[must_use]
pub fn render_virtual_file_naming_ts() -> String {
    let mut out = String::new();
    out.push_str(HEADER);

    for descriptor in descriptors_with_naming() {
        let Some(naming) = descriptor.virtual_file_naming.as_ref() else {
            continue;
        };
        render_descriptor_entry(&mut out, descriptor.tag_const_name(), naming);
    }

    out.push_str(FOOTER);
    out
}

fn render_descriptor_entry(out: &mut String, tag: &str, naming: &VirtualFileNaming) {
    out.push_str(&format!("  {tag}: {{\n"));
    out.push_str(&format!("    ide: {},\n", render_ide(naming.ide.as_ref())));
    out.push_str(&format!(
        "    apiSuffix: {},\n",
        render_opt_str(naming.api_suffix)
    ));
    out.push_str(&format!(
        "    testingApiSuffix: {},\n",
        render_opt_str(naming.testing_api_suffix)
    ));
    out.push_str(&format!(
        "    sidecarSuffixes: {},\n",
        render_str_array(naming.sidecar_suffixes)
    ));
    out.push_str("  },\n");
}

fn render_ide(ide: Option<&IdeSuffixPolicy>) -> String {
    match ide {
        None => "null".to_string(),
        Some(IdeSuffixPolicy::Fixed(suffix)) => {
            format!("{{ kind: \"fixed\", suffix: {} }}", quote(suffix))
        }
        Some(IdeSuffixPolicy::JsxConditional { jsx, non_jsx }) => format!(
            "{{ kind: \"jsxConditional\", jsx: {}, nonJsx: {} }}",
            quote(jsx),
            quote(non_jsx)
        ),
    }
}

fn render_opt_str(value: Option<&str>) -> String {
    match value {
        None => "null".to_string(),
        Some(s) => quote(s),
    }
}

fn render_str_array(values: &[&str]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let inner: Vec<String> = values.iter().map(|s| quote(s)).collect();
    format!("[{}]", inner.join(", "))
}

/// Quote a string as a TS double-quoted literal. The suffixes are static
/// adapter constants (`.ts`, `.tsx`, …) with no embedded quotes or
/// backslashes, so a plain wrap is exact.
fn quote(s: &str) -> String {
    format!("\"{s}\"")
}

impl FrameworkAdapterDescriptor {
    /// The TS object-key constant name for this adapter's tag (the wire
    /// tag's `as_str_name`, e.g. `FRAMEWORK_TAG_VUE`), used as the mirror
    /// map key so the generated module is keyed by the closed wire tag.
    fn tag_const_name(&self) -> &'static str {
        self.tag.as_str_name()
    }
}

const HEADER: &str = r#"// @generated by verter — DO NOT EDIT BY HAND.
//
// Mirror of the Rust framework-adapter virtual-file naming column
// (`crates/verter_session/src/framework/descriptor.rs`). The descriptor
// table is the single authority; this file is rendered from it and
// byte-pinned by `virtual_file_naming_ts_freshness`. Regenerate via that
// test's update path after any descriptor-row change.
//
// Keyed by the closed wire `FrameworkTag` name (`as_str_name`). All
// suffixes append to the FULL carrier canonical (e.g. `App.vue` + `.ts`
// => `App.vue.ts`).

export interface VirtualFileIdeFixed {
  kind: "fixed";
  suffix: string;
}

export interface VirtualFileIdeJsxConditional {
  kind: "jsxConditional";
  jsx: string;
  nonJsx: string;
}

export type VirtualFileIdePolicy = VirtualFileIdeFixed | VirtualFileIdeJsxConditional;

export interface VirtualFileNaming {
  ide: VirtualFileIdePolicy | null;
  apiSuffix: string | null;
  testingApiSuffix: string | null;
  sidecarSuffixes: string[];
}

export const VIRTUAL_FILE_NAMING: Readonly<Record<string, VirtualFileNaming>> = {
"#;

const FOOTER: &str = "};\n";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic_and_contains_the_vue_row() {
        let a = render_virtual_file_naming_ts();
        let b = render_virtual_file_naming_ts();
        assert_eq!(a, b, "render must be deterministic");

        // The Vue row's live column must surface verbatim.
        assert!(a.contains("FRAMEWORK_TAG_VUE: {"));
        assert!(a.contains("kind: \"jsxConditional\", jsx: \".jsx\", nonJsx: \".tsx\""));
        assert!(a.contains("apiSuffix: \".ts\""));
        assert!(a.contains("testingApiSuffix: \".__verter_test.ts\""));
        assert!(a.contains("sidecarSuffixes: []"));
        // No descriptor without naming leaks an empty entry.
        assert!(a.ends_with("};\n"));
    }

    #[test]
    fn render_starts_with_the_do_not_edit_banner() {
        let rendered = render_virtual_file_naming_ts();
        assert!(rendered.starts_with("// @generated by verter — DO NOT EDIT BY HAND.\n"));
    }
}
