// @generated by verter — DO NOT EDIT BY HAND.
//
// The tag-discriminated host compile request the native adapter decodes,
// projected from the Rust declarations that decode it. Regenerate with
// `pnpm gen:host-request-ts`; a hand edit, or a Rust change without a
// regen, fails the freshness guard.
//
// Every rule below is the decoder's, not a convention:
//
// - Every object is closed. A key outside its declared set is refused at
//   decode, including a key that belongs to the other framework's arm or
//   to another product.
// - Every non-optional field is required. An absent key is a refusal, not
//   a substituted value.
// - An optional field may be omitted, or set to `undefined` or `null`;
//   all three read as absent, and what absent MEANS is decided by the
//   compiler, not here.
// - Every string union is closed. A spelling outside it is refused at
//   decode. A slot typed `string` is forwarded verbatim: the wire owns no
//   vocabulary over it, and whether one exists elsewhere is that slot's
//   own business, not this shape's.
//
// Nothing in this shape decides whether a compile is legal: the product
// set, the backend/product pairing and option support are the compiler's
// own rules, reported as its own refusals after the request is accepted.

export interface HostAnalysisProductOptions {
  wantScriptBindings: boolean;
  wantTemplateData: boolean;
}

/**
 * Dev-server tooling flavour for Main-assembly decoration. Wire spellings
 * are all-lowercase, matching the legacy `FfiCompileProfile.hmr_strategy`
 * vocabulary (`"none"` / `"vite"` / `"webpack"`).
 */
export type HostHmrStrategy = "none" | "vite" | "webpack";

/**
 * Source identity and dev/prod profile shared by every product requested
 * in one compile.
 */
export interface HostCompileIdentity {
  filename?: string | null;
  componentId?: string | null;
  isProduction: boolean;
  forceJs: boolean;
  /**
   * The `ssrContext.modules` manifest key form — root-relative under
   * Vite; absent falls back to the canonical id. Exactly the legacy
   * `FfiCompileProfile.ssr_module_id` semantics.
   */
  ssrModuleId?: string | null;
  /**
   * Dev-server tooling flavour gating the natively composed `__file`
   * and hot-accept trailer; absent = no decoration. The Svelte Main
   * assembly has no decoration consumer, matching the legacy profile
   * where the field is inert for Svelte.
   */
  hmrStrategy?: HostHmrStrategy | null;
}

export interface HostIdeProductOptions {
  wantSourceMap: boolean;
  embedAmbientTypes: boolean;
  conditionalRootNarrowing: boolean;
  strictSlots: boolean;
  typesModuleName?: string | null;
  ideChunkBoundaries: boolean;
}

/**
 * Which part of Vue's style cascade a runtime product owns. Wire spellings
 * match the legacy profile route's `styleProcessing` and the canonical
 * [`verter_compiler::compile_request::RuntimeStyleProcessing::wire_name`]:
 * kebab-case, so `AuthoredOnly` is `"authored-only"`, not the `camelCase`
 * container default's `authoredOnly`.
 */
export type HostRuntimeStyleProcessing = "complete" | "authored-only";

export interface HostRuntimeProductOptions {
  /**
   * Absent resolves to the request's own `isProduction` — the framework's
   * documented derivation, computed by the canonical request rather than
   * substituted here.
   */
  inline?: boolean | null;
  runtimeSourceMap: boolean;
  /**
   * Style-pipeline ownership for this runtime product. Absent selects the
   * compiler-owned complete authored-to-published cascade; the
   * bundler-owned style lane states `"authored-only"`.
   */
  styleProcessing?: HostRuntimeStyleProcessing | null;
}

/**
 * Presence-only marker for the `compatibility` object: the one inventoried
 * field it may carry (`componentApi`) is refused, so it has no wire slot.
 */
export type HostSvelteCompatibility = Record<string, never>;

export type HostSvelteCss = "injected" | "external";

export interface HostSvelteCustomElementProp {
  attribute?: string | null;
  reflect?: boolean | null;
  /**
   * The caller's prop-type spelling, carried verbatim. The wire owns no
   * membership over the custom-element prop-type vocabulary: an
   * unrecognised spelling decodes fine here and is refused at canonical
   * request construction, the one place that decides the vocabulary, so
   * this boundary cannot drift from it or refuse at a different stage
   * than the direct canonical entry point does.
   */
  propType?: string | null;
}

export interface HostSvelteCustomElementDescriptor {
  tag?: string | null;
  shadow?: boolean | null;
  props: { [key in string]: HostSvelteCustomElementProp };
}

export type HostSvelteFragments = "html" | "tree";

export type HostSvelteNamespace = "html" | "svg" | "mathMl" | "foreign";

export type HostSvelteRunes = "true" | "false" | "infer";

/**
 * Svelte-owned compile options. `generateModule` / `experimentalAsync`
 * are well-formed options whose module-compilation capability is refused;
 * the trailing slots are the unconditionally refused rows.
 */
export interface HostSvelteCompileOptions {
  dev?: boolean | null;
  generateModule?: boolean | null;
  experimentalAsync?: boolean | null;
  customElement?: boolean | null;
  customElementDescriptor?: HostSvelteCustomElementDescriptor | null;
  namespace?: HostSvelteNamespace | null;
  css?: HostSvelteCss | null;
  preserveComments?: boolean | null;
  preserveWhitespace?: boolean | null;
  fragments?: HostSvelteFragments | null;
  runes?: HostSvelteRunes | null;
  discloseVersion?: boolean | null;
  compatibility?: HostSvelteCompatibility | null;
  loose?: boolean | null;
  accessors?: boolean | null;
  immutable?: boolean | null;
  compatibilityComponentApi?: boolean | null;
  hmr?: boolean | null;
  customElementExtend?: boolean | null;
}

export interface HostVueAssetUrlOptions {
  base?: string | null;
  includeAbsolute?: boolean | null;
  tags: { [key in string]: Array<string> };
}

export type HostVueAssetUrlTransform = "disabled" | { "enabled": HostVueAssetUrlOptions };

/**
 * Which Vue client codegen backend a runtime product resolves to.
 * `Inferred` defers to the parsed source's own marker.
 */
export type HostVueBackend = "inferred" | "vdom" | "vapor";

export type HostVueCssModuleLocalsConvention =
  | "camelCase"
  | "camelCaseOnly"
  | "dashes"
  | "dashesOnly"
  | "asIs";

export type HostVueCssModuleScopeBehaviour = "local" | "global";

export interface HostVueCssModules {
  scopeBehaviour?: HostVueCssModuleScopeBehaviour | null;
  hashPrefix?: string | null;
  localsConvention?: HostVueCssModuleLocalsConvention | null;
  exportGlobals?: boolean | null;
}

export type HostVueParsePad = "space" | "line" | "off";

export type HostVueWhitespace = "preserve" | "condense";

/**
 * Vue-owned compile options. The trailing `compatConfig*` / `codegenMode`
 * slots exist only so a caller who supplies a refused option is told which
 * one — presence is what the conversion refuses, `false` included.
 */
export interface HostVueCompileOptions {
  backend: HostVueBackend;
  /**
   * Mirrors the canonical `ssr` OPTION one-for-one. It is not the SSR
   * demand: whether a compile produces server output is derived from
   * the requested product set, and that derivation stays the canonical
   * request's. The two are independent — this flag disagreeing with the
   * requested products is not refused when the request is constructed.
   */
  ssr: boolean;
  isCustomElement: Array<string>;
  /**
   * Exactly two elements; any other length is a typed malformed-value
   * refusal, never a fallback to the framework's own delimiters.
   */
  delimiters?: Array<string> | null;
  whitespace?: HostVueWhitespace | null;
  comments?: boolean | null;
  hoistStatic?: boolean | null;
  cacheHandlers?: boolean | null;
  hmr?: boolean | null;
  optimizeImports?: boolean | null;
  runtimeModuleName?: string | null;
  ssrRuntimeModuleName?: string | null;
  parsePad?: HostVueParsePad | null;
  ignoreEmpty?: boolean | null;
  babelParserPlugins: Array<string>;
  genDefaultAs?: string | null;
  propsDestructure?: boolean | null;
  scriptCustomElement?: boolean | null;
  transformAssetUrls?: HostVueAssetUrlTransform | null;
  styleTrim?: boolean | null;
  cssModules?: HostVueCssModules | null;
  compatConfig?: boolean | null;
  compatConfigMode?: boolean | null;
  compatConfigCompilerIsOnElement?: boolean | null;
  compatConfigCompilerVBindSync?: boolean | null;
  compatConfigCompilerVIfVForPrecedence?: boolean | null;
  compatConfigCompilerVBindObjectOrder?: boolean | null;
  compatConfigCompilerVOnNative?: boolean | null;
  compatConfigCompilerNativeTemplate?: boolean | null;
  compatConfigCompilerInlineTemplate?: boolean | null;
  compatConfigCompilerFilters?: boolean | null;
  transformCompatConfig?: boolean | null;
  codegenMode?: boolean | null;
}

export type HostRuntimeClientProduct = { kind: "runtimeClient" } & HostRuntimeProductOptions;

export type HostRuntimeServerProduct = { kind: "runtimeServer" } & HostRuntimeProductOptions;

export type HostIdeCompanionProduct = { kind: "ideCompanion" } & HostIdeProductOptions;

/**
 * Carries no options: its output is shaped by host-resolved
 * profile identities the caller never supplies.
 */
export type HostPublicApiProduct = { kind: "publicApi" };

/**
 * Carries no options, for the same reason as `publicApi`.
 */
export type HostDeclarationsProduct = { kind: "declarations" };

export type HostAnalysisProduct = { kind: "analysis" } & HostAnalysisProductOptions;

/**
 * One requested compiler product. The product set is the demand
 * document: there is no target preset that expands into a bundle of
 * products, and request order is preserved.
 *
 * An arm that carries no options carries nothing but its tag:
 * `{ "kind": "publicApi", "inline": true }` is a refusal, not a
 * silently ignored option.
 */
export type HostRequestedProduct =
  | HostRuntimeClientProduct
  | HostRuntimeServerProduct
  | HostIdeCompanionProduct
  | HostPublicApiProduct
  | HostDeclarationsProduct
  | HostAnalysisProduct;

export interface HostVueCompileRequest {
  framework: "vue";
  identity: HostCompileIdentity;
  products: Array<HostRequestedProduct>;
  options: HostVueCompileOptions;
}

export interface HostSvelteCompileRequest {
  framework: "svelte";
  identity: HostCompileIdentity;
  products: Array<HostRequestedProduct>;
  options: HostSvelteCompileOptions;
}

/**
 * A host compile request tagged by `framework`, so framework-owned
 * options are structurally unreachable from the other framework's arm
 * and a foreign key inside either arm is refused at decode.
 */
export type HostCompileRequest =
  | HostVueCompileRequest
  | HostSvelteCompileRequest;
