//! Resilient `TypeProvider` wrapper.
//!
//! Wraps a `TypeProvider` (tsserver / TSGO) so a backend crash transparently
//! respawns the process and replays the desired editor state into the fresh
//! instance.
//!
//! # Single-writer actor
//!
//! All replayed state — the open/loaded file set, inferred-project path configs,
//! workspace folders, and published carrier-companion registrations — together
//! with the live inner provider are owned by ONE actor task. Callers never touch
//! that state directly: every state change is a typed [`Command`] sent over a
//! channel, and the actor serialises mutation against the crash/respawn
//! lifecycle.
//!
//! Because the actor owns the desired-state set, the replay that follows a
//! respawn reads the set as it is at install time — there is no snapshot taken
//! at crash time that a later mutation could race:
//!
//! * a file closed (or a carrier retracted, or content updated) before the fresh
//!   provider goes live is absent from / current in the replay;
//! * a mutation issued WHILE restarting is either folded into the replay or
//!   applied to the provider after it goes live — never lost, never observed
//!   half-applied (no caller ever sees a partially replayed provider).
//!
//! Carrier registration needs no separate serialization lock: there is no guard
//! to hold across a snapshot/replay/swap, because there is no snapshot and no
//! swap-of-shared-maps — the actor IS the serialization point.
//!
//! # Lock discipline
//!
//! No synchronous guard (`RwLock` / mutex / map guard) is ever held across an
//! `.await` or a channel send. A command/payload is built while holding any
//! guard, the guard is dropped, and only then is the send / provider call
//! awaited. The crate denies `clippy::await_holding_lock` to keep this enforced.

use std::collections::hash_map::Entry;
use std::collections::{HashMap, HashSet};
use std::future::Future;
use std::hash::{Hash, Hasher};
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::{Arc, Mutex as StdMutex};
use std::time::{Duration, Instant};

use tokio::sync::{mpsc, oneshot, Notify, RwLock};

use crate::protocol::*;
use crate::traits::{ProviderFuture, TypeProvider};

/// Notification severity levels for provider events.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NotifySeverity {
    Info,
    Warning,
    Error,
}

/// Notification interface for provider lifecycle events.
///
/// The LSP implements this to call `client.show_message()`.
/// Component-meta can use a logging-only or no-op implementation.
pub trait ProviderNotifier: Send + Sync + 'static {
    fn notify(&self, severity: NotifySeverity, message: String);
}

/// No-op notifier (logs via tracing only).
pub struct TracingNotifier;

impl ProviderNotifier for TracingNotifier {
    fn notify(&self, severity: NotifySeverity, message: String) {
        match severity {
            NotifySeverity::Info => tracing::info!("{}", message),
            NotifySeverity::Warning => tracing::warn!("{}", message),
            NotifySeverity::Error => tracing::error!("{}", message),
        }
    }
}

type SpawnFuture<'a, P> = Pin<Box<dyn Future<Output = Result<P, TypeProviderError>> + Send + 'a>>;

pub trait ResilientBackend<P>: Send + Sync + 'static
where
    P: TypeProvider + Send + Sync + 'static,
{
    fn log_name(&self) -> &'static str;

    fn user_label(&self) -> &'static str;

    fn restarting_error(&self) -> &'static str;

    fn spawn<'a>(&'a self, crash_notify: Arc<Notify>) -> SpawnFuture<'a, P>;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CachedFileMode {
    Load,
    Open,
}

#[derive(Debug, Clone)]
struct CachedFile {
    content: String,
    mode: CachedFileMode,
}

#[derive(Debug, Clone)]
struct CachedPathConfig {
    base_url: String,
    paths: serde_json::Value,
}

/// A published carrier-companion registration retained across a provider respawn.
///
/// Keyed by the companion path. `content` is the carrier's generated bytes kept
/// ONLY for the inner provider's local position conversion (never the user's
/// editor buffer, never forwarded to the engine); `project_file_name` is the
/// owning configured-project tsconfig the carrier routes its queries to. On a
/// respawn this is replayed via the CONTENTLESS `register_carrier_member` path —
/// NOT through the file set / `open_file` (which would wrongly make the engine
/// the carrier's content authority).
#[derive(Debug, Clone)]
struct CachedCarrier {
    source_path: String,
    content: String,
    project_file_name: String,
}

/// The provider priority lane a forwarded file mutation should use.
#[derive(Debug, Clone, Copy)]
enum Lane {
    Foreground,
    Background,
    Normal,
}

/// A provider-agnostic desired-state mutation.
///
/// The actor records the durable effect (the file set / path configs / folders /
/// carrier registrations) and forwards the same intent to the live provider.
#[derive(Debug)]
enum DesiredMutation {
    Open {
        path: String,
        content: String,
    },
    Load {
        path: String,
        content: String,
    },
    Update {
        path: String,
        content: String,
    },
    Close {
        path: String,
    },
    ConfigurePaths {
        base_url: String,
        paths: serde_json::Value,
    },
    UpdateWorkspaceFolders {
        added: Vec<serde_json::Value>,
        removed: Vec<serde_json::Value>,
    },
    RegisterCarrier {
        source_path: String,
        companion_path: String,
        content: String,
        project_file_name: String,
    },
}

/// Commands the single-writer actor serialises.
///
/// Every variant carries an ack channel so the submitter observes completion in
/// order: a caller's mutation resolves only once it has been applied to the
/// desired-state set and forwarded; the crash monitor's `Crashed`/`GoLive`
/// resolve only once the live cell has been cleared / installed.
enum Command<P> {
    /// Apply a desired-state mutation and forward it to the live provider (if one
    /// is currently live; otherwise the mutation is retained for replay).
    Mutate {
        mutation: DesiredMutation,
        lane: Lane,
        ack: oneshot::Sender<Result<(), TypeProviderError>>,
    },
    /// The live provider crashed: drop it so queries fail closed while we
    /// respawn.
    Crashed { ack: oneshot::Sender<()> },
    /// A fresh provider is ready: replay the current desired-state set into it,
    /// THEN install it as live. No caller observes the provider before the replay
    /// completes.
    GoLive {
        provider: Arc<P>,
        ack: oneshot::Sender<()>,
    },
}

struct ResilientState<P, B>
where
    P: TypeProvider + Send + Sync + 'static,
    B: ResilientBackend<P>,
{
    /// The live provider cell. Read by queries; written ONLY by the actor.
    inner: Arc<RwLock<Option<Arc<P>>>>,
    /// Command channel into the single-writer actor. Unbounded so a send never
    /// blocks/awaits on capacity (so a send can never stall behind backpressure);
    /// ordering + flow control come from the per-command ack.
    commands: mpsc::UnboundedSender<Command<P>>,
    notifier: Arc<dyn ProviderNotifier>,
    backend: B,
    restart_count: AtomicU32,
    max_restarts: u32,
    /// Deliberate-teardown intent. Set by `shutdown()` BEFORE the inner provider
    /// is torn down, so the crash monitor recognizes the resulting crash-notify
    /// wake as the requested teardown: no user-facing "crashed. Restarting"
    /// notification, no respawn into a dying session.
    torn_down: AtomicBool,
    /// Crash-quarantine bookkeeping for read-only queries. See [`QueryWatch`].
    query_watch: Arc<StdMutex<QueryWatch>>,
}

/// How long an errored query fingerprint stays eligible for crash attribution.
/// A child's death surfaces to in-flight callers as transport errors that can
/// race the crash monitor's wake by a scheduler tick; anything that errored
/// within this narrow window of the crash is treated as having been in flight
/// at the death. Deliberately SHORT: a wide window would implicate every
/// bystander that failed while the engine was down.
const QUARANTINE_RECENT_ERROR_TTL: Duration = Duration::from_millis(500);

/// Bound on the recently-errored ring (memory fuse; oldest entries drop first).
const QUARANTINE_RECENT_ERROR_CAP: usize = 64;

/// Crash implications before a fingerprint is quarantined.
///
/// Attribution is ambiguous at a single crash: the in-flight set holds the
/// killer AND innocent bystanders (diagnostics pulls, concurrent hovers), and a
/// bystander that merely failed during the crash must be servable after
/// recovery (the real-provider recovery regression pins that contract). A
/// GENUINE killer distinguishes itself by RECURRENCE: replayed after the
/// restart, it is in flight at the next death too. Two consecutive
/// implications quarantine it — breaking the crash-restart loop on the second
/// cycle, well inside the restart budget — while a bystander's strike is
/// erased by its first successful completion.
const QUARANTINE_STRIKE_THRESHOLD: u32 = 2;

/// Identity of a read-only provider query, precise enough that quarantining it
/// blocks exactly the request shape that killed the engine and nothing else.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
struct QueryFingerprint {
    method: &'static str,
    path: String,
    offset: u64,
    extra: u64,
}

impl QueryFingerprint {
    fn new(method: &'static str, path: &str, offset: u64, extra: u64) -> Self {
        Self {
            method,
            path: path.to_string(),
            offset,
            extra,
        }
    }
}

/// Hash auxiliary request payload (trigger characters, resolve data) into the
/// fingerprint's `extra` dimension.
fn hash_extra(payload: &str) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    payload.hash(&mut hasher);
    hasher.finish()
}

/// Crash-quarantine bookkeeping.
///
/// Every crash implicates the requests in flight at the death (plus those that
/// errored within [`QUARANTINE_RECENT_ERROR_TTL`] of it — the transport-error
/// vs monitor-wake race). An implication is a STRIKE; at
/// [`QUARANTINE_STRIKE_THRESHOLD`] consecutive strikes the fingerprint is
/// QUARANTINED: never again replayed verbatim into the restarted engine — the
/// identical request killed the engine repeatedly and would burn the restart
/// budget in an infinite crash-restart loop. A quarantined request fails
/// closed (empty result) while the restarted engine keeps serving everything
/// else. A fingerprint's strikes are erased by its first successful
/// completion (bystanders self-heal), and a path's whole attribution clears
/// when its content changes (the same position against new content is a NEW
/// request).
#[derive(Default)]
struct QueryWatch {
    /// Fingerprints currently in flight against the live provider (multiset).
    in_flight: HashMap<QueryFingerprint, u32>,
    /// Fingerprints that recently completed with an error, with their
    /// completion instant (crash attribution window).
    recent_errors: Vec<(QueryFingerprint, Instant)>,
    /// Consecutive crash implications per fingerprint (no successful
    /// completion in between).
    strikes: HashMap<QueryFingerprint, u32>,
    /// Fingerprints attributed to repeated engine crashes: never replayed.
    quarantined: HashSet<QueryFingerprint>,
}

impl QueryWatch {
    fn begin(&mut self, fp: &QueryFingerprint) {
        *self.in_flight.entry(fp.clone()).or_insert(0) += 1;
    }

    fn end(&mut self, fp: &QueryFingerprint, ok: bool) {
        if let Some(count) = self.in_flight.get_mut(fp) {
            if *count > 1 {
                *count -= 1;
            } else {
                self.in_flight.remove(fp);
            }
        }
        if ok {
            // A successful completion proves the request does not kill the
            // engine — erase its crash strikes (bystander self-heal).
            self.strikes.remove(fp);
        } else {
            let now = Instant::now();
            self.recent_errors
                .retain(|(_, at)| now.duration_since(*at) < QUARANTINE_RECENT_ERROR_TTL);
            if self.recent_errors.len() >= QUARANTINE_RECENT_ERROR_CAP {
                self.recent_errors.remove(0);
            }
            self.recent_errors.push((fp.clone(), now));
        }
    }

    fn is_quarantined(&self, fp: &QueryFingerprint) -> bool {
        self.quarantined.contains(fp)
    }

    /// Attribute a crash: strike everything in flight now plus everything that
    /// errored within the race window; quarantine repeat offenders.
    fn record_crash_implications(&mut self) {
        let now = Instant::now();
        let mut implicated: HashSet<QueryFingerprint> = self.in_flight.keys().cloned().collect();
        for (fp, at) in self.recent_errors.drain(..) {
            if now.duration_since(at) < QUARANTINE_RECENT_ERROR_TTL {
                implicated.insert(fp);
            }
        }
        for fp in implicated {
            let strikes = self.strikes.entry(fp.clone()).or_insert(0);
            *strikes += 1;
            if *strikes >= QUARANTINE_STRIKE_THRESHOLD {
                tracing::warn!(
                    "query {} {}@{} was in flight at {} consecutive engine crashes — \
                     quarantined (fails closed until the file changes)",
                    fp.method,
                    fp.path,
                    fp.offset,
                    strikes,
                );
                self.quarantined.insert(fp);
            }
        }
    }

    /// A content change for `path` invalidates its crash attribution.
    fn clear_path(&mut self, path: &str) {
        self.quarantined.retain(|fp| fp.path != path);
        self.strikes.retain(|fp, _| fp.path != path);
        self.recent_errors.retain(|(fp, _)| fp.path != path);
    }
}

/// RAII in-flight registration: completes as ok/err, or — when dropped without
/// completing (caller cancellation racing the engine's death) — conservatively
/// as an error so the crash window still sees it.
struct InFlightGuard {
    watch: Arc<StdMutex<QueryWatch>>,
    fp: Option<QueryFingerprint>,
}

impl InFlightGuard {
    fn begin(watch: Arc<StdMutex<QueryWatch>>, fp: QueryFingerprint) -> Self {
        watch
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .begin(&fp);
        Self {
            watch,
            fp: Some(fp),
        }
    }

    fn complete(mut self, ok: bool) {
        if let Some(fp) = self.fp.take() {
            self.watch
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .end(&fp, ok);
        }
    }
}

impl Drop for InFlightGuard {
    fn drop(&mut self) {
        if let Some(fp) = self.fp.take() {
            self.watch
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .end(&fp, false);
        }
    }
}

pub struct ResilientProvider<P, B>
where
    P: TypeProvider + Send + Sync + 'static,
    B: ResilientBackend<P>,
{
    state: Arc<ResilientState<P, B>>,
}

impl<P, B> ResilientProvider<P, B>
where
    P: TypeProvider + Send + Sync + 'static,
    B: ResilientBackend<P>,
{
    pub fn new(
        provider: P,
        crash_notify: Arc<Notify>,
        backend: B,
        notifier: Arc<dyn ProviderNotifier>,
        max_restarts: u32,
    ) -> Self {
        let inner = Arc::new(RwLock::new(Some(Arc::new(provider))));
        let (commands, command_rx) = mpsc::unbounded_channel();
        let log_name = backend.log_name();

        let state = Arc::new(ResilientState {
            inner: Arc::clone(&inner),
            commands,
            notifier,
            backend,
            restart_count: AtomicU32::new(0),
            max_restarts,
            torn_down: AtomicBool::new(false),
            query_watch: Arc::new(StdMutex::new(QueryWatch::default())),
        });

        tokio::spawn(run_actor(command_rx, inner, log_name));
        spawn_crash_monitor(Arc::clone(&state), crash_notify);

        Self { state }
    }

    async fn get_inner(&self) -> Result<Arc<P>, TypeProviderError> {
        // Clone the live provider out from under the read guard; the guard is
        // dropped at the end of the statement, before the caller awaits the
        // forwarded provider call.
        self.state
            .inner
            .read()
            .await
            .clone()
            .ok_or_else(|| TypeProviderError::new(self.state.backend.restarting_error()))
    }

    /// Submit a desired-state mutation to the actor and await its application.
    ///
    /// The command is built and enqueued without holding any guard; the only
    /// await is on the actor's ack.
    async fn submit_mutation(
        &self,
        mutation: DesiredMutation,
        lane: Lane,
    ) -> Result<(), TypeProviderError> {
        // A content mutation invalidates the mutated path's crash attribution:
        // the same position against NEW content is a new request, so it must be
        // released from quarantine once the mutation has been applied.
        let quarantine_clear = match &mutation {
            DesiredMutation::Open { path, .. }
            | DesiredMutation::Load { path, .. }
            | DesiredMutation::Update { path, .. }
            | DesiredMutation::Close { path } => Some(path.clone()),
            DesiredMutation::RegisterCarrier { companion_path, .. } => Some(companion_path.clone()),
            DesiredMutation::ConfigurePaths { .. }
            | DesiredMutation::UpdateWorkspaceFolders { .. } => None,
        };
        let (ack, ack_rx) = oneshot::channel();
        self.state
            .commands
            .send(Command::Mutate {
                mutation,
                lane,
                ack,
            })
            .map_err(|_| TypeProviderError::new(self.state.backend.restarting_error()))?;
        let result = ack_rx
            .await
            .map_err(|_| TypeProviderError::new(self.state.backend.restarting_error()))?;
        if result.is_ok() {
            if let Some(path) = quarantine_clear {
                self.state
                    .query_watch
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .clear_path(&path);
            }
        }
        result
    }

    /// Run a read-only provider query under crash quarantine.
    ///
    /// A fingerprint attributed to an engine crash is NEVER replayed into the
    /// (restarted) engine: it fails closed with `fail_closed()` instead —
    /// preventing the identical killer request from re-crashing the fresh
    /// process in an infinite crash-restart loop. Everything else registers as
    /// in-flight for the crash monitor's attribution window.
    async fn run_guarded<T, F, Fut>(
        &self,
        fp: QueryFingerprint,
        fail_closed: impl FnOnce() -> T,
        run: F,
    ) -> Result<T, TypeProviderError>
    where
        F: FnOnce(Arc<P>) -> Fut,
        Fut: Future<Output = Result<T, TypeProviderError>>,
    {
        let provider = self.get_inner().await?;
        let quarantined = {
            let watch = self
                .state
                .query_watch
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner());
            watch.is_quarantined(&fp)
        };
        if quarantined {
            tracing::warn!(
                "{} query {} {}@{} is quarantined after an engine crash — failing closed \
                 (a content change to the file lifts the quarantine)",
                self.state.backend.log_name(),
                fp.method,
                fp.path,
                fp.offset,
            );
            return Ok(fail_closed());
        }
        let guard = InFlightGuard::begin(Arc::clone(&self.state.query_watch), fp);
        let result = run(provider).await;
        guard.complete(result.is_ok());
        result
    }
}

/// The single-writer actor loop.
///
/// Owns the desired-state set (no locks — it is task-local) and is the sole
/// writer of the shared live-provider cell.
async fn run_actor<P>(
    mut command_rx: mpsc::UnboundedReceiver<Command<P>>,
    inner: Arc<RwLock<Option<Arc<P>>>>,
    log_name: &'static str,
) where
    P: TypeProvider + Send + Sync + 'static,
{
    let mut state = DesiredState::default();

    while let Some(command) = command_rx.recv().await {
        match command {
            Command::Mutate {
                mutation,
                lane,
                ack,
            } => {
                state.apply(&mutation);
                // Snapshot the live provider Arc, drop the read guard, THEN await.
                let live = {
                    let guard = inner.read().await;
                    guard.clone()
                };
                let result = match live {
                    Some(provider) => forward(provider.as_ref(), &mutation, lane).await,
                    // No live provider yet (mid-restart): the mutation is now in
                    // the desired-state set and will be replayed on go-live.
                    None => Ok(()),
                };
                let _ = ack.send(result);
            }
            Command::Crashed { ack } => {
                let crashed = {
                    let mut guard = inner.write().await;
                    guard.take()
                };
                if let Some(provider) = crashed {
                    // Clear the live cell before awaiting teardown so queries fail
                    // closed. Owned providers then kill/reap their crashed child under
                    // their bounded shutdown contract before respawn is admitted.
                    let _ = provider.shutdown().await;
                }
                let _ = ack.send(());
            }
            Command::GoLive { provider, ack } => {
                // Replay the CURRENT desired-state set (built from every command
                // processed before this one) into the fresh provider, then make
                // it live. No caller can observe it until install completes.
                state.replay_into(provider.as_ref(), log_name).await;
                {
                    let mut guard = inner.write().await;
                    *guard = Some(provider);
                }
                let _ = ack.send(());
            }
        }
    }
}

/// The actor-owned desired editor state: the authority the replay reads from.
#[derive(Default)]
struct DesiredState {
    files: HashMap<String, CachedFile>,
    path_configs: Vec<CachedPathConfig>,
    workspace_folders: Vec<serde_json::Value>,
    carrier_registrations: HashMap<String, CachedCarrier>,
}

impl DesiredState {
    /// Record a mutation's durable effect.
    fn apply(&mut self, mutation: &DesiredMutation) {
        match mutation {
            DesiredMutation::Open { path, content } => {
                self.cache_file(path, content, Some(CachedFileMode::Open))
            }
            DesiredMutation::Load { path, content } => {
                self.cache_file(path, content, Some(CachedFileMode::Load))
            }
            DesiredMutation::Update { path, content } => self.cache_file(path, content, None),
            DesiredMutation::Close { path } => {
                self.files.remove(path);
                // A closed companion must not be replayed as a carrier after a
                // respawn — dropping its registration keeps a retracted carrier
                // from re-entering the fresh provider (fail-closed across restart).
                self.carrier_registrations.remove(path);
            }
            DesiredMutation::ConfigurePaths { base_url, paths } => {
                self.cache_path_config(base_url, paths.clone())
            }
            DesiredMutation::UpdateWorkspaceFolders { added, removed } => {
                self.cache_workspace_folders(added, removed)
            }
            DesiredMutation::RegisterCarrier {
                source_path,
                companion_path,
                content,
                project_file_name,
            } => {
                self.carrier_registrations.insert(
                    companion_path.clone(),
                    CachedCarrier {
                        source_path: source_path.clone(),
                        content: content.clone(),
                        project_file_name: project_file_name.clone(),
                    },
                );
            }
        }
    }

    /// Insert/refresh a file, preserving `open` > `load` priority: an opened file
    /// is never downgraded to load-only, and an update keeps the existing mode.
    fn cache_file(&mut self, path: &str, content: &str, mode: Option<CachedFileMode>) {
        match self.files.entry(path.to_string()) {
            Entry::Occupied(mut entry) => {
                let cached = entry.get_mut();
                cached.content = content.to_string();
                if let Some(next_mode) = mode {
                    match next_mode {
                        CachedFileMode::Open => cached.mode = CachedFileMode::Open,
                        CachedFileMode::Load if cached.mode != CachedFileMode::Open => {
                            cached.mode = CachedFileMode::Load;
                        }
                        CachedFileMode::Load => {}
                    }
                }
            }
            Entry::Vacant(entry) => {
                entry.insert(CachedFile {
                    content: content.to_string(),
                    mode: mode.unwrap_or(CachedFileMode::Open),
                });
            }
        }
    }

    fn cache_path_config(&mut self, base_url: &str, paths: serde_json::Value) {
        if let Some(existing) = self
            .path_configs
            .iter_mut()
            .find(|config| config.base_url == base_url)
        {
            existing.paths = paths;
            return;
        }
        self.path_configs.push(CachedPathConfig {
            base_url: base_url.to_string(),
            paths,
        });
    }

    fn cache_workspace_folders(
        &mut self,
        added: &[serde_json::Value],
        removed: &[serde_json::Value],
    ) {
        for folder in removed {
            if let Some(uri) = folder.get("uri").and_then(|v| v.as_str()) {
                self.workspace_folders
                    .retain(|existing| existing.get("uri").and_then(|v| v.as_str()) != Some(uri));
            }
        }
        for folder in added {
            if let Some(uri) = folder.get("uri").and_then(|v| v.as_str()) {
                self.workspace_folders
                    .retain(|existing| existing.get("uri").and_then(|v| v.as_str()) != Some(uri));
            }
            self.workspace_folders.push(folder.clone());
        }
    }

    /// Replay the desired-state set into a freshly respawned provider.
    ///
    /// Folders, then path configs, then the file set (preserving each file's
    /// load/open mode), then carrier registrations (CONTENTLESS — the engine-side
    /// plugin remains the carrier's content authority). Replay failures are logged
    /// but never abort the sequence; a later mutation re-establishes the entry.
    async fn replay_into<P: TypeProvider>(&self, provider: &P, log_name: &str) {
        if !self.workspace_folders.is_empty() {
            let _ = provider
                .update_workspace_folders(self.workspace_folders.clone(), Vec::new())
                .await;
        }

        for config in &self.path_configs {
            let _ = provider
                .configure_paths(&config.base_url, config.paths.clone())
                .await;
        }

        for (path, file) in &self.files {
            let result = match file.mode {
                CachedFileMode::Load => provider.load_file(path, &file.content).await,
                CachedFileMode::Open => provider.open_file(path, &file.content).await,
            };
            if let Err(err) = result {
                tracing::warn!(
                    "Failed to replay {} into {} after restart: {}",
                    path,
                    log_name,
                    err
                );
            }
        }

        for (companion_path, carrier) in &self.carrier_registrations {
            if let Err(err) = provider
                .register_carrier_member(
                    &carrier.source_path,
                    companion_path,
                    &carrier.content,
                    &carrier.project_file_name,
                )
                .await
            {
                tracing::warn!(
                    "Failed to re-register carrier {} into {} after restart: {}",
                    companion_path,
                    log_name,
                    err
                );
            }
        }
    }
}

/// Forward a mutation to the live provider on the requested lane.
async fn forward<P: TypeProvider>(
    provider: &P,
    mutation: &DesiredMutation,
    lane: Lane,
) -> Result<(), TypeProviderError> {
    match mutation {
        DesiredMutation::Open { path, content } => match lane {
            Lane::Foreground => provider.open_file(path, content).await,
            Lane::Background => provider.open_file_background(path, content).await,
            Lane::Normal => provider.open_file_normal(path, content).await,
        },
        DesiredMutation::Load { path, content } => match lane {
            Lane::Foreground => provider.load_file(path, content).await,
            Lane::Background => provider.load_file_background(path, content).await,
            Lane::Normal => provider.load_file_normal(path, content).await,
        },
        DesiredMutation::Update { path, content } => match lane {
            Lane::Foreground => provider.update_file(path, content).await,
            Lane::Background => provider.update_file_background(path, content).await,
            Lane::Normal => provider.update_file_normal(path, content).await,
        },
        DesiredMutation::Close { path } => match lane {
            Lane::Foreground => provider.close_file(path).await,
            Lane::Background => provider.close_file_background(path).await,
            Lane::Normal => provider.close_file_normal(path).await,
        },
        DesiredMutation::ConfigurePaths { base_url, paths } => match lane {
            Lane::Background => {
                provider
                    .configure_paths_background(base_url, paths.clone())
                    .await
            }
            Lane::Foreground | Lane::Normal => {
                provider.configure_paths(base_url, paths.clone()).await
            }
        },
        DesiredMutation::UpdateWorkspaceFolders { added, removed } => match lane {
            Lane::Background => {
                provider
                    .update_workspace_folders_background(added.clone(), removed.clone())
                    .await
            }
            Lane::Foreground | Lane::Normal => {
                provider
                    .update_workspace_folders(added.clone(), removed.clone())
                    .await
            }
        },
        // Carrier registration has no priority lanes; the lane is irrelevant.
        DesiredMutation::RegisterCarrier {
            source_path,
            companion_path,
            content,
            project_file_name,
        } => {
            provider
                .register_carrier_member(source_path, companion_path, content, project_file_name)
                .await
        }
    }
}

fn spawn_crash_monitor<P, B>(state: Arc<ResilientState<P, B>>, crash_notify: Arc<Notify>)
where
    P: TypeProvider + Send + Sync + 'static,
    B: ResilientBackend<P>,
{
    tokio::spawn(async move {
        crash_notify.notified().await;

        // TEARDOWN DISCRIMINATION: a deliberate `shutdown()` produces the same
        // crash-notify wake as a real death (the torn-down child's stdout EOF).
        // That is the REQUESTED teardown — reporting it as a crash would mint a
        // spurious user-facing "crashed. Restarting" notification on every
        // clean editor shutdown and respawn an engine into a dying session.
        if state.torn_down.load(Ordering::SeqCst) {
            tracing::debug!(
                "{} exit during deliberate teardown — not a crash",
                state.backend.log_name()
            );
            return;
        }

        tracing::warn!(
            "{} crash detected - initiating restart sequence",
            state.backend.log_name()
        );

        // CRASH QUARANTINE: strike the requests in flight at (or erroring
        // moments before) the death. Whatever killed the engine is in that
        // set; a repeat offender is quarantined and never replayed into the
        // restarted engine again.
        state
            .query_watch
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .record_crash_implications();

        // Drop the live provider through the actor so queries fail closed while
        // we respawn — the actor is the sole writer of the live cell.
        let (cleared, cleared_rx) = oneshot::channel();
        if state
            .commands
            .send(Command::Crashed { ack: cleared })
            .is_err()
        {
            // Actor gone — the wrapper has been torn down.
            return;
        }
        let _ = cleared_rx.await;

        state.notifier.notify(
            NotifySeverity::Warning,
            format!(
                "TypeScript server ({}) crashed. Restarting...",
                state.backend.user_label()
            ),
        );

        // Only this monitor is live at a time (the next one is spawned only after
        // a successful go-live), so the restart counter has a single accessor and
        // needs no lock. Retry a FAILED respawn within this restart sequence: a
        // transient spawn failure (resource pressure, a still-releasing port/pipe)
        // must not leave the provider dead for the rest of the session. Retries
        // share the SAME restart budget (`max_restarts`) and backoff schedule as
        // crash events, so a persistently failing backend still fails closed —
        // bounded, never a hot respawn loop.
        loop {
            // A teardown that lands mid-restart aborts the sequence: never
            // respawn an engine into a session that is shutting down.
            if state.torn_down.load(Ordering::SeqCst) {
                tracing::debug!(
                    "{} teardown during restart sequence — abandoning respawn",
                    state.backend.log_name()
                );
                return;
            }
            let attempt = state.restart_count.fetch_add(1, Ordering::Relaxed) + 1;

            if attempt > state.max_restarts {
                tracing::error!(
                    "{} restart limit reached ({}) - staying in verter-only mode",
                    state.backend.log_name(),
                    state.max_restarts
                );
                state.notifier.notify(
                    NotifySeverity::Error,
                    format!(
                        "TypeScript server ({}) crashed {} times. Running in verter-only mode for the rest of this session.",
                        state.backend.user_label(),
                        state.max_restarts
                    ),
                );
                return;
            }

            let delay_secs = (1u64 << (attempt - 1)).min(4);
            tracing::info!(
                "{} restart attempt {attempt}/{} after {delay_secs}s",
                state.backend.log_name(),
                state.max_restarts
            );
            tokio::time::sleep(std::time::Duration::from_secs(delay_secs)).await;

            let new_crash_notify = Arc::new(Notify::new());
            match state.backend.spawn(Arc::clone(&new_crash_notify)).await {
                Ok(provider) => {
                    let provider = Arc::new(provider);

                    // Replay + install atomically through the actor: the fresh provider
                    // is not made live until the current desired-state set (file set,
                    // path configs, folders, AND carrier registrations) has been
                    // replayed into it.
                    let (live, live_rx) = oneshot::channel();
                    if state
                        .commands
                        .send(Command::GoLive {
                            provider,
                            ack: live,
                        })
                        .is_err()
                    {
                        return;
                    }
                    let _ = live_rx.await;

                    tracing::info!(
                        "{} restarted successfully (attempt {attempt})",
                        state.backend.log_name()
                    );
                    state.notifier.notify(
                        NotifySeverity::Info,
                        "TypeScript server restarted successfully.".to_string(),
                    );

                    state.restart_count.store(0, Ordering::Relaxed);
                    spawn_crash_monitor(state, new_crash_notify);
                    return;
                }
                Err(err) => {
                    tracing::error!(
                        "Failed to restart {} (attempt {attempt}): {}",
                        state.backend.log_name(),
                        err
                    );
                    state.notifier.notify(
                        NotifySeverity::Error,
                        format!("Failed to restart TypeScript server: {err}"),
                    );
                    // Loop: retry against the SAME budget + backoff rather than
                    // leaving the provider permanently dead on a transient failure.
                }
            }
        }
    });
}

impl<P, B> TypeProvider for ResilientProvider<P, B>
where
    P: TypeProvider + Send + Sync + 'static,
    B: ResilientBackend<P>,
{
    fn provider_id(&self) -> &'static str {
        // The wrapped provider's identity is stable across restarts (the backend
        // always respawns the same provider type), so read it from the live
        // inner when present, else fall back to the backend's user label.
        self.state
            .inner
            .try_read()
            .ok()
            .and_then(|guard| guard.as_ref().map(|provider| provider.provider_id()))
            .unwrap_or_else(|| self.state.backend.user_label())
    }

    fn supports_completion_resolve(&self) -> bool {
        self.state
            .inner
            .try_read()
            .ok()
            .and_then(|guard| {
                guard
                    .as_ref()
                    .map(|provider| provider.supports_completion_resolve())
            })
            .unwrap_or(false)
    }

    fn open_file(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Open { path, content }, Lane::Foreground)
                .await
        })
    }

    fn load_file(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Load { path, content }, Lane::Foreground)
                .await
        })
    }

    fn update_file(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Update { path, content }, Lane::Foreground)
                .await
        })
    }

    fn close_file(&self, path: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Close { path }, Lane::Foreground)
                .await
        })
    }

    fn notify_carrier_changed(&self, companion_path: &str) -> ProviderFuture<'_, ()> {
        // Pure engine-cache eviction signal; it changes no desired state, so it
        // bypasses the actor and runs directly against the live provider.
        let path_owned = companion_path.to_string();
        Box::pin(async move {
            let provider = self.get_inner().await?;
            provider.notify_carrier_changed(&path_owned).await
        })
    }

    fn register_carrier_member(
        &self,
        source_path: &str,
        companion_path: &str,
        content: &str,
        project_file_name: &str,
    ) -> ProviderFuture<'_, ()> {
        let source_path = source_path.to_string();
        let companion_path = companion_path.to_string();
        let content = content.to_string();
        let project_file_name = project_file_name.to_string();
        Box::pin(async move {
            self.submit_mutation(
                DesiredMutation::RegisterCarrier {
                    source_path,
                    companion_path,
                    content,
                    project_file_name,
                },
                Lane::Foreground,
            )
            .await
        })
    }

    fn get_completions(
        &self,
        path: &str,
        offset: u32,
        trigger_character: Option<&str>,
    ) -> ProviderFuture<'_, CompletionResult> {
        let path_owned = path.to_string();
        let trigger_owned = trigger_character.map(|s| s.to_string());
        let fp = QueryFingerprint::new(
            "completions",
            path,
            u64::from(offset),
            hash_extra(trigger_character.unwrap_or_default()),
        );
        Box::pin(async move {
            self.run_guarded(
                fp,
                || CompletionResult {
                    items: Vec::new(),
                    is_incomplete: false,
                },
                move |provider| async move {
                    provider
                        .get_completions(&path_owned, offset, trigger_owned.as_deref())
                        .await
                },
            )
            .await
        })
    }

    fn get_hover(&self, path: &str, offset: u32) -> ProviderFuture<'_, Option<HoverInfo>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("hover", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(
                fp,
                || None,
                move |provider| async move { provider.get_hover(&path_owned, offset).await },
            )
            .await
        })
    }

    fn get_diagnostics(&self, path: &str) -> ProviderFuture<'_, Vec<TypeDiagnostic>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("diagnostics", path, 0, 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_diagnostics(&path_owned).await
            })
            .await
        })
    }

    fn get_definition(&self, path: &str, offset: u32) -> ProviderFuture<'_, Vec<TypeLocation>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("definition", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_definition(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_type_definition(
        &self,
        path: &str,
        offset: u32,
    ) -> ProviderFuture<'_, Vec<TypeLocation>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("type_definition", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_type_definition(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_references(&self, path: &str, offset: u32) -> ProviderFuture<'_, Vec<TypeLocation>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("references", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_references(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_rename_locations(
        &self,
        path: &str,
        offset: u32,
    ) -> ProviderFuture<'_, Vec<RenameLocation>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("rename_locations", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_rename_locations(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_signature_help(
        &self,
        path: &str,
        offset: u32,
    ) -> ProviderFuture<'_, Option<SignatureHelp>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("signature_help", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, || None, move |provider| async move {
                provider.get_signature_help(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_code_actions(
        &self,
        path: &str,
        start_offset: u32,
        end_offset: u32,
        diagnostics: &[ProviderDiagnosticContext],
    ) -> ProviderFuture<'_, Vec<TypeCodeAction>> {
        let path_owned = path.to_string();
        let diagnostics = diagnostics.to_vec();
        let fp = QueryFingerprint::new(
            "code_actions",
            path,
            u64::from(start_offset) | (u64::from(end_offset) << 32),
            0,
        );
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider
                    .get_code_actions(&path_owned, start_offset, end_offset, &diagnostics)
                    .await
            })
            .await
        })
    }

    fn get_semantic_tokens(&self, path: &str) -> ProviderFuture<'_, Vec<SemanticToken>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("semantic_tokens", path, 0, 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_semantic_tokens(&path_owned).await
            })
            .await
        })
    }

    fn get_document_highlights(
        &self,
        path: &str,
        offset: u32,
    ) -> ProviderFuture<'_, Vec<TypeDocumentHighlight>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("document_highlights", path, u64::from(offset), 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_document_highlights(&path_owned, offset).await
            })
            .await
        })
    }

    fn get_inlay_hints(
        &self,
        path: &str,
        start_offset: u32,
        end_offset: u32,
    ) -> ProviderFuture<'_, Vec<InlayHint>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new(
            "inlay_hints",
            path,
            u64::from(start_offset) | (u64::from(end_offset) << 32),
            0,
        );
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider
                    .get_inlay_hints(&path_owned, start_offset, end_offset)
                    .await
            })
            .await
        })
    }

    fn resolve_completion(
        &self,
        path: &str,
        data: CompletionResolveData,
    ) -> ProviderFuture<'_, Option<CompletionResolveResult>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new(
            "resolve_completion",
            path,
            0,
            hash_extra(&format!("{data:?}")),
        );
        Box::pin(async move {
            self.run_guarded(
                fp,
                || None,
                move |provider| async move { provider.resolve_completion(&path_owned, data).await },
            )
            .await
        })
    }

    fn shutdown(&self) -> ProviderFuture<'_, ()> {
        Box::pin(async {
            // Declare teardown intent BEFORE tearing the inner provider down:
            // the resulting crash-notify wake (child exit EOF) is the requested
            // teardown, never a crash to report/restart from.
            self.state.torn_down.store(true, Ordering::SeqCst);
            if let Ok(provider) = self.get_inner().await {
                let _ = provider.shutdown().await;
            }
            Ok(())
        })
    }

    fn resync_open_files(&self) -> ProviderFuture<'_, ()> {
        // Resync does not change the desired-state set, so it bypasses the actor
        // and runs directly against the live provider. Concurrency with an
        // in-flight `update_file` is made stale-safe at the provider (ipc) layer
        // by its per-file content generation gate.
        Box::pin(async move {
            match self.get_inner().await {
                Ok(provider) => provider.resync_open_files().await,
                Err(_) => Ok(()),
            }
        })
    }

    fn configure_paths(&self, base_url: &str, paths: serde_json::Value) -> ProviderFuture<'_, ()> {
        let base_url = base_url.to_string();
        Box::pin(async move {
            self.submit_mutation(
                DesiredMutation::ConfigurePaths { base_url, paths },
                Lane::Foreground,
            )
            .await
        })
    }

    fn update_workspace_folders(
        &self,
        added: Vec<serde_json::Value>,
        removed: Vec<serde_json::Value>,
    ) -> ProviderFuture<'_, ()> {
        Box::pin(async move {
            self.submit_mutation(
                DesiredMutation::UpdateWorkspaceFolders { added, removed },
                Lane::Foreground,
            )
            .await
        })
    }

    fn child_pid(&self) -> Option<u32> {
        self.state
            .inner
            .try_read()
            .ok()
            .and_then(|guard| guard.as_ref().and_then(|provider| provider.child_pid()))
    }

    // ── Background-priority forwarding ──────────────────────────────

    fn open_file_background(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Open { path, content }, Lane::Background)
                .await
        })
    }

    fn load_file_background(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Load { path, content }, Lane::Background)
                .await
        })
    }

    fn update_file_background(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Update { path, content }, Lane::Background)
                .await
        })
    }

    fn close_file_background(&self, path: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Close { path }, Lane::Background)
                .await
        })
    }

    fn get_diagnostics_background(&self, path: &str) -> ProviderFuture<'_, Vec<TypeDiagnostic>> {
        let path_owned = path.to_string();
        let fp = QueryFingerprint::new("diagnostics", path, 0, 0);
        Box::pin(async move {
            self.run_guarded(fp, Vec::new, move |provider| async move {
                provider.get_diagnostics_background(&path_owned).await
            })
            .await
        })
    }

    fn configure_paths_background(
        &self,
        base_url: &str,
        paths: serde_json::Value,
    ) -> ProviderFuture<'_, ()> {
        let base_url = base_url.to_string();
        Box::pin(async move {
            self.submit_mutation(
                DesiredMutation::ConfigurePaths { base_url, paths },
                Lane::Background,
            )
            .await
        })
    }

    fn update_workspace_folders_background(
        &self,
        added: Vec<serde_json::Value>,
        removed: Vec<serde_json::Value>,
    ) -> ProviderFuture<'_, ()> {
        Box::pin(async move {
            self.submit_mutation(
                DesiredMutation::UpdateWorkspaceFolders { added, removed },
                Lane::Background,
            )
            .await
        })
    }

    // ── Normal-priority forwarding ──────────────────────────────────

    fn open_file_normal(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Open { path, content }, Lane::Normal)
                .await
        })
    }

    fn load_file_normal(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Load { path, content }, Lane::Normal)
                .await
        })
    }

    fn update_file_normal(&self, path: &str, content: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        let content = content.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Update { path, content }, Lane::Normal)
                .await
        })
    }

    fn close_file_normal(&self, path: &str) -> ProviderFuture<'_, ()> {
        let path = path.to_string();
        Box::pin(async move {
            self.submit_mutation(DesiredMutation::Close { path }, Lane::Normal)
                .await
        })
    }
}

#[cfg(test)]
#[path = "resilient_tests.rs"]
pub(crate) mod resilient_tests;
